= CheckSignatureResult -- метод (byte[], Stream, X509Certificate2, bool, bool, DateTime?)

Проверяет подпись.

* *Пространство имен:* DocsVision.BackOffice.ObjectModel.Services
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

[[CheckSignatureResult_CheckSignature_MT__section_jct_3ds_mpb]]
== Синтаксис

[source,csharp]
----
CheckSignatureResult CheckSignature(byte[] signature, Stream contentStream, X509Certificate2 certificate, bool detached, bool isHash, DateTime? signatureDate)
----

[[CheckSignatureResult_CheckSignature_MT__section_nyy_4fs_mpb]]
Параметры

signature::
Тип: http://msdn.microsoft.com/ru-ru/library/system.byte.aspx[System.Byte][]
+
Закодированный в сообщение CMS/PKCS 7 поток подписываемых данных
contentStream::
Тип: http://msdn.microsoft.com/ru-ru/library/system.io.stream.aspx[System.IO.Stream]
+
Поток подписываемых данных

certificate::
Тип: http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]
+
Сертификат подписи
detached::
Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
+
Устанавливается значение true, если подпись является отсоединённой

isHash::
Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
+
Устанавливается значение true, если подпись является простой
signatureDate::
Тип: http://msdn.microsoft.com/ru-ru/library/system.datetime.aspx[System.DateTime]
+
Дата создания подписи

Возвращаемое значение:

::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/CheckSignatureResult_CL.adoc[CheckSignatureResult]
+
Возвращает результат проверки подписи
