= IAccessCheckingService.GetUserRoles - метод (BaseCard, Guid)

Получает список ролей карточки для указанного сотрудника.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
IEnumerable<RoleModelRole> GetUserRoles(BaseCard card, Guid employeeId)
----

Параметры

card::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard]
+
Карточка библиотеки "Базовые объекты"
employeeId::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
+
Идентификатор сотрудника

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<RoleModelRole>
+
Коллекция объектов типа xref:api/DocsVision/BackOffice/ObjectModel/RoleModelRole_CL.adoc[RoleModelRole]

== Заметки

В первую очередь производиться поиск в локальном кэше. В случае возникновения ошибки, метод вернет пустую коллекцию.
