= IAccessCheckingService.IsOperationAllowed - метод (BaseCard, BuiltInOperation)

Возвращает признак разрешения выполнения встроенной операции для заданной карточки.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
bool IsOperationAllowed(BaseCard card, BuiltInOperation operation)
----

Параметры

card::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Карточка из библиотеки "Базовые объекты"
operation::
  Тип: xref:../BuiltInOperation_CL.adoc[BuiltInOperation]
  +
  Встроенная операция

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  true - операция разрешена, иначе false

== Заметки

Если операция не запрещена, то она отмечается разрешенной.

== Примеры

Ниже приведен пример определения наличия прав у роли текущего сотрудника, достаточных для редактирования основного файла некого документа

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов    

// Получение сервиса 
IAccessCheckingService accessCheckingService = objectContext.GetService<IAccessCheckingService>();

//получение документа
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

//true - операция редактирования разрешена
bool allowed = accessCheckingService.IsOperationAllowed(document, Document.MainFileEditOperation);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IAccessCheckingService_IN.adoc[IAccessCheckingService - интерфейс]
