= IAccessCheckingService.GetUserRoles - метод (BaseCard)

Получает список ролей карточки для текущего сотрудника.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IEnumerable<RoleModelRole> GetUserRoles(BaseCard card)
----

Параметры

card::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Карточка библиотеки "Базовые объекты"

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<RoleModelRole>
  +
  Коллекция объектов типа xref:../RoleModelRole_CL.adoc[RoleModelRole]

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Возникает при передаче в метод NULL.
|===

== Заметки

В первую очередь производиться поиск в локальном кэше. В случае возникновения ошибки, метод вернет пустую коллекцию.

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IAccessCheckingService_IN.adoc[IAccessCheckingService - интерфейс]
