= IAccessCheckingService.GetUserRoles - метод (BaseCard, Guid)

Получает список ролей карточки для указанного сотрудника.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IEnumerable<RoleModelRole> GetUserRoles(BaseCard card, Guid employeeId)
----

Параметры

card::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Карточка библиотеки "Базовые объекты"
employeeId::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Идентификатор сотрудника

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<RoleModelRole>
  +
  Коллекция объектов типа xref:../RoleModelRole_CL.adoc[RoleModelRole]

== Заметки

В первую очередь производиться поиск в локальном кэше. В случае возникновения ошибки, метод вернет пустую коллекцию.

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IAccessCheckingService_IN.adoc[IAccessCheckingService - интерфейс]
