= IBarcodeService.PrintBarcode -- метод (Document, BarcodePrintSettings, PrinterSettings)

Отправляет на печать штрих-код документа.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void PrintBarcode(Document document, BarcodePrintSettings settings, PrinterSettings printerSettings)
----

Параметры::
document:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]`
+
Документ
settings:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BarcodePrintSettings_CL.adoc[BarcodePrintSettings]`
+
Настройки печати штрих-кода
printerSettings:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.drawing.printing.printersettings.aspx[System.Drawing.Printing.PrinterSettings]`
+
Сведения о печати документа

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `document`.
|`http://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException]` |Ошибка возвращается в случае, если у сотрудника недостаточно прав для печати штрих-кода.
|===

== Примеры

В следующем примере производиться отправка на печать штрих-кода, определённого в документе с идентификатором 00000000-0000-0000-0000-000000000000

[source,csharp]
----
<.>

IBarcodeService barcodeService = objectContext.GetService<IBarcodeService>();
IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

BarcodePrintSettingsCollection settingsCollection = barcodeService.GetBarcodePrintSettings(staffService.GetCurrentEmployee(), document.SystemInfo.CardKind); <.>

BarcodePrintSettings printSettings = BarcodePrintSettings.DefaultSettings; <.>

var printDialog = new PrintDialog();
printDialog.UseEXDialog = true; <.>

if (printDialog.ShowDialog() = System.Windows.Forms.DialogResult.OK)
{
 barcodeService.PrintBarcode(document, printSettings, printDialog.PrinterSettings); <.>
}
----
<.> Инициализация контекста объектов.
<.> Получение сервисов.
<.> Получение документа.
<.> Получение коллекции доступных настроек для печати штрих-кода.
<.> Получение настроек печати по умолчанию.
<.> Вывод диалога выбора принтера.
