= IBaseCardService.GetSignaturePartData -- метод (BaseCardSignaturePart)

Извлекает данные из части подписи.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
byte[] GetSignaturePartData(BaseCardSignaturePart singaturePart)
----

Параметры::
singaturePart:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCardSignaturePart_CL.adoc[BaseCardSignaturePart]
+
Часть подписи

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/system.byte.aspx[System.Byte][]
+
Содержимое подписи

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр singaturePart.
|===

== Заметки

Полученные данные могут быть использованы,например, в методе xref:api/DocsVision/BackOffice/ObjectModel/Services/IBaseCardService.AddSignaturePart_MT.adoc[IBaseCardService.AddSignaturePart].
