= IBaseUniversalService.AddItem -- метод (BaseUniversalItemType, BaseUniversalItem)

Добавляет строку в указанный узел справочника.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseUniversalItem AddItem(BaseUniversalItemType itemType, BaseUniversalItem item)
----

Параметры::
itemType:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItemType_CL.adoc[BaseUniversalItemType]
+
Узел справочника
item:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItem_CL.adoc[BaseUniversalItem]
+
Добавляемая строка

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItem_CL.adoc[BaseUniversalItem]
+
Ссылка на строку

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр itemType или item.
|===

== Заметки

В случае, если узел itemType уже содержит значение item, будет возвращен null.
