= IBaseUniversalService.AddNewViewField - метод (String, SectionField, BaseUniversalItemType)

Создает отображаемое поле в коллекции полей, и возвращает на него ссылку.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
BaseUniversalItemTypeViewField AddNewViewField(string fieldName, SectionField sectionField, BaseUniversalItemType itemType)
----

Параметры

fieldName::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Название поля для которого создается отображение
sectionField::
  Тип: xref:../../../Platform/Data/Metadata/CardModel/SectionField_CL.adoc[SectionField]
  +
  Поле секции для которого создается отображение
itemType::
  Тип: xref:../BaseUniversalItemType_CL.adoc[BaseUniversalItemType]
  +
  Узел справочника к которому добавляется отображаемое поле

Возвращаемое значение

::
  Тип: xref:../BaseUniversalItemTypeViewField_CL.adoc[BaseUniversalItemTypeViewField]
  +
  Отображаемое поле

== Примеры

В приведенном ниже примере создается отображаемое поле в узле конструктора справочников

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов
         
//получение необходимых сервисов
IBaseUniversalService baseUniversalService = objectContext.GetService<IBaseUniversalService>();

//получение поставщика метаданных
IMetadataProvider iMetadataProvider = objectContext.GetService<IMetadataProvider>();

//получение секции, которая содержит отображаемое поле (в нашем случае секция "Строка справочника" карточки "Конструктор справочников")
CardSection cardSectionMetadata = iMetadataProvider.GetSection(new Guid("1B1A44FB-1FB1-4876-83AA-95AD38907E24")); 

//получение узла, для которого добавляется отображаемое поле
BaseUniversalItemType baseUniversalItemType = objectContext.GetObject<BaseUniversalItemType>(new Guid("00000000-0000-0000-0000-000000000000"));

//получение поля "Описание" 
SectionField sectionField = cardSectionMetadata.Fields[new Guid("8B45BC58-6831-40C1-B654-E0C0C6E36115")];

//создание нового отображаемого поля и установка порядкового номера
BaseUniversalItemTypeViewField baseUniversalItemTypeViewField = baseUniversalService.AddNewViewField(sectionField.Name, sectionField, baseUniversalItemType);
baseUniversalItemTypeViewField.Order = baseUniversalItemType.ViewFields.Count;

//сохранение            
objectContext.SaveObject(baseUniversalItemTypeViewField);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IBaseUniversalService_IN.adoc[IBaseUniversalService - интерфейс]
