= IBaseUniversalService.AddNewItem -- метод (BaseUniversalItemType)

Создает новую строку в указанном узле справочника.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseUniversalItem AddNewItem(BaseUniversalItemType itemType)
----

Параметры::
itemType:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItemType_CL.adoc[BaseUniversalItemType]`
+
Узел справочника

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItem_CL.adoc[BaseUniversalItem]`
+
Добавленная строка

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `itemType`.
|===

== Примеры

В примере, сервис используется для добавления строки в существующий узел

[source,csharp]
----
<.>

IBaseUniversalService baseUniversalService = objectContext.GetService<IBaseUniversalService>(); <.>

BaseUniversalItemType baseUniversalItemType = objectContext.GetObject<BaseUniversalItemType>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

BaseUniversalItem baseUniversalItem = baseUniversalService.AddNewItem(baseUniversalItemType);
baseUniversalItem.Name = "Строка справочника";
baseUniversalItem.Description = "Строка справочника созданная из кода"; <.>
objectContext.SaveObject<BaseUniversalItem>(baseUniversalItem);
----
<.> Инициализация контекста объектов.
<.> Получение сервисов.
<.> Получение узла, в который будет произведено добавление строки.
<.> Добавление строки.
