= IBaseCardService.AddSignature -- метод (SignatureList, X509Certificate2, String, StatesState)

Инициализирует электронную подпись и добавляет её в список подписей.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseCardSignature AddSignature(SignatureList signatureList, X509Certificate2 certificate, string cardDescription, StatesState cardState)
----

Параметры::
signatureList:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/SignatureList_CL.adoc[SignatureList]
+
Список подписей
certificate:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]
+
Сертификат
cardDescription:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Примечание к подписи
cardState:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesState_CL.adoc[StatesState]
+
Состояние карточки

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCardSignature_CL.adoc[BaseCardSignature]
+
Объект содержащий полную информацию по установленной ЭЦП

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр signatureList.
|===

== Заметки

Если certificate не задан, то будет проставлена простая подпись.
