= IBaseCardService.CopySignatures -- метод (SignatureList, SignatureList)

Создает список подписей на основе имеющегося.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void CopySignatures(SignatureList sourceSignatureList, SignatureList destinationSignatureList)
----

Параметры::
sourceSignatureList:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/SignatureList_CL.adoc[SignatureList]
+
Исходный список подписей
destinationSignatureList:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/SignatureList_CL.adoc[SignatureList]
+
Конечный список подписей

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр sourceSignatureList или destinationSignatureList.
|===

== Заметки

При копировании создаются объекты типа BaseCardSignature и BaseCardSignaturePart, которые заполняются данными существующих подписей и частей подписи.
