= IBaseCardService.CanStartBusinessProcesses - метод (BaseCard, IEnumerable<KindsCardProcess>)

Проверяет допустимость запуска коллекции бизнес-процессов и возвращает список ошибок.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IEnumerable<StartBusinessProcessErrorInfo> CanStartBusinessProcesses(BaseCard baseCard, IEnumerable<KindsCardProcess> kindsCardProcesses)
----

Параметры

baseCard::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Проверяемая карточка
kindsCardProcesses::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<KindsCardProcess>
  +
  Коллекция видов бизнес-процессов типа xref:../KindsCardProcess_CL.adoc[KindsCardProcess]

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StartBusinessProcessErrorInfo>
  +
  Коллекция ошибок типа xref:Entities/StartBusinessProcessErrorInfo_CL.adoc[StartBusinessProcessErrorInfo]

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр baseCard или processSettings.
|===

== Заметки

Метод выполняет последовательный вызов метода [.keyword .apiname]#IBaseCardService.CanStartBusinessProcess# для каждого элемента коллекции kindsCardProcesses.

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IBaseCardService_IN.adoc[IBaseCardService - интерфейс]
