= IBaseUniversalService.CopyItemType -- метод (BaseUniversalItemType, BaseUniversalItemType)

Создает копию узла в заданным узле конструктора справочников.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseUniversalItemType CopyItemType(BaseUniversalItemType copiedItemType, BaseUniversalItemType targetItemType)
----

Параметры::
copiedItemType:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItemType_CL.adoc[BaseUniversalItemType]`
+
Копируемый узел

targetItemType:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItemType_CL.adoc[BaseUniversalItemType]`
+
Узел в который производится копирование

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItemType_CL.adoc[BaseUniversalItemType]`
+
Созданная копия узла

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `copiedItemType`.
|===

== Примеры

[source,csharp]
----
<.>

IBaseUniversalService baseUniversalService = objectContext.GetService<IBaseUniversalService>(); <.>

BaseUniversalItemType baseUniversalItemTypeToCopy = objectContext.GetObject<BaseUniversalItemType>(new Guid("00000000-0000-0000-0000-000000000000")); <.>
           
BaseUniversalItemType baseUniversalItemTypeParent = objectContext.GetObject<BaseUniversalItemType>(new Guid("00000000-0000-0000-0000-000000000001")); <.>

BaseUniversalItemType copiedItem = baseUniversalService.CopyItemType(baseUniversalItemTypeToCopy, baseUniversalItemTypeParent);
copiedItem.Name = string.Format("Копия {0}", baseUniversalItemTypeToCopy.Name); <.>

objectContext.SaveObject<BaseUniversalItemType>(copiedItem); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервисов.
<.> Копируемый узел справочника.
<.> Узел в который будет произведено копирование.
<.> Создание копии.
<.> Сохранение.
