= IBaseCardService.GetBaseCardSectionRows -- метод (BaseCard, CardSection)

Возвращает коллекцию всех строк секции карточки.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
IEnumerable<BaseCardSectionRow> GetBaseCardSectionRows(BaseCard card, CardSection section)
----

Параметры::
card:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard]
+
Карточка
section:::
Тип: xref:api/DocsVision/Platform/Data/Metadata/CardModel/CardSection_CL.adoc[CardSection]
+
Секция карточки

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<BaseCardSectionRow>
+
Коллекция строк секции типа xref:api/DocsVision/BackOffice/ObjectModel/BaseCardSectionRow_CL.adoc[BaseCardSectionRow]

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр card или section.
|===
