= IBaseCardService.StopBusinessProcess -- метод (BaseCard, Process)

Останавливает выполнение бизнес-процесса.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void StopBusinessProcess(BaseCard baseCard, Process processInstance)
----

Параметры::
baseCard:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard]
+
Карточка
processInstance:::
Тип: xref:api/DocsVision/Workflow/Objects/Process_CL.adoc[Process]
+
Экземпляр бизнес-процесса

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр baseCard или processInstance.
|===

== Заметки

Бизнес-процесс переводится в статус "Остановлен". При невозможности определения текущего сотрудника (IStaffService.GetCurrentEmployee()), что возможно при некорректном открытии сессии, -- метод не отработает.
