= IBaseCardService.InitializeBusinessProcessVariables -- метод (Process, Dictionary<String, Object>)

Выполняет инициализацию переменных бизнес-процесса.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void InitializeBusinessProcessVariables(Process process, Dictionary<string, object> variablesKeyValuePairs)
----

Параметры::
process:::
Тип: `xref:api/DocsVision/Workflow/Objects/Process_CL.adoc[Process]`
+
Бизнес-процессы

variablesKeyValuePairs:::
Тип: `http://msdn.microsoft.com/ru-ru/library/xfhwa508.aspx[System.Collections.Generic.Dictionary]<String, Object>`
+
Коллекция содержащая название переменной и её значение

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `process` или `variablesKeyValuePairs`.
|===

== Заметки

Метод выполняет поиск в бизнес-процессе переменной с заданным именем, определяет наличие у неё признака переменной с набором значений и записывает переданное значение в переменную.

== Примеры

В приведенном примере создается экземпляр бизнес-процесса, на основе существующего шаблона, после чего выполняется инициализация двух его переменных (`var1` и `var2`)

[source,csharp]
----
<.>

Library WorkflowLibrary = new Library(userSession, 1, 1, false); <.>

DocsVision.Workflow.Objects.Process processTemplate = WorkflowLibrary.GetProcess(new Guid("00000000-0000-0000-0000-000000000000")); <.>

DocsVision.Workflow.Objects.Process processInstance = WorkflowLibrary.CreateProcess(processTemplate); <.>

IBaseCardService baseCardService = objectContext.GetService<IBaseCardService>();
IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

baseCardService.InitializeBusinessProcessVariables(processInstance, new System.Collections.Generic.Dictionary<string, object>{ <.>
 {"var1", "Значение строковой переменной"},
 {"var2", new object[]{1,2,4}} <.>
});

processInstance.Start(staffService.GetCurrentEmployee().AccountName, WorkflowLibrary.Dictionary, ExecutionModeEnum.Automatic, true); <.>
----
<.> Инициализация контекста объектов.
<.> Инициализация объекта для работы с библиотекой карточкой СУБП.
<.> Получение шаблона бизнес-процесса.
<.> Создание экземпляра бизнес-процесса.
<.> Получение необходимых сервисов.
<.> Инициализация двух переменных.
<.> `var2` является переменной с набором значений.
<.> Запуск экземпляра бизнес-процесса.
