= IBaseUniversalService.AddNewItem - метод (BaseUniversalItemType)

Создает новую строку в указанном узле справочника.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
BaseUniversalItem AddNewItem(BaseUniversalItemType itemType)
----

Параметры

itemType::
  Тип: xref:../BaseUniversalItemType_CL.adoc[BaseUniversalItemType]
  +
  Узел справочника

Возвращаемое значение

::
  Тип: xref:../BaseUniversalItem_CL.adoc[BaseUniversalItem]
  +
  Добавленная строка

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр itemType.
|===

== Примеры

В примере, сервис используется для добавления строки в существующий узел

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

//получение сервисов
IBaseUniversalService baseUniversalService = objectContext.GetService<IBaseUniversalService>();

//получение узла, в который будет произведено добавление строки
BaseUniversalItemType baseUniversalItemType = objectContext.GetObject<BaseUniversalItemType>(new Guid("00000000-0000-0000-0000-000000000000"));

//добавление строки
BaseUniversalItem baseUniversalItem = baseUniversalService.AddNewItem(baseUniversalItemType);
baseUniversalItem.Name = "Строка справочника";
baseUniversalItem.Description = "Строка справочника созданная из кода";
objectContext.SaveObject<BaseUniversalItem>(baseUniversalItem);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IBaseUniversalService_IN.adoc[IBaseUniversalService - интерфейс]
