= IBaseUniversalService.CopyItem -- метод (BaseUniversalItem, BaseUniversalItemType)

Создает копию строки в заданным узле конструктора справочников.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseUniversalItem CopyItem(BaseUniversalItem copiedItem, BaseUniversalItemType targetItemType)
----

Параметры::
copiedItem:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItem_CL.adoc[BaseUniversalItem]`
+
Копируемая строка
targetItemType:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItemType_CL.adoc[BaseUniversalItemType]`
+
Узел в который производится копирование

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItem_CL.adoc[BaseUniversalItem]`
+
Созданная копия строки

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр copiedItem или targetItemType.
|===
