= IBaseUniversalService.CanMoveItemType -- метод (BaseUniversalItemType, BaseUniversalItemType)

Определяет возможность перемещения узла в заданный узел конструктора справочников.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool CanMoveItemType(BaseUniversalItemType movedItemType, BaseUniversalItemType targetItemType)
----

Параметры::
movedItemType:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItemType_CL.adoc[BaseUniversalItemType]
+
Узел, который проверяется на возможность перемещения
targetItemType:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItemType_CL.adoc[BaseUniversalItemType]
+
Узел, в который планируется перемещение

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
+
true -- перемещение допустимо, иначе false

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр movedItemType.
|===

== Заметки

Метод проходит дерево от targetItemType до его родительского узла, проверяя наличии movedItemType среди родительских узлов.
