= IBaseUniversalService.AddNewItemType -- метод (BaseUniversalItemType)

Создает дочерний узел в указанном узле справочника.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseUniversalItemType AddNewItemType(BaseUniversalItemType parentItemType)
----

Параметры

parentItemType::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItemType_CL.adoc[BaseUniversalItemType]
+
Родительский узел

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversalItemType_CL.adoc[BaseUniversalItemType]
+
Добавленный узел

== Заметки

Если parentItemType не задан, то узел будет создан в корневом узле дерева справочника.

== Примеры

[source,csharp]
----
//Инициализация контекста объектов

//получение сервисов
IBaseUniversalService baseUniversalService = objectContext.GetService<IBaseUniversalService>();

//создаем новый узел в корне справочника
BaseUniversalItemType baseUniversalItemType = baseUniversalService.AddNewItemType(null);
baseUniversalItemType.Name = "Узел справочника";
baseUniversalItemType.Description = "Узел справочника созданный из кода";

//элементы узла будут использовать порядковые номера
baseUniversalItemType.UseOrder = true;

//сохранение
objectContext.SaveObject<BaseUniversalItemType>(baseUniversalItemType);
----
