= ICategoriesService.FindCategoryByName -- метод (CategoriesCategory, String)

Выполняет поиск категории с заданным именем.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
CategoriesCategory FindCategoryByName(CategoriesCategory parentCategory, string name)
----

Параметры::
parentCategory:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/CategoriesCategory_CL.adoc[CategoriesCategory]`
+
Категория, в которой осуществляется поиск

name:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Название категории

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/CategoriesCategory_CL.adoc[CategoriesCategory]`
+
Искомая категория

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `name`.
|===

== Заметки

Поиск игнорирует регистр значения параметра name. Если параметр `parentCategory` не задан (значение `null`), то будет выполнен поиск в корневой категории. Поиск выполняется только среди непосредственных потомков `parentCategory` -- поиск в подкатегориях не выполняется.

== Примеры

[source,csharp]
----
<.>

ICategoriesService categoriesService = objectContext.GetService<ICategoriesService>(); <.>

CategoriesCategory category = categoriesService.FindCategoryByName(null, "Новая категория"); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса для работы со Справочником категорий.
<.> Поиск категории с названием "Новая категория" (регистр не имеет значения) в корневой категории.
