= ICategoriesService.AddCategory - метод (CategoriesCategory)

Добавляет новую категорию в [.dfn .term]_Справочник категорий_, в указанную родительскую категорию.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
CategoriesCategory AddCategory(CategoriesCategory parentCategory)
----

Параметры

parentCategory::
  Тип: xref:../CategoriesCategory_CL.adoc[CategoriesCategory]
  +
  Родительская категория

Возвращаемое значение

::
  Тип: xref:../CategoriesCategory_CL.adoc[CategoriesCategory]
  +
  Созданная категория

== Заметки

Если параметр parentCategory не задан (имеет значение null), то в качестве родительской категории будет использована корневая категория [.dfn .term]_Справочника категорий_.

== Примеры

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса для работы с сервисами  
ICategoriesService categoriesService = objectContext.GetService<ICategoriesService>();

// Добавление категории в корневую категорию
CategoriesCategory category = categoriesService.AddCategory(null);
category.Name = "Новая категория";
category.Comment = "Пример создания категории";

// Получение и присвоение представления. Если представление не задано, то будет использоваться Дайджест
category.View = objectContext.GetObject<SavedViewsView>(new Guid("00000000-0000-0000-0000-000000000000"));

// Сохранение
objectContext.SaveObject(category);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ICategoriesService_IN.adoc[ICategoriesService - интерфейс]
