= ICategoriesService.FindCategoryByName - метод (CategoriesCategory, String)

Выполняет поиск категории с заданным именем.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
CategoriesCategory FindCategoryByName(CategoriesCategory parentCategory, string name)
----

Параметры

parentCategory::
  Тип: xref:../CategoriesCategory_CL.adoc[CategoriesCategory]
  +
  Категория, в которой осуществляется поиск
name::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Название категории

Возвращаемое значение

::
  Тип: xref:../CategoriesCategory_CL.adoc[CategoriesCategory]
  +
  Искомая категория

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр name.
|===

== Заметки

Поиск игнорирует регистр значения параметра name. Если параметр parentCategory не задан (значение null), то будет выполнен поиск в корневой категории. Поиск выполняется только среди непосредственных потомков parentCategory - поиск в подкатегориях не выполняется.

== Примеры

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса для работы со Справочником категорий
ICategoriesService categoriesService = objectContext.GetService<ICategoriesService>();

// Поиск категории с названием "Новая категория" (регистр не имеет значения) в корневой категории
CategoriesCategory category = categoriesService.FindCategoryByName(null, "Новая категория");
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ICategoriesService_IN.adoc[ICategoriesService - интерфейс]
