= ICryptService.RemoveEncryption -- метод (X509Certificate2, Guid)

Расшифровывает файл и удаляет связанные с ним крипто-объекты.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void RemoveEncryption(X509Certificate2 certificate, Guid fileId)
----

Параметры

certificate::
Тип: http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]
+
Сертификат шифрования, которым зашифрован файл
fileId::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
+
Идентификатор зашифрованного файла

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр certificate.
|http://msdn.microsoft.com/ru-ru/library/system.invalidoperationexception.aspx[System.InvalidOperationException] |Ошибка возвращается в случае, если файл с указанным идентификатором не существует.
|===

== Заметки

Данный метод, в отличии от метода ICryptService.DecryptFile, удаляет крипто-объекты, используемые для расшифровки файла сотрудниками, которым предоставлен соответствующий доступ.

== Примеры

Приведенный ниже пример содержит код скрипта карточки типа _Документ_, который расшифровывает основные файла текущей карточки. В ходе работы скрипта будет вызвана, при необходимости, форма для выбора сертификата шифрования.

[source,csharp]
----
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Forms;
using System.Security.Cryptography.X509Certificates;

using DocsVision.Platform.ObjectManager;
using DocsVision.Platform.ObjectModel;
using DocsVision.BackOffice.WinForms;
using DocsVision.BackOffice.WinForms.Controls;
using DocsVision.BackOffice.ObjectModel;
using DocsVision.BackOffice.ObjectModel.Services;

namespace BackOffice
{
 public class CardDocumentПримерScript : CardDocumentДокументУДScript
 {
  private void RemoveEncryption_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
  {
   bool cancel = false;
            
   // Вызов формы выбора сертификата
   X509Certificate2 certificate = SelectCertificateForm.SelectCertificate(ref cancel, base.CardControl.ObjectContext);
   if(cancel) return;
            
   // Получения сервиса шифрования базовых объектов
   ICryptService cryptService = base.CardControl.ObjectContext.GetService<ICryptService>();

   // Получение основных файлов
   IEnumerable<DocumentFile> mainFiles = (base.BaseObject as Document).Files.Where<DocumentFile>(t => t.FileType = DocumentFileType.Main);
   foreach (DocumentFile item in mainFiles)
   {
    FileData fileData = base.Session.FileManager.GetFile(item.FileVersionRowId);
                
    // Проверка наличия зашифрованного файла
    if(fileData.Encrypted)
    {
     cryptService.RemoveEncryption(certificate, item.FileVersionRowId);
    }
   }
  }
 }
}
----
