= ICryptService.RemoveCryptAccount - метод (X509Certificate2, Guid, String)

Отменяет доступ указанного сотрудника к зашифрованному файлу.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void RemoveCryptAccount(X509Certificate2 certificate, Guid fileId, string accountName)
----

Параметры

certificate::
Тип: http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]
+
Сертификат шифрования, которым зашифрован файл
fileId::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
+
Идентификатор зашифрованного файла
accountName::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Учетная запись сотрудника, у которого отбирается доступ к зашифрованному файлу

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр certificate или accountName.
|http://msdn.microsoft.com/ru-ru/library/system.invalidoperationexception.aspx[System.InvalidOperationException] |Ошибка возвращается в случае, если файл с указанным идентификатором не существует.
|===

== Заметки

В том случае, если доступ к файлу имеет только владелец, то файл будет расшифрован.
