= IDocumentService.AddAdditionalFile -- метод (Document, String)

Добавляет в документ дополнительный файл.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
DocumentFile AddAdditionalFile(Document document, string filePath)
----

Параметры

document::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]
+
Документ, в который добавляется файл
filePath::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Путь к добавляемому файлу

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/DocumentFile_CL.adoc[DocumentFile]
+
Файл документа

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр document или filePath.
|https://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException] |Ошибка возвращается, если недостаточно прав для добавления дополнительного файла.
|https://msdn.microsoft.com/ru-ru/library/system.invalidoperationexception.aspx[System.InvalidOperationException] |Ошибка возвращается в случае, если невозможно загрузить дополнительный файл, в.т.ч. по причине наличия в документе дополнительного файла с подобным именем.
|===

== Примеры

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IDocumentService documentService = objectContext.GetService<IDocumentService>();

// Получение документа
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

// Добавление дополнительного файла
documentService.AddAdditionalFile(document, @"Z:\Служебная записка на ремонт компьютера.docx");            
objectContext.AcceptChanges();      
----
