= IDocumentService.AddSignatures - метод (Document, DocumentFile, SignedCms)

Добавляет коллекцию новых подписей в список подписей карточки. Определяет, к какому файлу будет добавлена подпись. Позволяет использовать для подписания криптографическое сообщение типа [.keyword .apiname]#SignedCms#.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

[[AddSignatures1__section_upb_2wr_4pb]]
== Синтаксис

[source,csharp]
----
IEnumerable<BaseCardSignature> AddSignatures(Document document, DocumentFile mainFile, SignedCms signedCms);
----

Параметры

document::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]
+
Подписываемый документ
mainFile::
xref:api/DocsVision/BackOffice/ObjectModel/DocumentFile_CL.adoc[DocumentFile]
+
Определяет, к какому файлу будет добавлена подпись
signedCms::
Тип: http://msdn.microsoft.com/ru-ru/library/System.Security.Cryptography.Pkcs.SignedCms.aspx[SignedCms]
+
Сообщение CMS/PKCS 7

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<BaseCardSignature>
+
Список подписей

[[AddSignatures1__section_vpb_2wr_4pb]]
== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр document или signedCms.
|===

[[AddSignatures1__section_xpb_2wr_4pb]]
== Заметки

Данный метод может быть использован для импорта подписанного файла, сохраненного в виде сообщения CMS/PKCS 7, в карточку. Docsvision экспортирует подписанные файлы в один файл с расширением `p7s`, либо в два файла: экспортируемый файл и отдельно сообщение CMS/PKCS 7 в виде файла с расширением `p7s`. Для извлечения исходного файла из сообщения предназначен метод xref:api/DocsVision/BackOffice/ObjectModel/Services/IDocumentService.DecodeSignedDocument_MT.adoc[IDocumentService.DecodeSignedDocument].
