= IDocumentService.CanRemoveMainFiles - метод (Document document, IEnumerable<DocumentFile>)

Определяет возможность удаления указанных основных файлов.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
bool CanRemoveMainFiles(Document document, IEnumerable<DocumentFile> files)
----

Параметры

document::
  Тип: xref:../Document_CL.adoc[Document]
  +
  Документ
files::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<DocumentFile>
  +
  Список удаляемых файлов документа типа xref:../DocumentFile_CL.adoc[DocumentFile]

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  true - все файлы могут быть удалены, иначе - false

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр files.
|===

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IDocumentService_IN.adoc[IDocumentService - интерфейс]
