= IDocumentService.DownloadAdditionalFile -- метод (Document, DocumentFile, String)

Выгружает дополнительный файл документа в указанный каталог.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void DownloadAdditionalFile(Document document, DocumentFile additionalFile, string path)
----

Параметры

document::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]
+
Документ, содержащий выгружаемый файл
additionalFile::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/DocumentFile_CL.adoc[DocumentFile]
+
Возвращаемый файл документа
path::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Путь для выгрузки файла

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр additionalFile.
|http://msdn.microsoft.com/ru-ru/library/system.argumentoutofrangeexception.aspx[System.ArgumentOutOfRangeException] |Ошибка возвращается в случае, если не задан параметр path.
|http://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException] |Ошибка возвращается в случае, если у сотрудника недостаточно прав для чтения основного файла.
|===

== Примеры

В примере демонстрируется использование метода DownloadAdditionalFile при выгрузке первого дополнительного файла документа

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервиса для работы с документами
IDocumentService documentService = objectContext.GetService<IDocumentService>();

// Получение первого дополнительного файла документа
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));
DocumentFile firstAdditionalFile = document.Files.First(t=>t.FileType = DocumentFileType.Additional);

// Выгрузка файла на файловую систему
documentService.DownloadAdditionalFile(document, firstAdditionalFile, @"c:\" + firstAdditionalFile.FileName);
----
