= IDocumentService.DownloadMainFileVersion -- метод (Document, DocumentFile, Guid)

Выгружает определённую версию основного файла документа.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
string DownloadMainFileVersion(Document document, DocumentFile file, Guid versionId)
----

Параметры::
document:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]`
+
Документ

file:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/DocumentFile_CL.adoc[DocumentFile]`
+
Файл документа

versionId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор версии файла

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Путь, по которому был выгружен файл

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `document` или `file`.
|===
