= IDocumentService.GetMainFile -- метод (DocumentFile)

Возвращает карточку файл с версиями из основного файла документа.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
VersionedFileCard GetMainFile(DocumentFile file)
----

Параметры

file::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/DocumentFile_CL.adoc[DocumentFile]
+
Основной файл документа

Возвращаемое значение::
Тип: xref:api/DocsVision/Platform/ObjectManager/SystemCards/VersionedFileCard_CL.adoc[VersionedFileCard]
+
Карточка файла с версиями

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр file.
|===

== Примеры

Ниже приведен пример получения файла с версиями из первого основного файла документа

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IDocumentService documentService = objectContext.GetService<IDocumentService>();

// Получение документа
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

// Получение файла с версиями
VersionedFileCard versionedFileCard = documentService.GetMainFile(document.Files.First(t => t.FileType = DocumentFileType.Main));
----
