= IDocumentService.ApplyKindSettings -- метод (Document, KindsCardKind)

Устанавливает у документа настройки указанного вида карточки.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void ApplyKindSettings(Document document, KindsCardKind kind)
----

Параметры::
document:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]
+
Документ, к которому применяются настройки вида карточки
kind:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardKind_CL.adoc[KindsCardKind]
+
Вид карточки, из которого будут получены настройки

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр document или kind.
|===

== Заметки

Применение настроек вида карточки включает прикрепление к документу основных и дополнительных файлов, заданных в настройках указанного вида kind.
