= IDocumentService.CheckActualSignature - метод (Document, ICollection<CardFieldSetting>, BaseCardSignature)

Определяет актуальность ЭЦП по отношению к данным документа.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
bool CheckActualSignature(Document document, ICollection<CardFieldSetting> fields, BaseCardSignature signature)
----

Параметры

document::
  Тип: xref:../Document_CL.adoc[Document]
  +
  Документ, проверяемые тестируемые данные
fields::
  Тип: http://msdn.microsoft.com/ru-ru/library/92t2ye13.aspx[System.Collections.Generic.ICollection]<CardFieldSetting>
  +
  Коллекция полей типа xref:Entities/KindSetting/CardFieldSetting_CL.adoc[CardFieldSetting], у которых должна быть проверена подпись. Список полей определен в Справочнике видов карточек
signature::
  Тип: xref:../BaseCardSignature_CL.adoc[BaseCardSignature]
  +
  ЭЦП, для которой производится проверка

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  true - подпись актуальна, иначе false

== Заметки

Данный метод проверяет части указанной подписи на соответствие текущим данным (версия основного файла) документа, без верификации самой ЭЦП.

== Примеры

Ниже приведен пример использования данного метода в скрипте карточки

[source,pre,codeblock,language-csharp]
----
using System.Linq;
using System.Windows.Forms.Design;

using DocsVision.BackOffice.ObjectModel;
using DocsVision.BackOffice.ObjectModel.Services;
using DocsVision.BackOffice.ObjectModel.Services.Entities.KindSetting;
using DocsVision.Platform.ObjectModel;

namespace BackOffice
{
 public class CardDocumentПримерScript : CardDocumentДокументУДScript
 {
  private void checkActual_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
  {
   Document document = (base.BaseObject as Document);
   ObjectContext objectContext = base.CardControl.ObjectContext;

   IDocumentService documentService = objectContext.GetService<IDocumentService>();
   IUIService uiService = objectContext.GetService<IUIService>();

   DocumentSetting documentSetting = documentService.GetKindSettings(document.SystemInfo.CardKind);

   BaseCardSignature lastSignature = document.MainInfo.SignatureList.Signatures.Last();

   bool result = documentService.CheckActualSignature(document, documentSetting.DocumentSignature.Fields, lastSignature);

   if (result)
   {
    uiService.ShowMessage("Последняя подпись является актуальной");
   } else {
    uiService.ShowError("Последняя подпись неактуальна");
   }
  }
 }
}
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IDocumentService_IN.adoc[IDocumentService - интерфейс]
