= IDocumentService.CanAttachMainFile - метод (Document, VersionedFileCard, SignedCms)

Определяет возможность добавления основного файла в документ.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool CanAttachMainFile(Document document, string fileName, SignedCms signedCms)
----

Параметры

document::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]
+
Документ, для которого определяется возможность добавления основного файла
versionedFileCard::
Тип: xref:api/DocsVision/Platform/ObjectManager/SystemCards/VersionedFileCard_CL.adoc[VersionedFileCard]
+
Карточка основного файла
signedCms::
Тип: https://msdn.microsoft.com/ru-ru/library/system.security.cryptography.pkcs.signedcms.aspx[SignedCms]
+
Сообщение CMS/PKCS 7

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
+
true - указанный файл может быть добавлен как основной, иначе - false
