= IDocumentService.CanUnlockMainFile -- метод (Document, DocumentFile, LockStatus)

Определяет возможность разблокировки определённого основного файла документа.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool CanUnlockMainFile(Document document, DocumentFile file, LockStatus lockStatus)
----

Параметры::
document:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]`
+
Документ

file:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/DocumentFile_CL.adoc[DocumentFile]`
+
Файл документа

lockStatus:::
Тип: `xref:api/DocsVision/Platform/ObjectManager/LockStatus_EN.adoc[LockStatus]`
+
Собственное значение состояние блокировки файла документа, если настоящее состояние блокировки не должно учитываться

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- файл может быть разблокирован, иначе -- `false`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `document` или `file`.
|`https://msdn.microsoft.com/ru-ru/library/system.invalidoperationexception.aspx[System.InvalidOperationException]` |Ошибка возвращается в случае, если невозможно сопоставить файл версионной карточки, указанному файлу документа -- `file`.
|===
