= IDocumentService.DecodeSignedDocument -- метод (String, Document, SignedCms)

Расшифровывает сообщение CMS/PKCS 7, которое содержится в файле, расположенном по указанному пути.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
string DecodeSignedDocument(string filePath, Document document, out System.Security.Cryptography.Pkcs.SignedCms signedCms)
----

Параметры::
filePath:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Путь к файлу с криптографическим сообщением
document:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]
+
Документ, в который производится добавление содержимого сообщения. Если документ содержит основной файл с именем идентичным имени файла (без учета расширения p7s) загружаемого сообщения, то содержимое основного файла будет загружено в сообщение
signedCms:::
Тип: http://msdn.microsoft.com/ru-ru/library/System.Security.Cryptography.Pkcs.SignedCms.aspx[SignedCms]
+
Сообщение CMS/PKCS 7. Если не было проинициализировано, то будет выполнена инициализация

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Расположение временного файла, содержащего расшифрованный объект

== Примеры

Ниже приведен пример скрипта карточки, который запускает загрузку основного файла упакованного с подписью в криптографическое сообщение.

[source,csharp]
----
using System.Security.Cryptography.Pkcs;
using System.Windows.Forms;
using DocsVision.BackOffice.ObjectModel;
using DocsVision.BackOffice.ObjectModel.Services;
using DocsVision.Platform.ObjectModel;

namespace BackOffice
{
 public class CardDocumentПримерScript : CardDocumentДокументУДScript
 {
  private void importMainFile_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
  {
   Document document = (base.BaseObject as Document);
   ObjectContext objectContext = base.CardControl.ObjectContext;
   
   // Получение сервиса для работы с документами
   IDocumentService documentService = objectContext.GetService<IDocumentService>();

   // Организация выбора файла с криптографическим сообщением
   OpenFileDialog openFileDialog = new OpenFileDialog();
   openFileDialog.Multiselect = false;
   openFileDialog.Filter = "Файлы p7s (*.p7s)|*.p7s";
   DialogResult result = openFileDialog.ShowDialog();
   if (result != DialogResult.OK) return;
   string fileName = openFileDialog.FileName;

   SignedCms signedCms = null;

   // Расшифровка (распаковка) файла p7s, сообщение CMS/PKCS 7 записывается в signedCms
   string decodedFileName = documentService.DecodeSignedDocument(fileName, document, out signedCms);

   // Загрузка основного файла и подписи к нему в документ
   documentService.AttachMainFile(document, decodedFileName, signedCms);
  }
 }
}
----
