= IDocumentService.AddAdditionalFiles - метод (Document, IEnumerable<string>)

Добавляет дополнительные файлы в документ.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IEnumerable<DocumentFile> AddAdditionalFiles(Document document, IEnumerable<string> filePaths)
----

Параметры

document::
  Тип: xref:../Document_CL.adoc[Document]
  +
  Документ, в который будут добавлены файлы
filePaths::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<System.String>
  +
  Расположение файлов

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<DocumentFile>
  +
  Список файлов документа

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр document или filePaths.
|http://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException] |Ошибка возвращается в случае, если текущее состояние документа не позволяет выполнить операцию добавления.
|http://msdn.microsoft.com/ru-ru/library/system.invalidoperationexception.aspx[System.InvalidOperationException] |Ошибка возникает при наличии в документе файла с аналогичным добавляемому названием, либо в случае превышения размера вложений.
|===

== Заметки

Перед непосредственным добавлением файлов будет выполнена проверка на возможность добавления, в результате чего может быть возвращена ошибка.

== Примеры

В приведенном примере к документу добавляются два дополнительных файла с файловой системы

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IDocumentService documentService = objectContext.GetService<IDocumentService>();

// Получение документа
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

// Добавление дополнительных файлов
string[] filePaths = new string[] { @"X:\Document.docx", @"X:\Document2.docx" };
documentService.AddAdditionalFiles(document, filePaths);

// Сохранение
objectContext.SaveObject(document);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IDocumentService_IN.adoc[IDocumentService - интерфейс]
