= IDocumentService.CheckMainFileSigned - метод (Document, DocumentFile)

Определяет наличие подписи у указанного основного файла документ.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
bool CheckMainFileSigned(Document document, DocumentFile mainFile)
----

Параметры

document::
  Тип: xref:../Document_CL.adoc[Document]
  +
  Документ
mainFile::
  Тип: xref:../DocumentFile_CL.adoc[DocumentFile]
  +
  Файл документа

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  true - файл подписан, иначе false

== Примеры

Далее приведен пример использования метода [.keyword .apiname]#CheckMainFileSigned# при определении наличия подписи у первого основного файла документа

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IDocumentService documentService = objectContext.GetService<IDocumentService>();

// Получение документа
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

// Получение первого основного файла         
DocumentFile documentFile = document.Files.First(t => t.FileType = DocumentFileType.Main);

// Проверка подписи
bool result = documentService.CheckMainFileSigned(document, documentFile);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IDocumentService_IN.adoc[IDocumentService - интерфейс]
