= IDocumentService.VerifySignature -- метод (Document, BaseCardSignature, X509Certificate2, Boolean, Boolean, ICollection<CardFieldSetting>)

Выполняет проверку ЭЦП, установленной на документе, файлах документа или полях, и возвращает результат проверки.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseCardSignatureVerification VerifySignature(Document document, BaseCardSignature signature, X509Certificate2 certificate, bool signDocument, bool signAttachments, ICollection<CardFieldSetting> fields);
----

Параметры::
document:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]`
+
Документ, содержащий подписанные данные
signature:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseCardSignature_CL.adoc[BaseCardSignature]`
+
ЭЦП, установленная на данной карточке
certificate:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]`
+
Сертификат ЭЦП
signDocument:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Выполнять проверку подписи, установленной на документе -- проверяется подпись, установленная на основных файлах
signAttachments:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Выполнять проверку подписи, установленной на дополнительных файлах
fields:::
Тип: `http://msdn.microsoft.com/ru-ru/library/92t2ye13.aspx[System.Collections.Generic.ICollection]<CardFieldSetting>`
+
Коллекция полей типа xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/KindSetting/CardFieldSetting_CL.adoc[CardFieldSetting], у которых должна быть проверена подпись. Список подписываемых полей задается в Справочнике видов карточек

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/BaseCardSignatureVerification_CL.adoc[BaseCardSignatureVerification]`
+
Результат проверки ЭЦП

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `document` или signature.
|===

== Примеры

Ниже приведен пример скрипта карточки, определяющий действительность ЭЦП, установленных на основным и дополнительных файлах карточки, а также действительность подписи установленной на контролируемые поля

[source,csharp]
----
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Windows.Forms.Design;

using DocsVision.BackOffice.ObjectModel;
using DocsVision.BackOffice.ObjectModel.Services;
using DocsVision.BackOffice.ObjectModel.Services.Entities.KindSetting;
using DocsVision.Platform.ObjectModel;

namespace BackOffice
{
 public class CardDocumentПримерScript : CardDocumentДокументУДScript
 {
  private void verifySignature_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
  {
   Document document = (base.BaseObject as Document);
   ObjectContext objectContext = base.CardControl.ObjectContext;

   // Получение необходимых сервисов
   IDocumentService documentService = objectContext.GetService<IDocumentService>();
   IUserProfileCardService iUserProfileCardService = objectContext.GetService<IUserProfileCardService>();
   IUIService uiService = objectContext.GetService<IUIService>();

   // Получение сертификата сотрудника
   X509Certificate2 certificate = iUserProfileCardService.GetCertificate(base.Session.Properties["AccountName"].Value.ToString());
   
   // Получение настроек вида карточки Документ
   DocumentSetting documentSetting = documentService.GetKindSettings(document.SystemInfo.CardKind);

   // Получение последней установленной подписи, по ней будет определять подлинность документа
   BaseCardSignature lastSignature = document.MainInfo.SignatureList.Signatures.Last();

   // Выполнение проверки ЭЦП, установленной на основные и дополнительные документы, а также на поля (для подписания) определённые в Справочнике видов карточек
   var result = documentService.VerifySignature(document, lastSignature, certificate, true, true, documentSetting.DocumentSignature.Fields);

   // Оповещение пользователя о результате проверки ЭЦП
   if (result.IsValid)
   {
    uiService.ShowMessage("Документ является надежным");
   } else {
    uiService.ShowError("Документ не является надежным");
   }
  }
 }
}
----
