= IDocumentService.GetKindSettings -- метод (KindsCardKind)

Возвращает настройки заданного вида карточки Документ.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
DocumentSetting GetKindSettings(KindsCardKind kind)
----

Параметры::
kind:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardKind_CL.adoc[KindsCardKind]
+
Вид карточки Документ

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/KindSetting/DocumentSetting_CL.adoc[DocumentSetting]
+
Настройки вида документа

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр kind.
|===

== Заметки

Настройки вида карточки задаются в _Справочнике видов карточек_.

== Примеры

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IDocumentService documentService = objectContext.GetService<IDocumentService>();

// Получение вида карточки (в примере "Заявка")
KindsCardKind kind = objectContext.GetObject<KindsCardKind>(new Guid("7DB9044E-91B7-447D-8CAA-5E5A4967B8D4"));

// Получение настроек вида карточки        
DocumentSetting documentSettings = documentService.GetKindSettings(kind);
----
