= IDocumentService.DownloadAdditionalFile - метод (Document, DocumentFile)

Выгружает в файловую систему указанный дополнительный файл документа.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
string DownloadAdditionalFile(Document document, DocumentFile additionalFile)
----

Параметры

document::
  Тип: xref:../Document_CL.adoc[Document]
  +
  Документ
additionalFile::
  Тип: xref:../DocumentFile_CL.adoc[DocumentFile]
  +
  Дополнительный файл документа

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Путь, по которому был выгружен файл

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр additionalFile.
|http://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException] |Ошибка возвращается в случае, если у сотрудника недостаточно прав на чтение дополнительного файла.
|===

== Примеры

Ниже приведен пример использования метода [.keyword .apiname]#DownloadAdditionalFile# при выгрузке дополнительного файла документа

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса для работы с документами
IDocumentService documentService = objectContext.GetService<IDocumentService>();

// Получение документа
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

// Выгрузка первого дополнительного файла на диск, по пути path
string path = documentService.DownloadAdditionalFile(document, document.Files.First(t => t.FileType = DocumentFileType.Additional));
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IDocumentService_IN.adoc[IDocumentService - интерфейс]
