= IDocumentService.GetPartSignatureInfo -- метод (BaseCardSignaturePart signaturePart)

Возвращает информацию о части подписи документа.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

[[IDocumentService_GetPartSignatureInfo__section_u1q_yty_mpb]]
== Синтаксис

[source,csharp]
----
SignatureInfo GetPartSignatureInfo(Document document, BaseCardSignaturePart signaturePart, X509Certificate2 certificate);
----

Параметры

document::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]
+
Документ, из которого будет получена информация о подписи
signaturePart::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCardSignaturePart_CL.adoc[BaseCardSignaturePart]
+
Часть подписи
certificate::
Тип: http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]
+
Сертификат подписи

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/DigitalSignature/SignatureInfo_CL.adoc[SignatureInfo]
+
Информация о подписи
