= IDocumentService.DownloadMainFile - метод (Document, DocumentFile, String)

Выгружает основной файл документа в указанный каталог.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
[WorkflowVisible(WorkflowVisibility.Visible)]
void DownloadMainFile(Document document, DocumentFile file, string path)
----

Параметры

document::
  Тип: xref:../Document_CL.adoc[Document]
  +
  Документ
file::
  Тип: xref:../DocumentFile_CL.adoc[DocumentFile]
  +
  Файл документа
path::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Путь для сохранения файла

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр document или file.
|http://msdn.microsoft.com/ru-ru/library/system.argumentoutofrangeexception.aspx[System.ArgumentOutOfRangeException] |Ошибка возвращается в случае, если не задан параметр path.
|http://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException] |Ошибка возвращается в случае, если у сотрудника недостаточно прав для чтения основного файла.
|===

== Примеры

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса для работы с документами        
IDocumentService documentService = objectContext.GetService<IDocumentService>();

// Получение документа с основным файлом
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

// Сохранение первого основного файла
documentService.DownloadMainFile(document, document.Files.FirstOrDefault(t=>t.FileType = DocumentFileType.Main), @"C:\SampleDownload.docx");
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IDocumentService_IN.adoc[IDocumentService - интерфейс]
