= IKindService.AddCardKind - метод (ObjectCollection<KindsCardKind>, String)

Добавляет к приведенной коллекции видов карточке подвид с указанным названием и возвращает на него ссылку.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
KindsCardKind AddCardKind(ObjectCollection<KindsCardKind> cardKinds, string name)
----

Параметры

cardKinds::
  Тип: xref:../../../Platform/ObjectModel/ObjectCollection_CL.adoc[ObjectCollection]<KindsCardKind>
  +
  Коллекция видов карточек
name::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Название нового вида карточек

Возвращаемое значение

::
  Тип: xref:../KindsCardKind_CL.adoc[KindsCardKind]
  +
  Созданный вид карточки

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр cardKinds.
|===

== Заметки

Коллекция видов карточек может быть получена, например, из свойства типа карточки: xref:../KindsCardType.Kinds_PR.adoc[KindsCardType.Kinds].

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IKindService_IN.adoc[IKindService - интерфейс]
