= IKindService.AddCardKind - метод (KindsCardKind)

Добавляет к заданному виду карточки подвид и возвращает ссылку на созданный объект.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
KindsCardKind AddCardKind(KindsCardKind parentKind)
----

Параметры

parentKind::
  Тип: xref:../KindsCardKind_CL.adoc[KindsCardKind]
  +
  Родительский вид карточки

Возвращаемое значение

::
  Тип: xref:../KindsCardKind_CL.adoc[KindsCardKind]
  +
  Созданный вид карточки

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр parentKind.
|===

== Заметки

Название создаваемого вида карточки будет сформировано на основе названия родительского вида карточки, либо на основе типа карточки.

== Примеры

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса для работы со Справочником видов карточек
IKindService kindService = objectContext.GetService<IKindService>();

// Получение родительского вида "Заявка"
KindsCardKind parentKind = objectContext.GetObject<KindsCardKind>(new Guid("7DB9044E-91B7-447D-8CAA-5E5A4967B8D4"));

// Добавление нового вида карточки
KindsCardKind newKind = kindService.AddCardKind(parentKind);

// Обязательное сохранение
objectContext.SaveObject(newKind);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IKindService_IN.adoc[IKindService - интерфейс]
