= IKindService.AddProcessSettings - метод (KindsCardKind, Guid, String)

Добавляет бизнес-процесс c настройками к указанному виду карточки.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
KindsCardProcess AddProcessSettings(KindsCardKind cardKind, Guid templateId, string name)
----

Параметры

cardKind::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardKind_CL.adoc[KindsCardKind]
+
Вид карточки, к которой осуществляется добавление
templateId::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
+
Идентификатор шаблона бизнес-процесса

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardProcess_CL.adoc[KindsCardProcess]
+
Бизнес-процесс, описанный в настройках карточки определенного вида

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр cardKind или templateId.
|===
