= IKindService.AddCardKind -- метод (KindsCardKind, String)

Добавляет к виду карточки подвид с указанным названием и возвращает на него ссылку.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
KindsCardKind AddCardKind(KindsCardKind parentKind, string name)
----

Параметры::
parentKind:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardKind_CL.adoc[KindsCardKind]
+
Родительский вид карточки
name:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Название нового вида карточки

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardKind_CL.adoc[KindsCardKind]
+
Добавленный вид карточки

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр parentKind.
|===
