= IKindService.AddProcessOperation - метод (KindsCardProcess, StatesOperation)

Добавляет бизнес-процесс к списку процессов, привязанных к операциям в карточке определенного вида.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
KindsCardProcessOperation AddProcessOperation(KindsCardProcess process, StatesOperation operation)
----

Параметры

process::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardProcess_CL.adoc[KindsCardProcess]
+
Параметры связываемого бизнес-процесса
operation::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesOperation_CL.adoc[StatesOperation]
+
Операция в карточке, приводящая к запуску бизнес-процесса

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardProcessOperation_CL.adoc[KindsCardProcessOperation]
+
Операция процесса

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр process или operation.
|===
