= IKindService.AddCardKind - метод (KindsCardType)

Добавляет дополнительный вид карточки, указанного типа, и возвращает на него ссылку.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
KindsCardKind AddCardKind(KindsCardType cardType)
----

Параметры

cardType::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardType_CL.adoc[KindsCardType]
+
Тип карточки, к которому осуществляется добавление вида карточки

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardKind_CL.adoc[KindsCardKind]
+
Ссылка на новый вид карточки

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр cardType.
|===

== Заметки

Название нового вида карточки будет сформировано на основе названия типа карточки.

== Примеры

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервиса для работы со Справочником видов карточек
IKindService kindService = objectContext.GetService<IKindService>();

// Получение типа карточки "Документ"
KindsCardType kindType = kindService.GetCardType(new Guid("B9F7BFD7-7429-455E-A3F1-94FFB569C794"));

// Добавление нового вида карточки
KindsCardKind newKind = kindService.AddCardKind(kindType);

// Обязательное сохранение
objectContext.SaveObject(newKind);
----
