= IKindService.GetCardDefaultLocationDescription - метод (KindsCardCreationSettingLocation)

Возвращает название размещения по умолчанию для карточки определенного вида.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
string GetCardDefaultLocationDescription(KindsCardCreationSettingLocation location)
----

Параметры

location::
  Тип: xref:../KindsCardCreationSettingLocation_EN.adoc[KindsCardCreationSettingLocation]
  +
  Размещение вида карточки

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Название размещения

== Заметки

Размещение по умолчанию, для создаваемого экземпляра карточки определенного вида, регулируется в Справочнике видов карточек.

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IKindService_IN.adoc[IKindService - интерфейс]
