= ILockService.IsObjectLockedByAnotherUser<T> -- метод (T, String)

Определяет наличие у объекта блокировки, установленной другим сотрудником, а также учетную запись сотрудника, выполнившего блокировку.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool IsObjectLockedByAnotherUser<T>(T obj, out string ownerName) where T : ObjectBase
----

Параметры типа

T::
Тип заблокированного объекта

Параметры::
obj:::
Тип: T
+
Объект, для которого проверяется блокировка
ownerName:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Учетная запись владельца блокировки

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
+
Если объект заблокирован другим сотрудником, возвращает true. Если блокировка не установлена, либо установлена самим сотрудником, возвращает false

== Примеры

[source,csharp]
----
//Инициализация контекста объектов
ILockService lockService = objectContext.GetService<ILockService>();

// Получение документа
Document document = objectContext.GetObject<Document>();
string lockOwner;

// Получение сведений о блокировке
bool locked = lockService.IsObjectLockedByAnotherUser<BaseCard>(document, out lockOwner);
----
