= INumeratorCardService.AddNumeratorRange - метод (NumeratorCard, Int32, Int32, Guid)

Добавляет в нумератор новый диапазон номеров.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
NumeratorRange AddNumeratorRange(NumeratorCard card, int startNumber, int endNumber, Guid ownerId)
----

Параметры

card::
  Тип: xref:../../../Platform/ObjectManager/SystemCards/NumeratorCard_CL.adoc[NumeratorCard]
  +
  Нумератор, в который добавляется новый диапазон
startNumber::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.int32.aspx[System.Int32]
  +
  Начальный номер диапазона
endNumber::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.int32.aspx[System.Int32]
  +
  Конечный номер диапазона
ownerId::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Начальный номер диапазона

Возвращаемое значение

::
  Тип: xref:../../../Platform/ObjectManager/SystemCards/NumeratorRange_CL.adoc[NumeratorRange]
  +
  Диапазон нумератора

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр card.
|===

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/INumeratorCardService_IN.adoc[INumeratorCardService - интерфейс]
