= INumerationRulesService.AddNewCondition -- метод (NumerationRulesRuleItem)

Добавляет условие в строку правила нумерации в _конструкторе правил нумерации_.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
NumerationRulesRuleItemCondition AddNewCondition(NumerationRulesRuleItem ruleItem)
----

Параметры::
ruleItem:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/NumerationRulesRuleItem_CL.adoc[NumerationRulesRuleItem]`
+
Строка правила нумерации, в которую добавляется условие

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/NumerationRulesRuleItemCondition_CL.adoc[NumerationRulesRuleItemCondition]`
+
Добавленное условие

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр ruleItem.
|===
