= INumeratorCardService.AddNumeratorZone -- метод (NumeratorCard, String)

Добавляет в нумератор новую зону нумерации.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
NumeratorZone AddNumeratorZone(NumeratorCard card, string name)
----

Параметры::
card:::
Тип: xref:api/DocsVision/Platform/ObjectManager/SystemCards/NumeratorCard_CL.adoc[NumeratorCard]
+
Нумератор, в который добавляется новая зона
name:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Название добавляемой зоны

Возвращаемое значение::
Тип: xref:api/DocsVision/Platform/ObjectManager/SystemCards/NumeratorZone_CL.adoc[NumeratorZone]
+
Зона нумерации

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр card.
|===
