= IPartnersService.FindCompanyByNameOnServer -- метод (PartnersCompany, String)

Осуществляет поиск подразделения с заданным названием.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
PartnersCompany FindCompanyByNameOnServer(PartnersCompany parentUnit, string unitName)
----

Параметры

parentUnit::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/PartnersCompany_CL.adoc[PartnersCompany]
+
Организация, в которой выполняется поиск дочернего подразделения/организации
unitName::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Название искомого подразделения

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/PartnersCompany_CL.adoc[PartnersCompany]
+
Организация с указанным названием

== Заметки

Если parentUnit не задан, то будет осуществлен поиск в корневом каталоге подразделений.
