= IReferenceListService.CreateReference -- метод (ReferenceList, LinksLinkType, FoldersFolder)

Добавляет ссылку на папку в _список ссылок_.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
ReferenceListReference CreateReference(ReferenceList referenceList, LinksLinkType linkType, FoldersFolder foldersFolder)
----

Параметры::
referenceList:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/ReferenceList_CL.adoc[ReferenceList]`
+
Список ссылок на карточки, в который добавляется ссылка
linkType:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/LinksLinkType_CL.adoc[LinksLinkType]`
+
Тип ссылки
foldersFolder:::
Тип: `xref:api/DocsVision/Platform/SystemCards/ObjectModel/FoldersFolder_CL.adoc[FoldersFolder]`
+
Папка, на которую создается ссылка

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/ReferenceListReference_CL.adoc[ReferenceListReference]`
+
Ссылка

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр referenceList или foldersFolder.
|===
