= IReferenceListService.CreateReference - метод (ReferenceList, LinksLinkType, BaseCard, String, Boolean)

Добавляет ссылку на карточку в [.dfn .term]_список ссылок_.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
ReferenceListReference CreateReference(ReferenceList referenceList, LinksLinkType linkType, BaseCard cardObject, string cardDescription, bool hardlink)
----

Параметры

referenceList::
  Тип: xref:../ReferenceList_CL.adoc[ReferenceList]
  +
  Список ссылок на карточки, в который добавляется ссылка
linkType::
  Тип: xref:../LinksLinkType_CL.adoc[LinksLinkType]
  +
  Тип ссылки
cardObject::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Карточка, на которую создается ссылка
cardDescription::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Описание ссылки
hardlink::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  Если true, то жесткая ссылка

Возвращаемое значение

::
  Тип: xref:../ReferenceListReference_CL.adoc[ReferenceListReference]
  +
  Ссылка

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр referenceList или cardObject.
|===

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IReferenceListService_IN.adoc[IReferenceListService - интерфейс]
