= IReferenceListService.CreateReferenceFromReference -- метод (ReferenceList, ReferenceListReference)

Создает ссылку на основе существующей ссылки.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
ReferenceListReference CreateReferenceFromReference(ReferenceList referenceList, ReferenceListReference reference)
----

Параметры::
referenceList:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/ReferenceList_CL.adoc[ReferenceList]
+
Список ссылок на карточки, в который добавляется ссылка
reference:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/ReferenceListReference_CL.adoc[ReferenceListReference]
+
Ссылка, на основе которой создается другая ссылка

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/ReferenceListReference_CL.adoc[ReferenceListReference]
+
Ссылка

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр referenceList или reference.
|===

== Заметки

Метод создает копию ссылки reference в списке ссылок referenceList.
