= IReferenceListService.TryGetReferenceListFromCard -- метод (Guid, Boolean, ReferenceList)

Получает _список ссылок на карточки_ из карточки.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool TryGetReferenceListFromCard(Guid cardId, bool createNew, out ReferenceList referenceList)
----

Параметры

cardId::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
+
Идентификатор карточки, из которой возвращает _список ссылок на карточки_
createNew::
Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
+
При true, если _список ссылок на карточки_ отсутствует в карточек, будет создан новый
referenceList::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/ReferenceList_CL.adoc[ReferenceList]
+
_Список ссылок на карточки_

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
+
Возвращает true, если есть _список ссылок на карточки_, иначе -- false

== Примеры

[source,csharp]
----
//Инициализация контекста объектов
IReferenceListService referenceListService = objectContext.GetService<IReferenceListService>();

// Карточка, из которой будет получен список ссылок на карточки
Guid cardId = new Guid("DED125DE-4097-E511-9417-90E6BA57B9F8");
ReferenceList referenceList;

// Получаем список ссылок
bool result = referenceListService.TryGetReferenceListFromCard(cardId, true, out referenceList);
----
