= IReferenceListService.RemoveReference -- метод (BaseCard, ReferenceList, ReferenceListReference)

Удаляет ссылку из _списка ссылок на карточки_.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool RemoveReference(BaseCard parentCard, ReferenceList referenceList, ReferenceListReference reference)
----

Параметры::
parentCard:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard]`
+
Карточка со списком ссылок
referenceList:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/ReferenceList_CL.adoc[ReferenceList]`
+
Список ссылок на карточки, из которого удаляется ссылка
reference:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/ReferenceListReference_CL.adoc[ReferenceListReference]`
+
Удаляемая ссылка

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Если `true` -- ссылка была удалена, иначе -- `false`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр referenceList или reference.
|===

== Заметки

Также удаляется обратная ссылка.
