= IStaffService.DeleteDeputy -- метод (StaffEmployee, StaffDeputy)

Удаляет заместителя сотрудника.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void DeleteDeputy(StaffEmployee employee, StaffDeputy deputy)
----

Параметры::
employee:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудник с заместителем
deputy:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffDeputy_CL.adoc[StaffDeputy]`
+
Заместитель, который должен быть удален

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `employee` или `deputy`.
|===

== Примеры

Ниже приведен пример удаления заместителя у текущего сотрудника.

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

StaffEmployee employee = staffService.GetCurrentEmployee();
StaffEmployee deputyEmployee = objectContext.GetObject<StaffEmployee>(new Guid("21E55387-6A4A-4B86-AC0F-1A454DE1F3DD")); <.>

StaffDeputy deputy = employee.Deputies.First(t => t.Employee = deputyEmployee); <.>

staffService.DeleteDeputy(employee, deputy); <.>
objectContext.AcceptChanges();   
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение текущего сотрудника и сотрудника, выполняющего роль заместителя.
<.> Получение удаляемого заместителя сотрудника.
<.> Удаление сотрудника.
