= IStateService.IsOperationAllowedFull - метод (BuiltInOperation, BaseCard)

Данный метод определяет возможность выполнения указанной операции с заданной карточкой, с учетом прав доступа.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
bool IsOperationAllowedFull(BuiltInOperation builtInOperation, BaseCard baseCard)
----

Параметры

builtInOperation::
  Тип: xref:../BuiltInOperation_CL.adoc[BuiltInOperation]
  +
  Встроенная операция
baseCard::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Карточка, для которой выполняется проверка

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  true - операция допустима, иначе false

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр builtInOperation или baseCard.
|===

== Примеры

В примере демонстрируется использование метода [.keyword .apiname]#IsOperationAllowedFull# для определения возможности отклонения задания текущим сотрудником

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStateService stateService = objectContext.GetService<IStateService>();

// Получение задания, для которого определяется возможность делегирования
Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));

// Проверка возможности отклонения сотрудником
bool isValid = stateService.IsOperationAllowedFull(Task.RejectOperation, task);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
