= IStaffService.SynchronizeUnitWithActiveDirectory - метод ([Тип параметра перегрузки])

Синхронизирует данные подразделения [.dfn .term]_справочника сотрудников_ с Active Directory.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
void SynchronizeUnitWithActiveDirectory(StaffUnit unit, IADSynchronizationSettings settings, ILongProcessManager syncManager)
----

Параметры

unit::
  Тип: xref:../StaffUnit_CL.adoc[StaffUnit]
  +
  Синхронизируемое подразделение
settings::
  Тип: xref:Entities/ActiveDirectory/ADSync/IADSynchronizationSettings_IN.adoc[IADSynchronizationSettings]
  +
  Параметры синхронизации
syncManager::
  Тип: xref:Entities/ILongProcessManager_IN.adoc[ILongProcessManager]
  +
  Менеджер длительных процессов

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр unit, settings или syncManager.
|===

== Заметки

Пример инициализации менеджера длительных процессов см. в xref:../../../../../pages/SC_TM_SyncFromAD.adoc[примере].

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStaffService_IN.adoc[IStaffService - интерфейс]
