= IStaffService.GetGroupItems - метод (StaffGroup, Boolean)

Возвращает элементы заданной группы.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IEnumerable<StaffGroupItem> GetGroupItems(StaffGroup group, bool selection)
----

Параметры

group::
  Тип: xref:../StaffGroup_CL.adoc[StaffGroup]
  +
  Группа
selection::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  true - возвращать только элементы, которые могут быть выбраны в карточке, иначе - false

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StaffGroupItem>
  +
  Все элементы типа xref:../StaffGroupItem_CL.adoc[StaffGroupItem]

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр group.
|===

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStaffService_IN.adoc[IStaffService - интерфейс]
