= IStateService.FindOperationByBuiltIn -- метод (BuiltInOperation, KindsCardKind)

Возвращает операцию (редактирования или перехода), определённую в _Конструкторе состояний_ и соответствующую заданной встроенной операции.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StatesOperation FindOperationByBuiltIn(BuiltInOperation builtInOperation, KindsCardKind kind)
----

Параметры::
builtInOperation:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BuiltInOperation_CL.adoc[BuiltInOperation]`
+
Встроенная операция

kind:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид карточки

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StatesOperation_CL.adoc[StatesOperation]`
+
Операция _конструктора состояний_

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `builtInOperation`.
|===
