= IStateService.GetStateMachineBranches - метод (KindsCardKind)

Возвращает список доступных, для указанного вида карточки, переходов автомата состояний.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IList<StatesStateMachineBranch> GetStateMachineBranches(KindsCardKind cardKind)
----

Параметры

cardKind::
  Тип: xref:../KindsCardKind_CL.adoc[KindsCardKind]
  +
  Вид карточки, для которого должны быть получены переходы автомата состояний

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/5y536ey6.aspx[System.Collections.Generic.IList]<StatesStateMachineBranch>
  +
  Список переходов автомата состояний, типа xref:../StatesStateMachineBranch_CL.adoc[StatesStateMachineBranch]

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
