= IStaffService.AddNewUnit - метод (StaffUnit)

Добавляет вложенное подразделение в указанную организацию.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
StaffUnit AddNewUnit(StaffUnit parentUnit)
----

Параметры

parentUnit::
  Тип: xref:../StaffUnit_CL.adoc[StaffUnit]
  +
  Организация, в которую добавляется подразделение

Возвращаемое значение

::
  Тип: xref:../StaffUnit_CL.adoc[StaffUnit]
  +
  Добавленное подразделение

== Заметки

Если параметр parentUnit не задан, организация будет добавлена в корень [.dfn .term]_Справочника сотрудников_.

== Примеры

Ниже приведен пример добавления новой организации в [.dfn .term]_Справочник сотрудников_

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStaffService staffService = objectContext.GetService<IStaffService>();

// Добавление новой организации (тип StaffUnitType.Organization)
StaffUnit unit = staffService.AddNewUnit(null);
unit.Type = StaffUnitType.Organization;
unit.Name = "ООО \"Василёк\"";
objectContext.SaveObject(unit);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStaffService_IN.adoc[IStaffService - интерфейс]
