= IStateService.IsOperationAllowed - метод (BuiltInOperation, BaseCard)

Определяет возможность выполнения встроенной операции, применительно к определенной карточке.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
bool IsOperationAllowed(BuiltInOperation builtInOperation, BaseCard baseCard)
----

Параметры

builtInOperation::
  Тип: xref:../BuiltInOperation_CL.adoc[BuiltInOperation]
  +
  Встроенная операция
baseCard::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Карточка, для которой выполняется проверка

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  true - операция допустима, иначе - false

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр builtInOperation или baseCard.
|===

== Заметки

Доступность операции проверяется исключительно на основе данных [.dfn .term]_конструктора состояние_.

== Примеры

В примере демонстрируется использование метода [.keyword .apiname]#IsOperationAllowed# для определения возможности делегирования задания другому сотруднику

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStateService stateService = objectContext.GetService<IStateService>();

// Получение задания, для которого определяется возможность делегирования
Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));

// Проверка возможности совершения операции делегирования
bool isValid = stateService.IsOperationAllowed(Task.DelegateOperation, task);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
