= IStaffService.IsEmployeeInGroup -- метод (StaffEmployee, StaffGroup, Boolean)

Определяет принадлежность сотрудника к указанной группе.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool IsEmployeeInGroup(StaffEmployee employee, StaffGroup group, bool searchInChildGroups)
----

Параметры::
employee:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудник

group:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffGroup_CL.adoc[StaffGroup]`
+
Группа, к которой осуществляется принадлежность

searchInChildGroups:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- также проверять подчиненные подразделения

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- пользователь входит в группу, иначе -- `false`
