= IStateService.ChangeState - метод (BaseCard, StatesStateMachineBranch)

Изменяет состояние карточки.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
void ChangeState(BaseCard card, StatesStateMachineBranch branch)
----

Параметры

card::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Карточка, для которой выполняется смена состояния
branch::
  Тип: xref:../StatesStateMachineBranch_CL.adoc[StatesStateMachineBranch]
  +
  Переход автомата состояний

== Примеры

Далее приведен пример завершения исполнения карточки, следуя переходу состояний - "Начато-Завершено"

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStateService stateService = objectContext.GetService<IStateService>();

// Задание, у которого изменяется состояние
Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));

// Смена состояния
stateService.ChangeState(task, stateService.FindBranchByBuiltIn(Task.NotStartedToCompletedByComplete, task.SystemInfo.State));
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
