= IStateService.GetOperations - метод (KindsCardKind)

Возвращает список операций (редактирования и перехода), определенных в [.dfn .term]_Конструкторе состояний_ для указанного вида карточки.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IList<StatesOperation> GetOperations(KindsCardKind cardKind);
----

Параметры

cardKind::
  Тип: xref:../KindsCardKind_CL.adoc[KindsCardKind]
  +
  Вид карточки

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/5y536ey6.aspx[System.Collections.Generic.IList]<StatesOperation>
  +
  Список операций в виде списка объектов типа xref:../StatesOperation_CL.adoc[StatesOperation]

== Заметки

Если для данного вида задействовано наследование, то будет возвращен список операций от родительского вида карточки.

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
