= IStaffService.SynchronizeUnitWithActiveDirectory - метод ([Тип параметра перегрузки])

Синхронизирует данные подразделения _справочника сотрудников_ с Active Directory.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void SynchronizeUnitWithActiveDirectory(StaffUnit unit, IADSynchronizationSettings settings, ILongProcessManager syncManager)
----

Параметры

unit::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StaffUnit_CL.adoc[StaffUnit]
+
Синхронизируемое подразделение
settings::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/ActiveDirectory/ADSync/IADSynchronizationSettings_IN.adoc[IADSynchronizationSettings]
+
Параметры синхронизации
syncManager::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/ILongProcessManager_IN.adoc[ILongProcessManager]
+
Менеджер длительных процессов

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр unit, settings или syncManager.
|===

== Заметки

Пример инициализации менеджера длительных процессов см. в xref:SC_TM_SyncFromAD.adoc[примере].
