= IStateService.GetOrCreatePreferredCardKindSetting - метод (KindsCardKind)

Возвращает, а при необходимости создает, настройки автомата состояний вида карточки.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
StatesCardKindStateSetting GetOrCreatePreferredCardKindSetting(KindsCardKind cardKind)
----

Параметры

cardKind::
  Тип: xref:../KindsCardKind_CL.adoc[KindsCardKind]
  +
  Вид карточки

Возвращаемое значение

::
  Тип: xref:../StatesCardKindStateSetting_CL.adoc[StatesCardKindStateSetting]
  +
  Настройки автомата состояний

== Заметки

В том случае, если вид cardKind наследует свои настройки от родительского вида, настройки автомата состояний будут сформированы для него (для родительского вида с собственными настройками).

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
