= IStaffService.SynchronizeWithActiveDirectory - метод (IADSynchronizationSettings, ILongProcessManager)

Синхронизирует данные групп, ролей и подразделений [.dfn .term]_справочника сотрудников_ с Active Directory.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
void SynchronizeWithActiveDirectory(IADSynchronizationSettings settings, ILongProcessManager syncManager)
----

Параметры

settings::
  Тип: xref:Entities/ActiveDirectory/ADSync/IADSynchronizationSettings_IN.adoc[IADSynchronizationSettings]
  +
  Параметры синхронизации Справочника сотрудников и Active Directory
syncManager::
  Тип: xref:Entities/ILongProcessManager_IN.adoc[ILongProcessManager]
  +
  Менеджер длительных процессов

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр settings или syncManager.
|===

== Заметки

Синхронизация элементов [.dfn .term]_справочника сотрудников_ возможна при наличии настроенной связи соответствующего элемента с контейнером в Active Directory.

== Примеры

Пример синхронизации доступен по xref:../../../../../pages/SC_TM_SyncFromAD.adoc[ссылке].

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStaffService_IN.adoc[IStaffService - интерфейс]
