= IStateService.AddOperation - метод (StatesCardKindStateSetting, Boolean)

Добавляет операцию в настройки автомата состояний вида карточки.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
StatesOperation AddOperation(StatesCardKindStateSetting kindStateSettings, bool editModeOnly)
----

Параметры

kindStateSettings::
  Тип: xref:../StatesCardKindStateSetting_CL.adoc[StatesCardKindStateSetting]
  +
  Настройки автомата состояний вида карточки в [.dfn .term]_конструкторе состояний_
editModeOnly::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  Если true, то операция доступна только в режиме редактирования

Возвращаемое значение

::
  Тип: xref:../StatesOperation_CL.adoc[StatesOperation]
  +
  Добавленное состояние

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр kindStateSettings.
|===

== Заметки

Название добавляемой операции будет сформировано на основе названия операции по умолчанию - "Операция N"

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
