= IStateService.GetKindStateSetting - метод (KindsCardKind)

Возвращает настройки вида карточки, заданные в [.dfn .term]_Конструкторе состояний_.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
StatesCardKindStateSetting GetKindStateSetting(KindsCardKind cardKind)
----

Параметры

cardKind::
  Тип: xref:../KindsCardKind_CL.adoc[KindsCardKind]
  +
  Вид карточки

Возвращаемое значение

::
  Тип: xref:../StatesCardKindStateSetting_CL.adoc[StatesCardKindStateSetting]
  +
  Параметры [.dfn .term]_Конструктора состояний_ для вида карточки

== Примеры

Далее приведен пример использования метода [.keyword .apiname]#GetKindStateSetting# при получении начального состояния карточки задание вида "На исполнение".

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStateService stateService = objectContext.GetService<IStateService>();
KindsCardKind cardKind = objectContext.GetObject<KindsCardKind>(new Guid("AB801854-70AF-4B6C-AB48-1B59B5D11AA9"));

// Получение настроек вида
StatesCardKindStateSetting stateSetting = stateService.GetKindStateSetting(cardKind);

// Получение начального состояния
StatesState startState = stateSetting.FirstState;
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
