= IStaffService.ActualizeEmployeesState -- метод

Актуализирует состояние сотрудника в соответствии с параметрами, заданными в _Справочнике сотрудников_.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void ActualizeEmployeesState()
----

== Заметки

Данный метод выполняет блокировку или разблокировку сотрудника, основываясь на значении периода его отсутствия, определённом в _Справочнике сотрудников_. Проверка осуществляется для всех сотрудников, присутствующих в _Справочнике сотрудников_. Данный метод используется в бизнес-процессе "Процесс актуализации состояния сотрудников".

== Примеры

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

staffService.ActualizeEmployeesState(); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Осуществление актуализации.
