= IStateService.FindOperationByBuiltIn -- метод (BuiltInOperation, BaseCard)

Возвращает операцию _конструктора состояний_, соответствующую указанной встроенной операции.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StatesOperation FindOperationByBuiltIn(BuiltInOperation builtInOperation, BaseCard baseCard)
----

Параметры::
builtInOperation:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BuiltInOperation_CL.adoc[BuiltInOperation]`
+
Встроенная операция

baseCard:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard]`
+
Карточка, относительно типа которой определяется переход

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StatesOperation_CL.adoc[StatesOperation]`
+
Операция _конструктора состояний_

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `builtInOperation`.
|===
