= IStaffService.AddUnitTreeEmployeesToGroup -- метод (StaffGroup, StaffUnit)

Добавляет всех сотрудников подразделения в указанную группу _справочника сотрудников_.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
List<StaffGroupItem> AddUnitTreeEmployeesToGroup(StaffGroup group, StaffUnit unit)
----

Параметры::
group:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffGroup_CL.adoc[StaffGroup]`
+
Группа, в которую добавляются сотрудники
unit:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffUnit_CL.adoc[StaffUnit]`
+
Подразделение, сотрудники которого добавляются в группу group

Возвращаемое значение::
Тип: `https://msdn.microsoft.com/ru-ru/library/6sh2ey19.aspx[System.Collections.Generic.List]<StaffGroupItem>
+
Список добавленных элементов типа xref:api/DocsVision/BackOffice/ObjectModel/StaffGroupItem_CL.adoc[StaffGroupItem]

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр group или unit.
|===
