= IStaffService.AddNewUnit -- метод (StaffUnit)

Добавляет вложенное подразделение в указанную организацию.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StaffUnit AddNewUnit(StaffUnit parentUnit)
----

Параметры::
parentUnit:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffUnit_CL.adoc[StaffUnit]`
+
Организация, в которую добавляется подразделение

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffUnit_CL.adoc[StaffUnit]`
+
Добавленное подразделение

== Заметки

Если параметр parentUnit не задан, организация будет добавлена в корень _Справочника сотрудников_.

== Примеры

Ниже приведен пример добавления новой организации в _Справочник сотрудников_

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStaffService staffService = objectContext.GetService<IStaffService>();

// Добавление новой организации (тип StaffUnitType.Organization)
StaffUnit unit = staffService.AddNewUnit(null);
unit.Type = StaffUnitType.Organization;
unit.Name = "ООО \"Василёк\"";
objectContext.SaveObject(unit);
----
