= IStaffService.FindDeputiesWhereEmployeeIsDeputy -- метод (StaffEmployee)

Возвращает список замещений сотрудников, в которых указанный сотрудник является заместителем.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
List<StaffDeputy> FindDeputiesWhereEmployeeIsDeputy(StaffEmployee employee);
----

Параметры::
employee:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee]
+
Сотрудник, для которого определяется список замещений

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/6sh2ey19.aspx[System.Collections.Generic.List]<StaffDeputy>
+
Список замещений, представленный коллекцией объектов xref:api/DocsVision/BackOffice/ObjectModel/StaffDeputy_CL.adoc[StaffDeputy]

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр employee.
|===

== Заметки

Заместители сотрудников добавляются в _Справочнике сотрудников_.

== Примеры

Ниже приведен пример использования сервиса для отбора прав у текущего сотрудника, позволяющих ему, как заместителю другого сотрудника, выполнять подписание документов ЭЦП.

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStaffService staffService = objectContext.GetService<IStaffService>();

// Получение списка замещений в который участвует текущий сотрудник
List<StaffDeputy> deputy = staffService.FindDeputiesWhereEmployeeIsDeputy(staffService.GetCurrentEmployee());

// Сброс флага, разрешающего подписание документов, для всех замещений
foreach (StaffDeputy item in deputy)
{
 item.Signature = false;
}
objectContext.AcceptChanges();
----
