= IStaffService.SynchronizeWithActiveDirectory -- метод (IADSynchronizationSettings, ILongProcessManager)

Синхронизирует данные групп, ролей и подразделений _справочника сотрудников_ с Active Directory.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void SynchronizeWithActiveDirectory(IADSynchronizationSettings settings, ILongProcessManager syncManager)
----

Параметры::
settings:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/ActiveDirectory/ADSync/IADSynchronizationSettings_IN.adoc[IADSynchronizationSettings]
+
Параметры синхронизации Справочника сотрудников и Active Directory
syncManager:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/ILongProcessManager_IN.adoc[ILongProcessManager]
+
Менеджер длительных процессов

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр settings или syncManager.
|===

== Заметки

Синхронизация элементов _справочника сотрудников_ возможна при наличии настроенной связи соответствующего элемента с контейнером в Active Directory.

== Примеры

Пример синхронизации доступен по xref:samples/object-model/staff-sync-ad.adoc[ссылке].
