= IStateService.AddOperation -- метод (StatesCardKindStateSetting, Boolean)

Добавляет операцию в настройки автомата состояний вида карточки.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StatesOperation AddOperation(StatesCardKindStateSetting kindStateSettings, bool editModeOnly)
----

Параметры

kindStateSettings::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesCardKindStateSetting_CL.adoc[StatesCardKindStateSetting]
+
Настройки автомата состояний вида карточки в _конструкторе состояний_
editModeOnly::
Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
+
Если true, то операция доступна только в режиме редактирования

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesOperation_CL.adoc[StatesOperation]
+
Добавленное состояние

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр kindStateSettings.
|===

== Заметки

Название добавляемой операции будет сформировано на основе названия операции по умолчанию -- "Операция N"
