= IStateService.AreOperationsAllowed -- метод (IEnumerable<BuiltInOperation>, BaseCard)

Проверяет возможность выполнения встроенных операций, применительно к определенной карточке.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
IDictionary<BuiltInOperation, bool> AreOperationsAllowed(IEnumerable<BuiltInOperation> builtInOperations, BaseCard baseCard)
----

Параметры::
builtInOperations:::
Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<BuiltInOperation>
+
Список проверяемых встроенных операций
baseCard:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard]
+
Карточка, для которой выполняется проверка

Возвращаемое значение::
Тип: https://msdn.microsoft.com/ru-ru/library/s4ys34ea.aspx[System.Collections.Generic.IDictionary]<BuiltInOperation, Boolean>
+
Коллекция пар: встроенная операция и признак того, что она может быть выполнена (если значение -- true)

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр builtInOperations или baseCard.
|===

== Заметки

Список операций проверяется исключительно на основе данных _конструктора состояние_; проверка возможности выполнения операции по ролевой модели не выполняется.
