= IStaffService.PropagateNotAvailable - метод (StaffUnit)

Распространяет признак "Не показывать при выборе" с родительского подразделения на дочерние подразделения и сотрудников.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
void PropagateNotAvailable(StaffUnit staffUnit)
----

Параметры

staffUnit +
xref:../StaffUnit_CL.adoc[StaffUnit]::
  Подразделение [.dfn .term]_Справочника сотрудников_, для дочерних элементов которого устанавливается признак "Не показывать при выборе"

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр staffUnit.
|===

== Примеры

Ниже приведен пример распространения признака "Не показывать при выборе" с подразделения с идентификатором 00000000-0000-0000-0000-000000000000, на вложенные подразделения и сотрудников

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

StaffUnit unit = objectContext.GetObject<StaffUnit>(new Guid("00000000-0000-0000-0000-000000000000"));
IStaffService staffService = objectContext.GetService<IStaffService>();

staffService.PropagateNotAvailable(unit);
objectContext.AcceptChanges();
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStaffService_IN.adoc[IStaffService - интерфейс]
