= IStateService.FindLineBranchesByStartState - метод (StatesState)

Возвращает все допустимые переходы состояний карточки, имеющей указанное начальное состояние.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IEnumerable<StatesStateMachineBranch> FindLineBranchesByStartState(StatesState state)
----

Параметры

state::
  Тип: xref:../StatesState_CL.adoc[StatesState]
  +
  Начальное состояние

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StatesStateMachineBranch>
  +
  Коллекция объектов типа xref:../StatesStateMachineBranch_CL.adoc[StatesStateMachineBranch]

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр state.
|===

== Примеры

Ниже приведен пример использования метода [.keyword .apiname]#FindLineBranchesByStartState# при получении всех доступных переходов из состояния Делегировано для карточки задания вида На исполнение

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов
        
// Получение сервиса
IStateService stateService = objectContext.GetService<IStateService>();
KindsCardKind cardKind = objectContext.GetObject<KindsCardKind>(new Guid("AB801854-70AF-4B6C-AB48-1B59B5D11AA9"));

// Получение состояния Делегировано
StatesState state = stateService.FindStateByBuiltIn(Task.DelegatedState, cardKind);

// Доступные переходы из состояния Делегирования
IEnumerable<StatesStateMachineBranch> branches = stateService.FindLineBranchesByStartState(state);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
