= IStaffService.AddNewGroup - метод (StaffGroup)

Данный метод позволяет добавить новою подгруппу в существующую группу сотрудников.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
StaffGroup AddNewGroup(StaffGroup parentGroup)
----

Параметры

parentGroup::
  Тип: xref:../StaffGroup_CL.adoc[StaffGroup]
  +
  Группа пользователей, в которую осуществляется добавление новой группы

Возвращаемое значение

::
  Тип: xref:../StaffGroup_CL.adoc[StaffGroup]
  +
  Объектная модель новой группы пользователей

== Заметки

Если parentGroup не задан, группа будет добавлена в корневой узел групп, в [.dfn .term]_Справочнике сотрудников_.

== Примеры

Ниже приведен пример простого добавления нового подразделения в корневой узел, в [.dfn .term]_Справочник сотрудников_

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса для работы со Справочником сотрудников
IStaffService staffService = objectContext.GetService<IStaffService>();

// Добавление подразделения
StaffUnit staffUnit = staffService.AddNewUnit(null);
staffUnit.Name = "Подразделение компании";

// Сохранение изменений
objectContext.SaveObject(staffUnit);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStaffService_IN.adoc[IStaffService - интерфейс]
