= IStaffService.AddNewEmployeePicture - метод (StaffEmployee)

Добавляет сотруднику новую фотографию.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
StaffPicture AddNewEmployeePicture(StaffEmployee employee)
----

Параметры

employee::
  Тип: xref:../StaffEmployee_CL.adoc[StaffEmployee]
  +
  Сотрудник

Возвращаемое значение

::
  Тип: xref:../StaffPicture_CL.adoc[StaffPicture]
  +
  Фотография сотрудника

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр employee.
|===

== Примеры

Ниже приведен пример добавления фотографии текущему сотруднику. Изображение загружается с диска.

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStaffService staffService = objectContext.GetService<IStaffService>();

// Получение текущего сотрудника
StaffEmployee employee = staffService.GetCurrentEmployee();

// Добавление фотографии
StaffPicture picture = staffService.AddNewEmployeePicture(employee);
picture.Image = new Bitmap(@"Z:\EmployeePicture.jpg");
objectContext.AcceptChanges();
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStaffService_IN.adoc[IStaffService - интерфейс]
