= IStaffService.AddEmployeeToGroup - метод (StaffGroup, StaffEmployee)

Добавляет указанного сотрудника в группу сотрудников.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
StaffGroupItem AddEmployeeToGroup(StaffGroup group, StaffEmployee employee)
----

Параметры

group::
  Тип: xref:../StaffGroup_CL.adoc[StaffGroup]
  +
  Группа, в которую включается сотрудника
employee::
  Тип: xref:../StaffEmployee_CL.adoc[StaffEmployee]
  +
  Добавляемый сотрудник

Возвращаемое значение

::
  Тип: xref:../StaffGroupItem_CL.adoc[StaffGroupItem]
  +
  Сотрудник, включенный в группу

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр group или employee.
|===

== Примеры

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStaffService staffService = objectContext.GetService<IStaffService>();

// Получение группы, в которую добавляется сотрудник
StaffGroup group = staffService.GetGroup(new Guid("00000000-0000-0000-0000-000000000000"));

// Получение сотрудника
StaffEmployee employee = staffService.Get(new Guid("00000000-0000-0000-0000-000000000001"));

// Добавление сотрудника
staffService.AddEmployeeToGroup(group, employee);
objectContext.SaveObject(group);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStaffService_IN.adoc[IStaffService - интерфейс]
