= IStateService.IsOperationAllowedFull - метод (StatesOperation, BaseCard)

Определяет возможность выполнения операции ([.dfn .term]_конструктора состояний_), применительно к определенной карточке, с учетом прав доступа.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
bool IsOperationAllowedFull(StatesOperation operation, BaseCard baseCard)
----

Параметры

operation::
  Тип: xref:../StatesOperation_CL.adoc[StatesOperation]
  +
  Операция из [.dfn .term]_конструктора состояний_
baseCard::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Карточка, для которой выполняется проверка

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  true - операция допустима, иначе - false

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр operation или baseCard.
|===

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
