= IStateService.ChangeState -- метод (BaseCard, StatesState, Boolean, String)

Изменяет состояние карточки.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void ChangeState(BaseCard card, StatesState endState, bool startBusinessProcess, out string startBusinessProcessErrors)
----

Параметры::
card:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard]
+
Карточка, для которой выполняется смена состояния
endState:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesState_CL.adoc[StatesState]
+
Конечное состояние карточки
startBusinessProcess:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Если true, то будут запущены бизнес-процессы, связанные с изменением состояния карточки
startBusinessProcessErrors:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Журнал ошибок запуска бизнес-процессов
