= IStaffService.GetRoleEmployees - метод (StaffRole)

Возвращает список сотрудников с указанной ролью.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
System.Collections.Generic.IEnumerable<StaffEmployee> GetRoleEmployees(StaffRole role)
----

Параметры

role::
  Тип: xref:../StaffRole_CL.adoc[StaffRole]
  +
  Роль сотрудника, подразделения или группы

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StaffEmployee>
  +
  Список сотрудников типа xref:../StaffEmployee_CL.adoc[StaffEmployee]

== Заметки

Метод [.keyword .apiname]#GetRoleEmployees#, помимо сотрудников непосредственно имеющих роль `role`, включает сотрудников из групп, ролей и подразделений, у которых включена роль `role`.

== Примеры

Пример получения списка сотрудников, имеющих роль с идентификатором 00000000-0000-0000-0000-000000000000

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов
StaffRole role = objectContext.GetObject<StaffRole>(new Guid("00000000-0000-0000-0000-000000000000"));
IStaffService staffService = objectContext.GetService<IStaffService>();

var employees = staffService.GetRoleEmployees(role);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStaffService_IN.adoc[IStaffService - интерфейс]
