= IStaffService.CreateFolder -- метод (StaffUnit, String)

Создает папку с указанным именем в корневой папке подразделения.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
FoldersFolder CreateFolder(StaffUnit parentUnit, string folderName)
----

Параметры

parentUnit::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StaffUnit_CL.adoc[StaffUnit]
+
Подразделение, в корневую папку которого добавляется папка
folderName::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Название добавляемой папки

Возвращаемое значение::
Тип: xref:api/DocsVision/Platform/SystemCards/ObjectModel/FoldersFolder_CL.adoc[FoldersFolder]
+
Созданная папка

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр parentUnit, либо folderName не имеет значения. Также ошибка может быть возвращена в случае отсутствия у parentUnit корневой папки.
|===

== Заметки

В свойствах подразделения должна быть указана корневая папка.
