= IStateService.AddBranch -- метод (StatesCardKindStateSetting, StatesState, StatesState, StatesOperation)

Создает новый переход в автомате состояний вида карточки.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StatesStateMachineBranch AddBranch(StatesCardKindStateSetting kindStateSettings, StatesState startState, StatesState endState, StatesOperation operation)
----

Параметры::
kindStateSettings:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesCardKindStateSetting_CL.adoc[StatesCardKindStateSetting]
+
Настройки автомата состояний для вида карточки
startState:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesState_CL.adoc[StatesState]
+
Начальное состояние перехода
endState:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesState_CL.adoc[StatesState]
+
Конечное состояние перехода
operation:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesOperation_CL.adoc[StatesOperation]
+
Операция перехода

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesStateMachineBranch_CL.adoc[StatesStateMachineBranch]
+
Переход автомата состояний

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр kindStateSettings, startState или operation.
|===
