= IStaffService.FindDeputiesWhereEmployeeIsDeputy - метод (StaffEmployee)

Возвращает список замещений сотрудников, в которых указанный сотрудник является заместителем.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
List<StaffDeputy> FindDeputiesWhereEmployeeIsDeputy(StaffEmployee employee);
----

Параметры

employee::
  Тип: xref:../StaffEmployee_CL.adoc[StaffEmployee]
  +
  Сотрудник, для которого определяется список замещений

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/6sh2ey19.aspx[System.Collections.Generic.List]<StaffDeputy>
  +
  Список замещений, представленный коллекцией объектов xref:../StaffDeputy_CL.adoc[StaffDeputy]

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр employee.
|===

== Заметки

Заместители сотрудников добавляются в [.dfn .term]_Справочнике сотрудников_.

== Примеры

Ниже приведен пример использования сервиса для отбора прав у текущего сотрудника, позволяющих ему, как заместителю другого сотрудника, выполнять подписание документов ЭЦП.

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStaffService staffService = objectContext.GetService<IStaffService>();

// Получение списка замещений в который участвует текущий сотрудник
List<StaffDeputy> deputy = staffService.FindDeputiesWhereEmployeeIsDeputy(staffService.GetCurrentEmployee());

// Сброс флага, разрешающего подписание документов, для всех замещений
foreach (StaffDeputy item in deputy)
{
 item.Signature = false;
}
objectContext.AcceptChanges();
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStaffService_IN.adoc[IStaffService - интерфейс]
