= IStateService.AreOperationsAllowed -- метод (IEnumerable<StatesOperation>, BaseCard)

Проверяет возможность выполнения операций (_конструктора состояний_), применительно к определенной карточке.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
IDictionary<StatesOperation, bool> AreOperationsAllowed(IEnumerable<StatesOperation> statesOperations, BaseCard baseCard)
----

Параметры::
statesOperations:::
Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StatesOperation>
+
Список проверяемых операций
baseCard:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard]
+
Карточка, для которой выполняется проверка

Возвращаемое значение::
Тип: https://msdn.microsoft.com/ru-ru/library/s4ys34ea.aspx[System.Collections.Generic.IDictionary]<StatesOperation, Boolean>
+
Коллекция пар: операция и признак того, что она может быть выполнена (если значение -- true)

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр statesOperations или baseCard.
|===

== Заметки

Список операций проверяется исключительно на основе данных _конструктора состояние_; проверка возможности выполнения операции по ролевой модели не выполняется.
