= IStateService.FindBranchByBuiltIn - метод (BuiltInBranch, StatesState)

Возвращает переход автомата состояний, соответствующий определенному начальному состоянию и указанному встроенному переходу.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
StatesStateMachineBranch FindBranchByBuiltIn(BuiltInBranch builtInBranch, StatesState state)
----

Параметры

builtInBranch::
  Тип: xref:../BuiltInBranch_CL.adoc[BuiltInBranch]
  +
  Встроенный переход
state::
  Тип: xref:../StatesState_CL.adoc[StatesState]
  +
  Начальное состояние

Возвращаемое значение

::
  Тип: xref:../StatesStateMachineBranch_CL.adoc[StatesStateMachineBranch]
  +
  Переход состояний, представленный в [.dfn .term]_Конструкторе состояний_

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр builtInBranch или state.
|===

== Примеры

Ниже приведен пример использования метода [.keyword .apiname]#FindBranchByBuiltIn# для получения перехода из состояния Отложено в Отклонено, для карточки задания вида [.dfn .term]_На исполнение_

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStateService stateService = objectContext.GetService<IStateService>();
KindsCardKind cardKind = objectContext.GetObject<KindsCardKind>(new Guid("AB801854-70AF-4B6C-AB48-1B59B5D11AA9"));

// Получение состояния Отложено
StatesState state = stateService.FindStateByBuiltIn(Task.DeferredState, cardKind);

// Получение перехода из Отложено в Отклонено
StatesStateMachineBranch branch = stateService.FindBranchByBuiltIn(Task.DeferredToRejectedByReject, state);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
