= IStaffService.AddGroupFolder -- метод (StaffGroup, Guid, Boolean)

Добавляет папку в папки группы указанной группе сотрудников.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StaffGroupFolder AddGroupFolder(StaffGroup staffGroup, Guid folderId, bool showInTab)
----

Параметры::
staffGroup:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StaffGroup_CL.adoc[StaffGroup]
+
Группа, которой добавляется папка группы
folderId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор добавляемой папки
showInTab:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- папка будет отображаться в области _моих папок_ пользователя, иначе false

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StaffGroupFolder_CL.adoc[StaffGroupFolder]
+
Папка группы

== Примеры

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IStaffService staffService = objectContext.GetService<IStaffService>();

// Получение группы
StaffGroup group = staffService.GetGroup(new Guid("00000000-0000-0000-0000-000000000000"));

// Добавление к группе существующей папки с идентификатором 00000000-0000-0000-0000-000000000001
staffService.AddGroupFolder(group, new Guid("00000000-0000-0000-0000-000000000001"), true);
objectContext.AcceptChanges();
----
