= IStateService.AddBranch - метод (StatesCardKindStateSetting, StatesState, StatesState, StatesOperation)

Создает новый переход в автомате состояний вида карточки.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
StatesStateMachineBranch AddBranch(StatesCardKindStateSetting kindStateSettings, StatesState startState, StatesState endState, StatesOperation operation)
----

Параметры

kindStateSettings::
  Тип: xref:../StatesCardKindStateSetting_CL.adoc[StatesCardKindStateSetting]
  +
  Настройки автомата состояний для вида карточки
startState::
  Тип: xref:../StatesState_CL.adoc[StatesState]
  +
  Начальное состояние перехода
endState::
  Тип: xref:../StatesState_CL.adoc[StatesState]
  +
  Конечное состояние перехода
operation::
  Тип: xref:../StatesOperation_CL.adoc[StatesOperation]
  +
  Операция перехода

Возвращаемое значение

::
  Тип: xref:../StatesStateMachineBranch_CL.adoc[StatesStateMachineBranch]
  +
  Переход автомата состояний

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр kindStateSettings, startState или operation.
|===

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService - интерфейс]
