= ITaskService.CompleteTask -- метод (Task, String, StaffEmployee)

Завершает задание от имени указанного сотрудника.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BuiltInState CompleteTask(Task task, string comments, StaffEmployee completedUser)
----

Параметры::
task:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]`
+
Задание
comments:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Комментарий к завершению задания
completedUser:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудник, завершающий задание

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BuiltInState_CL.adoc[BuiltInState]`
+
Состояние завершения

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр task или completedUser.
|`https://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException]` |Ошибка возвращается, если у владельца сессии недостаточно прав для завершения задания.
|===

== Заметки

Данный метод завершает задание с указанием completedUser в качестве сотрудника, завершившего задание. Операция выполняется в контексте владельца сессии, поэтому владелец сессии должен иметь право на завершении данного задания. Для изменения фактического состояния карточки необходимо использовать метод xref:api/DocsVision/BackOffice/ObjectModel/Services/IStateService.ChangeState_MT.adoc[IStateService.ChangeState] .
