= ITaskGroupService.ReorderSelectedPerformers - метод (ObjectCollection<TaskGroupSelectedPerformer>)

Повторно выстраивает порядок исполнения группы задания исполнителями.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
void ReorderSelectedPerformers(ObjectCollection<TaskGroupSelectedPerformer> selectedPerformers)
----

Параметры

selectedPerformers::
  Тип: xref:../../../Platform/ObjectModel/ObjectCollection_CL.adoc[ObjectCollection]<TaskGroupSelectedPerformer>
  +
  Коллекция исполнителей группы заданий - xref:../TaskGroupSelectedPerformer_CL.adoc[TaskGroupSelectedPerformer]

== Заметки

Данный метод просто заново проставляет значение `Order` у исполнителя группы заданий.

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskGroupService_IN.adoc[ITaskGroupService - интерфейс]
