= ITaskListService.AddTask -- метод (TaskList, Task, BaseCard)

Добавляет существующее задание в предоставленный список заданий

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskListTask AddTask(TaskList taskList, Task task, BaseCard parentCard)
----

Параметры::
taskList:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskList_CL.adoc[TaskList]
+
Список заданий
task:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]
+
Добавляемое задание
parentCard:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard]
+
Карточка, содержащая список заданий, в который осуществляется добавление

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskListTask_CL.adoc[TaskListTask]
+
Задание в списке заданий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр taskList, task или parentCard.
|===

== Заметки

Данный метод записывает событие добавления подчиненного задания в журнал карточки parentCard.
