= ITaskService.StopExecutionTask -- метод (Task)

Прекращает исполнение задания.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void StopExecutionTask(Task task)
----

Параметры::
task:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]`
+
Задание, которое будет прекращено

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `task`.
|`https://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException]` |Ошибка возвращается, если недостаточно прав для прекращения задания.
|===

== Заметки

Прекращение задания, в отличие от завершения, не является штатной операцией, и необходима для принудительного завершения задания. Исполнение подчиненных заданий не прекращается.

== Примеры

[source,csharp]
----
<.>

ITaskService taskService = objectContext.GetService<ITaskService>();
IStateService stateService = objectContext.GetService<IStateService>(); <.>

Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

taskService.StopExecutionTask(task);
stateService.ChangeState(task, stateService.FindStateByBuiltIn(Task.CompletedState, task)); <.>
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
<.> Получение сервисов.
<.> Получение задания.
<.> Прекращение исполнения задания.
