= ITaskService.AddPerformer - метод (Task, StaffEmployee)

Добавляет сотрудника в список назначенных исполнителей задания.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
void AddPerformer(Task task, StaffEmployee performer)
----

Параметры

task::
  Тип: xref:../Task_CL.adoc[Task]
  +
  Задание, в которое назначается исполнитель
performer::
  Тип: xref:../StaffEmployee_CL.adoc[StaffEmployee]
  +
  Исполнитель, непосредственно взявший задание в исполнение

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр task или performer.
|===

== Примеры

Ниже приведен простой пример использования метода [.keyword .apiname]#AddPerformer# для назначения исполнителя задания.

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение задания и сотрудника-исполнителя по идентификаторам
Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));
StaffEmployee performer = objectContext.GetObject<StaffEmployee>(new Guid("00000000-0000-0000-0000-000000000001"));

// Получение сервиса для работы с заданиями
ITaskService taskService = objectContext.GetService<ITaskService>();

// Назначение исполнителя в задание
taskService.AddPerformer(task, performer);
objectContext.AcceptChanges();
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskService_IN.adoc[ITaskService - интерфейс]
