= ITaskService.IsUserCurrentPerformer -- метод (Task, StaffEmployee)

Определяет, входит ли указанный сотрудник в список текущих исполнителей.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool IsUserCurrentPerformer(Task task, StaffEmployee user)
----

Параметры::
task:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]`
+
Задание

user:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудник

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- сотрудник входит в число текущих исполнителей, иначе -- `false`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `task` или `user`.
|===
