= ITaskService.AddChildCopyField - метод (Task)

Добавляет в настройки задания параметры копирования поля из родительского задания в дочернее.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
TaskPresetChildCopyField AddChildCopyField(Task task)
----

Параметры

task::
  Тип: xref:../Task_CL.adoc[Task]
  +
  Задание, для которого выполняется настройка

Возвращаемое значение

::
  Тип: xref:../TaskPresetChildCopyField_CL.adoc[TaskPresetChildCopyField]
  +
  Объектная модель копируемого поля

== Заметки

Данный метод позволяет добавить настройку копирования полей из родительского задания в подчиненное для отдельной карточки [.dfn .term]_Задания_. Указанные поля (дополнительно к тем, что определенны в [.dfn .term]_Справочнике видов карточек_) будут скопированы в подчиненное задание при создании из родительской карточки.

== Примеры

В приведенном примере демонстрируется использование метода [.keyword .apiname]#AddChildCopyField# при добавлении полей, копируемых в подчиненное задание.

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение необходимых сервисов
IMetadataProvider metadataProvider = objectContext.GetService<IMetadataProvider>();
ITaskService taskService = objectContext.GetService<ITaskService>();

// Получение задания
Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));

// Добавление настройки копирования поля
TaskPresetChildCopyField taskPresetChildCopyField = taskService.AddChildCopyField(task);
            
// Получение поля Название из секции Задание
DocsVision.Platform.Data.Metadata.CardModel.SectionField sectionField = metadataProvider.GetField(new Guid("F5C843C0-5CE1-4727-81BF-0C764A43243B"));
DocsVision.Platform.Data.Metadata.CardModel.CardSection section = sectionField.GetParent<DocsVision.Platform.Data.Metadata.CardModel.CardSection>();

// Определение значений копируемого поля
taskPresetChildCopyField.SectionName = section.Name;
taskPresetChildCopyField.FieldId = sectionField.Id;
taskPresetChildCopyField.FieldName = sectionField.DisplayName.GetLocalization(System.Globalization.CultureInfo.CurrentCulture);
taskPresetChildCopyField.FieldAlias = sectionField.Name;

// Формирование пути к секции
Stack<Guid> sections = new Stack<Guid>();
while (section != null)
{
 sections.Push(section.Id);
 section = section.GetParent<DocsVision.Platform.Data.Metadata.CardModel.CardSection>();
}
taskPresetChildCopyField.SectionPath = CardFieldSetting.BuildSectionPath(sections);          
objectContext.SaveObject<Task>(task);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskService_IN.adoc[ITaskService - интерфейс]
