= ITaskService.CreateChildTask - метод (Task, KindsCardKind, BaseCard, TaskList)

Создает дочернее задание.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
Task CreateChildTask(Task parentTask, KindsCardKind kind, BaseCard parentCard, TaskList parentCardTaskList)
----

Параметры

parentTask::
  Тип: xref:../Task_CL.adoc[Task]
  +
  Основное задание
kind::
  Тип: xref:../KindsCardKind_CL.adoc[KindsCardKind]
  +
  Вид создаваемого задания
parentCard::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Родительская карточка
parentCardTaskList::
  Тип: xref:../TaskList_CL.adoc[TaskList]
  +
  Список подчинённых заданий из родительской карточки

Возвращаемое значение

::
  Тип: xref:../Task_CL.adoc[Task]
  +
  Подчиненное задание

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр kind, parentCard или parentCardTaskList.
|===

== Примеры

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
ITaskService taskService = objectContext.GetService<ITaskService>();

// Получение основного задания
Task parentTask = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));

// Создание дочернего задания
Task childTask = taskService.CreateChildTask(parentTask, parentTask.SystemInfo.CardKind, parentTask, parentTask.MainInfo.ChildTaskList);
childTask.MainInfo.Name = "Подчиненное задание";
objectContext.AcceptChanges();
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskService_IN.adoc[ITaskService - интерфейс]
