= ITaskGroupService.AddDelegatePreset -- метод (TaskGroupPresets, StaffUnit)

Добавляет подразделение в число исполнителей в индивидуальные настройки исполнителя группы заданий.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroupPresetsDelegate AddDelegatePreset(TaskGroupPresets presets, StaffUnit unit)
----

Параметры::
presets:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/TaskGroupPresets_CL.adoc[TaskGroupPresets]`
+
Группа заданий

unit:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffUnit_CL.adoc[StaffUnit]`
+
Подразделение

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/TaskGroupPresetsDelegate_CL.adoc[TaskGroupPresetsDelegate]`
+
Индивидуальные настройки исполнителя группы заданий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `presets`.
|===
