= ITaskGroupService.AddDelegatePresetSearchWord -- метод (TaskGroupPresets, Guid)

Добавляет поисковое слово в число исполнителей в индивидуальные настройки исполнителя группы заданий.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroupPresetsDelegate AddDelegatePresetSearchWord(TaskGroupPresets presets, Guid searchWordId)
----

Параметры::
presets:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/TaskGroupPresets_CL.adoc[TaskGroupPresets]`
+
Группа заданий
searchWordId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор поискового слова

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/TaskGroupPresetsDelegate_CL.adoc[TaskGroupPresetsDelegate]`
+
Индивидуальные настройки исполнителя группы заданий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `presets`.
|===
