= ITaskGroupService.GetKindSettings -- метод (KindsCardKind)

Возвращает настройки вида группы заданий.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroupSetting GetKindSettings(KindsCardKind kind)
----

Параметры

kind::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardKind_CL.adoc[KindsCardKind]
+
Вид группы заданий, для которого получаем настройки

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/KindSetting/TaskGroupSetting_CL.adoc[TaskGroupSetting]
+
Настройки вида

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр kind.
|===

== Заметки

В данном случае имеются ввиду настройки, которые были установлены в _справочнике видов карточек_ у вида группы заданий.
