= ITaskService.AddSignature - метод (Task, X509Certificate2, StatesOperation, Guid, IEnumerable<CardFieldSetting>, IEnumerable<Document>)

Данный метод добавляет новую подпись в список подписей карточки [.dfn .term]_Задание_, и устанавливает ЭЦП на указанные поля карточки, а также на указанные документы.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
BaseCardSignature AddSignature(Task task, X509Certificate2 certificate, StatesOperation operation, Guid signatureType, IEnumerable<CardFieldSetting> fields, IEnumerable<Document> documents)
----

Параметры

task::
  Тип: xref:../Task_CL.adoc[Task]
  +
  Задание, содержащее подписываемые данные
certificate::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]
  +
  Сертификат сотрудника, которым будет выполнено подписания
operation::
  Тип: xref:../StatesOperation_CL.adoc[StatesOperation]
  +
  Подписываемая операция
signatureType::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Тип подписи, который может быть получен из [.keyword .apiname]#TaskOperationSignatureSetting.Name#
fields::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<CardFieldSetting>
  +
  Коллекция подписываемых полей типа xref:Entities/KindSetting/CardFieldSetting_CL.adoc[CardFieldSetting], определенных для карточки в Справочнике видов карточек
documents::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<Document>
  +
  Коллекция подписываемых документов типа xref:../Document_CL.adoc[Document]

Возвращаемое значение

::
  Тип: xref:../BaseCardSignature_CL.adoc[BaseCardSignature]
  +
  Подпись

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр task и operation.
|===

== Заметки

Настройки (подписываемые поля; операция, при которой будет произведено подписание; и т.д.), используемые при подписании, задаются в [.dfn .term]_Справочнике видов карточек_.

== Примеры

Ниже приведен пример скрипта, который позволяет осуществить подписание операции в карточке [.dfn .term]_Задание_, также будет подписан основной файл

[source,pre,codeblock,language-csharp]
----
using System.Linq;
using System.Reflection;

using DocsVision.BackOffice.ObjectModel;
using DocsVision.BackOffice.ObjectModel.Services;
using DocsVision.BackOffice.WinForms.Controls;
using DocsVision.Platform.ObjectModel;

namespace BackOffice
{
 public class CardTaskТестScript : CardTaskНа_ознакомлениеScript
 {
  private void SignOperation_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
  {
   ObjectContext objectContext = base.CardControl.ObjectContext;
   Task task = (base.BaseObject as Task);

   // Получение сервиса для работы с заданиями
   ITaskService taskService = objectContext.GetService<ITaskService>();

   // Метод (EnsureSign) проверки данных карточки перед подписанием не является публичным, поэтому используем механизм отражения
   MethodInfo ensureSign = this.CardControl.GetType().GetMethod("EnsureSign", BindingFlags.NonPublic | BindingFlags.Instance);
   bool result = (ensureSign.Invoke(this.CardControl, null) as bool?).Value;
   if (!result) return;

   bool cancel = false;

   // Выбор сертификата сотрудника
   var certificate = SelectCertificateForm.SelectCertificate(ref cancel, base.CardControl.ObjectContext);
   if (cancel) return;

   // Получение настроек вида карточки Задания, для получения настроек подписания
   var taskSetting = taskService.GetKindSettings(task.SystemInfo.CardKind);

   // Выбор Вида подписи (определена в Справочнике видов карточек, в секции Подпись/Подписание операций) с названием SignOperation 
   var signatureSetting = taskSetting.OperationSignatures.First(t => t.SignatureName = "SignOperation");
   
   // Составление списка документов из ссылок
   IEnumerable<Document> documents = task.MainInfo.ReferenceList.References.Select(t => objectContext.GetObject<Document>(t.Card));

   // Добавление подписи. Из настроек подписания, для примера, берем первую настройку
   taskService.AddSignature(task, certificate, signatureSetting.SignedOperations[0], new System.Guid(signatureSetting.Name), signatureSetting.Fields, documents);
  }
 }
}
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskService_IN.adoc[ITaskService - интерфейс]
