= ITaskService.ResolveDelegatePerformer - метод (Task, StaffEmployee)

Получает список текущих исполнителей задания, за которых указанный сотрудник может делегировать задание.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IEnumerable<StaffEmployee> ResolveDelegatePerformer(Task task, StaffEmployee delegatedEmployee)
----

Параметры

task::
  Тип: xref:../Task_CL.adoc[Task]
  +
  Задание
delegatedEmployee::
  Тип: xref:../StaffEmployee_CL.adoc[StaffEmployee]
  +
  Сотрудник, для которого выполняется проверка

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StaffEmployee>
  +
  Список сотрудников типа xref:../StaffEmployee_CL.adoc[StaffEmployee]

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр task или delegatedEmployee.
|===

== Заметки

Если текущий сотрудник входит в число текущих исполнителей задания, то будет возращен только он. При получении списка определяется принадлежность сотрудника к заместителям исполнителей задания. Проверка прав на делегирование не выполняется.

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskService_IN.adoc[ITaskService - интерфейс]
