= ITaskListService.GetTasksTree - метод (TaskList)

Возвращает список узлов дерева заданий, построенного из списка заданий.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IEnumerable<TaskTreeInfo> GetTasksTree(TaskList taskList)
----

Параметры

taskList::
  Тип: xref:../TaskList_CL.adoc[TaskList]
  +
  Список заданий

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<TaskTreeInfo>
  +
  Коллекция информации по узлам xref:../TaskTreeInfo_CL.adoc[TaskTreeInfo] дерева заданий

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр taskList.
|===

== Примеры

Далее приведен пример получения дерева заданий из списка задания с использованием метода [.keyword .apiname]#GetTasksTree#

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
ITaskListService taskListService = objectContext.GetService<ITaskListService>();

// Получение документа, содержащего список заданий
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

// Получение дерева заданий из списка заданий документа
IEnumerable<TaskTreeInfo> tree = taskListService.GetTasksTree(document.MainInfo.Tasks);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskListService_IN.adoc[ITaskListService - интерфейс]
