= ITaskGroupService.ValidateInactivePerformers -- метод (TaskGroup, String)

Проверяет группу заданий на отсутствие активных исполнителей.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool ValidateInactivePerformers(TaskGroup taskGroup, out string errorMessage)
----

Параметры::
taskGroup:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskGroup_CL.adoc[TaskGroup]
+
Группа заданий
errorMessage:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Сообщение об ошибке

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- в списке исполнителей есть активные исполнители, иначе -- `false`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр taskGroup.
|===

== Заметки

Активные исполнители -- исполнители, у которых состояние находится в значении "Активен".
