= ITaskListService.AddTaskGroup - метод (TaskList, TaskGroup, BaseCard)

Добавляет группу заданий в предоставленный список заданий.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
TaskListTaskGroup AddTaskGroup(TaskList taskList, TaskGroup taskGroup, BaseCard parentCard)
----

Параметры

taskList::
  Тип: xref:../TaskList_CL.adoc[TaskList]
  +
  Список заданий, в который добавляется группа заданий
taskGroup::
  Тип: xref:../TaskGroup_CL.adoc[TaskGroup]
  +
  Добавляемая группа заданий
parentCard::
  Тип: xref:../BaseCard_CL.adoc[BaseCard]
  +
  Карточка, содержащая список заданий, в который добавляется группа заданий

Возвращаемое значение

::
  Тип: xref:../TaskListTaskGroup_CL.adoc[TaskListTaskGroup]
  +
  Группа карточек

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр taskList, taskGroup или parentCard.
|===

== Заметки

Дополнительно записывает событие добавления группы карточек в историю работы с карточкой.

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskListService_IN.adoc[ITaskListService - интерфейс]
