= ITaskGroupService.AddSelectedPerformer - метод (TaskGroup, StaffEmployee)

Добавляет сотрудника в список выбранных исполнителей группы заданий.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
TaskGroupSelectedPerformer AddSelectedPerformer(TaskGroup routeStage, StaffEmployee employee)
----

Параметры

routeStage::
  Тип: xref:../TaskGroup_CL.adoc[TaskGroup]
  +
  Группа заданий, в список выбранных исполнителей которой добавляется сотрудник
employee::
  Тип: xref:../StaffEmployee_CL.adoc[StaffEmployee]
  +
  Добавляемый сотрудник

Возвращаемое значение

::
  Тип: xref:../TaskGroupSelectedPerformer_CL.adoc[TaskGroupSelectedPerformer]
  +
  Выбранный исполнитель

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр routeStage или employee.
|===

== Примеры

Ниже приведен пример добавления текущего сотрудника в список выбранных исполнителей группы заданий.

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервисов
ITaskGroupService taskGroupService = objectContext.GetService<ITaskGroupService>();
IStaffService staffService = objectContext.GetService<IStaffService>();

// Получение группы заданий
TaskGroup taskGroup = objectContext.GetObject<TaskGroup>(new Guid("00000000-0000-0000-0000-000000000000"));

// Добавление исполнителя
TaskGroupSelectedPerformer selectedPerformer = taskGroupService.AddSelectedPerformer(taskGroup, staffService.GetCurrentEmployee());
objectContext.AcceptChanges();
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskGroupService_IN.adoc[ITaskGroupService - интерфейс]
