= ITaskService.InitializeDefaults -- метод (Task)

Инициализация параметров нового задания.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void InitializeDefaults(Task task)
----

Параметры::
task:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]
+
Задание

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр task.
|===

== Заметки

При вызове метода InitializeDefaults, владелец сессии устанавливается в качестве автора задания, а настройки заполняются в соответствии с настройками вида карточки. Данный метод рекомендуется вызывать после создания задания методом xref:api/DocsVision/BackOffice/ObjectModel/Services/ITaskService.CreateTask_MT.adoc[CreateTask].
