= ITaskService.RejectTask -- метод (Task, StaffEmployee, String)

Отклоняет задание.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void RejectTask(Task task, StaffEmployee employee, string comment)
----

Параметры

task::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]
+
Отклоняемое задание
employee::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee]
+
Сотрудник, отклонивший задание
comment::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Комментарий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр task или employee.
|https://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException] |Ошибка возвращается, если недостаточно прав для отзыва задания.
|===

== Примеры

Ниже приведен пример отклонения задания. Для фактической смены состояния карточки необходимо использовать метод IStateService.ChangeState.

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервисов
ITaskService taskService = objectContext.GetService<ITaskService>();
IStateService stateService = objectContext.GetService<IStateService>();
IStaffService staffService = objectContext.GetService<IStaffService>();
            
Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));

// Отклонение задания
taskService.RejectTask(task, staffService.GetCurrentEmployee(), "Уже выполнено");
stateService.ChangeState(task, stateService.FindStateByBuiltIn(Task.RejectedState, task));
objectContext.AcceptChanges();   
----
