= ITaskService.AddSelectedPerformer - метод (TaskMainInfo, StaffEmployee)

Добавляет указанного сотрудника в список выбранных исполнителей задания.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
TaskSelectedPerformer AddSelectedPerformer(TaskMainInfo mainInfo, StaffEmployee employee)
----

Параметры

mainInfo::
  Тип: xref:../TaskMainInfo_CL.adoc[TaskMainInfo]
  +
  Основная информация карточки
employee::
  Тип: xref:../StaffEmployee_CL.adoc[StaffEmployee]
  +
  Выбранный исполнитель

Возвращаемое значение

::
  Тип: xref:../TaskSelectedPerformer_CL.adoc[TaskSelectedPerformer]
  +
  Сущность выбранного исполнителя

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр mainInfo или employee.
|===

== Примеры

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
ITaskService taskService = objectContext.GetService<ITaskService>();

// Получение задания и исполнителя для него
Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));
StaffEmployee employee = objectContext.GetObject<StaffEmployee>(new Guid("00000000-0000-0000-0000-000000000001"));

// Добавление выбранного исполнителя
taskService.AddSelectedPerformer(task.MainInfo, employee);
objectContext.AcceptChanges();   
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskService_IN.adoc[ITaskService - интерфейс]
