= ITaskService.AddChildKindSettings - метод (KindsCardKind, ObjectCollection<TaskPresetChildKindSetting>, Boolean)

Добавляет в переданную коллекцию настроек вид, доступный для выбора при создании подчинённого задания.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
TaskPresetChildKindSetting AddChildKindSettings(KindsCardKind kindsCardKind, ObjectCollection<TaskPresetChildKindSetting> kindSettings, bool creatable)
----

Параметры

kindsCardKind::
  Тип: xref:../KindsCardKind_CL.adoc[KindsCardKind]
  +
  Вид карточки
kindSettings::
  Тип: xref:../../../Platform/ObjectModel/ObjectCollection_CL.adoc[ObjectCollection]<TaskPresetChildKindSetting>
  +
  Коллекция настроек видов (типа xref:../TaskPresetChildKindSetting_CL.adoc[TaskPresetChildKindSetting]) для подчиненного задания
creatable::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  true - данный вид может быть создан из родительского задания, иначе - false

Возвращаемое значение

::
  Тип: xref:../TaskPresetChildKindSetting_CL.adoc[TaskPresetChildKindSetting]
  +
  Параметры создания вида подчиненного задания

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskService_IN.adoc[ITaskService - интерфейс]
