= ITaskGroupService.AddDelegatePreset -- метод (TaskGroupPresets, StaffRole)

Добавляет роль в число исполнителей в индивидуальные настройки исполнителя группы заданий.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroupPresetsDelegate AddDelegatePreset(TaskGroupPresets presets, StaffRole role)
----

Параметры

presets::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskGroupPresets_CL.adoc[TaskGroupPresets]
+
Группа заданий
role::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StaffRole_CL.adoc[StaffRole]
+
Роль

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskGroupPresetsDelegate_CL.adoc[TaskGroupPresetsDelegate]
+
Индивидуальные настройки исполнителя группы заданий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр presets.
|===
