= ITaskService.AddSelectedPerformer -- метод (TaskMainInfo, StaffEmployee)

Добавляет указанного сотрудника в список выбранных исполнителей задания.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskSelectedPerformer AddSelectedPerformer(TaskMainInfo mainInfo, StaffEmployee employee)
----

Параметры

mainInfo::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskMainInfo_CL.adoc[TaskMainInfo]
+
Основная информация карточки
employee::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee]
+
Выбранный исполнитель

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskSelectedPerformer_CL.adoc[TaskSelectedPerformer]
+
Сущность выбранного исполнителя

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр mainInfo или employee.
|===

== Примеры

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервиса
ITaskService taskService = objectContext.GetService<ITaskService>();

// Получение задания и исполнителя для него
Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));
StaffEmployee employee = objectContext.GetObject<StaffEmployee>(new Guid("00000000-0000-0000-0000-000000000001"));

// Добавление выбранного исполнителя
taskService.AddSelectedPerformer(task.MainInfo, employee);
objectContext.AcceptChanges();   
----
