= ITaskService.GetLastDelegate - метод (Task)

Возвращает последнюю запись списка делегирования.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
TaskDelegate GetLastDelegate(Task task)
----

Параметры

task::
  Тип: xref:../Task_CL.adoc[Task]
  +
  Задание

Возвращаемое значение

::
  Тип: xref:../TaskDelegate_CL.adoc[TaskDelegate]
  +
  Элемент списка делегирования

== Примеры

Приведенный далее пример демонстрирует использование метода [.keyword .apiname]#GetLastDelegate# при получении сотрудника (первого из списка), которому выполнено делегирование.

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
ITaskService taskService = objectContext.GetService<ITaskService>();

// Получение задания
Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));

// Получение сотрудника, которому выполнено делегирование
TaskDelegate taskDelegate = taskService.GetLastDelegate(task);
StaffEmployee employee = taskDelegate.DelegatedTo.FirstOrDefault().Employee;
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskService_IN.adoc[ITaskService - интерфейс]
