= ITaskGroupService.ValidateBeforeSendToPerformance -- метод (TaskGroup, String)

Определяет готовность группы заданий к отправке на исполнение.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool ValidateBeforeSendToPerformance(TaskGroup assignment, out string errorMessage)
----

Параметры::
assignment:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/TaskGroup_CL.adoc[TaskGroup]`
+
Группа заданий
errorMessage:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Список ошибок, мешающих отправке

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- группа заданий может быть отправлена, иначе -- `false`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр assignment.
|===

== Заметки

В ходе проверки определяется заполнение следующих данных: автор; название; контроллер или ответственный исполнитель, если группа заданий на контроле; исполнители. Также проверяется вхождение индивидуальных сроков исполнения заданий исполнителями в общий срок исполнения группы заданий.
