= ITaskService.SetTaskCompletionResult -- метод (Task, TaskCompletionParameter)

Устанавливает результат завершения задания.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void SetTaskCompletionResult(Task task, TaskCompletionParameter completionParameter)
----

Параметры

task::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]
+
Задание, для которого устанавливается результат завершения
completionParameter::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskCompletionParameter_CL.adoc[TaskCompletionParameter]
+
Параметры завершения задания

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр task или completionParameter.
|===
