= ITaskService.ValidateForBegin -- метод (Task, String)

Определяет готовность задания к отправке на исполнение.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool ValidateForBegin(Task task, out string errorMessage)
----

Параметры::
task:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]
+
Задание
errorMessage:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
+
Сообщение с ошибкой

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
+
true -- ошибок не обнаружено, иначе -- false

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр task.
|===

== Заметки

Для успешного прохождения проверки, должны быть заполнены автор и название задания, а также выбран исполнитель/исполнители задания.
