= ITaskListService.CreateTaskGroup - метод (TaskList, TaskGroup)

Добавляет существующую группу заданий в предоставленный список заданий, без внесения изменений в историю карточки.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskListTaskGroup CreateTaskGroup(TaskList taskList, TaskGroup taskGroup)
----

Параметры

taskList::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskList_CL.adoc[TaskList]
+
Список заданий, в который будет добавлена группа заданий
taskGroup::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskGroup_CL.adoc[TaskGroup]
+
Добавляемая группа заданий

Возвращаемое значение::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskListTaskGroup_CL.adoc[TaskListTaskGroup]
+
Добавленная группа заданий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр taskList или taskGroup.
|===

== Заметки

Данный метод, в отличии от метода [.keyword .apiname]#AddTaskGroup#, не добавляет соответствующую запись в историю карточки.

== Примеры

[source,csharp]
----
//Инициализация контекста объектов

// Получение настройки 
IStaffService staffService = objectContext.GetService<IStaffService>();        
ITaskGroupService taskGroupService = objectContext.GetService<ITaskGroupService>();
ITaskListService taskListService = objectContext.GetService<ITaskListService>();

// Получение документа со списком заданий           
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));
TaskList taskList = document.MainInfo.Tasks;

// Получение вида карточки для группы заданий (в примере - Группа заданий УД)
KindsCardKind kind = objectContext.GetObject<KindsCardKind>(new Guid("6D76D0A7-5434-40F2-912E-6370D33C3151"));

// Создание новой группы заданий          
TaskGroup taskGroup = taskGroupService.CreateTaskGroup(kind);
taskGroup.MainInfo.Name = "Группа заданий документа";
taskGroup.MainInfo.Author = staffService.GetCurrentEmployee();

// Добавление группы в список заданий
taskListService.CreateTaskGroup(taskList, taskGroup);
objectContext.AcceptChanges();
----
