= ITaskListService.RemoveTask -- метод (TaskList, Task, BaseCard)

Удаляет задание из переданного списка заданий.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void RemoveTask(TaskList taskList, Task task, BaseCard parentCard)
----

Параметры::
taskList:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/TaskList_CL.adoc[TaskList]
+
Список заданий
task:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]
+
Удаляемое задание
parentCard:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard]
+
Карточка, в которой содержится taskList

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр taskList, task или parentCard.
|https://msdn.microsoft.com/ru-ru/library/system.exception.aspx[System.Exception] |Ошибка возвращается при наличии установленной на taskList блокировки.
|===

== Примеры

Ниже приведен пример, в котором производится удаление первого задания в списке заданий документа

[source,csharp]
----
//Инициализация контекста объектов

// Получение сервиса
ITaskListService taskListService = objectContext.GetService<ITaskListService>();

// Получение документа с заполненным списком заданий
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

// Получение списка заданий из документа и первого задания из списка
TaskList taskList = document.MainInfo.Tasks;
Task task = taskList.Tasks.First().Task;

// Удаление задания
taskListService.RemoveTask(taskList, task, document);
objectContext.AcceptChanges();
----
