= ITaskService.RejectTask - метод (Task, StaffEmployee, String)

Отклоняет задание.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
void RejectTask(Task task, StaffEmployee employee, string comment)
----

Параметры

task::
  Тип: xref:../Task_CL.adoc[Task]
  +
  Отклоняемое задание
employee::
  Тип: xref:../StaffEmployee_CL.adoc[StaffEmployee]
  +
  Сотрудник, отклонивший задание
comment::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Комментарий

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр task или employee.
|https://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException] |Ошибка возвращается, если недостаточно прав для отзыва задания.
|===

== Примеры

Ниже приведен пример отклонения задания. Для фактической смены состояния карточки необходимо использовать метод [.keyword .apiname]#IStateService.ChangeState#.

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервисов
ITaskService taskService = objectContext.GetService<ITaskService>();
IStateService stateService = objectContext.GetService<IStateService>();
IStaffService staffService = objectContext.GetService<IStaffService>();
            
Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));

// Отклонение задания
taskService.RejectTask(task, staffService.GetCurrentEmployee(), "Уже выполнено");
stateService.ChangeState(task, stateService.FindStateByBuiltIn(Task.RejectedState, task));
objectContext.AcceptChanges();   
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/ITaskService_IN.adoc[ITaskService - интерфейс]
