= ITaskService.GetPartSignatureInfo -- метод (BaseCardSignaturePart signaturePart)

Возвращает информацию о части подписи документа.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

[[ITaskService_GetPartSignatureInfo__section_u1q_yty_mpb]]
== Синтаксис

[source,csharp]
----
SignatureInfo GetPartSignatureInfo(Task task, BaseCardSignaturePart signaturePart, X509Certificate2 certificate);
----

Параметры::
task:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]`
+
Задание, из которого будет получена информация о подписи
signaturePart:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/BaseCardSignaturePart_CL.adoc[BaseCardSignaturePart]`
+
Часть подписи
certificate:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]`
+
Сертификат подписи

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/DigitalSignature/SignatureInfo_CL.adoc[SignatureInfo]`
+
Информация о подписи
