= ITaskService.GetLastDelegate -- метод (Task)

Возвращает последнюю запись списка делегирования.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskDelegate GetLastDelegate(Task task)
----

Параметры::
task:::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/Task_CL.adoc[Task]`
+
Задание

Возвращаемое значение::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/TaskDelegate_CL.adoc[TaskDelegate]`
+
Элемент списка делегирования

== Примеры

Приведенный далее пример демонстрирует использование метода GetLastDelegate при получении сотрудника (первого из списка), которому выполнено делегирование.

[source,csharp]
----
<.>

ITaskService taskService = objectContext.GetService<ITaskService>(); <.>

Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

TaskDelegate taskDelegate = taskService.GetLastDelegate(task);
StaffEmployee employee = taskDelegate.DelegatedTo.FirstOrDefault().Employee; <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение задания.
<.> Получение сотрудника, которому выполнено делегирование.
