= IUserProfileCardService - интерфейс

Описывает сервис для работы с карточкой настроек пользователя.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public interface IUserProfileCardService
----

== Методы

[cols=",",options="header",]
|===
|Имя |Описание
|GetCertificate(String) |Получает сертификат пользователя с указанным именем учетной записи.
|GetSetting(Int32) |Получает из профиля пользователя настройку указанного типа.
|GetSetting(Int32, Object) |Получает из профиля пользователя настройку указанного типа, в случае ее отсутствия, возвращает значение второго параметра.
|GetSetting(Int32, Object, Guid) |Получает из профиля пользователя настройку указанного типа. Параметр objectId конкретизирует настройку, в случае присутствии нескольких однотипных настроек.
|SetCertificate(String, X509Certificate2) |Задает сертификат указанному пользователю.
|SetPersonalFolder(String, FoldersFolder) |Задает значение личной папки пользователя в карточке.
|SetSetting(Int32, Object) |Сохраняет в профиль настройку заданного типа.
|SetSetting(Int32, Guid, Object) |Сохраняет в профиль настройку с заданным идентификатором.
|===

== Примеры

Приведен пример простого использования методов сервиса - запись и чтение настроек

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

//задаем тип свойства и идентификатор
int settingType = 999;
Guid objectID = Guid.NewGuid();

//задаем значение свойства
iUserProfileCardService.SetSetting(settingType, objectID, "Белый");

//получаем значение свойства, если свойство отсутствует, что в контексте примера конечно невозможно, то вернется пуста строка
string value = (iUserProfileCardService.GetSetting(settingType, string.Empty, objectID) as string);
Console.WriteLine(value);
----

Еще один пример использования сервиса - создание и установка личной папки пользователя

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

//получение сервисов по работе со справочником сотрудников и профилями пользователей
IStateService stateService = objectContext.GetService<IStateService>();
IUserProfileCardService iUserProfileCardService = objectContext.GetService<IUserProfileCardService>();

//получение пользователя с идентификатором 00000000-0000-0000-0000-000000000000
StaffEmployee staffEmployee = staffService.Get(new Guid("00000000-0000-0000-0000-000000000000"));

//получение корневой папки "Папки"
FoldersFolder foldersFolder = objectContext.GetObject<FoldersFolder>(new Guid("FFFFFFFF-FFFF-0003-FFFF-000000000000"));

//создание новой папки с названием "OtherFolder"
FoldersFolder newfoldersFolder = new FoldersFolder();
newfoldersFolder.Name = "OtherFolder";

//добавление к корневой созданной папки и сохранение контекста
foldersFolder.Folders.Add(newfoldersFolder);
objectContext.AcceptChanges();

//назначение персональной папки
iUserProfileCardService.SetPersonalFolder(staffEmployee.AccountName, newfoldersFolder);
objectContext.AcceptChanges();
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services - пространство имен]
