= IVersionedFileCardService.Download - метод (VersionedFileCard)

Сохраняет последнюю версию версионного файла на диск.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
string Download(VersionedFileCard versionedFileCard)
----

Параметры

versionedFileCard::
  Тип: xref:../../../Platform/ObjectManager/SystemCards/VersionedFileCard_CL.adoc[VersionedFileCard]
  +
  Карточка файла с версиями

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Расположение выгруженного файла

== Заметки

Возвращает текущую версию файла. Блокировки не производится.

== Примеры

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Получение сервиса
IVersionedFileCardService versionedFileCardService = objectContext.GetService<IVersionedFileCardService>();

// Получение существующей карточки файла с версиями
VersionedFileCard versionedFileCard = versionedFileCardService.OpenCard(new Guid("00000000-0000-0000-0000-000000000000"));

// Выгрузка файла
string path = versionedFileCardService.Download(versionedFileCard);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IVersionedFileCardService_IN.adoc[IVersionedFileCardService - интерфейс]
