= IVersionedFileCardService.CheckIn -- метод (VersionedFileCard, Boolean, Int32, String, Boolean, String, Guid)

Снимает блокировку с карточки файла с версиями.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/ObjectModel/Services/Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void CheckIn(VersionedFileCard versionedFileCard, bool keepCheckout, int level, string comment, bool commentToVersion, string checkOutPath, System.Guid userId)
----

Параметры::
versionedFileCard:::
Тип: xref:api/DocsVision/Platform/ObjectManager/SystemCards/VersionedFileCard_CL.adoc[VersionedFileCard]
+
Карточка файла с версиями
keepCheckout:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Для сохранения блокировки должно быть значение true
level:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.int32.aspx[System.Int32]`
+
Позиция числа, значение которого будет увеличено, в номере версии
comment:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Комментарий к версии или к файлу
commentToVersion:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
При значении true, `comment` -- комментарий к версии, иначе -- комментарий к файлу
checkOutPath:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Путь к выгруженному файлу
userId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор сотрудника, выполнившего блокировку файла

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.invalidoperationexception.aspx[System.InvalidOperationException] |Ошибка возникает, если файл не заблокирован, либо заблокирован, но не сотрудником с идентификатором `userId`, либо выгруженный файл `checkOutPath` не существует.
|===

== Примеры

Пример снятия блокировки с заблокированного и первого файла документа с повышением вспомогательного номера версии. Предполагается, что блокировка и изменения были произведены ранее.

[source,csharp]
----
//Инициализация контекста объектов
        
IVersionedFileCardService versionedFileCardService = objectContext.GetService<IVersionedFileCardService>();
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

// Получение файла с версией из документа
VersionedFileCard versionedFileCard = versionedFileCardService.OpenCard(document.Files[0].FileId);

// Снятие блокировки с повышением версии
versionedFileCardService.CheckIn(versionedFileCard, false, 1);
----
