= IVersionedFileCardService.GetVersionNumber - метод (VersionedFileCard, Guid)

Возвращает версии файла в текстовом виде.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
string GetVersionNumber(VersionedFileCard versionedFileCard, Guid versionId)
----

Параметры

versionedFileCard::
  Тип: xref:../../../Platform/ObjectManager/SystemCards/VersionedFileCard_CL.adoc[VersionedFileCard]
  +
  Версионный файл

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Тестовая метка версии

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр versionedFileCard или versionId.
|===

== Примеры

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

//
IVersionedFileCardService versionedFileCardService = objectContext.GetService<IVersionedFileCardService>();

Document document = objectContext.GetObject<Document>(new Guid("94F4E425-917C-E511-9416-90E6BA57B9F8"));
DocumentFile documentFile = document.Files.First();
          
VersionedFileCard fileCard =  versionedFileCardService.OpenCard(documentFile.FileId);
string version = versionedFileCardService.GetVersionNumber(fileCard, documentFile.FileVersionId);
----

*На уровень выше:* xref:../../../../../api/DocsVision/BackOffice/ObjectModel/Services/IVersionedFileCardService_IN.adoc[IVersionedFileCardService - интерфейс]
