= ITaskListService.RemoveTask -- метод (TaskList, Task, BaseCard)

Удаляет задание из переданного списка заданий.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void RemoveTask(TaskList taskList, Task task, BaseCard parentCard)
----

Параметры::
taskList:::
Тип: `xref:BackOffice-ObjectModel-Task:TaskList_CL.adoc[TaskList]`
+
Список заданий

task:::
Тип: `xref:BackOffice-ObjectModel-Task:Task_CL.adoc[Task]`
+
Удаляемое задание

parentCard:::
Тип: `xref:xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Карточка, в которой содержится `taskList`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `taskList`, `task` или `parentCard`.
|`https://msdn.microsoft.com/ru-ru/library/system.exception.aspx[System.Exception]` |Ошибка возвращается при наличии установленной на `taskList` блокировки.
|===

== Примеры

Ниже приведен пример, в котором производится удаление первого задания в списке заданий документа

[source,csharp]
----
<.>

ITaskListService taskListService = objectContext.GetService<ITaskListService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

TaskList taskList = document.MainInfo.Tasks; <.>
Task task = taskList.Tasks.First().Task;

taskListService.RemoveTask(taskList, task, document); <.>
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение документа с заполненным списком заданий.
<.> Получение списка заданий из документа и первого задания из списка.
<.> Удаление задания.
