= ITaskListService.AddTask -- метод (TaskList, Task, BaseCard)

Добавляет существующее задание в предоставленный список заданий

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskListTask AddTask(TaskList taskList, Task task, BaseCard parentCard)
----

Параметры::
taskList:::
Тип: `xref:BackOffice-ObjectModel:TaskList_CL.adoc[TaskList]`
+
Список заданий

task:::
Тип: `xref:BackOffice-ObjectModel:Task_CL.adoc[Task]`
+
Добавляемое задание

parentCard:::
Тип: `xref:BackOffice-ObjectModel:BaseCard_CL.adoc[BaseCard]`
+
Карточка, содержащая список заданий, в который осуществляется добавление

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:TaskListTask_CL.adoc[TaskListTask]`
+
Задание в списке заданий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `taskList`, `task` или `parentCard`.
|===

== Заметки

Данный метод записывает событие добавления подчиненного задания в журнал карточки parentCard.
