= ITaskListService.AddTaskGroup -- метод (TaskList, TaskGroup, BaseCard)

Добавляет группу заданий в предоставленный список заданий.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskListTaskGroup AddTaskGroup(TaskList taskList, TaskGroup taskGroup, BaseCard parentCard)
----

Параметры::
taskList:::
Тип: `xref:BackOffice-ObjectModel-Task:TaskList_CL.adoc[TaskList]`
+
Список заданий, в который добавляется группа заданий

taskGroup:::
Тип: `xref:BackOffice-ObjectModel-Task:TaskGroup_CL.adoc[TaskGroup]`
+
Добавляемая группа заданий

parentCard:::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Карточка, содержащая список заданий, в который добавляется группа заданий

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Task:TaskListTaskGroup_CL.adoc[TaskListTaskGroup]`
+
Группа карточек

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `taskList`, `taskGroup` или `parentCard`.
|===

== Заметки

Дополнительно записывает событие добавления группы карточек в историю работы с карточкой.
