= IDocumentService.CheckMainFileSigned -- метод (Document, DocumentFile)

Определяет наличие подписи у указанного основного файла документ.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool CheckMainFileSigned(Document document, DocumentFile mainFile)
----

Параметры::
document:::
Тип: `xref:BackOffice-ObjectModel:Document_CL.adoc[Document]`
+
Документ

mainFile:::
Тип: `xref:BackOffice-ObjectModel:DocumentFile_CL.adoc[DocumentFile]`
+
Файл документа

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- файл подписан, иначе -- `false`

== Примеры

Далее приведен пример использования метода `CheckMainFileSigned` при определении наличия подписи у первого основного файла документа.

[source,csharp]
----
<.>

IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

DocumentFile documentFile = document.Files.First(t => t.FileType = DocumentFileType.Main); <.>

bool result = documentService.CheckMainFileSigned(document, documentFile); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение документа.
<.> Получение первого основного файла.
<.> Проверка подписи.
