= IDocumentService.GetPartSignatureInfo -- метод (BaseCardSignaturePart signaturePart)

Возвращает информацию о части подписи документа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

[[IDocumentService_GetPartSignatureInfo__section_u1q_yty_mpb]]
== Синтаксис

[source,csharp]
----
SignatureInfo GetPartSignatureInfo(Document document, BaseCardSignaturePart signaturePart, X509Certificate2 certificate);
----

Параметры::
document:::
Тип: `xref:BackOffice-ObjectModel-Document:Document_CL.adoc[Document]`
+
Документ, из которого будет получена информация о подписи

signaturePart:::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BaseCardSignaturePart_CL.adoc[BaseCardSignaturePart]`
+
Часть подписи

certificate:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]`
+
Сертификат подписи

Возвращаемое значение::
Тип: `xref:BackOffice-DigitalSignature:SignatureInfo_CL.adoc[SignatureInfo]`
+
Информация о подписи
