= IDocumentService.GetKindSettings -- метод (KindsCardKind)

Возвращает настройки заданного вида карточки Документ.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
DocumentSetting GetKindSettings(KindsCardKind kind)
----

Параметры::
kind:::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид карточки Документ

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Services-Entities:Entities/KindSetting/DocumentSetting_CL.adoc[DocumentSetting]`
+
Настройки вида документа

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `kind`.
|===

== Заметки

Настройки вида карточки задаются в _Справочнике видов карточек_.

== Примеры

[source,csharp]
----
<.>

IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>

KindsCardKind kind = objectContext.GetObject<KindsCardKind>(new Guid("7DB9044E-91B7-447D-8CAA-5E5A4967B8D4")); <.>

DocumentSetting documentSettings = documentService.GetKindSettings(kind); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение вида карточки (в примере "Заявка").
<.> Получение настроек вида карточки.
