= IDocumentService.AddSignatures -- метод (Document, SignedCms, bool)

Добавляет коллекцию новых подписей в список подписей карточки. Устанавливает ЭЦП на поля, основные и дополнительные файлы документа. Позволяет использовать для подписания криптографическое сообщение типа `SignedCms`. Позволяет проверять срок действия добавляемых подписей.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
IEnumerable<BaseCardSignature> AddSignatures(Document document, SignedCms signedCms, bool verifySignatures)
----

Параметры::
document:::
Тип: `xref:BackOffice-ObjectModel:Document_CL.adoc[Document]`
+
Подписываемый документ

signedCms:::
Тип: `http://msdn.microsoft.com/ru-ru/library/System.Security.Cryptography.Pkcs.SignedCms.aspx[SignedCms]`
+
Сообщение CMS/PKCS 7

verifySignatures:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
При `true`, проверяется срок действия подписей

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<BaseCardSignature>`
+
Список подписей

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `document` или `signedCms`.
|===

== Заметки

Данный метод может быть использован для импорта подписанного файла, сохраненного в виде сообщения CMS/PKCS 7, в карточку. {dv} экспортирует подписанные файлы в один файл с расширением `.p7s`, либо в два файла: экспортируемый файл и отдельно сообщение CMS/PKCS 7 в виде файла с расширением `.p7s`. Для извлечения исходного файла из сообщения предназначен метод `xref:BackOffice-ObjectModel-Services-IDocumentService:IDocumentService.DecodeSignedDocument_MT.adoc[IDocumentService.DecodeSignedDocument]`.
