= IDocumentService.AttachMainFile -- метод (Document, string, SignedCms, bool)

Добавляет в документ подпись в качестве основного файла документа, проверяет срок действия подписи.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
DocumentFile AttachMainFile(Document document, string fileName, SignedCms signedCms, bool verifySignatures)
----

Параметры::
document:::
Тип: `xref:BackOffice-ObjectModel-Document:Document_CL.adoc[Document]`
+
Документ

fileName:::
Тип: `xref:Platform-ObjectManager-SystemCards:VersionedFileCard_CL.adoc[VersionedFileCard]`
+
Карточка файла с подписями

signedCms:::
Тип: `http://msdn.microsoft.com/ru-ru/library/System.Security.Cryptography.Pkcs.SignedCms.aspx[SignedCms]`
+
Сообщение CMS/PKCS 7

verifySignatures:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
При true, проверяется срок действия подписей

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Document:DocumentFile_CL.adoc[DocumentFile]`
+
Файл документа

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`https://msdn.microsoft.com/ru-ru/library/system.exception.aspx[System.Exception]` |Ошибка будет возвращена, если по каким либо причинам добавление основного файла невозможно.
|===

== Заметки

Данный метод, в отличие от метода `AddMainFile`, позволяет корректно загружать подписанные файлы.
