= IDocumentService.GetAdditionalFile -- метод (DocumentFile)

Возвращает карточку файл с версиями из дополнительного файла документа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
VersionedFileCard GetAdditionalFile(DocumentFile additionalFile)
----

Параметры::
additionalFile:::
Тип: `xref:BackOffice-ObjectModel-Document:DocumentFile_CL.adoc[DocumentFile]`
+
Дополнительный файл документа

Возвращаемое значение::
Тип: `xref:Platform-ObjectManager:SystemCards/VersionedFileCard_CL.adoc[VersionedFileCard]`
+
Карточка файла с версиями

== Примеры

Ниже приведен пример получения файла с версиями из документа

[source,csharp]
----
<.>

IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

VersionedFileCard versionedFileCard = documentService.GetAdditionalFile(document.Files.First(t => t.FileType = DocumentFileType.Additional)); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение документа.
<.> Получение файла с версиями.
