= IDocumentService.CreateDocument -- метод

Создает экземпляр нового документа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
Document CreateDocument()
----

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:Document_CL.adoc[Document]`
+
Карточка типа "Документ"

== Заметки

Для созданного экземпляра карточки будут использованы настройки корневого вида карточки.

== Примеры

Ниже приведен пример создания карточки типа Документ и изменение её описания.

[source,csharp]
----
<.>

IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>

Document document = documentService.CreateDocument(); <.>

document.Description = "Документ созданный из кода"; <.>

objectContext.SaveObject<Document>(document); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса для работы с документами.
<.> Создание документа.
<.> Изменение описания.
<.> Сохранение изменений в контексте.
