= IDocumentService.AddSignature -- метод (Document, X509Certificate2, SignatureLabel, StaffEmployee, String, Boolean, ICollection<CardFieldSetting>)

Данный метод предназначен для выполнения подписания операции в документе.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseCardSignature AddSignature(Document document, X509Certificate2 cert, bool signAttachments, ICollection<CardFieldSetting> fields, bool signDocument, StatesOperation operation, Guid signatureType)
----

Параметры::
document:::
Тип: `xref:BackOffice-ObjectModel-Document:Document_CL.adoc[Document]`
+
Документ

cert:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]`
+
Сертификат сотрудника

signAttachments:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Признак подписания дополнительных файлов документа: `true` -- подписывать, иначе -- `false`

fields:::
Тип: `https://msdn.microsoft.com/ru-ru/library/92t2ye13.aspx[System.Collections.Generic.ICollection]<CardFieldSetting>`
+
Поля документа, требующие подписания

signDocument:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Признак подписания основных файлов документа: `true` -- подписывать, иначе -- `false`

operation:::
Тип: `xref:BackOffice-ObjectModel-States:StatesOperation_CL.adoc[StatesOperation]`
+
Подписываемая операция

signatureType:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор вида подписи из _Справочника видов карточек_

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BaseCardSignature_CL.adoc[BaseCardSignature]`
+
Созданная подпись

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `document` или `operation`.
|===

== Заметки

Чтобы использовать возможность выполнять подписание операций, необходимо добавить соответствующую настройку в _Справочнике видов карточек_. Она регистрируется во вкладке *Подпись* в разделе *Подписание операций*.

== Примеры

Ниже приведен пример использования метода `AddSignature` при подписании операции перехода "Согласован" для карточки типа _Документ_

[source,csharp]
----
<.>

IDocumentService documentService = objectContext.GetService<IDocumentService>();
IStateService stateService = objectContext.GetService<IStateService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

KindsCardKind kind = document.SystemInfo.CardKind;
DocumentSetting documentSetting = documentService.GetKindSettings(kind); <.>

StatesOperation statesOperation = stateService.GetOperations(kind).First(t => t.DefaultName.Equals("Is approved")); <.>
                    
DocumentOperationSignatureSetting operationSignatureSetting = documentSetting.OperationSignatures.First(t => t.SignedOperations.Contains(statesOperation)); <.>

X509Certificate2 certificate = GetCertificate(); <.>

BaseCardSignature signature = documentService.AddSignature(document, certificate, operationSignatureSetting.SignAttachments,
operationSignatureSetting.Fields, operationSignatureSetting.SignDocument, statesOperation, new Guid(operationSignatureSetting.Name)); <.>
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
<.> Получение сервисов.
<.> Получение документа.
<.> Получение вида и настроек данного вида.
<.> Получение операции перехода "Согласован" из Конструктора состояний.
<.> Получение первой настройки подписания для операции перехода "Согласован".
<.> Получение сертификата сотрудника, выполняющего подписание.
<.> Подписание операции. Используются параметры подписания, определённые в Справочнике видов карточек.

Для получения сертификата сотрудника используется следующий метод:

[source,csharp]
----
static X509Certificate2 GetCertificate()
{
 X509Certificate2 certificate = new X509Certificate2();
 X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
 store.Open(OpenFlags.OpenExistingOnly);
 X509Certificate2Enumerator enumerator = store.Certificates.GetEnumerator();
 while (enumerator.MoveNext())
 {
  if (enumerator.Current.HasPrivateKey)
  {
   return enumerator.Current;
  }
 }
 return null;
}
----
