= IDocumentService.CreateDocument -- метод (String, KindsCardKind, DocumentVersioningType)

Создаёт документ с заданным видом карточки и добавляет основной файл с указанным типов версионинга.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
Document CreateDocument(string filePath, KindsCardKind kind, DocumentVersioningType versioningType)
----

Параметры::
filePath:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Путь к основному файлу

kind:::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид документа

versioningType:::
Тип: `xref:BackOffice-ObjectModel-Document:DocumentVersioningType_EN.adoc[DocumentVersioningType]`
+
Вид документа

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Document:Document_CL.adoc[Document]`
+
Созданный документ

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.invalidoperationexception.aspx[System.InvalidOperationException]` |Ошибка возникает в том случае, если добавляемый файл является подписанным, но в соответствующем сообщении отсутствуют файлы.
|===

== Примеры

Далее приведён пример создания карточки документ с основным файлом, у которого автоматический тип версионинга указан

[source,csharp]
----
<.>

IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>

KindsCardKind kind = objectContext.GetObject<KindsCardKind>(new Guid("7DB9044E-91B7-447D-8CAA-5E5A4967B8D4")); <.>

Document document = documentService.CreateDocument(@"x:\Sample.docx", kind, DocumentVersioningType.Auto);
objectContext.SaveObject(document); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение вида карточки (в примере, Заявка).
<.> Создание документа.
