= IDocumentService.GetMainFile -- метод (DocumentFile)

Возвращает карточку файл с версиями из основного файла документа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
VersionedFileCard GetMainFile(DocumentFile file)
----

Параметры::
file:::
Тип: `xref:BackOffice-ObjectModel-Document:DocumentFile_CL.adoc[DocumentFile]`
+
Основной файл документа

Возвращаемое значение::
Тип: `xref:Platform-ObjectManager-SystemCards:VersionedFileCard_CL.adoc[VersionedFileCard]`
+
Карточка файла с версиями

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `file`.
|===

== Примеры

Ниже приведен пример получения файла с версиями из первого основного файла документа

[source,csharp]
----
<.>

IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

VersionedFileCard versionedFileCard = documentService.GetMainFile(document.Files.First(t => t.FileType = DocumentFileType.Main)); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение документа.
<.> Получение файла с версиями.
