= IDocumentService.DownloadAdditionalFile -- метод (Document, DocumentFile)

Выгружает в файловую систему указанный дополнительный файл документа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
string DownloadAdditionalFile(Document document, DocumentFile additionalFile)
----

Параметры::
document:::
Тип: `xref:BackOffice-ObjectModel-Document:Document_CL.adoc[Document]`
+
Документ

additionalFile:::
Тип: `xref:BackOffice-ObjectModel-Document:DocumentFile_CL.adoc[DocumentFile]`
+
Дополнительный файл документа

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Путь, по которому был выгружен файл

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `additionalFile`.
|`http://msdn.microsoft.com/ru-ru/library/system.methodaccessexception.aspx[System.MethodAccessException]` |Ошибка возвращается в случае, если у сотрудника недостаточно прав на чтение дополнительного файла.
|===

== Примеры

Ниже приведен пример использования метода `DownloadAdditionalFile` при выгрузке дополнительного файла документа

[source,csharp]
----
//
<.>

//
IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>

//
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

//
string path = documentService.DownloadAdditionalFile(document, document.Files.First(t => t.FileType = DocumentFileType.Additional)); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса для работы с документами.
<.> Получение документа.
<.> Выгрузка первого дополнительного файла на диск, по пути `path`.
