= IDocumentService.ComputeFieldsSignature -- метод (Document, BaseCardSignature, X509Certificate2, ICollection<CardFieldSetting>)

Подписывает атрибуты документа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void ComputeFieldsSignature(Document document, BaseCardSignature signature, X509Certificate2 cert, ICollection<CardFieldSetting> properties)
----

Параметры::
document:::
Тип: `xref:BackOffice-ObjectModel:Document_CL.adoc[Document]`
+
Документ

signature:::
Тип: `xref:BackOffice-ObjectModel:BaseCardSignature_CL.adoc[BaseCardSignature]`
+
ЭЦП

cert:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]`
+
Сертификат сотрудника

properties:::
Тип: `https://msdn.microsoft.com/ru-ru/library/system.collections.icollection.aspx[System.Collections.ICollection]<CardFieldSetting>`
+
Список подписываемых атрибутов (полей карточки) типа `xref:BackOffice-ObjectModel-Services-Entities:Entities/KindSetting/CardFieldSetting_CL.adoc[CardFieldSetting]`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `document`.
|===
