= IDocumentService.AddSignature -- метод (Document, X509Certificate2, Boolean, ICollection<CardFieldSetting>)

Добавляет новую подпись в список подписей карточки и устанавливает ЭЦП на поля, основные и дополнительные файлы документа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseCardSignature AddSignature(Document document, X509Certificate2 cert, bool signAttachments, ICollection<CardFieldSetting> fields)
----

Параметры::
document:::
Тип: `xref:BackOffice-ObjectModel-Document:Document_CL.adoc[Document]`
+
Документ

cert:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]`
+
Сертификат, которым будет выполнено подписание

signAttachments:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- подписывать дополнительные файлы, иначе -- `false`

fields:::
Тип: `http://msdn.microsoft.com/ru-ru/library/92t2ye13.aspx[System.Collections.Generic.ICollection]<CardFieldSetting>`
+
Коллекция подписываемых полей типа `xref:BackOffice-ObjectModel-Services-Entities:Entities/KindSetting/CardFieldSetting_CL.adoc[CardFieldSetting]`, определённых для карточки в Справочнике видов карточек

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BaseCardSignature_CL.adoc[BaseCardSignature]`
+
Подпись

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `document`.
|===

== Заметки

Сертификат сотрудника может быть получен из карточки Настроек пользователя. Данный метод инициализирует новую подпись в виде объекта типа `BaseCardSignature`, которую использует при непосредственном подписании данных карточки _Документ_.

== Примеры

Ниже приведён пример подписания документа, осуществляемое из скрипта самой карточки

[source,csharp]
----
using DocsVision.BackOffice.ObjectModel;
using DocsVision.BackOffice.ObjectModel.Services;
using DocsVision.BackOffice.WinForms.Controls;

namespace BackOffice
{
 public class CardDocumentПримерScript : CardDocumentДокументУДScript
 {
  private void addSignature_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
  {

   IDocumentService documentService = base.CardControl.ObjectContext.GetService<IDocumentService>(); <.>
   bool cancel = false;

   var certificate = SelectCertificateForm.SelectCertificate(ref cancel, base.CardControl.ObjectContext); <.>
   if(cancel) return;

   var fields = documentService.GetKindSettings(base.BaseObject.SystemInfo.CardKind).DocumentSignature.Fields; <.>
   
   documentService.AddSignature((base.BaseObject as Document), certificate, false, fields); <.>
  }
 }
}
----
<.> Получение сервиса для работы с карточкой Документ.
<.> Отображение окна выбора сертификата. Простой сертификат может быть установлен, если присвоить `certificate` значение `null`.
<.> Получение из параметров вида карточки полей, для которых предусмотрено подписание.
<.> Осуществление подписания.
