= IDocumentService.AddMainFileComment -- метод (Document, DocumentFile, String)

Добавляет комментарий к основному файлу документа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool AddMainFileComment(Document document, DocumentFile file, string comment)
----

Параметры::
document:::
Тип: `xref:BackOffice-ObjectModel:Document_CL.adoc[Document]`
+
Документ, содержащий файл `file`

file:::
Тип: `xref:BackOffice-ObjectModel:DocumentFile_CL.adoc[DocumentFile]`
+
Объектная модель файла документа

comment:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Комментарий к файлу

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- комментарий был успешно добавлен, иначе -- `false`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `document`, `file` или `comment`.
|===

== Примеры

В приведенном примере комментарий добавляется к первому основному файлу

[source,csharp]
----
<.>

IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

DocumentFile file = document.Files.First(t => t.FileType = DocumentFileType.Main); <.>

documentService.AddMainFileComment(document, file, "Данный файл был проверен"); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение документа.
<.> Получение первого основного файла.
<.> Добавление комментария.
