= IDocumentService.RemoveMainFileComments -- метод (Document, DocumentFile, FileCommentCollection, IEnumerable<FileComment>)

Удаляет комментарии к файлу документа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void RemoveMainFileComments(Document document, DocumentFile file, FileCommentCollection collection, IEnumerable<FileComment> comments)
----

Параметры::
document:::
Тип: `xref:BackOffice-ObjectModel-Document:Document_CL.adoc[Document]`
+
Документ

file:::
Тип: `xref:BackOffice-ObjectModel-Document:DocumentFile_CL.adoc[DocumentFile]`
+
Файл документа

collection:::
Тип: `xref:Platform-ObjectManager-SystemCards:FileCommentCollection_CL.adoc[FileCommentCollection]`
+
Коллекция комментариев

comments:::
Тип: `http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<FileComment>`
+
Коллекция удаляемых комментариев

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `document`, `file`, `collection` или `comments`.
|===

== Примеры

В приведенном примере демонстрируется использование метода RemoveMainFileComments при удалении комментариев, содержащих слово "удалить", к первому основному файлу

[source,csharp]
----
<.>

IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

DocumentFile file = document.Files.First(t => t.FileType = DocumentFileType.Main); <.>

VersionedFileCard versionedFileCard = documentService.GetMainFile(file); <.>

documentService.RemoveMainFileComments(document, file, versionedFileCard.Comments, versionedFileCard.Comments.Where(t => t.Comment.Contains("удалить"))); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение документа.
<.> Получение первого основного файла.
<.> Получение карточки файла с версией из основного файла.
<.> Удаление комментария.
