= INumerationRulesService.DeleteRuleItem -- метод (NumerationRulesRuleItem, NumerationRulesRule)

Удаляет строку правила нумерации из _конструктора правил нумерации_.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void DeleteRuleItem(NumerationRulesRuleItem ruleItem, NumerationRulesRule rule)
----

Параметры::
ruleItem:::
Тип: `xref:BackOffice-ObjectModel-NumerationRules:NumerationRulesRuleItem_CL.adoc[NumerationRulesRuleItem]`
+
Удаляемая строка правила нумерации

rule:::
Тип: `xref:BackOffice-ObjectModel-NumerationRules:NumerationRulesRule_CL.adoc[NumerationRulesRule]`
+
Правило нумерации, из которого удаляется строка

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `ruleItem` или `rule`.
|===
