= Источники данных

Основная идея разработки визуальных форм карточек {dv} заключается в максимальном использовании стандартных элементов управления Visual Studio (TextBox, ComboBox, ListView и т.д.) -- вместо того, чтобы предлагать собственные элементы управления, которые разработчику понадобится дополнительно изучать. Этот подход имеет свои преимущества:

* Стандартные элементы управления хорошо документированы ( MSDN)
* У разработчиков обычно есть навыки работы с ними
* Совместимость элементов управления гарантируется Microsoft

Однако недостатком подобного подхода является тот факт, что стандартные элементы управления ничего “не знают” о {dv}. Соответственно, при их использовании разработчику придется каждый раз писать один и тот же код по загрузке данных из {dv} в элемент управления; и обратному сохранению данных из элемента управления в Docsvision.

Данную проблему предлагается решать при помощи Data Binding -- технологии Microsoft для динамического связывания элемента управления с источником данных (базой данных, внешней системой, провайдером и т.д.). Она дает следующие ключевые преимущества:

* Настройка в design-time (позволяет создать полнофункциональный элемент управления для обработки данных без написания какого-либо кода)
* Автоматизация рутинных операций по загрузке данных в элемент управления и сохранению изменений (разработчик избавлен от необходимости дублировать этот код для каждого элемента)
* Поддерживается подавляющим большинством стандартных элементов управления Visual Studio, а также элементами сторонних производителей

Для того, чтобы сделать подобное связывание возможным, требуется наличие специального объекта -- источника данных. Библиотека элементов управления {dv} предусматривает четыре таких объекта для разных типов данных в системе; а также один вспомогательный объект -- `SessionSource`.

== См. далее

* xref:CardsDevCompControlsSessionSource.adoc[Объект SessionSource]

== См. также

* xref:CardsDevCompControlsCardDataSource.adoc[Источник данных CardDataSource]
* xref:CardsDevCompControlsRowDataSource.adoc[Источник данных RowDataSource]
* xref:CardsDevCompControlsInfoRowDataSource.adoc[Источник данных InfoRowDataSource]
* xref:CardsDevCompControlsReportDataSource.adoc[Источник данных ReportDataSource]
