= Элемент управления Preview

Элемент управления Preview предназначен для просмотра содержимого файла без открытия файла. Соответствует элементу управления [.ph .uicontrol]*Предпросмотр файла* _Конструктора разметок_.

Preview не содержит элементов управления.

Preview содержит следующие свойства:

* FileName - возвращает название открытого файла;

Preview предоставляет следующие методы:

* ClosePreview - освобождает ресурсы и очищает область предварительного просмотра. Вызывается автоматически, перед вызовом [.keyword .apiname]#ShowPreview#;
* SetText(String) - передает текст для отображения в окно предварительного просмотра;
* ShowPreview(String) - формирует предварительный просмотр файла, расположенного по указанному пути;
* ShowPreview(String, IStream) - формирует предварительный просмотр файла, расположенного по указанному пути. Должен быть использован, если [.keyword .apiname]#SupportStreaming# возвращает true;
* SupportStreaming(String) - определяет поддержку обработчиком, формирующим предварительный просмотр файла, чтение файла из потока.

Preview позволяет подписываться на следующие события:

* PreviewCompleted - событие вызывается после отображения (используется метод [.keyword .apiname]#ShowPreview#) пользователю содержимого файла.

Пример использования Preview для отображением содержимого документа MS Word:

[source,csharp]
----
private void ShowButton_Click(object sender, EventArgs e)
{
 if (!this.preview.ShowPreview(@"X:\Sample.docx"))
  this.preview.SetText("Предварительный просмотр недоступен");
}
----

[NOTE]
====
[.note__title]#Прим.:# Для формирования предварительного просмотра, необходимо наличие на компьютере средств открытия файла.
====
