= Создание расширения для Консоли настройки

[NOTE]
====
[.note__title]#Прим.:# Исходный код [.dfn .term]_SnapIn_ расположен в подкаталоге [.ph .filepath]`NetstatSolution.Snapin` приложенного архива.
====

На данном этапе необходимо создать расширение для Консоли настройки ([.dfn .term]_SnapIn_), которое отвечает за загрузку CardPackage и SqlPackage в Docsvision, а также регистрирует пакет установки клиентской части.

[NOTE]
====
[.note__title]#Важное замечание:# [.dfn .term]_SnapIn_ является обязательным компонентом, при условии, что [.dfn .term]_решение_ использует собственную библиотеку карточек.
====

Как часть _Модуля учета сетевых устройств_, данный компонент выполняет следующие задачи:

* устанавливает и удаляет библиотеку карточек _Модуля учета сетевых устройств_;
* импортирует в Docsvision бизнес-процесс [.dfn .term]_Проверка доступности сетевых узлов_, а также пример карточки [.dfn .term]_Карточки учета сетевого оборудования_, а также данные [.dfn .term]_справочника видов карточек_, [.dfn .term]_конструктора разметок_, [.dfn .term]_конструктора состояний_ и [.dfn .term]_конструктора ролей_;
* регистрирует клиентский пакет установки;
* добавляет в [.dfn .term]_Консоль настройки Docsvision_ форму для ввода конфигурационных параметров _Модуля учета сетевых устройств_.

[NOTE]
====
[.note__title]#Прим.:# Пример реализации простого [.dfn .term]_SnapIn_ приведен в разделе xref:DM_ConsolePlugin.adoc[Модуль расширения Консоли настройки]
====

Компонент [.dfn .term]_SnapIn_ представляет собой библиотеку DLL, в которой присутствует класс, реализующий интерфейс [.keyword .apiname]#DocsVision.Tools.ServerConsole.ISnapIn# (сборка [.ph .filepath]`DocsVision.Tools.ServerConsole.Interfaces.dll`). Также данный класс может реализовывать несколько дополнительных интерфейсов:

* [.keyword .apiname]#IDBInformation# - является обязательным при создании [.dfn .term]_решения_, т.к. именно реализация данного интерфейса позволяет [.dfn .term]_SnapIn_ предоставлять пути к [.dfn .term]_CardPackage_ и [.dfn .term]_SqlPackage_.
* [.keyword .apiname]#IConfigurator# - добавляет в [.dfn .term]_SnapIn_ метод [.keyword .apiname]#Execute#, который запускается в режиме конфигурации модуля - вызывается командой [.ph .filepath]`ServerConsole.exe /c /n \{ИМЯ_РЕШЕНИЯ}`. Обычно данный метод отвечает за регистрацию пакетов установки клиентской части [.dfn .term]_решения_.
* [.keyword .apiname]#IUninstallSnapIn# - добавляет метод [.keyword .apiname]#Uninstall#, который вызывается при удалении решения - вызывается командой [.ph .filepath]`ServerConsole.exe /rs /n \{ИМЯ_РЕШЕНИЯ}`.

Помимо выполнения сервисных функций, [.dfn .term]_SnapIn_ может предоставлять пользовательский интерфейс для различных режимов работы [.dfn .term]_Консоли настройки_ .

[NOTE]
====
[.note__title]#Прим.:# Если Вы работаете с исходными кодами проекта, то [.dfn .term]_SnapIn_ собирается третьим.
====

== В этом подразделе

* xref:CreateSnapIn_Interface.adoc[Реализация стандартных интерфейсов]
* xref:CreateSnapIn_Control.adoc[Пользовательский интерфейс расширения]

== См. далее

* xref:CreateSnapIn_Interface.adoc[Реализация стандартных интерфейсов]

* *xref:../pages/CreateSnapIn_Interface.adoc[Реализация стандартных интерфейсов]* +
* *xref:../pages/CreateSnapIn_Control.adoc[Пользовательский интерфейс расширения]* +

*На уровень выше:* xref:../pages/CreateSolution.adoc[Пример разработки решения]
