= Создание расширения для Консоли настройки

[NOTE]
====
[.note__title]#Прим.:# Исходный код _SnapIn_ расположен в подкаталоге `NetstatSolution.Snapin` приложенного архива.
====

На данном этапе необходимо создать расширение для Консоли настройки (_SnapIn_), которое отвечает за загрузку CardPackage и SqlPackage в Docsvision, а также регистрирует пакет установки клиентской части.

[NOTE]
====
[.note__title]#Важное замечание:# _SnapIn_ является обязательным компонентом, при условии, что _решение_ использует собственную библиотеку карточек.
====

Как часть _Модуля учета сетевых устройств_, данный компонент выполняет следующие задачи:

* устанавливает и удаляет библиотеку карточек _Модуля учета сетевых устройств_;
* импортирует в Docsvision бизнес-процесс _Проверка доступности сетевых узлов_, а также пример карточки _Карточки учета сетевого оборудования_, а также данные _справочника видов карточек_, _конструктора разметок_, _конструктора состояний_ и _конструктора ролей_;
* регистрирует клиентский пакет установки;
* добавляет в _Консоль настройки Docsvision_ форму для ввода конфигурационных параметров _Модуля учета сетевых устройств_.

[NOTE]
====
[.note__title]#Прим.:# Пример реализации простого _SnapIn_ приведен в разделе xref:DM_ConsolePlugin.adoc[Модуль расширения Консоли настройки]
====

Компонент _SnapIn_ представляет собой библиотеку DLL, в которой присутствует класс, реализующий интерфейс [.keyword .apiname]#DocsVision.Tools.ServerConsole.ISnapIn# (сборка `DocsVision.Tools.ServerConsole.Interfaces.dll`). Также данный класс может реализовывать несколько дополнительных интерфейсов:

* [.keyword .apiname]#IDBInformation# - является обязательным при создании _решения_, т.к. именно реализация данного интерфейса позволяет _SnapIn_ предоставлять пути к _CardPackage_ и _SqlPackage_.
* [.keyword .apiname]#IConfigurator# - добавляет в _SnapIn_ метод [.keyword .apiname]#Execute#, который запускается в режиме конфигурации модуля - вызывается командой `ServerConsole.exe /c /n \{ИМЯ_РЕШЕНИЯ}`. Обычно данный метод отвечает за регистрацию пакетов установки клиентской части _решения_.
* [.keyword .apiname]#IUninstallSnapIn# - добавляет метод [.keyword .apiname]#Uninstall#, который вызывается при удалении решения - вызывается командой `ServerConsole.exe /rs /n \{ИМЯ_РЕШЕНИЯ}`.

Помимо выполнения сервисных функций, _SnapIn_ может предоставлять пользовательский интерфейс для различных режимов работы _Консоли настройки_ .

[NOTE]
====
[.note__title]#Прим.:# Если Вы работаете с исходными кодами проекта, то _SnapIn_ собирается третьим.
====

== В этом подразделе

* xref:CreateSnapIn_Interface.adoc[Реализация стандартных интерфейсов]
* xref:CreateSnapIn_Control.adoc[Пользовательский интерфейс расширения]

== См. далее

* xref:CreateSnapIn_Interface.adoc[Реализация стандартных интерфейсов]

