= Формирование CardPackage и SqlPackage

На этапе установки решения, в Docsvision могут быть импортированы определенные данные, например: данные справочников, карточки и бизнес-процессы, для чего должен быть подготовлен специальный пакет - [.keyword]*CardPackage*, содержащий файлы с данными карточек и т.д., а также файл со ссылками на эти файлы.

Один из сценариев использования пакета CardPackage - настроить разметку своего типа карточки в [.dfn .term]_Конструкторе разметок_, после чего выгрузить эту разметку и распространить её с пакетом установки на целевые сервера Docsvision. Аналогично можно поступить с [.dfn .term]_Конструктором состояний_ и [.dfn .term]_Конструктором ролей_.

[NOTE]
====
[.note__title]#Прим.:# Файлы пакета [.dfn .term]_CardPackage_ расположены в подкаталоге [.ph .filepath]`CardPackage` приложенного архива.
====

[NOTE]
====
[.note__title]#Важное замечание:# Все действия, связанные с формированием пакетов CardPackage и SqlPackage, должны выполняться на отдельном сервере Docsvision.
====

== Предварительная подготовка

Прежде всего необходимо загрузить библиотеку карточек в базу данных Docsvision (см. раздел xref:CardsDevDataSchemeUploadBase.adoc[Загрузка схем карточек в базу данных]), а также разместить на клиенте компоненты карточки и библиотеки карточек.

Компонент карточки на данном этапе достаточно разместить в каталоге Docsvision Windows-клиент.

Компонент библиотеки карточек должен быть зарегистрирован командой: [.ph .filepath]`regsvr32.exe \{Полный путь к сборке}` (к примеру, [.ph .filepath]`regsvr32.exe NetstatSolutionCardLib.dll`).

[NOTE]
====
[.note__title]#Прим.:# Для регистрации библиотеки с использованием утилиты [.ph .filepath]`regsvr32` необходимы административные права.
====

== Формирование данных

После того, как в Docsvision был загружен новый тип карточки, настраиваем его при помощи конструкторов, заполняем справочник, если решение его содержит, первоначальными данными, создаем необходимые бизнес-процессы и карточки.

Тип [.dfn .term]_Карточка учета сетевого оборудования_ была настроен с использованием:

* [.dfn .term]_Конструктора разметок_ - создана разметка с привязкой к данным карточки;
* [.dfn .term]_Конструктора состояний_ - добавлено начальное состояние;
* [.dfn .term]_Конструктора ролей_ - добавлены типовые права на работу с карточкой.

Также были внесены изменения (создан корневой вид карточки) в [.dfn .term]_Справочник видов карточек_.

Дополнительно был сформирован пустой (реализация бизнес-процесса выходит за рамки примера) бизнес-процесс "Проверка доступности сетевых узлов", а также экземпляр карточки [.dfn .term]_учета сетевого оборудования_.

Все эти данные предполагается автоматически загружать в Docsvision при установке [.dfn .term]_решения_.

== Выгрузка данных

Сформированные данные необходимо выгрузить из Docsvision в формате XML,т.к. при установке [.dfn .term]_решения_ они просто импортируются средствами платформы.

Карточки (включая бизнес-процессы) экспортируются стандартными средствами Docsvision Windows-клиент.

Для выгрузки данных из справочников и конструкторов рекомендуется использовать специализированную [.keyword]*Утилиту для экспорта решения* (CardTypeExtractor), которая доступна на сайте https://docsvision.zendesk.com/entries/22151452-%D0%AD%D0%BA%D1%81%D0%25%22[Портале технической поддержки Docsvision].

[NOTE]
====
[.note__title]#Прим.:# Для удобства, утилита [.keyword]*CardTypeExtractor* предоставляется вместе с исходным кодом данного решения и расположена в каталоге [.ph .filepath]`Other` архива.
====

== Создание CardPackage

Для того, чтобы закончить формирование пакета CardPackage, требуется создать файл [.ph .filepath]`CardPackage.xml` следующего формата:

[source,pre,codeblock,language-xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<CardPackage>
 <Card Path="относительный_путь_к_файлу_XML" ID="ID_карточки" Replace="1 если карточка должна заменить существующую; 0 – если дополнить"/>
 …
</CardPackage> 
----

[NOTE]
====
[.note__title]#Прим.:# Если для выгрузки данных использовалась утилита [.dfn .term]_CardTypeExtractor_, то файл [.ph .filepath]`CardPackage.xml` будет сформирован автоматически, но в него потребуется добавить записи о карточках, выгруженных из [.dfn .term]_Windows-клиента_ самостоятельно.
====

== Создание SqlPackage

[NOTE]
====
[.note__title]#Прим.:# Готовый файл ([.ph .filepath]`NetstatSolutionInstall.xml`) пакета SqlPackage содержится в каталоге [.ph .filepath]`Database` приложенного архива.
====

Помимо [.dfn .term]_CardPackage_, для пакета установки [.dfn .term]_решения_ требуется создать пакет [.dfn .term]_SqlPackage_, состоящий из единственного файла, в котором указано расположение файлов со схемами метаданных [.keyword]*библиотек карточек*, которые должны быть загружен в базу данных при установке [.dfn .term]_решения_.

[.dfn .term]_CardPackage_ должен соответствовать формату:

[source,pre,codeblock,language-xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<SqlPackage>
 <SqlFile>"относительный_путь_к_файлу_XML"</SqlFile>
 ...
</SqlPackage>
----

[NOTE]
====
[.note__title]#Прим.:# Как правило [.dfn .term]_SqlPackage_ содержит одну единственную ссылку на файл со схемой библиотеки карточек.
====

== См. также

* xref:CreateSnapIn.adoc[Создание расширения для Консоли настройки]

*На уровень выше:* xref:../pages/CreateSolution.adoc[Пример разработки решения]
