= Разработка компонента библиотеки карточек

[NOTE]
====
[.note__title]#Прим.:# Исходный код компонента библиотеки карточек расположен в подкаталоге `CardLib` приложенного архива.
====

Компонент библиотеки карточек является обязательной частью _решения_, он определяет корректность установки _решения_ в целом, а его отсутствие является сигналом Windows-клиенту о необходимости установки клиентской части. При большом размере и количестве схем карточек, зарегистрированных в библиотеке, а также большом числе клиентов Docsvision, компонент библиотеки карточек выполняет роль статического кэша на стороне клиента со схемами и ресурсами карточек, что предполагает выигрыш в части снижения нагрузки на сервер Docsvision.

[NOTE]
====
[.note__title]#Прим.:# Пример разработки компонента библиотеки карточек на C# приведен в Руководстве разработчика в разделе http://www.docsvision.com/docs/DeveloperManual/index.html#DV5_DeveloperManual/Concepts/CardsDevCompLibary.html. В статье https://docsvision.zendesk.com/entries/80645519[Создание компонента библиотеки карточек на C++] рассмотрен пример разработки компонента библиотеки на языке C++.

Обратите внимание: в версии Платформа 5.5.2 требования к компоненту библиотеки карточек были изменены. См. xref:WhatsNew.adoc[Что нового].
====

Компонент библиотеки карточек (C++) проще всего создать на основе готового шаблона (например, использовать исходный код компонента данной библиотеки) с заменой отдельных частей кода (например, идентификаторы библиотеки карточек и карточек) на собственные значения.

[NOTE]
====
[.note__title]#Прим.:# При разработке компонента без использования шаблона, требования к реализации остаются стандартными:

* должны быть реализованы интерфейсы [.keyword .apiname]#ICardLibraryInfo# и [.keyword .apiname]#ICardLibraryInfo2#;
* должны быть загружены ресурсы (схемы карточек и библиотеки карточек, а также их иконки);
* компонент библиотеки должен быть реализован как COM-компонент.
====

Полный алгоритм создания готового компонента на основе шаблона можно разбить на следующие шаги:

. Укажите действительную _Версию библиотеки карточек_ в файле dvver.h, в определении идентификатора сборки [.keyword .apiname]#VERSION_BUILD#. В этом же файле можно заменить авторство сборки.
. Добавьте в файл ресурсов (CardLib.rc) следующие ресурсы:
* В XMLDEF добавляются все схемы карточек, включенных в данную библиотеку, а также схема самой библиотеки карточек;
* В Icon добавляются иконки карточек и библиотеки карточек;
+
При необходимости добавьте в файл с идентификаторами ресурсов (Resource.h) идентификаторы новых ресурсов.
. Измените скрипт регистрации `CardLib.rgs`:
* в CLSID и ForceRemove нужно указать _идентификатор компонента библиотеки карточек_, который был указан при разработке схемы библиотеки карточек в параметре Activation string;
* в TypeLib нужно указать произвольный (сгенерировать самостоятельно) _идентификатор библиотеки типов_:
* заменить«NetstatSolution» на собственное название для регистрации COM-компонента.
. В файле CardLib.def укажите название файла сборки.
. В файле CardLib.idl необходимо указать _идентификатор компонента библиотеки карточек_ и _идентификатор библиотеки типов_, которые были использованы на шаге 3.
. В файле `CardLibInfo.cpp`:
* в массиве GetCardType.Cards перечислите идентификаторы всех карточек библиотеки (соблюдайте формат), их схемы (название ресурса) и иконки;
* в методе get_Version в sCardLibDef нужно указать собственное название ресурса со схемой библиотеки карточек.
. В свойствах проекта укажите необходимое название для сборки.

[NOTE]
====
[.note__title]#Прим.:# Если Вы работаете с исходными кодами проекта, то компонент библиотеки карточки собирается вторым.
====

== См. также

* xref:CreatePackages.adoc[Формирование CardPackage и SqlPackage]
