= Разработка сервиса для работы с карточкой

Т.к. ранее было решено вынести бизнес-логику карточки за пределы её класса в сервис, разработаем его.

. Создаем интерфейс, описывающий функциональность будущего сервиса:
+
[source,csharp]
----
public interface INetstatSolutionService
{
 // Создание новой карточки
 NetstatSolutionCard.ObjectModel.NetstatSolutionCard CreateCard(string name, string address, int type);

 // Добавление результата проверки в журнал
 ObjectModel.NetstatSolutionCardJournal AddJournalEntry(NetstatSolutionCard.ObjectModel.NetstatSolutionCard card, DateTime date, bool result);
}
----
. Добавляем класс, реализующий интерфейс INetstatSolutionService и наследующий от [.keyword .apiname]#ContextService# - базовый класс сервисов объектной модели:
+
[source,csharp]
----
internal class NetstatSolutionService : ContextService, INetstatSolutionService
----
+
Специально ограничиваем область видимости класса, т.к. контекст объектов предоставляет сервис по его интерфейсу.
. Реализуем функциональность, описанную интерфейсом [.keyword .apiname]#INetstatSolutionService#.
+
Реализацию смотрите в проекте решения.
. Создаем фабрику сервисов в виде класса, наследующего от [.keyword .apiname]#ServiceFactory#. Фабрика предоставляет экземпляр сервиса по его типу.
+
[source,csharp]
----
public class NetstatSolutionServiceFactory : ServiceFactory
{
 protected override object GetService(Type serviceType)
 {
  // Метод должен вернуть экземпляр класса, реализующего INetstatSolutionService, по интерфейсу
  if (serviceType = typeof(INetstatSolutionService))
  {
   return new NetstatSolutionService();
  }
  return null;
 }
}
----

После реализации фабрики сервисов, можно собрать проект и подключить библиотеку, содержащую сервис (интерфейс, реализацию) и фабрику сервисов, к проекту и запросить данный сервис из контекста объектов, если фабрика сервисов зарегистрирована в контексте объектов (см. xref:DM_FullContextInit.adoc[пример] инициализации контекста объектов).

[NOTE]
====
[.note__title]#Прим.:# Типы и интерфейс, разработанные для сервиса, собраны в папке `Services` проекта *NetstatSolutionCard*.
====

== См. далее

* xref:CreateCardLib_CardControl.adoc[Разработка компонента карточки]
