= Пример разработки решения

В данном практическом примере содержится типовой сценарий разработки _решения_.

Архив с исходным кодом _решения_ доступен по xref:attachment$netstatSolution.zip[ссылке].

Для работы с проектом Решения необходимы:

. Visual Studio 2013 или выше. *Для сборки проекта библиотеки карточек требуется Visual Studio 2013.*
. WiX Toolset – для сборки пакетов установки. Последняя версия доступна на http://wixtoolset.org/[странице] проекта.
. Установленные клиентские компоненты базовых модулей {dv} (обязательно Платформа, Windows-клиент), совместимые с платформой {dv} версии 5.5.2.

== В этом подразделе

* xref:Intro.adoc[Основные сведения]
* xref:CreateCardLib.adoc[Разработка библиотеки карточек]
* xref:CreatePackages.adoc[Формирование CardPackage и SqlPackage]
* xref:CreateSnapIn.adoc[Создание расширения для Консоли настройки]
* xref:CreateInstaller.adoc[Создание пакета установки]
* xref:UpdateSolution.adoc[Обновление решения]
* xref:License.adoc[Лицензирование]



