= Руководство по разработке

В данном разделе рассмотрены типовые сценарии разработки на платформе {dv} 5:

* Использование API {dv} для взаимодействия с объектами системы.
* Разработка новых типов карточек.
* Основы разработки расширений и модулей для платформы и приложения _Workflow_.

Примеры могут сопровождаться или не сопровождаться описанием задействованных в примере сущностей API {dv}. В любом случае для получения справочной информации об объектах API {dv} рекомендуется обращаться к их описанию, приведенному в разделе xref:api/class-lib.adoc[].

Все примеры, за исключением тех случаев, когда указано иное, разработаны на языке C# в среде разработки Visual Studio.

Для разработки внешних приложений потребуется установленный на компьютере разработки клиент {dv} 5.

.В этом разделе представлена следующая информация:
* xref:cards/general-information.adoc[].
* xref:cards/connect-to-dv-server.adoc[]
* xref:cards/init-object-context.adoc[]
* xref:cards/work-cards.adoc[]
* xref:folder-shortcut.adoc[]
* xref:files.adoc[]
* xref:links.adoc[]
* xref:numerators.adoc[]
* xref:use-reports.adoc[]
* xref:views/views.adoc[]
* xref:access-control.adoc[]
* xref:download-mode.adoc[]
* xref:delayed-changes.adoc[]
* xref:event-logs.adoc[]
* xref:solutions/cards/develop-solution.adoc[]
* xref:scripts/develop-scripts.adoc[]
* xref:workflow/develop-environment.adoc[]
* xref:appendix/appendix.adoc[]
