= Руководство по разработке

Базовая поставка платформы {dv} содержит полный набор средств для разработки собственных решений, удовлетворяющих потребности организации в сфере электронного документооборота и его автоматизации.

.К таким средствам можно отнести:
* Набор конструкторов -- мощное и простое средство настройки существующего программного продукта.
* Возможность разработки новых шлюзов, функций и сценариев для использования их в бизнес-процессах.
* Возможность создавать новые типы объектов платформы (карточек) для полноценного представления объектов целевой сферы деятельности.
* Публичный API для разработки отдельных утилит, сценариев бизнес-процессов.

Основное назначение данного раздела документа -- предоставить разработчику информацию о возможностях API {dv} через практические примеры.

.Помимо этого, документ содержит другие сведения, напрямую связанные с созданием решений:
* Создание собственных карточек и решений.
+
Собственные типы карточки разрабатываются, например, если невозможно или сложно реализовать необходимую бизнес-логику, либо иную функциональность в т.ч. пользовательский интерфейс при помощи конструкторов {dv}.
+
* Разработка сценариев в карточках.
+
Сценарии (скрипты) в карточках библиотеки _{bo}_ позволяют расширить их функциональность штатным образом без разработки нового решения.
+
* Разработка сценариев в бизнес-процессах.
+
Сценарии (скрипты) в бизнес-процессах являются одним из способов реализации специфических действий, не предусмотренных стандартными функциями бизнес-процессов.
+
* Разработка прикладных приложений (утилит).
+
Разработка внешних по отношению к {dv} приложений, выполняющих какие-либо действия в системе, может быть востребована при интеграции {dv} с другими системами (синхронизация справочных данных). Примерами таких утилит могут выступать приложения для импорта данных в справочники сотрудников и контрагентов, входящие в пакет разработчика.

В данном разделе приведена справочная информация об общем устройстве платформы и приложения _Workflow_, а также список ограничений на модификацию платформы, которые должны учитываться при разработке решений:

* Использование API {dv} для взаимодействия с объектами системы.
* Разработка новых типов карточек.
* Основы разработки расширений и модулей для платформы и приложения _Workflow_.

Примеры могут сопровождаться или не сопровождаться описанием задействованных в примере сущностей API {dv}. В любом случае для получения справочной информации об объектах API {dv} рекомендуется обращаться к их описанию, приведенному в разделе xref:DocsVisionObjectModel:class-lib.adoc[].

Все примеры, за исключением тех случаев, когда указано иное, разработаны на языке C# в среде разработки Visual Studio.

Для разработки внешних приложений потребуется установленный на компьютере разработки клиент {dv} 5.

.В этом разделе представлена следующая информация:
* xref:cards:general-information.adoc[].
* xref:cards:connect-to-dv-server.adoc[]
* xref:cards:init-object-context.adoc[]
* xref:cards:work-cards.adoc[]
* xref:cards:folder-shortcut.adoc[]
* xref:cards:files.adoc[]
* xref:views:links.adoc[]
* xref:cards:numerators.adoc[]
* xref:cards:use-reports.adoc[]
* xref:views:views.adoc[]
* xref:cards:access-control.adoc[]
* xref:views:download-mode.adoc[]
* xref:views:delayed-changes.adoc[]
* xref:views:event-logs.adoc[]
* xref:solutions:cards/develop-solution.adoc[]
* xref:scripts:develop-scripts.adoc[]
* xref:bpms:develop-environment.adoc[]
* xref:appendix:appendix.adoc[]
