= Руководство по разработке

В данном разделе рассмотрены типовые сценарии разработки на платформе {dv} 5:

* Использование API {dv} для взаимодействия с объектами системы.
* Разработка новых типов карточек.
* Основы разработки расширений и модулей для платформы и приложения _{wf}_.

Примеры могут сопровождаться или не сопровождаться описанием задействованных в примере сущностей API {dv}. В любом случае для получения справочной информации об объектах API {dv} рекомендуется обращаться к их описанию, приведенному в разделе xref:api/Intro.adoc[].

Все примеры, за исключением тех случаев, когда указано иное, разработаны на языке C# в среде разработки Visual Studio.

Для разработки внешних приложений потребуется установленный на компьютере разработки клиент {dv} 5.

.В этом разделе представлена следующая информация:
* xref:work-cards/general-information.adoc[].
* xref:work-cards/connect-to-dv-server.adoc[]
* xref:work-cards/init-object-context.adoc[]
* xref:work-cards/work-cards.adoc[]
* xref:folder-shortcut.adoc[]
* xref:files.adoc[]
* xref:dm_links.adoc[]
* xref:dm_numerators.adoc[]
* xref:dm_storedprocedure.adoc[]
* xref:dm_views.adoc[]
* xref:access-control.adoc[]
* xref:dm_downloadmode.adoc[]
* xref:dm_delayedchanges.adoc[]
* xref:dm_eventlogs.adoc[]
* xref:dm_cretatesolution.adoc[]
* xref:dm_scripts.adoc[]
* xref:dm_wf.adoc[]
* xref:dm_appendix.adoc[]
