= Примеры использования

== Подключение к серверу {dv}

Практически каждый метод веб-сервиса требует идентификатор пользовательской сессии, поэтому первоначальной задачей является создание сессии пользователя. Для этого предназначен метод xref:DevManualAppendix_WebService_Common_SessionLogin.adoc[SessionLogin]. Код для открытия пользовательской сессии может выглядеть следующим образом:

[source,pre,codeblock,language-python]
----
import xml.etree.ElementTree as ElementTree
import requests
from requests_ntlm import HttpNtlmAuth

# Адрес и учетные данные пользователя для подключения к {dv}
url = 'http://DOCSVISION_SERVER.COM/DocsVision/StorageServer/StorageServerService.asmx'
username = 'Domain\User.Name'
password = 'User.Password'

session = requests.Session()
session.auth = HttpNtlmAuth(username, password, session)
session.headers['Content-Type'] = 'text/xml; charset=utf-8'

# Устанавливаем цель запроса в заголовке запроса
session.headers['SOAPAction'] = 'http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/SessionLogin'

# SOAP-сообщение, в котором передаем адрес и сетевое имя клиента
body = """<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <SessionLogin xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <baseName></baseName>
      <sessionSettings>&lt;Settings&gt;&lt;Setting Name=&quot;ComputerAddress&quot; Type=&quot;string&quot; ReadOnly=&quot;1&quot;&gt;192.168.0.2&lt;/Setting&gt;&lt;Setting Name=&quot;ComputerName&quot; Type=&quot;string&quot;&gt;connectedComputer&lt;/Setting&gt;&lt;Setting Name=&quot;LocaleID&quot; Type=&quot;int&quot;&gt;1049&lt;/Setting&gt;&lt;/Settings&gt;</sessionSettings>
    </SessionLogin>
  </soap:Body>
</soap:Envelope>"""

# Отправляем SOAP-сообщение
response = session.post(url, data=body)

# Разбираем ответ и получаем идентификатор сессии
responseParsed = ElementTree.fromstring(response.content)
sessionId = responseParsed.findtext('.//{http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/}sessionId')
----

== Добавление файла в базу данных

После открытия сессии можно, к примеру, добавить файл (не путать с версионным файлом -- _карточка файла с версиями_) в базу данных.

Для добавления файла в базу данных необходимо:

. Создать объект-файл в базе данных, используя метод xref:DevManualAppendix_WebService_Files_FileCreate.adoc[FileCreate].
. Открыть созданный объект для записи, используя метод xref:DevManualAppendix_WebService_Files_FileOpen.adoc[FileOpen].
. Записать содержимое файла с файловой системы в открытый объект-файл, используя метод xref:DevManualAppendix_WebService_Files_FileWrite.adoc[FileWrite].
. Закрыть с сохранением открытый объект, используя метод xref:DevManualAppendix_WebService_Files_FileClose.adoc[FileClose]

Итоговый код может выглядеть следующим образом:

[source,pre,codeblock,language-python]
----
# Создаем объект-файл #

# Изменяем цель запроса в заголовке запроса
session.headers['SOAPAction'] = "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/FileCreate"

# SOAP-сообщение
body = """<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <FileCreate xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <sessionId>%s</sessionId>
      <name>Document_Order.docx</name>
    </FileCreate>
  </soap:Body>
</soap:Envelope>""" % sessionId

# Отправляем SOAP-сообщение
response = session.post(url, data=body)

# Разбираем ответ и получаем идентификатор объект-файла
responseParsed = ElementTree.fromstring(response.content)
fileId = responseParsed.findtext(".//{http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/}fileId")


# Открываем объект-файл #

# Изменяем цель запроса в заголовке запроса
session.headers['SOAPAction'] = "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/FileOpen"

# SOAP-сообщение
body = """<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <FileOpen xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <sessionId>%s</sessionId>
      <fileId>%s</fileId>
      <modify>true</modify>
    </FileOpen>
  </soap:Body>
</soap:Envelope>""" % (sessionId, fileId)

# Отправляем SOAP-сообщение
response = session.post(url, data=body)

# Разбираем ответ и выводим идентификатор новой карточки
responseParsed = ElementTree.fromstring(response.content)
fileHandleId = responseParsed.findtext(".//{http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/}fileHandleId")


# Запись данных в файл #

# Изменяем цель запроса в заголовке запроса
session.headers['SOAPAction'] = "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/FileWrite"

with open("Z:\\Order.docx", "rb") as document:
    encoded_string = base64.b64encode(document.read()).decode('utf-8')

# SOAP-сообщение
body = """<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <FileWrite xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <sessionId>%s</sessionId>
      <fileHandleId>%s</fileHandleId>
      <compressed>false</compressed>
      <fileData>%s</fileData>
    </FileWrite>
  </soap:Body>
</soap:Envelope>""" % (sessionId, fileHandleId, encoded_string)

# Отправляем SOAP-сообщение
session.post(url, data=body)


# Сохранение файла #

# Изменяем цель запроса в заголовке запроса
session.headers['SOAPAction'] = "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/FileClose"

# SOAP-сообщение
body = """<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <FileClose xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <sessionId>%s</sessionId>
      <fileHandleId>%s</fileHandleId>
      <commitWrite>true</commitWrite>
    </FileClose>
  </soap:Body>
</soap:Envelope>""" % (sessionId, fileHandleId)

# Отправляем SOAP-сообщение
session.post(url, data=body)

# Выводим идентификатор файла
print(fileId)
----

Приведенный пример может быть значительно упрощен, к примеру, с использованием soap-клиента, который может получить описание методов из WSDL.

== Создание карточки файла с версиями

Для создания карточки файла с версиями необходимо:

. Создать карточку типа "Файл с версиями", используя метод xref:DevManualAppendix_WebService_Card_CardCreate.adoc[CardCreate].
. Создать строки в секциях "Версии" и "Общая информация", используя метод xref:DevManualAppendix_WebService_Rows_RowCreate.adoc[RowCreate].
. Добавить, используя метод xref:DevManualAppendix_WebService_Rows_RowSetData.adoc[RowSetData], в строку секции "Версии" значения полей (см. xref:DM_StandartCards.adoc[Описание полей стандартной карточки]): FileId (используем идентификатор файла, полученный в предыдущем примере), Version и VersionNumber.
. Добавить, используя метод RowSetData, в строку секции "Общая информация" значения полей: CheckinDate, CurrentID (указывается идентификатор строки версии, созданной ранее), CurrentVersion, Name и NextVersion.
. Изменить описание карточки, используя xref:DevManualAppendix_WebService_Card_CardSetInfo.adoc[CardSetInfo].

Итоговый код может выглядеть следующим образом:

[source,pre,codeblock,language-python]
----
# Создание карточки типа Файл с версиями #

# Изменяем цель запроса в заголовке запроса
session.headers['SOAPAction'] = "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/CardCreate"

# SOAP-сообщение
body = """<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <CardCreate xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <sessionId>%s</sessionId>
      <cardId>6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3</cardId>
      <newInstanceId>00000000-0000-0000-0000-000000000000</newInstanceId>
    </CardCreate>
  </soap:Body>
</soap:Envelope>""" % sessionId

# Отправляем SOAP-сообщение
response = session.post(url, data=body)

# Разбираем ответ для получения идентификатора созданной карточки
responseParsed = ElementTree.fromstring(response.content)
newInstanceId = responseParsed.findtext(".//{http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/}newInstanceId")


# Создаем строки для секций 'Общая информация' и 'Версии', а также заполняем их поля #

# Для простоты используем дополнительные методы create_row (создание строки) и update_row (запись данных в строку)
# Реализация методов create_row и update_row приведена далее
versions_row_id = create_row(newInstanceId, 'F831372E-8A76-4ABC-AF15-D86DC5FFBE12')
update_row('F831372E-8A76-4ABC-AF15-D86DC5FFBE12', versions_row_id, '&lt;RowData&gt;&lt;row FileID=&quot;%s&quot; Version=&quot;1&quot; VersionNumber=&quot;2&quot;/&gt;&lt;/RowData&gt;' % fileId)

maininfo_row_id = create_row(newInstanceId, '2FDE03C2-FF87-4E42-A8C2-7CED181977FB')
update_row('2FDE03C2-FF87-4E42-A8C2-7CED181977FB', maininfo_row_id,
           '&lt;RowData&gt;&lt;row CheckinDate=&quot;%s&quot; CurrentID=&quot;%s&quot; CurrentVersion=&quot;1.1&quot; Name=&quot;Document_Order versionedFileCard&quot; NextVersion=&quot;2&quot; /&gt;&lt;/RowData&gt;' %(datetime.datetime.now().isoformat(), versions_row_id) )


# Добавляем описание #

# Изменяем цель запроса в заголовке запроса
session.headers['SOAPAction'] = "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/CardSetInfo"

# SOAP-сообщение
body = """<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <CardSetInfo xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <sessionId>%s</sessionId>
      <instanceID>%s</instanceID>
      <description>Document_Order versionedFileCard</description>
      <template>false</template>
      <topic></topic>
    </CardSetInfo>
  </soap:Body>
</soap:Envelope>""" % (sessionId, newInstanceId)

# Отправляем SOAP-сообщение
response = session.post(url, data=body)

# Выводим идентификатор созданной карточки
print(newInstanceId)
----

Идентификатор полученной карточки версионного файла можно, к примеру, записать в секцию "Файлы" карточки типа "Документ", что соответствует прикрепление файла к документу.

Дополнительные методы, использованные выше, реализованы следующим образом:

[source,pre,codeblock,language-python]
----
# Добавление пустой строки в секцию section_id карточки card_id

def create_row(card_id, section_id):
    session.headers['SOAPAction'] =  "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/RowCreate"

 # SOAP-сообщение
body =  """<?xml version="1.0" encoding="utf-8"?>
     <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
     <soap:Body>
     <RowCreate xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
     <sessionId>%s</sessionId>
     <sectionId>%s</sectionId>
     <rowId>00000000-0000-0000-0000-000000000000</rowId>
     <instanceID>%s</instanceID>
     <parentRowId>00000000-0000-0000-0000-000000000000</parentRowId>
     <parentTreeRowId>00000000-0000-0000-0000-000000000000</parentTreeRowId>
     </RowCreate>
     </soap:Body>
     </soap:Envelope>""" % (sessionId, section_id, card_id)

# Отправляем SOAP-сообщение
response = session.post(url,  data=body)

# Разбираем ответ и выводим идентификатор новой строки
responseParsed = ElementTree.fromstring(response.content)
    newRowId = responseParsed.findtext(".//{http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/}newRowId")
return newRowId


# Запись данных rowData в строку rowId секции sectionId #

def update_row(sectionId, rowId, rowData):
# Изменяем цель запроса в заголовке запроса
session.headers[ 'SOAPAction'] =  "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/RowSetData"

 # SOAP-сообщение
body =  """<?xml version="1.0" encoding="utf-8"?>
     <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
     <soap:Body>
     <RowSetData xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
     <sessionId>%s</sessionId>
     <sectionId>%s</sectionId>
     <rowId>%s</rowId>
     <rowData>%s</rowData>
     </RowSetData>
     </soap:Body>
     </soap:Envelope>""" % (sessionId, sectionId, rowId, rowData)

# Отправляем SOAP-сообщение
session.post(url,  data=body)
----
