= Параметры активации справочников

Открытие некоторых справочников Docsvision может сопровождаться установкой курсора (открытием) на заранее определенной записи справочника, что уменьшить количество переходов в интерфейсе при редактировании записи. Для установки курсора на определенный записи достаточно передать в метод xref:../api/DocsVision/Platform/CardHost/ICardHost_IN.adoc[CardHost.ShowCard] специальный объект, содержащий параметры активации карточки.

Далее приведен пример скрипта карточки, в котором используется функциональность открытия [.dfn .term]_Справочника сотрудников_ с установкой курсора на определенном сотруднике

[source,pre,codeblock]
----
// Приведение идентификатора сотрудника с требуемому формату
string employeeID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant();
         
// Получение идентификатора Справочника сотрудников
Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefStaff.ID;

// Получение идентификатора секции (в примере, секция Сотрудники), из которой осуществляется выбор
string sectionID = DocsVision.BackOffice.CardLib.CardDefs.RefStaff.Employees.ID.ToString("B").ToUpperInvariant();
         
// Установка параметров активации
object activateParams = new object[] { sectionID, employeeID, System.Reflection.Missing.Value, System.Reflection.Missing.Value,
 System.Reflection.Missing.Value, false, false, false, 0, System.Reflection.Missing.Value, true, true, 0 };

// Отображение справочника       
base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, ActivateMode.Select, ActivateFlags.None, activateParams);
----

Список допустимых параметров активации для разных типов справочников будет различным. Ниже приведены допустимые параметры и их назначение, сгруппированные по типу справочника.

== Справочник сотрудников

[width="100%",cols="15%,85%",options="header",]
|===
|Номер параметра |Описание
|0 a|
Идентификатор секции, из которой производится выбор:

* Сотрудники ([.keyword .apiname]#DocsVision.BackOffice.CardLib.CardDefs.RefStaff.Employees.ID#)
* Подразделения ([.keyword .apiname]#DocsVision.BackOffice.CardLib.CardDefs.RefStaff.Units.ID#)
* Роли ([.keyword .apiname]#DocsVision.BackOffice.CardLib.CardDefs.RefStaff.Roles.ID#)
* Группы ([.keyword .apiname]#DocsVision.BackOffice.CardLib.CardDefs.RefStaff.Group.ID#)
* Должности ([.keyword .apiname]#DocsVision.BackOffice.CardLib.CardDefs.RefStaff.Positions.ID#)

|1 |Идентификатор объекта, выбираемого при открытии справочника.
|3 |Массив идентификаторов выбранных объектов.
|5 |При true разрешается множественный выбор. Если указан false, то ,например, метод [.keyword .apiname]#SelectFromCard# вернет один результат независимо от количества выбранных записей.
|6 |Если true, то метод возвращает идентификаторы безопасности, а не идентификаторы сотрудников, подразделений и т.д.
|8 a|
Включает ограничение на выбор:

* 0 - ограничения отключены;
* 1 - выбор разрешен только из организаций;
* 2 - выбор разрешен только из групп.

|9 |Если задействован параметр 8, то указывается идентификатор той группы или подразделения, из которого будет разрешен выбор. Остальные подразделения или группы будут скрыты.
|10 |Не разрешать выбор подразделений, если true.
|11 |Не разрешать выбор организаций, если true.
|12 |Режим открытия записи (см. xref:../api/DocsVision/BackOffice/WinForms/Controls/ItemSelectionMode_EN.adoc[ItemSelectionMode]) приведенный к типу int.
|13 |Не отображать записи с флагом NotAvailable.
|14 |Не отображать записи с флагом NotSearchable.
|===

== Справочник контрагентов

[width="100%",cols="15%,85%",options="header",]
|===
|Номер параметра |Описание
|0 a|
Идентификатор секции, из которой производится выбор:

* Сотрудники ([.keyword .apiname]#CardLib.CardDefs.RefPartners.Employees.ID#)
* Подразделения ([.keyword .apiname]#CardLib.CardDefs.RefPartners.Companies.ID#)
* Группы ([.keyword .apiname]#CardLib.CardDefs.RefPartners.Groups.ID#)
* Должности ([.keyword .apiname]#CardLib.CardDefs.RefPartners.Positions.ID#)

|1 |Идентификатор объекта, выбираемого при открытии справочника.
|3 |Массив идентификаторов выбранных объектов.
|5 |При true разрешается множественный выбор.
|8 |Не разрешать выбор подразделений, если true.
|9 |Не разрешать выбор организаций, если true.
|10 |Режим открытия записи (см. xref:../api/DocsVision/BackOffice/WinForms/Controls/ItemSelectionMode_EN.adoc[ItemSelectionMode]) приведенный к типу int.
|===

== Конструктор справочников

[width="100%",cols="15%,85%",options="header",]
|===
|Номер параметра |Описание
|0 a|
Идентификатор секции, из которой производится выбор:

* Узлы справочника ([.keyword .apiname]#RefBaseUniversal.ItemTypes.ID#)
* Строки справочника ([.keyword .apiname]#RefBaseUniversal.Items.ID#)

|1 a|
Идентификатор открываемой/выбираемой строки.

Может использоваться только при открытии в режиме чтения/редактирования [.dfn .term]_Конструктора справочников_ методом [.keyword .apiname]#CardHost.ShowCard#. Должен быть указан узел (параметр 2), из которого выбирается строка.

|2 a|
Идентификатор узла из которого осуществляется выбор.

В режиме выбора строк ограничивает узел (отображается только указанный узел и его дочерние узлы), из которого могут быть выбраны строки.

Не предназначен для ограничения области выбора в режиме выбора узла.

|3 |Режим открытия записи (см. xref:../api/DocsVision/BackOffice/WinForms/Controls/ItemSelectionMode_EN.adoc[ItemSelectionMode]) приведенный к типу int.
|===

К примеру, чтобы выбрать строку (без открытия записи) из узла [.dfn .term]_Конструктора справочников_, нужно выполнить скрипт:

[source,pre,codeblock,language-csharp]
----
// Идентификатор Конструктора справочников
Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefBaseUniversal.ID;

// Идентификатор узла, из которого выбирается строка
Guid idNode = Guid.Parse("B8B58477-CCC3-4213-8190-EFC66FEF86C1");

// Идентификатор выбираемой строки
Guid idRow = Guid.Parse("C0C164D7-2C0F-48E9-A642-3ABC8D2CEFBB");
        
        
// Установка параметров активации
object activateParams = new object[] { DocsVision.BackOffice.CardLib.CardDefs.RefBaseUniversal.Items.ID, idRow, idNode, (int)ItemSelectionMode.Positioning};
                
// Отображение справочника с позиционирование курсора на нужной строке    
base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, ActivateMode.ReadOnly, ActivateFlags.None, activateParams);
----

== Справочник ссылок

[width="100%",cols="15%,85%",options="header",]
|===
|Номер параметра |Описание
|0 |ID секции, из которой выбираем (только типы ссылок)
|1 |ранее выбранный элемент
|3 |True, позволять выбор нескольких элементов
|6 a|
Режим открытия записи:

* 0 – позиционирование;
* 1 - редактирование;
* 2 – чтение;

|===

== Справочник категорий

[width="100%",cols="15%,85%",options="header",]
|===
|Номер параметра |Описание
|1 |Идентификатор объекта, выбираемого при открытии справочника.
|2 |При true разрешается множественный выбор.
|3 |Массив идентификаторов выбранных объектов.
|4 |Режим открытия записи (см. xref:../api/DocsVision/BackOffice/WinForms/Controls/ItemSelectionMode_EN.adoc[ItemSelectionMode]) приведенный к типу int.
|===

*На уровень выше:* xref:../pages/dm_appendix.adoc[Приложение]
