= Архивирование и извлечение карточки из архива

Для того, чтобы убрать из списка карточек карточки, работа с которыми завершена, они могут быть помещены в архив.

За архивацию карточек на уровне базового API отвечает метод [.keyword .apiname]#Archive#, который предоставляется классом карточки - [.keyword .apiname]#CardData#:

[source,pre,codeblock,language-csharp]
----
// Получаем данные карточки
CardData cardData = userSession.CardManager.GetCardData(cardId);

// Помещаем карточку в архив
cardData.Archive(ArchiveOptions.None);
----

Второй метод класса [.keyword .apiname]#CardData# позволяет извлечь карточку из архива:

[source,pre,codeblock,language-csharp]
----
cardData.Dearchive(ArchiveOptions.None)
----

Параметр, передаваемый в методы, определяет сценарий помещения и извлечения карточки из архива. Данный параметр может принимать значения:

* ArchiveOptions.None - без дополнительных параметров.
* ArchiveOptions.Delay - архивирование будет выполнено с задержкой.
* ArchiveOptions.IncludeLinkedCards - будут также архивированы связанные с архивируемой карточки.
* ArchiveOptions.IncludeLinkedFiles - будут также архивированы связанные с архивируемой файлы.

Объектная модель не предлагает методов для работы с архивом. При необходимости, пользуйтесь методами базового API.

== См. далее

* xref:dm_search.adoc[Поиск]

*На уровень выше:* xref:../pages/dm_cards.adoc[Работа с карточками]
