= Разработка объектной модели карточки

В объектной модели карточки должны быть перечислены все (или необходимые) её секции.

Базовым классом карточки выступает всё тот же класс ObjectBase.

В качестве примера реализуем объектную модель карточки, содержащую секции, рассмотренные xref:DM_CardsDev_CreateObjectModel_Sections.adoc[ранее]. Регистрация секций в карточке, аналогична регистрации полей в секции:

[source,pre,codeblock]
----
public class SampleCard : ObjectBase
{
 // Объявляем секции карточки
 // В качестве примера: плоская, коллекционная и иерархическая
 public static readonly ObjectProperty StructSectionProperty;
 public static readonly ObjectProperty CollectionSectionProperty;
 public static readonly ObjectProperty TreeSectionProperty;

 // Предоставляем доступ к секциям, а точнее к их строчкам
 public SampleCardStructSection StructSection
 {
  get
  {
   // Не обязательно. Если секция пустая (не содержит строчек), то в ней строчку
   if (((ObjectCollection<SampleCardStructSection>)base.GetValue(SampleCard.StructSectionProperty)).Count = 0)
   {
    ((ObjectCollection<SampleCardStructSection>)base.GetValue(SampleCard.StructSectionProperty)).Add(new SampleCardStructSection());
   }
   // Т.к. в секции может быть несколько строчек, для плоской секции возвращаем только одну строчку -- первую
   return ((ObjectCollection<SampleCardStructSection>)base.GetValue(SampleCard.StructSectionProperty)).First<SampleCardStructSection>();
  }
 }

 // Коллекционная секция возвращает весь список своих строчек
 public ObjectCollection<SampleCardCollectionSection> CollectionSection
 {
  get { return (ObjectCollection<SampleCardCollectionSection>)base.GetValue(SampleCard.CollectionSectionProperty); }
 }

 public ObjectCollection<SampleCardTreeSection> TreeSection
 {
  get { return (ObjectCollection<SampleCardTreeSection>)base.GetValue(SampleCard.TreeSectionProperty); }

  // Не обязательно. Добавлена возможность записывать значение секции напрямую
  set { base.SetValue(SampleCard.TreeSectionProperty, value); }
 }

 static SampleCard()
 {
  SampleCard.StructSectionProperty = ObjectProperty.Register("StructSection", typeof(ObjectCollection<SampleCardCollectionSection>), typeof(SampleCard));
  SampleCard.CollectionSectionProperty = ObjectProperty.Register("CollectionSection", typeof(ObjectCollection<SampleCardCollectionSection>), typeof(SampleCard));
  SampleCard.TreeSectionProperty = ObjectProperty.Register("TreeSection", typeof(ObjectCollection<SampleCardTreeSection>), typeof(SampleCard));
 }

 // Конструкторы для новой карточки и для существующей карточки
 protected internal SampleCard()
 {
 }
 protected internal SampleCard(ObjectInitializationData data): base(data)
 {
 }
}
----

Реализация объектной модели справочника ничем не отличается от реализации для карточки.

В библиотеке карточек _{bo}_ базовым классом карточки является класс xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[BaseCard], который дополняет функциональность класса ObjectBase, и который также можно использовать в качестве базового для объектной модели свой карточки. Для справочников в данном случае базовым классом выступает xref:api/DocsVision/BackOffice/ObjectModel/BaseDictionaryCard_CL.adoc[BaseDictionaryCard].

== См. далее

* xref:DM_CardsDev_CreateObjectModel_Mapper.adoc[Разработка преобразователя данных]
