= Модуль расширения Консоли настройки

В ряде случаев задача xref:DM_DistributionServer.adoc[установки серверной части решения] может быть усложнена необходимостью выполнения каких-то дополнительных действий, которые сложно (или невозможно) выполнить в рамках ограниченных возможностей инсталляционной программы. Такими действиями, в частности, могут являться:

* работа с базой данных;
* установка или конфигурирование NT-сервисов;
* создание Web-сайтов или виртуальных папок в IIS;
* взаимодействие с другими компонентами или решениями;
* изменение параметров работы решения после окончания установки
* и т.п.

Для упрощения решения этих задач предоставляется возможность разработки специального программного компонента - модуля расширения (Snap-In) для Консоли настройки Docsvision.

[NOTE]
====
[.note__title]#Прим.:# Консоль настройки Docsvision – универсальный инструмент для конфигурирования и администрирования сервера Docsvision. Подробнее его использование рассмотрено в «Руководстве администратора».
====

Механизм Snap-Ins (модулей расширения) является способом динамического расширения функциональности Консоли настройки новыми возможностями, которые могут появляться при установке в системе дополнительных модулей или решений. Аналогами подобного механизма могут выступать оснастки консоли администрирования (MMC) в Microsoft Windows или механизм плагинов (Plag-ins) в других программных средах.

[NOTE]
====
[.note__title]#Прим.:# В частности, средства конфигурирования стандартных решений «Управление процессами» и “Процессы WWF” также реализованы в виде модулей расширения для Консоли настройки – их можно рассматривать в качестве примера реализации.
====

Консоль настройки может работать в двух режимах:

* *Режим конфигурирования* (Мастера) – этот режим активируется при первичной установке или удалении конкретного решения (или сервера Docsvision в целом);
* *Режим администрирования* - этот режим активируется на рабочем сервере для изменения конкретных параметров работы сервера и/или конкретных решений.

Соответственно, каждый Snap-In для Консоли настройки также имеет возможность использовать один или оба этих режима. Например, можно реализовать Snap-In для собственного решения, который будет активироваться как при его установке (для выполнения каких-то сложных действий по регистрации компонент), так и позволит администратору системы менять какие-то параметры в процессе его работы.

В качестве Snap-In Консоли настройки может выступать любой программный компонент, реализующий ряд специальных интерфейсов (по аналогии с компонентами карточек Docsvision).

В коде компонента Snap-In могут быть реализованы следующие интерфейсы (все интерфейсы объявлены в сборке [.ph .filepath]`DocsVision.Tools.ServerConsole.Interfaces.dll`, которую необходимо подключить к проекту):

[.keyword .apiname]#DocsVision.Tools.ServerConsole.ISnapIn# – обязательный интерфейс для любого модуля расширения. Предполагает реализацию следующих свойств и методов:

* [.keyword .apiname]#Name# – свойство, которое должно возвращать отображаемое имя модуля расширения;
* [.keyword .apiname]#Initialize(IEnvironment environment)# – метод, который вызывается при первичной инициализации модуля расширения. На вход метода передается объект, описывающий контекст исполнения (Консоль Настройки);
* [.keyword .apiname]#QueryInterface(SnapInInterfacesEnum itfType)# - метод, который вызывается при запросе конкретных функций модуля расширения. Модуль расширения может выполнять следующие функции:
** [.keyword .apiname]#SnapInInterfacesEnum.CONFIGURATOR# - первичная инсталляция решения;
** [.keyword .apiname]#SnapInInterfacesEnum.WIZARD_CONTROL# - инсталляция в режиме Мастера;
** [.keyword .apiname]#SnapInInterfacesEnum.CONSOLE_CONTROL# - режим администрирования (настройки);
** [.keyword .apiname]#SnapInInterfacesEnum.TOOLS# - дополнительные инструменты;
** [.keyword .apiname]#SnapInInterfacesEnum.UNINSTALL_SNAP_IN# - режим деинсталляции решения;
** [.keyword .apiname]#SnapInInterfacesEnum.DB_INFORMATION# - режим обновления базы данных.
+
При запросе конкретной функции модуль расширения может либо вернуть ссылку на объект, реализующий соответствующий интерфейс (если он выполняет эту функцию), либо вернуть null (если он не выполняет эту функцию);

[.keyword .apiname]#DocsVision.Tools.ServerConsole.IDBInformation# – данный интерфейс является обязательным для модулей расширения, которые выполняют функции конфигурации или удаления решения. Методы данного интерфейса предназначены для загрузки каких-либо значений в базу данных (например, это необходимо при установке новых библиотек карточек, или шлюзов Workflow).

[NOTE]
====
[.note__title]#Важное замечание:# Обратите внимание на то, что для работы (например, обновление базы данных) с собственной библиотекой карточек из Консоли настройки Docsvision, необходимо разработать и загрузить в Консоль настройки расширение Windows-клиента, которое реализует интерфейс [.keyword .apiname]#IDBInformation#. Данное расширение должно возвращать схему разработанной библиотеки карточек.
====

Интерфейс предполагает реализацию следующих свойств и методов:

* [.keyword .apiname]#GetScript(ScriptTypeEnum type)# - Консоль настройки может вызвать данный метод при выполнении каких-либо действий с базой данных. В зависимости от типа действия, модуль расширения должен вернуть одно из следующих значений:
** [.keyword]*INSTALL_TABLES* – путь к файлу SQL-скрипта создания таблиц (для библиотек карточек);
** [.keyword]*INSTALL_ACTIONS* – путь к файлу SQL-скрипта создания хранимых процедур (для библиотек карточек);
** [.keyword]*INSTALL_FT_CATALOGS* – путь к файлу SQL-скрипта создания полнотекстовых каталогов;
** [.keyword]*UNINSTALL_FT_CATALOGS* – путь к файлу SQL-скрипта удаления полнотекстовых каталогов;
** [.keyword]*UNREGISTER_CARD_LIBRARY* – путь к файлу SQL-скрипта удаления библиотеки карточек;
** [.keyword]*UNINSTALL_ALL* – путь к файлу SQL-скрипта удаления других данных решения.
* [.keyword .apiname]#GetCardPackage()# - возвращает путь к файлу – пакету инсталлируемых XML-описаний карточек (это может потребоваться в случае, если для корректной работы решения необходимо наличии в базе данных каких-то предопределённых значений – заполненных справочников, шаблонов карточек и т.д.).
+
Файл с описанием пакета имеет следующий формат:

[source,pre,codeblock,language-xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<CardPackage>
 <Card Path="<путь_к_файлу_XML" ID="ID_карточки" Replace="1 если карточка должна заменить существующую; 0 – если дополнить"/>
 …
</CardPackage>
----
* [.keyword .apiname]#ContainsCardLib# – признак, содержит ли данное решение библиотеку карточек (нужно ли запрашивать SQL-скрипты дял создания таблиц и хранимых процедур).

[.keyword .apiname]#DocsVision.Tools.ServerConsole.IConfigurator# - необязательный интерфейс. Может быть реализован в модуле расширения, выполняющем функции первичной конфигурации решения (SnapInInterfacesEnum.CONFIGURATOR). Предполагает реализацию следующего метода:

* [.keyword .apiname]#Execute()# - единственный метод, который должен выполнять все задачи по корректной инсталляции решения. Возвращаемое значение показывает успешность (true) или неудачу (false) установки.

[.keyword .apiname]#DocsVision.Tools.ServerConsole.IUninstallSnapIn# - необязательный интерфейс. Может быть реализован в модуле расширения, выполняющем функции удаления решения (SnapInInterfacesEnum.UNINSTALL_SNAP_IN). Предполагает реализацию следующего метода:

* [.keyword .apiname]#Uninstall(Boolean)# - единственный метод, который должен выполнять все задачи по корректному удалению решения. Входящий параметр указывает на необходимость удалить (true) или сохранить (false) настройки решения.

[.keyword .apiname]#DocsVision.Tools.ServerConsole.ITools# - необязательный интерфейс. Может быть реализован в модуле расширения, дополняющим Консоль Настройки специфическими Инструментами (SnapInInterfacesEnum.TOOLS). Предполагает реализацию следующего свойства:

* [.keyword .apiname]#Controls# - возвращает массив элементов управления для конкретных инструментов. Элемент управления для реализации каждого инструмента должен реализовывать интерфейс IControl (IControl2).

[.keyword .apiname]#DocsVision.Tools.ServerConsole.IConsoleControl# - необязательный интерфейс. Может быть реализован в элементе управления, который будет отображаться пользователю при установке в режиме Мастера (SnapInInterfacesEnum.WIZARD_CONTROL), или в режиме администрирования (SnapInInterfacesEnum.CONSOLE_CONTROL). Интерфейс предполагает реализацию следующих свойств и методов:

* [.keyword .apiname]#ControlChanged# – событие, которое элемент управления должен инициировать при изменении данных;
* [.keyword .apiname]#Caption# – свойство, возвращающее отображаемое имя элемента управления;
* [.keyword .apiname]#Instance# – свойство, возвращающее ссылку на элемент управления WinForms;
* [.keyword .apiname]#Changed# – признак изменения настроек решения;
* [.keyword .apiname]#Valid# – признак корректности указанных настроек решения;
* [.keyword .apiname]#Initialize()# – метод первичной инициализации элемента управления;
* [.keyword .apiname]#Execute()# – метод, вызываемый при завершении конфигурирования.

Пример кода модуля расширения с реализацией этих интерфейсов:

[source,pre,codeblock,language-csharp]
----
namespace DocsVision.Sample.SnapIn
{
 public class SnapIn : ISnapIn, IConfigurator, IUninstallSnapIn
 {
  private IEnvironment _environment;
  
  // Реализация интерфейса ISnapIn
  public SnapIn() { }
  
  public string Name
  {
   get { return "My Snap-In"; }
  }
  
  public string LibraryID
  {
   get { return "00000000-0000-0000-0000-000000000000"; }
  } 
  
  public void Initialize(IEnvironment environment)
  {
   _environment = environment;
  }
  
  public object QueryInterface(SnapInInterfacesEnum itfType)
  {
   object result = null;
   switch (itfType)
   {
    case SnapInInterfacesEnum.CONFIGURATOR:
    case SnapInInterfacesEnum.UNINSTALL_SNAP_IN:
     result = this;
     break;
   }
   return result;
  }
  
  // Реализация интерфейса IConfigurator
  public bool Execute()
  {
   // Регистрация компонент решения
   
   return true;
  }
  
  // Реализация интерфейса IUninstallSnapIn
  public void Uninstall(bool removeSettings)
  {
   // Разрегистрация компонент решения
  }
 }
}
----

В коде модуля расширения, можно обращаться к различным вспомогательным сервисам, предоставляемым Консолью настройки для упрощения решения типовых задач. Для этого нужно воспользоваться ссылкой на объект контекста ([.keyword .apiname]#IEnvironment#), которая передается модулю расширения при инициализации. Этот объект имеет единственный метод: [.keyword .apiname]#QueryService(EnvironmentServiceEnum service)# – возвращающий ссылку на конкретный вспомогательный сервис, запрошенный в параметре. Доступны следующие сервисы:

* [.keyword .apiname]#EnvironmentServiceEnum.LOG# – возвращает ссылку на сервис ILog, позволяющий записывать сообщения в общий журнал работы Консоли настройки;
* [.keyword .apiname]#EnvironmentServiceEnum.COMMON_SETTINGS# – возвращает ссылку на сервис ICommonSettings2, позволяющий прочитать и/или изменить основные настройки сервера Docsvision;
* [.keyword .apiname]#EnvironmentServiceEnum.WORKER_PROCESS# – возвращает ссылку на сервис IWorkerProcess, позволяющий модулю расширения корректно функционировать при выполнении длительных операций (например, отображать индикатор прогресса выполнения). Для реализации таких операций, соответствующие объекты модуля расширения должны реализовывать интерфейс ILengthyOperation3;
* [.keyword .apiname]#EnvironmentServiceEnum.DB_INSTALLER#– возвращает ссылку на сервис IDbInstaller, позволяющий выполнять операции с базой данных (например, исполнить сценарий SQL из строки или из файла);
* [.keyword .apiname]#EnvironmentServiceEnum.CARD_LIB_CONFIGURATOR# – возвращает ссылку на сервис ICardLibConfigurator2, позволяющий корректно установить или удалить описание библиотеки карточек;
* [.keyword .apiname]#EnvironmentServiceEnum.CARD_IMPORTER# – возвращает ссылку на сервис ICardImporter, позволяющий загрузить в базу данных предопределённые значения (экспортированные в формат XML);
* [.keyword .apiname]#EnvironmentServiceEnum.MANAGEMENT# – возвращает ссылку на сервис IManagement, позволяющий управлять работой других сервисов и решений.

Пример использования вспомогательного сервиса Консоли настройки в модуле расширения для записи сообщения в журнал:

[source,pre,codeblock,language-csharp]
----
ILog log = (ILog)_environment.QueryService(EnvironmentServiceEnum.LOG);
log.WriteMessage("Конфигурирование решения успешно завершено");
----

Разработанный модуль расширения необходимо зарегистрировать на сервере в процессе инсталляции серверной части решения. Для этого программа инсталляции должна создать в реестре ключ в ветке [.ph .filepath]`HKLM\Software\DocsVision\\{ВЕРСИЯ}\Console\Snap-Ins`. Необходимо создать ключ с именем своего модуля расширения, в котором создать два строковых значения:

* Path – полный путь к сборке, в которой реализован модуль расширения;
* TypeName – имя основного класса, реализующего интерфейс ISnapIn в разработанном модуле расширения (например, DocsVision.Sample.SnapIn.SnapIn).

Для того, чтобы запустить Консоль настройки в режиме конфигурирования нового модуля расширения, необходимо запустить её исполняемый файл с ключами: [.ph .filepath]`ServerConsole.exe /c /n \{ИМЯ_РЕШЕНИЯ}`. Вызов этой команды можно сделать последним шагом программы инсталляции серверной части решения.

== См. также

* xref:dm_testing.adoc[Отладка и тестирование]

*На уровень выше:* xref:../pages/dm_extension.adoc[Разработка расширений Docsvision]
