= Подключение к серверу Docsvision

Первым шагом на пути разработки внешнего, по отношению к серверу и клиенту (Windows-клиенту) Docsvision, приложению является подключение к серверу Docsvision. При этом должен быть получен экземпляр [.dfn .term]_пользовательской сессии_ (или сессии пользователя) - главный объект базового API, обеспечивающий единую точку доступа к остальным функциям API данного уровня. При разработке скриптов карточки (в [.dfn .term]_Конструкторе скриптов_, либо в [.dfn .term]_Конструкторе разметок_) и бизнес-процессов создавать пользовательскую сессию не требуется - готовую сессию можно получить из класса скрипта карточки, а также из параметров вызываемых в бизнес-процессе методов.

С физической точки зрения, сессия - контекст сеанса связи с сервером для конкретного пользователя. Сессия ассоциируется с конкретной доменной учетной записью, от имени которой установлено соединение, и в дальнейшем все привилегии на доступ к данным из этой сессии будут проверяться именно для этой учетной записи.

[NOTE]
====
[.note__title]#Важное замечание:# Для выполнения операции с привилегиями другого пользователя необходимо явно указать его данные при создании сессии.
====

С точки зрения разработки, [.dfn .term]_пользовательская сессия_ - экземпляр класса xref:../api/DocsVision/Platform/ObjectManager/UserSession_CL.adoc[UserSession]), который создается следующим образом:

[source,pre,codeblock,language-csharp]
----
UserSession CreateUserSession()
{
 // Создаем экземпляр менеджера сессий
 SessionManager sessionManager = SessionManager.CreateInstance();

            
 // SERVERNAME - имя сервера Docsvision
 // USERNAME и PASSWORD - данные учетной записи для подключения к серверу Docsvision
 string connectionString = "ConnectAddress=http://{SERVERNAME}/DocsVision/StorageServer/StorageServerService.asmx;UserName={USERNAME};Password={PASSWORD}";
            
 // Передаем менеджеру сессий параметры подключения к серверу (описание см. по ссылке)
 sessionManager.Connect(connectionString);

 // Создаем сессию пользователя
 UserSession userSession = sessionManager.CreateSession();

 return userSession;
}
----

Для использования приведенных в коде типов потребуется:

. Добавить в проект сборку Docsvision:
* [.ph .filepath]`DocsVision.Platform.ObjectManager.dll`
+
Указанный DLL-файл входит в состав клиента и сервера Docsvision.
. Подключить пространство имен:

[source,pre,codeblock,language-csharp]
----
using DocsVision.Platform.ObjectManager;
----

В приведенном выше примере строка подключения к серверу содержит логин и пароль пользователя, если эти сведения не указываются, то подключение будет выполнено от имени пользователя, запустившего программу. Полный список параметров соединения с сервером Docsvision приведен в разделе xref:dm_appendix_serverconnectionparameters.adoc[Параметры соединения с сервером Docsvision].

Каждая пользовательская сессия обладает набором определенных параметров, значение которых устанавливается автоматически (значение некоторых параметров можно изменить, но только на время работы в сессии). Значение определенного параметра пользовательской сессии можно из массива [.keyword .apiname]#UserSession.Properties#.

[NOTE]
====
[.note__title]#Прим.:# Описание доступных параметров приведено в разделе xref:dm_appendix_usersessionproperties.adoc[Список свойств пользовательской сессии].
====

Для работы с пользовательскими сессиями могут быть полезны два других метода [.dfn .term]_менеджера сессий_:

* [.keyword .apiname]#CloseSession(Guid)# - принудительно закрывает любую пользовательскую сессию (требуются права администратора системы);
* [.keyword .apiname]#GetOpenSessions# - возвращает список всех открытых сессий.

== См. далее

* xref:dm_createobjectcontext.adoc[Инициализация контекста объектов]

*На уровень выше:* xref:../pages/dm_container.adoc[Руководство по разработке]
