= Блокировка и снятие блокировки

Чтобы предупредить возникновение конфликтных ситуаций, вытекающих из одновременной работы нескольких пользователей с одним объектом, платформа Docsvision предлагает использовать механизм блокировок, который защищает отдельный объект (карточку или строку) от изменений из сессий других пользователей, оставляя его доступным на чтение.

Система предлагает два варианта блокировки:

* Временная, ограниченная сроком существования пользовательской сессии, из которой блокировка была установлена. Такая блокировка снимается автоматически после завершения пользовательской сессии, если объект не был освобожден пользователем самостоятельно.
* Постоянная, которая действует во время существования пользовательской сессии, из которой блокировка установлена, а также после её завершения. Данная блокировка может быть снята только явно – тем, кто её установил, либо администратором системы.

== Базовый API

Базовый API предоставляет методы для установки блокировки на карточку, строку и файл.

На карточку может быть установлена как временная, так и постоянная блокировка:

[source,csharp]
----
// Получаем карточку
CardData cardData = userSession.CardManager.GetCardData(cardId);

// Устанавливаем временную блокировку
card.PlaceLock();

// Устанавливаем постоянную блокировку
card.PlaceLock(true);
----

Аналогичным образом устанавливается временна или постоянная блокировка на строку секции:

[source,csharp]
----
// Получаем секцию, содержащую блокируемую строку
SectionData section = card.Sections[sectionId]

// Для примера, устанавливаем временную блокировку на первую строку секции
section.FirstRow.PlaceLock()
----

Абсолютно аналогично работает блокировка файлов (не путать с карточками файла с версиями и файлами документов):

[source,csharp]
----
// Получаем файл
FileData fileData = userSession.FileManager.GetFile(fileId);

// Устанавливаем постоянную блокировку
fileData.PlaceLock(true);
----

Помимо методов блокировки, классы карточек ([.keyword .apiname]#CardData#), строк ([.keyword .apiname]#RowData#) и файлов ([.keyword .apiname]#FileData#) содержат методы снятия блокировки, определяемые интерфейсом xref:..xref:api/DocsVision/Platform/ObjectManager/ILockable_IN.adoc[ILockable]:

* [.keyword .apiname]#RemoveLock# - снимает блокировку с объекта, установленную в собственной сессии;
* [.keyword .apiname]#ForceUnlock# - принудительно снимает блокировку, в т.ч. установленную другим пользователем - необходимы административные права.

Также интерфейс [.keyword .apiname]#ILockable# определяет несколько свойств:

* `LockStatus` - состояние блокировки.
* `LockOwner` - учетная запись сотрудника, выполнившего блокировку.

Устанавливать блокировку на объект рекомендуется во всех сценариях, связанных с изменением данных, непосредственно после получения объекта. В сочетании с проверкой состояния блокировки код может быть следующим:

[source,pre,codeblock]
----
// Проверяем наличие блокировки у карточки 
if (cardData.LockStatus = LockStatus.Free)
{
 // Установка временной блокировки
 cardData.PlaceLock();
}else
{
 MessageBox.Show("Карточка заблокирована пользователем " + cardData.LockOwner);
}
----

Здесь:

* cardData - карточка, которая должна быть заблокирована.

Помимо методов, которые предлагают классы карточек, строк и файлов, базовый API предоставляет специальный объект для работы с блокировками - _менеджер блокировок_, который можно получить из сессии пользователя:

[source,csharp]
----
LockManager lockManager = userSession.LockManager;
----

Менеджер блокировок предлагает два метода:

* GetLockableObject - возвращает интерфейс [.keyword .apiname]#ILockable# для карточки с определенным идентификатором.
* GetLockedObjects - предоставляет заблокированные объекты определенного типа, с возможность получения объектов, заблокированных только текущим пользователем.

== Объектная модель

API данного уровня предоставляет две точки доступа к механизму блокировки:

* методы _контекста объектов_:
** xref:..xref:api/DocsVision/Platform/ObjectModel/ObjectContext.LockObject_1_MT.adoc[ObjectContext.LockObject] - установка блокировки, в т.ч. постоянной;
** xref:..xref:api/DocsVision/Platform/ObjectModel/ObjectContext.UnlockObject_MT.adoc[ObjectContext.UnlockObject] - снятие собственной блокировки.
+
Заблокировать карточку, используя методы _контекста объектов_, можно следующим образом:
+
[source,csharp]
----
// Получаем карточку (но может быть и строка)
BaseCard card = objectContext.GetObject<BaseCard>(cardId);

// Устанавливаем постоянную блокировку
objectContext.LockObject(card, true);
----
+
Абсолютно аналогично блокируется строка карточки:
+
[source,csharp]
----
BaseCardSectionRow row = objectContext.GetObject<BaseCardSectionRow>(rowId);
objectContext.LockObject(row, true);
----
+
Здесь:
** rowId - идентификатор блокируемой строки.
* методы сервиса для работы с блокировками - xref:..xref:api/DocsVision/BackOffice/ObjectModel/Services/ILockService_IN.adoc[ILockService]:
** LockObject - устанавливает на объект временную блокировку.
** UnlockObject - снимает с объекта временную блокировку.
+
Далее приведен пример, в котором документ (карточка типа _Документ_) блокируется для изменения, после чего блокировка снимается.
+
[source,csharp]
----
// Получение сервиса для работы с блокировками
ILockService lockService = objectContext.GetService<ILockService>();

// Получение изменяемого документа
Document document = objectContext.GetObject<Document>(cardId);

// Проверяем, что объект не заблокирован
if (!(lockService.IsObjectLockedByAnotherUser(document) && lockService.IsObjectLockedByAnotherUser(document)))
{
 // Блокируем документ для изменения
 lockService.LockObject(document);
 
 // Вносим изменение. В качестве примера, изменяется название документа
 document.MainInfo.Name = "Новое название документа";
 objectContext.SaveObject(document);

 // Снимаем блокировку
 lockService.UnlockObject(document);
}
----
+
Блокировка и снятие блокировки со строк выполняется аналогично.

== См. далее

* xref:dm_cardarchive.adoc[Архивирование и извлечение карточки из архива]
