= Инсталляция серверной части решения

Если решение включает в себя какие-либо карточки (новые или модификацию имеющихся), то первоочередным шагом при его распространении является загрузка описаний этих карточек в базу данных на выбранном рабочем сервере.

Если решение предполагается установить на один конкретный сервер (разовая операция), то это действие можно выполнить вручную при помощи программы "CardManager"(установив на этот сервер пакет Resource Kit) или запуском SQL-скрипта, предварительно сгенерированного *CardManager* для этой библиотеки карточек (команда *Сгенерировать сценарий SQL для библиотеки карточек*). Оба этих способа приведут к одинаковому результату -- загрузке описаний карточек решения в конкретную базу данных.

[IMPORTANT]
====
При каждом обновлении версии платформы на сервере все дополнительные решения необходимо заново загружать в базу данных. В противном случае карточки этих решений будут считаться устаревшими и станут недоступны для использования (данные не будут потеряны, просто карточки решения не будут видны в {wincl}е).
====

Если же решение планируется тиражировать (устанавливать более чем на одной площадке), то выполнять обновление базы данных каждый раз вручную будет нецелесообразно. В этом случае рекомендуется создание отдельной инсталляционной программы для серверной части решения, с помощью которой обновление базы данных будет выполняться в автоматическом режиме.

Такая инсталляционная программа может быть создана при помощи любых специализированных средств (Install Shield, Visual Studio 2003 или 2005, WISE и т.п.), предназначенных для создания инсталляций. В состав этой инсталляционной программы можно будет включить специальный шаг, который будет исполнять SQL-скрипт по загрузке карточек решения в базу данных (выбор конкретной базы данных можно реализовать в диалоге в рамках этой же инсталляционной программы или прочитать имя текущей рабочей базы данных из реестра). Содержание данного шага зависит от конкретной среды создания инсталляционных программ (InstallShield, например, предлагает встроенный инструмент для исполнения SQL-сценариев; в других средах может понадобиться написать код для исполнения SQL самостоятельно и т.д.).

Кроме этого, в число задач серверной установки входит размещение инсталляционного пакета клиентской части решения (о создании этого пакета рассказывается ниже) в определённой папке на сервере, откуда этот пакет может быть загружен всеми клиентами. Пакет достаточно просто скопировать в заданную папку, которая обычно расположена по пути:`\ProgramFiles\DocsVision\Platform\\{ВЕРСИЯ_ПЛАТФОРМЫ}\Server\Site\Setup\\{ИМЯ_РЕШЕНИЯ}.`. Тогда этот инсталляционный пакет будет доступен с клиентских машин по URL:`http://\{ИМЯ_СЕРВЕРА}/\{ВИРТУАЛЬНАЯ_ПАПКА}/Setup/\{ИМЯ_РЕШЕНИЯ}/\{НАЗВАНИЕ_ПАКЕТА}`. Например: `http://localhost/DocsVision/Setup/TakeOfficeClient/TakeOfficeClient.msi`

Возможны также какие-то дополнительные действия, которые должны быть выполненны в процессе установки серверной части решения -- это может быть регистрация и запуск каких-то специализированных сервисов, установка прикладных бизнес-процессов, создание виртуальных папок в IIS и т.п. В этом случае необходимые файлы этих дополнительных компонент решения рекомендуется размещать по пути:`\ProgramFiles\DocsVision\\{ИМЯ_РЕШЕНИЯ}\\{ВЕРСИЯ}\Server\`.

А необходимые для работы решения дополнительные настройки рекомендуется сохранять в реестре по пути: `HKLM\DocsVision\\{ИМЯ_РЕШЕНИЯ}\\{ВЕРСИЯ}\`.
