= Разработка расширений Docsvision

Полноценный процесс кастомизации решения не может обойтись без создания дополнений в клиентской или серверной части продукта. Организации может потребоваться внести в интерфейс Windows-клиента изменения не реализуемые в рамках объектной модели, например, возможность формирования файла экспорта определенного формата непосредственно из Windows-клиента. Также, может потребоваться выполнять определенные методы в контексте сервера и с его привилегиями. Разработка расширений с использованием объектной модели {dv} не сложнее процесса разработки карточки, а преимущество такого похода, через создание плагинов, неоспоримо.

Методика разработки расширений для Windows-клиента, во многом похожа на разработку карточек и описана в разделе xref:dm_extension_navigator.adoc[Расширение Windows-клиента].

Типы объектной модели, требующие реализации в процессе разработки серверных расширений, перечислены в разделе xref:DM_ServerPlugins.adoc[Серверные расширения].

Раздел xref:DM_ConsolePlugin.adoc[Модуль расширения Консоли настройки] освещает создание специфического компонента для Консоли настройки сервера Docsvision.

== См. далее

* xref:dm_extension_navigator.adoc[Расширение Windows-клиента]

.В данном разделе
* xref:DM_ServerPlugins.adoc[Серверные расширения]
* xref:DM_ConsolePlugin.adoc[Модуль расширения Консоли настройки]


