= Работа с файлами

Платформа Docsvision позволяет загружать в базу данных и извлекать из базы данных пользовательские файлы произвольного формата. Для работы с файлами в системе существует специальная системная карточка - _карточка файла_, а также набор интерфейсов менеджера объектов для манипуляций с файлами.

Для работы с файлами можно использовать несколько видов объектов:

* системный объект - *файл* - реализует простейшую функциональность для хранения файлов в базе данных Docsvision;
* системный объект - *версия файла* - реализует дополнительные атрибуты для нумерованной версии файла;
* системная *карточка файла* - поддерживают функциональность по хранению нескольких версий файла, комментариев к ним и дополнительных механизмов работы с файлом;
* карточка файла из решения «Делопроизводство» (не рассматривается);
* карточка - список файлов из решения «Делопроизводство» (не рассматривается).

== Системный объект - файл

Для работы с простыми файлами в системе предусмотрен объект xref:api/DocsVision/Platform/ObjectManager/FileData_CL.adoc[FileData]. Это самый низкоуровневый объект для работы с двоичными данными файла – поэтому у него нет таких понятий как "версия" или "свойства".

Работа со стандартными файлами осуществляется при помощи менеджера файлов, который может быть получен из интерфейса менеджера объектов xref:api/DocsVision/Platform/ObjectManager/UserSession.FileManager_PR.adoc[UserSession.FileManager]. Менеджер файлов позволяет выполнять простейшие операции с файлами - создавать, удалять, копировать и осуществлять поиск файлов в системе

В примере, создадим *файл* с названием NewFile и загрузим в него файл с ФС NewFile.doc, после чего присвоим переменной newFileId значение идентификатора созданного файла

[source,csharp]
----
//создание нового файла
FileData file = userSession.FileManager.CreateFile("NewFile");

//загрузка файла из ФС
file.Upload("C:\\NewFile.doc");

//получение идентификатора для дальнейшего использования
Guid newFileId = file.Id; 
----

== Внешнее хранение файлов

В системе Docsvision файл имеет две составляющие: информационную и бинарную. В информационной части хранится информация о файле (название, размер и т. п.), в бинарной – бинарное содержимое файла.

Информационная часть файла храниться в БД Docsvision, бинарная может храниться в основной БД или в другом поддерживаемом хранилище.

[NOTE]
====
[.note__title]#Прим.:# Подробная информация о внешнем хранении файлов приведена в пункте xref:ExternalStorages.adoc[Внешние хранилища], Руководстве администратора модуля «Платформа» и документе «Общее описание системы».
====

При работе с данными файла следует учитывать следующую особенность: между информационной и бинарной частью файла устанавливается связь один ко многим – несколько информационных частей могут ссылаться на одни бинарные данные. Например, данная ситуация возникает при копировании файла с помощью метода [.keyword .apiname]#FileData.Copy#. После изменения содержимого файла (с использованием стандартного API) оригинал и копия станут ссылаться на собственный (уникальный) экземпляр бинарных данных.

[[concept_et3_2kz_f4__section_urg_fhq_v4b]]
== Офлайн режим файла

Для файлов поддерживается офлайн режим, при котором файл перемещается в хранилище, поддерживающее режим офлайн.

Файл в режиме офлайн не участвуют в обработке информации (прежде всего - построение полнотекстового каталога), а также недоступны для получения и изменения до возвращения в режим онлайн. Если попытаться читать или записывать данные файла, выгруженного из базы (и если выключена автоматическая загрузка его обратно в базу), то клиенту будет возвращена ошибка. Такая же ошибка будет возвращена, если попытаться выгрузить уже выгруженный файл. Если попытаться загрузить файл, уже находящийся в базе, клиенту также будет возвращена ошибка.

Изменение оперативного статуса файлов выполняется с помощью методов [.keyword .apiname]#FileData.TakeOffline# и [.keyword .apiname]#FileData.BringOnline#.

[NOTE]
====
[.note__title]#Важное замечание:# Для выполнения операций вытеснения/восстановления файлов из внешнего хранилища требуется наличие привилегии оператора архива (членство в группе «Docsvision Archive Operators»).
====

Текущее состояние файла определяется элементом из перечисления xref:api/DocsVision/Platform/ObjectManager/OfflineState_EN.adoc[OfflineState - перечисление].

== Системный объект - версия файла

Версия файла (объект xref:api/DocsVision/Platform/ObjectManager/SystemCards/FileVersion_CL.adoc[FileVersion]) расширяет функциональность стандартного файла и наследует его интерфейс. Свойства и методы версии файла повторяют аналогичные свойства файла и добавляют к ним собственные. Объект версии файла не может быть создан разработчиком напрямую и используется только в системной карточке файла с версиями (xref:api/DocsVision/Platform/ObjectManager/SystemCards/VersionedFileCard_CL.adoc[VersionedFileCard]).

== Системная карточка файла

Системная карточка файла используется для обеспечения удобства работы с файлами и предоставляет дополнительные возможности, такие как:

* поддержка неограниченного количества версий каждого файла;
* возможность задания комментариев к версиям файла;
* обеспечение безопасности при работе с файлом;
* поддержка механизма единоличного владения файлом (CheckIn/CheckOut).

Для работы с системной карточкой файла в менеджере объектов предусмотрен объект xref:api/DocsVision/Platform/ObjectManager/SystemCards/VersionedFileCard_CL.adoc[VersionedFileCard].

Поскольку карточка файла является обычной карточкой Docsvision, то для её создания необходимо прибегнуть к помощи объекта - менеджера карточек (xref:api/DocsVision/Platform/ObjectManager/CardManager_CL.adoc[CardManager]).

Пример создания и первичной инициализации карточки файла:

[source,csharp]
----
//Создание карточки файла с версиями (6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3 - идентификатор такого типа карточек)
VersionedFileCard fileCard = (VersionedFileCard)userSession.CardManager.CreateCard(new Guid("6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3"));

//Первичная инициализация карточки файла
fileCard.Initialize("C:\\NewFile.doc", Guid.Empty, false, false);

//Получение первой версии файла
FileVersion fileVersion = fileCard.CurrentVersion;

//Вывод номера версии
Console.WriteLine(fileVersion.VersionString);
----

Таким образом, для работы с файлами:

* при использовании системы в качестве хранилища файлов произвольного формата для простоты следует использовать системный объект-файл;
* при необходимости ведения сложной иерархии версий файла и реализации механизмов CheckIn/CheckOut следует использовать системную карточку файла.

== См. также

* xref:dm_accesscontrol.adoc[Работа с правами доступа]
