= Общие сведения

Вместе с платформой разработчик получает два уровня API:

* Базовый API - универсальное средство программного доступа ко всем функциям платформы Docsvision. Может быть использован в проектах, основанных на .NET (сборка `DocsVision.Platform.ObjectManager.dll`) и COM (сборка `ObjectManager.dll`) технологиях.
* Высокоуровневый слой, объектная модель Docsvision (далее - "объектная модель") - набор базовых объектов и функциональных возможностей, с помощью которых могут быть реализованы специализированные модели сущностей выбранной предметной области. Использование готовых базовых типов позволяет снизить издержки на разработку собственного решения, обеспечит прозрачность архитектуры, простоту расширения и интеграции нескольких решений, включая "Базовые объекты" (являются частью платформы Docsvision). API данного уровня является удобным средством для работы с карточками. Сборки данного уровня API имеют только .NET-версию.

В зависимости от применимости функциональных возможностей выбранного уровня API, можно выделить четыре группы задач разработчика:

. Задачи, при решении которых могут быть задействован как базовый API, так и объектная модель. Это, например, с некоторыми ограничениями, доступ к данным карточек.
. Задачи, которые эффективнее решать с использованием методов объектной модели. Одной из таких задач является запуск задания на исполнение.
. Задачи, которые могут быть решены только методами базового API, например: поиск данных по секции карточки.
. Задачи, которые не могут быть решены с помощью API Docsvision.

Если при решении определенной задачи потребуется задействовать методы обоих уровней API нужно помнить, что каждый слой обладает собственным механизмом кэширования, что может повлиять на актуальность данных на одном слое по сравнению в другим.

В примерах использования API, рассмотренных в разделе xref:dm_container.adoc[Руководство по разработке], если это возможно, одна задача будет решена как методами базового API, так и методами объектной модели, что позволит оценить удобство и функциональные возможности разных уровней при решении конкретной задачи.

Далее в разделе приведена информация относительно некоторых ключевых объектов и терминов API Docsvision, которые необходимы для понимания последующих примеров разработки.

== В этом подразделе

* xref:dm_session_context.adoc[Пользовательская сессия и контекст объектов]
* xref:dm_managers.adoc[Менеджеры базового API]
* xref:dm_services.adoc[Сервисы объектной модели]
* xref:dm_mappers.adoc[Преобразователи данных]
* xref:dm_objects.adoc[Объекты хранения данных]

== См. также

* xref:dm_connection.adoc[Подключение к серверу Docsvision]

