= Преобразователи данных

В объектной модели Docsvision карточки представляются в виде сущностей конкретной предметной области, к примеру: задания, документы, книги и т.п. Каждый тип таких сущностей обладает, как правило, собственной объектной моделью, которая определенным образом связана с данными карточки. Для того, чтобы определить механизм этого связывания, реализуется специальный класс - _преобразовать данных_,- в котором определяется связь между элементом карточки и свойством объектной модели, представляющим данный элемент.

При получении объекта из _контекста объектов_, данные карточки автоматически загружаются в объектную модель карточки, а при сохранении данных выполняется обратная операция. Для работы данного механизма соответствующий преобразователь данных должен быть загружен в _контекст объектов_.

В базовую поставку Docsvision входят _преобразователи данных_, которые необходимы для работы с объектной моделью карточек библиотеки "Базовые объекты". Для работы с объектной моделью собственных типов карточек, разработчику предлагается реализовать собственный _преобразователь данных_.

== См. далее

* xref:dm_objects.adoc[Объекты хранения данных]

== См. также

* xref:DM_CardsDev_CreateObjectModel_Mapper.adoc[Разработка преобразователя данных]
