= Разработка скриптов карточки

Помимо разработки новых типов карточек, а также модификации компонентов существующих, новая бизнес-логика может быть добавлена в карточку с помощью скрипта карточки. В скриптах используется стандартный API Docsvision (базовый и объектная модель), а средой разработки служит _Конструктор разметок_ и _Конструктор скриптов_, описание работы с которыми приведено в документе *Docsvision. Руководство по настройке*.

В данном разделе приведена информация о специальных возможностях API Docsvision, которые могут быть использованы в скриптах карточки.

== В этом разделе

* xref:dm_scripts_getcontrol.adoc[Доступ к элементам управления карточки]
* xref:dm_cardhost.adoc[Взаимодействие с контейнером карточек]
* xref:dm_scripts_subscription.adoc[Подписка на события]
* xref:dm_scripts_getchildcards.adoc[Доступ к подчиненным карточкам из карточки BackOffice]
* xref:dm_scripts_getribbon.adoc[Доступ к элементам ленты карточки]

== См. также

* xref:dm_wf.adoc[Разработка в среде СУБП]


