= Подписка на события

Элементы управления (реализованные на базе компонентов DevExpress), используемые при создании пользовательского интерфейса карточек библиотеки _{bo}_, разрешают подписываться на события, наследуемые от оригинальных компонентов (описание событий приведено в документации к соответствующим элементам управления DevExpress). Помимо этого, элементы управления {dv} могут предоставлять дополнительные события, описание которых приведено в этом разделе.

[IMPORTANT]
====
Если подписка на событие выполняется из кода скрипта карточки (а не настроена в Конструкторе разметок), то необходимо добавить в скрипт карточки код, отписывающий от события, который должен выполняться при закрытии карточки. В противном случае из-за использования механизма переиспользования компонента карточки обработчик события может вызываться многократно (по числу переиспользований компонента карточки).
====

.В данном разделе
* xref:dm_scripts_subscription_listlinksfiles.adoc[События элемента управления 'Ссылки']
* xref:dm_scripts_subscription_documentFiles.adoc[События элемента управления файлами документа]
