= Поиск объектов с использованием базового API

Возможности поиска объектов методами базового API можно разделить на две принципиально разные группы:

* Серверный поиск - наиболее мощный, выполняющийся на сервере метод. Клиент подготавливает XML-строку, содержащую поисковый запрос в специальном формате, и передает её серверу Docsvision, который должен вернуть результат в виде строк, помещаемых затем в кэш. Поисковый запрос может быть передан в виде готовой XML-строки, либо в виде объекта, сформированного методами [.keyword .apiname]#ObjectManager#.
* Клиентская фильтрация - простая фильтрации строк XML-документа карточки с использованием XPath-выражений, предлагаемая ObjectManager.

Таким образом необходимо самостоятельно решить, какой метод поиска будет более приемлемым (учитывая производительность и простоту реализации) в конкретной ситуации.

== В этом разделе

* xref:dm_search_api_server.adoc[Серверный поиск]
* xref:dm_search_api_filter.adoc[Клиентская фильтрация]
* xref:dm_search_api_save.adoc[Сохранение поискового запроса]

* *xref:../pages/dm_search_api_server.adoc[Серверный поиск]* +
* *xref:../pages/dm_search_api_filter.adoc[Клиентская фильтрация]* +
* *xref:../pages/dm_search_api_save.adoc[Сохранение поискового запроса]* +

*На уровень выше:* xref:../pages/dm_search.adoc[Поиск]
