= Пользовательская сессия и контекст объектов

В API Docsvision существуют две ключевые сущности, представляющие функциональные возможности своего слоя API: _пользовательская сессия_ (или сессия пользователя) и _контекст объектов_.

_Пользовательская сессия_ является главным объектом в базовом API, обеспечивая единую точку доступа к остальным функциям данного API.

С физической точки зрения, сессия - контекст сеанса связи с сервером для конкретного пользователя. Сессия ассоциируется с доменной учетной записью, от имени которой установлено соединение, и в дальнейшем все привилегии на доступ к данным из этой сессии проверяются относительно этой учетной.

В рамках сессии кэшируются все данные, к которым производилось обращение, для ускорения последующего доступа к ним. Размер кэша и продолжительность пребывания в нём данных автоматически регулируются платформой, на основании внутренних алгоритмов. Разработчик может только явно потребовать удаления конкретных объектов из кэша (при помощи методов этих объектов).

Создание сессии является первоочередной задачей при разработке любых внешних (относительно платформы) приложений, работающих с Docsvision. При разработке внутрисистемных объектов, таких как скрипты карточек (в _Конструкторе скриптов_ или _Конструкторе разметок_) или бизнес-процессы, готовая сессия передается при инициализации.

_Контекст объектов_ - элемент объектной модели, который обеспечивает загрузку и сохранение данных карточек, а также предоставляет доступ к функциям, реализующим основную бизнес-логику для работы с бизнес-объектами. Функциональные возможности контекста объектов обеспечивают инициализации объектной модели карточки при загрузке её данных из базы данных, а также последующее связывание данных.

_Контекст объектов_ должен быть проинициализирован для возможности работы с объектной моделью карточки. Исключением являются разработка скриптов карточек и бизнес-процессов - в этих случаях готовый _контекст объектов_ будет доступен из базового класса (для скрипта карточки) и из параметров вызванного метода (для бизнес-процесса).

Для инициализации _контекста объектов_ потребуется _пользовательская сессия_.

== См. далее

* xref:dm_managers.adoc[Менеджеры базового API]
