= Справочник видов карточек

[cols=",",]
|===
|Назначение |Предназначен для управления иерархией видов для существующих типов карточек, добавление и удаление видов, а также настройка определенных параметров видов.
|Класс карточки |xref:..xref:api/DocsVision/BackOffice/ObjectModel/Kinds_CL.adoc[DocsVision.BackOffice.ObjectModel.Kinds]
|===

Для работы с карточкой предназначен сервис xref:..xref:api/DocsVision/BackOffice/ObjectModel/Services/IKindService_IN.adoc[IKindService], с помощью которого можно программно создавать и удалять виды карточек, управлять настройками, кроме того, возможна добавление и удаление расширений.

Доступные операции:

* добавление и удаление вида карточки в справочник;
* добавление типа карточки;
* управление настройками способов создания карточек видов;
* добавление и удаление расширений;
* управление настройками расширений;
* управление настройками бизнес-процессов в карточке.

В приведенном примере создается новый вид для xref:DM_TM_LibBaseObject_Document.adoc[карточки "Документ"]

[source,csharp]
----
//Инициализация контекста объектов

//получение сервиса
IKindService kindService = objectContext.GetService<IKindService>();

// получаем тип карточки "Документ"
KindsCardType kindsCardType = kindService.GetCardType(DocsVision.BackOffice.CardLib.CardDefs.CardDocument.ID);

//создаем новый вид в полученном типе, с названием "Тестовый вид карточки"
KindsCardKind kindsCardKind = kindService.AddCardKind(kindsCardType);
kindsCardKind.Name = "Тестовый вид карточки";

// вид будет использовать свои настройки
kindsCardKind.UseOwnSettings = true;
kindsCardKind.UseOwnExtendedSettings = true;
kindsCardKind.UseOwnLayouts = true;

// добавляем БП в настройки вида
kindService.AddProcessSettings(kindsCardKind, new Guid("12345678-0000-0000-0000-000000000000"), "Отправить на согласование");

//сохранение изменений
objectContext.AcceptChanges();
----

[NOTE]
====
[.note__title]#Прим.:# Карточка "Справочник видов карточек" блокируется для записи, при открытии справочника в Windows-клиенте.
====
