= Список ссылок на карточки заданий

[cols=",",]
|===
|Назначение |Создает список заданий для последующего добавление в другую карточку (например, Документ).
|Класс карточки |xref:../api/DocsVision/BackOffice/ObjectModel/TaskList_CL.adoc[DocsVision.BackOffice.ObjectModel.TaskList]
|===

Для работы с карточкой предназначен сервис xref:../api/DocsVision/BackOffice/ObjectModel/Services/ITaskListService_IN.adoc[ITaskListService], с помощью которого можно создавать и получать карточки списков заданий, которые прикладываются к карточкам документа.

Доступные операции:

* создать карточку списка заданий;
* добавить задание в список;
* удалить задание;
* получить дерево заданий;
* получить описание узла дерева заданий.

В примере создается список заданий, в который добавляется отдельное задание. Список закрепляется за документом.

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов
//Получение документа с ИД 00000000-0000-0000-0000-000000000000 для которого будет добавлено задание 
Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));

//Получение сервисов для работы с сотрудниками, заданиями и списками заданий
IStaffService staffService = objectContext.GetService<IStaffService>();
ITaskService taskService = objectContext.GetService<ITaskService>();
ITaskListService taskListService = objectContext.GetService<ITaskListService>();

//Создание списка заданий и присвоение его документу
TaskList taskList = taskListService.CreateTaskList();
document.MainInfo.Tasks = taskList;

//Получение вида задания. В нашем случае На исполнение
KindsCardKind taskKind = objectContext.GetObject<KindsCardKind>(new Guid("AB801854-70AF-4B6C-AB48-1B59B5D11AA9"));

//Инициализация задания. Автором и исполнителем назначаем текущего пользователя 
Task task = taskService.CreateTask(taskKind);
task.MainInfo.Name = "Задача для Иванова";
task.MainInfo.Author = staffService.GetCurrentEmployee();
taskService.AddSelectedPerformer(task.MainInfo, staffService.GetCurrentEmployee());

//Добавление списка заданий к документу
taskListService.AddTask(taskList, task, document);

//Сохранение контекста
objectContext.AcceptChanges();
----

*На уровень выше:* xref:../pages/dm_baseobjectscards.adoc[Библиотека карточек 'Базовые объекты']
