= Конструктор состояний

[cols=",",]
|===
|Назначение |Позволяет описать жизненный цикл карточки.
|Класс карточки |xref:..xref:api/DocsVision/BackOffice/ObjectModel/StatesDictionary_CL.adoc[DocsVision.BackOffice.ObjectModel.StatesDictionary]
|===

Для работы с карточкой предназначен сервис xref:..xref:api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[IStateService], с помощью которого можно работать с автоматом состояний. Он предоставляет возможность управления операциями, состояниями, ветвями перехода между состояниями и диаграммой состояний. Помимо этого, с помощью данного сервиса можно узнать, какие операции доступны для заданной карточки и в какое состояние ее можно перевести.

Доступные операции:

* создание ветки перехода из одного состояния в другое;
* создание операции для смены состояния;
* создание состояния;
* получение состояний доступности операций;
* создание разметки диаграммы состояний;
* поиск ветки перехода;
* поиск операций;
* поиск состояний;
* получение объекта настройки прав для вида карточки;
* получение списка операций для вида карточки;
* получение списка ветвей перехода;
* получение разметки диаграммы состояний;
* получение списка состояний;
* удаление объекта настройки прав для вида карточки;
* локализация названия операции;
* локализация названия состояния;
* определение возможности удаления операции.

В примере выведем в консоль названия всех состояний для вида документа Внутренний

[source,csharp]
----
//Инициализация контекста объектов

//Получение сервиса для работы со справочником состояний
IStateService stateService = objectContext.GetService<IStateService>();

//Получение вида документа Внутренний
KindsCardKind kind = objectContext.GetObject<KindsCardKind>(new Guid("7db9044e-91b7-447d-8caa-5e5a4967b8d4"));

//Получение допустимых состояний для данного вида и вывод на консоль
IList<StatesState> states = stateService.GetStates(kind);
foreach (var item in states)
{
 Console.WriteLine(item.DefaultName);
}
----

См. также пример из раздела xref:DM_TM_LibBaseObject_Task.adoc[Задание]
