= Конструктор справочников

[cols=",",]
|===
|Назначение |Карточка предназначена для организации древовидной структуры простых текстовых данных.
|Класс карточки |xref:api/DocsVision/BackOffice/ObjectModel/BaseUniversal_CL.adoc[DocsVision.BackOffice.ObjectModel.BaseUniversal]
|===

Для работы с карточкой предназначен сервис xref:api/DocsVision/BackOffice/ObjectModel/Services/IBaseUniversalService_IN.adoc[IBaseUniversalService], с помощью которого можно управлять узлами и строками справочника.

Доступные операции:

* создание узлов и строк;
* копирование, перемещение и удаление узлов и строк справочника;
* поиск узлов и строк
* создание и получение отображаемых полей.

Ниже приведен пример создания справочника техники некого магазина. Создается новый узел "Мониторы", в который помещаются узлы с марками и строки с моделями.

[source,csharp]
----
//Инициализация контекста объектов

//получение сервиса
IBaseUniversalService baseUniversalService = objectContext.GetService<IBaseUniversalService>();

//получение объектной модели Конструктора справочников 
BaseUniversal baseUniversal = objectContext.GetObject<BaseUniversal>(DocsVision.BackOffice.CardLib.CardDefs.RefBaseUniversal.ID);

//создания одного из узлов первого уровня. null -- позволяет создать элемент без родителей, т.е. корневой.
BaseUniversalItemType techType = baseUniversalService.AddNewItemType(null);
techType.Name = "Мониторы";
techType.Description = "Мониторы всех фирм";

//создание узла с названиями производителей        
BaseUniversalItemType techMark = baseUniversalService.AddNewItemType(techType);
techMark.Name = "LG";
techMark.Description = "Производитель LG";

//создание строк с моделями мониторов
BaseUniversalItem item = baseUniversalService.AddNewItem(techMark);
item.Name = "34UM95";
item.Description = "Модель 34UM95. Разрешение экрана 3440x1440. Матрица IPS.";

item = baseUniversalService.AddNewItem(techMark);
item.Name = "29UM65";
item.Description = "Модель 29UM65. Разрешение экрана 2560x1080. Матрица IPS.";

//сохранение изменений            
objectContext.AcceptChanges();
----

Пример можно использовать как часть проекта синхронизации внутреннего справочника фирмы и поставщика техники. Справочник можно подключить к карточке, которая будет играть роль бланка для выписывания техники со склада.
