= Часто задаваемые вопросы

*Каким образом получить родительский объект имея подчиненный?*

Для этого предназначен метод xref:api/DocsVision/Platform/ObjectModel/ObjectHelper.GetParent_MT.adoc[ObjectHelper.GetParent], который, к примеру, можно использовать для получения документа, которому принадлежит файл:

[source,csharp]
----
// documentFile -- файл (тип DocumentFile) искомого документа
Document document = ObjectHelper.GetParent<Document>(documentFile);
----

*Как изменить значение в элементе управления в карточке*

Для доступа к элементу управления из скрипта карточки, достаточно обратиться к методу FindPropertyItem базового класса карточки xref:api/DocsVision/BackOffice/WinForms/BaseCardControl_CL.adoc[BaseCardControl], передав название элемента управления:

[source,csharp]
----
ICustomizableControl control = CardControl;

// Получение элемента управления
ILayoutPropertyItem layoutItem = control.FindPropertyItem<ILayoutPropertyItem>("Theme");

// Установка нового значения
layoutItem.ControlValue = "Новое значение"; 

// Сохранение
layoutItem.Commit();
----

Название элемента можно посмотреть в _Конструкторе разметок_.

*Пример работы с {dv} из Powershell*

В приведенном ниже примере, создается скрипт, выполняющий подключение к серверу {dv}, и получение номера из карточки Нумератора

[source,pre,codeblock]
----
# Требуется указать действительный путь к используемым библиотекам Docsvision
Add-Type -Path с:\DocsVision.Platform.dll
Add-Type -Path с:\DocsVision.Platform.ObjectManager.dll

# Требуется указать действительный адрес подключения к Docsvision
$connectionString = "ConnectAddress=http://docsvision.domain.com/DocsVision/StorageServer/StorageServerService.asmx"
$sessionManager = [DocsVision.Platform.ObjectManager.SessionManager]::CreateInstance($connectionString)
$userSession = $sessionManager.CreateSession()

# Требуется передать действительный адрес Нумератора
[GUID]$numeratorCardID = "00000000-0000-0000-0000-000000000000"
[DocsVision.Platform.ObjectManager.SystemCards.NumeratorCard]$numeratorCard = $userSession.CardManager.GetCard($numeratorCardID)
[GUID]$outId = [GUID]::Empty

# Получение номера из первой зоны нумерации
$number = $numeratorCard.Zones[0].GetNumber([GUID]::Empty, 1, [ref] $outId);

# Вывод полученного номера
write $number
----

Аналогичная задача может быть решена без объектной модели -- прямым обращением к сервису Docsvision

[source,pre,codeblock]
----
# Адрес сервиса Docsvision
$serverUri = "http://docsvision.domain.com/DocsVision/StorageServer/StorageServerService.asmx"

# Идентификатор карточки нумератора и название зоны, в которых будет резервироваться номер
[GUID]$numeratorCardID = "00000000-0000-0000-0000-000000000000"
$zoneName = "Zone"

$result = 0
[GUID]$numberId = [GUID]::Empty
[GUID]$userID = [GUID]::Empty

$client = New-WebServiceProxy -Uri $serverUri"?WSDL" -UseDefaultCredential

# Открытие сессии
[GUID]$sessionId = $client.SessionLogin("","", [ref]$result)

# Получение номера
$number = $client.NumGetFirstFree($sessionId, $numeratorCardID, $zoneName, $userID, [ref]$numberId) 
----

[NOTE]
====
Полное описание методов сервиса приведено в разделе xref:development-manual/dm_appendix_webservice.adoc[Методы веб-сервиса Docsvision].
====

*Как узнать идентификатор карточки*

Узнать идентификатор существующий карточки можно несколькими способами:

* посмотреть в Windows-клиенте -- идентификатор карточки отображается в её свойствах;
* используя утилиту {dv} Explorer (входит в Resource Kit) -- идентификатор карточки отображается в поле *Selected card ID*.

*Получить идентификатор созданной карточки, используя объектную модель*

Для получения идентификатора объекта (например, объект document типа DocsVision.BackOffice.ObjectModel.Document) можно воспользоваться методом ObjectContext.GetObjectRef(ObjectBase)#:

[source,csharp]
----
Guid id_document = objectContext.GetObjectRef(document).Id;
или так (начиная с НО9):
Guid id_document = document.GetObjectId();
----

[NOTE]
====
Корректный идентификатор нового объекта может быть получен только после сохранения объекта в _контексте объектов_.
====

*Получить отображаемое имя текущего сотрудника*

[source,csharp]
----
StaffEmployee currentEmployee = objectContext.GetService<IStaffService>().GetCurrentEmployee();
string displayName = currentEmployee.DisplayName;
----

*Получить карточку сотрудника по его идентификатору (id_empl)*

[source,csharp]
----
StaffEmployee staffEmployee = staffService.Get(new Guid("id_empl"));
----

*Считывание данных с элемента управления типа коллекция, например "Сотрудники"*

Для сотрудников, в `ControlValue` соответствующего элемента управления содержится коллекция идентификатором выбранных сотрудников -- IEnumerable<Guid>. Для записи, в `ControlValue` передается массив таких идентификаторов (Guid[]).

*Доступ к значению поля*

[source,csharp]
----
int? result = userSession.CardManager.GetCardData(cardID).Sections[sectionID].FirstRow.GetInt32(fieldAlias);
----

cardID -- идентификатор карточки; sectionID -- идентификатор секции; fieldAlias -- псевдоним поля

С точки зрения доступа, динамические поля не отличаются от статических, поэтому получение значения такого поля может выглядеть следующим образом

[source,csharp]
----
//идентификатор карточки
Guid cardID = new Guid("00000000-0000-0000-0000-000000000000");

//название динамической секции
string sectionAlias = "DynSection";

//название динамического поля
string fieldAlias = "DynField";

//получение типа карточки
CardType type = userSession.CardManager.GetCardData(cardID).Type;

//получение идентификатора
Guid sectionID = type.Sections[sectionAlias].Id;

//получение значения поля через старую объектную модель   
int? result = userSession.CardManager.GetCardData(cardID).Sections[sectionID].FirstRow.GetInt32(fieldAlias);
   
//или даже так, если через новую объектную модель
Document document = objectContext.GetObject<Document>(cardID);
result = (((BaseCardSectionRow)document.GetSection(sectionID)[0])[fieldAlias] as int?);
----

*Как узнать идентификатор определенного вида карточки*

Воспользуйтесь утилитой {dv} Explorer (входит в Resource Kit).

. Нажать *Card types*. В открывшемся окне определить идентификатор типа карточки (идентификатор в Selected type ID), также идентификатор можно найти в разделе xref:DM_StandartCards.adoc[Описание полей стандартной карточки] (идентификатор указан вначале описания конкретной карточки).
. Нажать *Cards*. В списке типов карточек выбрать "Справочник видов карточек", после чего нажать *Search*.
. Выбрать найденный справочник (будет в единственном экземпляре). В справочнике нужно найти строку с найденным ранее идентификатором типа карточки (по содержимому поля CardTypeId)
. Нажать *Enter section*.
. Найти в дереве видов карточек нужный вид по названию. В значении поля RowID будет искомый идентификатор вида карточки.

*Получение сертификата сотрудника*

Сертификаты используются при подписании/шифровании/расшифровке данных карточек, а также при верификации установленных подписей. Сертификат сотрудника может быть получен несколькими способами:

. Вне контекста Windows-клиента:
+
[source,csharp]
----
IUserProfileCardService iUserProfileCardService = objectContext.GetService<IUserProfileCardService>();
X509Certificate2 certificate = iUserProfileCardService.GetCertificate(@"DOMAIN\IvanovII");
----
+
Для получения сертификата сотрудника с использованием метода GetCertificate, он (сертификат) должен быть указана в соответствующем поле (см. Руководство по настройке), в Справочнике сотрудников.
+
[[concept_rcq_qll_w4__Method_GetCertificate]]
Другой вариант -- получения сертификата из хранилища сертификатов ОС Windows. В примере получаем первый сертификат с закрытым ключом.

[source,csharp]
----
X509Certificate2 GetCertificate()
{
 X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
 store.Open(OpenFlags.OpenExistingOnly);
 foreach (var item in store.Certificates)
 {
  if (item.HasPrivateKey) return item;
 }
 return null;
}
----
. В контексте Windows-клиента (например, в скрипте карточки)
+
[source,csharp]
----
bool cancel = false;
X509Certificate2 certificate = DocsVision.BackOffice.WinForms.Controls.SelectCertificateForm.SelectCertificate(ref cancel, objectContext);
if(cancel) return;
----
+
В данном случае, сотруднику будет выведено окно выбора сертификата.
