= Получение данных представления

Другой важной задачей при работе с представлениями является получение конкретной выборки данных на основании предварительно подготовленного (программно или через пользовательский интерфейс) описания представления. Для того, чтобы получить данные представления, необходимо воспользоваться методом xref:api/DocsVision/Platform/ObjectManager/CardManager.GetViewData_1_MT.adoc[CardManager.GetViewData].

Пример получения данных системного представления Дайджест, примененного к конкретной папке:

[source,csharp]
----
const string FOLDER_ID = "5929489F-3CC0-4B48-A032-9CCE7F9674CF";
InfoRowCollection viewdata = session.CardManager.GetViewData(ViewSource.FromFolder(new Guid(FOLDER_ID)));
----

Другой пример: получение данных представления по XML-описанию на основании результатов сформированного поискового запроса:

[source,csharp]
----
//Формирование поискового запроса
SearchQuery query = session.CreateSearchQuery();
//...

//Получение данных представления
ViewSource source = ViewSource.FromSearch(query.GetXml(true, null));
InfoRowCollection viewData = session.CardManager.GetViewData(source, view.GetXml());
----

Метод возвращает InfoRowCollection - набор строк, соответствующий результатам запроса. Возможность его сортировки в объектной модели не предусмотрена, то есть сортировать его можно только внешними средствами.

== См. также

* xref:dm_cardhost.adoc[Взаимодействие с контейнером карточек]
