= Разработка в среде СУБП

Данный раздел содержит информацию, предназначенную для разработчиков, создающих решение на платформе Docsvision с использованием приложения [.dfn .term]_Управление процессами_. В разделе раскрываются вопросы связанные с созданием дополнительных [.keyword]*функций* СУБП, [.keyword]*сценариев*, [.keyword]*шлюзов* и других объектов системы, расширяющих её функциональные возможности по реализации специфических бизнес-процессов.

В данном разделе освещаются следующие темы:

* правила разработки пользовательских [.dfn .term]_функций_ и [.dfn .term]_шлюзов_;
* правила разработки, отладки и использования [.dfn .term]_сценариев_;

== В этом подразделе

* xref:WorkflowDevManualBegin.adoc[Общие сведения]
* xref:WorkflowDevManualComponents.adoc[Программные компоненты СУБП]

== См. также

* xref:SM_Workflow_Cat.adoc[Примеры использования API Workflow]

* *xref:../pages/WorkflowDevManualBegin.adoc[Общие сведения]* +
* *xref:../pages/WorkflowDevManualComponents.adoc[Программные компоненты СУБП]* +
* *xref:../pages/WorkflowDevManualAppendix.adoc[Список COM интерфейсов]* +
* *xref:../pages/WorkflowSubscription.adoc[Подписка на события шлюза]* +

*На уровень выше:* xref:../pages/dm_container.adoc[Руководство по разработке]
