= Работа с файлами

Платформа {dv} позволяет загружать в базу данных и извлекать из базы данных пользовательские файлы произвольного формата. Для работы с файлами в системе существует специальная системная карточка -- _карточка файла_, а также набор интерфейсов менеджера объектов для манипуляций с файлами.

.Для работы с файлами можно использовать несколько видов объектов:
* Системный объект -- *файл* -- реализует простейшую функциональность для хранения файлов в базе данных {dv}.
* Системный объект -- *версия файла* -- реализует дополнительные атрибуты для нумерованной версии файла.
* Системная *карточка файла* -- поддерживают функциональность по хранению нескольких версий файла, комментариев к ним и дополнительных механизмов работы с файлом.
* Карточка файла из решения _Делопроизводство_ (не рассматривается).
* Карточка -- список файлов из решения _Делопроизводство_ (не рассматривается).

== Системный объект -- файл

Для работы с простыми файлами в системе предусмотрен объект xref:api/DocsVision/Platform/ObjectManager/FileData_CL.adoc[`FileData`]. Это самый низкоуровневый объект для работы с двоичными данными файла -- поэтому у него нет таких понятий как "версия" или "свойства".

Работа со стандартными файлами осуществляется при помощи менеджера файлов, который может быть получен из интерфейса менеджера объектов xref:api/DocsVision/Platform/ObjectManager/UserSession.FileManager_PR.adoc[`UserSession.FileManager`]. Менеджер файлов позволяет выполнять простейшие операции с файлами -- создавать, удалять, копировать и осуществлять поиск файлов в системе

В примере, создадим *файл* с названием `NewFile` и загрузим в него файл из файловой системы `NewFile.doc`, после чего присвоим переменной `newFileId` значение идентификатора созданного файла

[source,csharp]
----
FileData file = userSession.FileManager.CreateFile("NewFile"); <.>

file.Upload("C:\\NewFile.doc"); <.>

Guid newFileId = file.Id; <.>
----
<.> Создание нового файла.
<.> Загрузка файла из файловой системы.
<.> Получение идентификатора для дальнейшего использования.

== Внешнее хранение файлов

В системе {dv} файл имеет две составляющие: информационную и бинарную. В информационной части хранится информация о файле (название, размер и т. п.), в бинарной -- бинарное содержимое файла.

Информационная часть файла храниться в БД {dv}, бинарная может храниться в основной БД или в другом поддерживаемом хранилище.

[NOTE]
====
Подробная информация о внешнем хранении файлов приведена в пункте xref:ExternalStorages.adoc["Внешние хранилища"], Руководстве администратора модуля {pl} и документе "Общее описание системы".
====

При работе с данными файла следует учитывать следующую особенность: между информационной и бинарной частью файла устанавливается связь один ко многим -- несколько информационных частей могут ссылаться на одни бинарные данные. Например, данная ситуация возникает при копировании файла с помощью метода `FileData.Copy`. После изменения содержимого файла (с использованием стандартного API) оригинал и копия станут ссылаться на собственный (уникальный) экземпляр бинарных данных.

== Офлайн режим файла

Для файлов поддерживается офлайн режим, при котором файл перемещается в хранилище, поддерживающее режим офлайн.

Файл в режиме офлайн не участвуют в обработке информации (прежде всего -- построение полнотекстового каталога), а также недоступны для получения и изменения до возвращения в режим онлайн. Если попытаться читать или записывать данные файла, выгруженного из базы (и если выключена автоматическая загрузка его обратно в базу), то клиенту будет возвращена ошибка. Такая же ошибка будет возвращена, если попытаться выгрузить уже выгруженный файл. Если попытаться загрузить файл, уже находящийся в базе, клиенту также будет возвращена ошибка.

Изменение оперативного статуса файлов выполняется с помощью методов `FileData.TakeOffline` и `FileData.BringOnline`.

[IMPORTANT]
====
Для выполнения операций вытеснения/восстановления файлов из внешнего хранилища требуется наличие привилегии оператора архива (членство в группе _Docsvision Archive Operators_).
====

Текущее состояние файла определяется элементом из перечисления xref:api/DocsVision/Platform/ObjectManager/OfflineState_EN.adoc[`OfflineState` -- перечисление].

== Системный объект -- версия файла

Версия файла (объект xref:api/DocsVision/Platform/ObjectManager/SystemCards/FileVersion_CL.adoc[`FileVersion`]) расширяет функциональность стандартного файла и наследует его интерфейс. Свойства и методы версии файла повторяют аналогичные свойства файла и добавляют к ним собственные.

Объект версии файла не может быть создан разработчиком напрямую и используется только в системной карточке файла с версиями xref:api/DocsVision/Platform/ObjectManager/SystemCards/VersionedFileCard_CL.adoc[`VersionedFileCard`].

== Системная карточка файла

Системная карточка файла используется для обеспечения удобства работы с файлами и предоставляет дополнительные возможности, такие как:

* Поддержка неограниченного количества версий каждого файла.
* Возможность задания комментариев к версиям файла.
* Обеспечение безопасности при работе с файлом.
* Поддержка механизма единоличного владения файлом (`CheckIn`/`CheckOut`).

Для работы с системной карточкой файла в менеджере объектов предусмотрен объект xref:api/DocsVision/Platform/ObjectManager/SystemCards/VersionedFileCard_CL.adoc[`VersionedFileCard`].

Поскольку карточка файла является обычной карточкой {dv}, то для её создания необходимо прибегнуть к помощи объекта -- менеджера карточек (xref:api/DocsVision/Platform/ObjectManager/CardManager_CL.adoc[`CardManager`]).

.Пример создания и первичной инициализации карточки файла:
[source,csharp]
----
VersionedFileCard fileCard = (VersionedFileCard)userSession.CardManager.CreateCard(new Guid("6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3")); <.>

fileCard.Initialize("C:\\NewFile.doc", Guid.Empty, false, false); <.>

FileVersion fileVersion = fileCard.CurrentVersion; <.>

Console.WriteLine(fileVersion.VersionString); <.>
----
<.> Создание карточки файла с версиями, `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3` -- идентификатор такого типа карточек.
<.> Первичная инициализация карточки файла.
<.> Получение первой версии файла.
<.> Вывод номера версии.

.Таким образом, для работы с файлами:
* При использовании системы в качестве хранилища файлов произвольного формата для простоты следует использовать системный объект-файл.
* При необходимости ведения сложной иерархии версий файла и реализации механизмов `CheckIn`/`CheckOut` следует использовать системную карточку файла.
