= Основные сведения

Пример, приведенный в данном разделе, содержит полный сценарий создания собственного *решения* (на платформе Docsvision) для учета сетевого оборудования организации и сбора статистики его отказов, а также исходные коды всего проекта.

В процессе его создания будут рассмотрены вопросы, связанные с разработкой библиотеки карточек, пакетов установки, а также необходимых модулей Docsvision. Вопросы, связанные с локализацией решений, а также созданием пакетов установки для различных платформ, здесь не рассматриваются.

Для данного решения будут созданы:

* библиотека карточек и ее компонент;
* карточка *учета сетевого оборудования* и ее компонент.
* модуль расширения _Консоли настройки_ (далее – *SnapIn*);
* два пакета установки: клиентская и серверная части.

Помимо этого разработаем объектную модель карточки; также введем дополнительное требование на совместимость карточки с конструкторами Docsvision, чтобы иметь возможность настраивать разметку карточки при помощи _конструктора разметок_.

Для того, чтобы решение было законченным, также потребуются:

* бизнес-процесс _Проверка доступности сетевых узлов_ (непосредственная реализация логики проверки не предусмотрена), который должен фиксировать факт изменения доступности сетевого устройства;
* выгруженные настройки _справочника видов карточек_, _конструктора разметок_, _конструктора состояний_ и др.;
* в качестве примера, экземпляр карточки _учета сетевого оборудования_, который предполагается загружаться в Docsvision при установке решения. В собственном решении подобным образом может быть загружен шаблон карточки.

Данное руководство сопровождается исходными кодами всего _решения_, в том числе пакетов установки, а также схемами библиотеки карточек и карточки.

Архив решения имеет следующую структуру:

* bin – каталог с основными сборками Docsvision, использованными в проекте компонента карточки.
+
[NOTE]
====
[.note__title]#Прим.:# Все сборки Docsvision, использованные в проектах решения, устанавливаются вместе с Docsvision Windows-клиент и платформой Docsvision.
====
* Binaries – каталог для размещения готовых сборок.
* CardDefs – каталог со схемами карточки _учета сетевого оборудования_ и библиотеки _Модуля учета сетевых устройств_, а также их ресурсами.
* CardLib – каталог с проектом (C++) компонента библиотеки карточек.
* CardPackage – каталог с данными справочников и конструкторов, выгруженных из базы данных Docsvision. Используются на этапе xref:CreatePackages.adoc[Формирование CardPackage и SqlPackage].
* Database – каталог с файлом, определяющим путь к файлу с метаданными библиотеки карточек. Используются на этапе xref:CreatePackages.adoc[Формирование CardPackage и SqlPackage].
* Installers – каталог сборки пакетов установки.
* NetstatSolution.Snapin – каталог с проектом модуля расширения _Консоли настройки_ Docsvision.
* NetstatSolutionCard – каталог с проектом компонента карточки, а также его объектной моделью.
* NetstatSolutionClientInstaller – каталог с проектом пакета установки клиентской части _решения_.
* NetstatSolutionInstaller – каталог с проектом пакета установки серверной части _решения_.
* Other – в данном каталоге содержится утилита *CardTypeExtractor*, которая будет использована на этапе xref:CreatePackages.adoc[Формирование CardPackage и SqlPackage].

[NOTE]
====
[.note__title]#Прим.:# Идентификаторы некоторых сущностей (к примеру, идентификатор библиотеки карточек) используются в нескольких компонентах, что будет обозначено дополнительно в тексте. Таким идентификаторам будет присвоено уникальное названием, выделенное в тексте жирным и курсивным начертанием.
====

== См. далее

* xref:CreateCardLib.adoc[Разработка библиотеки карточек]
