= Начало работы

Базовая поставка платформы Docsvision содержит полный набор средств для разработки собственных решений, удовлетворяющих потребности организации в сфере электронного документооборота и его автоматизации. К таким средствам можно отнести:

* набор конструкторов - мощное и простое средство настройки существующего программного продукта;
* возможность разработки новых шлюзов, функций и сценариев для использования их в бизнес-процессах;
* возможность создавать новые типы объектов платформы (карточек) для полноценного представления объектов целевой сферы деятельности;
* публичный API для разработки отдельных утилит, сценариев бизнес-процессов;

Основное назначение данного документа - предоставить разработчику информацию о возможностях API Docsvision через практические примеры. Помимо этого, документ содержит другие сведения, напрямую связанные с созданием решений:

* Создание собственных карточек и решений.
+
Собственные типы карточки разрабатываются, например, если невозможно (сложно) реализовать необходимую бизнес-логику, либо иную функциональность (в т.ч. пользовательский интерфейс) при помощи конструкторов Docsvision.
* Разработка сценариев в карточках.
+
Сценарии (скрипты) в карточках библиотеки "Базовые объекты" позволяют расширить их функциональность штатным образом без разработки нового решения.
* Разработка сценариев в бизнес-процессах.
+
Сценарии (скрипты) в бизнес-процессах являются одним из способов реализации специфических действий, не предусмотренных стандартными функциями бизнес-процессов.
* Разработка прикладных приложений (утилит).
+
Разработка внешних по отношению к Docsvision приложений, выполняющих какие-либо действия в системе, может быть востребована при интеграции Docsvision с другими системами (синхронизация справочных данных). Примерами таких утилит могут выступать приложения для импорта данных в справочники сотрудников и контрагентов, входящие в пакет разработчика.

Далее приведена справочная информация об общем устройстве платформы и приложения "Управление процессами", а также список ограничений на модификацию платформы, которые должны учитываться при разработке решений.
