= Синхронизация Справочника сотрудников с Active Directory

Для синхронизации _Справочника сотрудников_ с Active Directory достаточно вызвать специальный метод сервиса для работы со xref:cards/bo-lib/staff.adoc[Справочником сотрудников]

[source,csharp]
----
//Инициализация контекста объектов и получение сервиса
IStaffService staffService = objectContext.GetService<IStaffService>();

// Инициализация параметров синхронизации
SynchronizationDepartmentsSettings syncSettings = new SynchronizationDepartmentsSettings();

// Инициализация менеджера длительных процессов
LongProcessManager longProcessManager = new LongProcessManager();

//Выполнение синхронизации
staffService.SynchronizeWithActiveDirectory(syncSettings, longProcessManager);
----

В приведенном примере класс SynchronizationDepartmentsSettings должен реализовывать интерфейс xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/ActiveDirectory/ADSync/IADSynchronizationSettings_IN.adoc[IADSynchronizationSettings], например, следующим образом:

[source,csharp]
----
class SynchronizationDepartmentsSettings : IADSynchronizationSettings
{
 public bool CreateFolders { get { return false; } }
 public bool DeleteItems { get { return false; } }
 public bool LoadCertificates { get { return false; } }
 public bool LoadDisabled { get { return false; } }
 public bool NotCheckDomain { get { return false; } }

 public ADSynchronizationMode SynchronizationMode
 {
  get { return ADSynchronizationMode.FromADToDictionary; } // Направление синхронизации в сторону Справочника сотрудников
 }
 public bool SynchronizeChildren { get { return false; } }

 public bool SynchronizeDepartments
 {
  get { return true; } // Разрешить синхронизацию подразделений
 }
 public bool SynchronizeGroups { get { return false; } }
 public bool SynchronizeNewMoved { get { return false; } }
 public bool SynchronizeRoles { get { return false; } }
}
----

Здесь класс SynchronizationDepartmentsSettings устанавливает требование по синхронизации подразделений в _Справочнике сотрудников_ информацией, полученной из Active Directory.

[NOTE]
====
Полное описание свойств класса SynchronizationDepartmentsSettings смотрите в описании интерфейса IADSynchronizationSettings.
====

Менеджер длительных процессов `longProcessManager` должен реализовывать интерфейс xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/ILongProcessManager_IN.adoc[ILongProcessManager], и для простоты определим его следующим образом:

[source,csharp]
----
class LongProcessManager : ILongProcessManager
{
 public void Cancel() { }
 public bool CancellationPending { get {return false;} }
 public bool PausePending { get { return false; } }
 public void LogMessage(string message) { }
}
----

Чтобы синхронизация могла быть выполнена необходимо связать элемент _Справочника сотрудников_ и объект Active Directory. Подробнее об этом читайте в соответствующем разделе документа "Docsvision 5. Руководство по настройке".
