= Получение заместителя сотрудника

Приведенный далее скрипт используется для получения первого активного постоянного заместителя с правом исполнения.

_Сценарий_ работает со следующими _переменными процесса_:

* `UserDV` - сотрудник, для которого определяется заместитель.
* `Deputy` - переменная будет использована для сохранения заместителя.

[source,csharp]
----
// подключение системных библиотек
using System;
using System.Xml;

// подключение библиотек СУБП
using DocsVision.Workflow.Objects;
using DocsVision.Workflow.Runtime;
using DocsVision.Workflow.Gates;
using DocsVision.Platform.HelperAPI;

namespace DVScriptHost
{
 class DVScript
 {
  public void Execute(DocsVision.Workflow.Runtime.ProcessInfo process, PassState passInfo)
  {
   try
   {

    // Получение переменных процесса
    ProcessVariable oUserDV = process.GetVariableByName("UserDV");
    ProcessVariable oDeputy = process.GetVariableByName("Deputy");

    // Приведение к типу Сотрудник DV
    DVPrincipal dvUser = oUserDV.Value as DVPrincipal;
   
    // Получение первого (по списку) активного постоянного заместителя с правом исполнения    
    DVPrincipal dvDeputy = dvUser.ActiveDeputy;
   
    // Сохранение найденного значения в переменную
    oDeputy.Value = dvDeputy;
   } catch (Exception ex)
   {

    // Добавление сообщения об ошибке в журнал процесса
    process.LogMessage("Ошибка выполнения скрипта:" + ex.Message);
   }
  }
 }
}
----

Свойство `ActiveDeputy` сущности типа [.keyword .apiname]#DVPrincipal# возвращает первого активного постоянного заместителя с правом исполнения, которого также можно получить вызвав метод GetActiveDeputy(true, false,false,true) объекта типа [.keyword .apiname]#DVPrincipal#. Установив значение соответствующего параметра метода [.keyword .apiname]#GetActiveDeputy(bool Performing, bool Control, bool Signature, bool PermanentDeputy)# в true можно получить заместителя, обладающего необходимым набором прав:

* Performing - с правом исполнения
* Control - с правом ответственного исполнения
* Signature - с правом подписи
* PermanentDeputy - постоянный заместитель

Если все параметры в значении false, будет возвращен первый активный заместитель с любыми правами.
