= Сценарии

_Сценарии_ представляют собой мощный механизм расширения функциональности _СУБП_, используемый в тех случаях, когда требуемые действия слишком сложно (или невозможно) выполнить при помощи стандартных _функций_.

Типовые применения _сценариев_ следующие:

* преобразование типов и форматов данных;
* динамическое изменение данных процесса во время его работы (добавление и удаление переменных процесса, изменение значений переменных);
* сложные операции обработки данных, которые невозможно осуществить стандартными средствами (например, работа со справочниками и специфическими карточками Docsvision);
* взаимодействие с внешними системами (не предусмотренное _функциями_ или _шлюзами_ этих систем).

Функция сценария (Script) позволяет выполнить в рамках процесса произвольный код на языке платформы .NET (C# или VB.NET).

== В этом подразделе

* xref:WorkflowDevManualComponents31.adoc[Разработка сценариев]
* xref:WorkflowDevManualComponents32.adoc[Взаимодействие с объектной моделью Workflow]
* xref:WorkflowDevManualComponents33.adoc[Отладка сценариев]
* xref:WorkflowDevManualComponents34.adoc[Сохранение сценария в виде сборки]
