= Общие сведения

Платформа Docsvision и приложение [.dfn .term]_Управление процессами_ представляют собой систему описания сложных процессов обработки информации в организации и полнофункциональный Workflow-сервер. [.dfn .term]_СУБП_ представляет собой решение на основе платформы Docsvision, предназначенное для создания бизнес-процессов любой сложности и управления ими.

Ключевыми объектами в терминологии [.dfn .term]_СУБП_ являются [.keyword]*бизнес-процесс*, [.keyword]*переменные процесса*, [.dfn .term]_функции_ и [.dfn .term]_шлюзы_.

== Бизнес-процесс

[.dfn .term]_Бизнес-процесс_ представляет собой формальное описание бизнес-процесса организации, которое строится из набора атомарных операций ([.dfn .term]_функций_), составляющих процесс, и связей между ними, определяющих порядок выполнения операций. [.dfn .term]_Функции_ [.dfn .term]_бизнес-процесса_ оперируют данными внешних систем с помощью [.dfn .term]_шлюзов_ и обмениваются данными через [.dfn .term]_переменные процесса_.

[.dfn .term]_Бизнес-процесс_ должен обязательно включать в себя специальную [.dfn .term]_функцию_, инициирующую выполнение процесса, а также одну или несколько [.dfn .term]_функций_, завершающих выполнение процесса. Остальные [.dfn .term]_функции_ могут быть связаны между собой произвольным количеством связей, которые определяют порядок их выполнения в [.dfn .term]_бизнес-процесса_. Возможно наличие в процессе циклов, условных и безусловных переходов.

Физически [.dfn .term]_бизнес-процесс_ состоит из набора данных, хранящихся в базе данных Docsvision, набора свойств и методов для операций с этими данными, а также карточки Docsvision типа [.dfn .term]_Бизнес-процесс_, реализующей пользовательский интерфейс для управления данными процесса.

== Переменные процесса

[.dfn .term]_Переменные процесса_ являются сущностями, которыми оперируют [.dfn .term]_функции_ процесса, обеспечивая единый способ обмена информацией между [.dfn .term]_функциями_ процесса.

Каждая переменная имеет уникальный идентификатор (в формате строки), который позволяет отличить её от остальных переменных [.dfn .term]_бизнес-процесса_: имя, значение (величину или набор данных, которые характеризуют переменную) и отображаемое значение, которое может как соответствовать значению, так и характеризовать переменную для пользователя более явным образом. Например, для переменной, представляющей карточку Docsvision, значением является идентификатор карточки, а отображаемым значением – её название.

[NOTE]
====
[.note__title]#Важное замечание:# Имена переменных в бизнес-процессе являются регистро-зависимыми.
====

Все [.dfn .term]_переменные процесса_ являются строго типизированными. К стандартным (системным) типам переменных относятся следующие типы:

* Строка;
* Целое;
* Дробное;
* Логическое значение (Да/Нет);
* Дата/Время;
* Перечисление – при формировании шаблона процесса можно описать поля типа перечисления и задать все возможные значения. Все значения перечисления в процессе – строковые.

Кроме этих стандартных типов, в процесс могут быть добавлены переменные шлюзов. Каждый зарегистрированный в системе шлюз поставляет собственные типы переменных.

Автоматического преобразования типов не предусмотрено. Для преобразования экземпляра переменной из одного типа в другой (если это предусмотрено) необходимо использовать специальные функции, либо воспользоваться [.keyword]*сценарием* (см. далее).

== Функции

Описание процесса содержит набор принадлежащих ему [.dfn .term]_функций_, настройки их свойств (свойства [.dfn .term]_функции_ могут быть проинициализированы как непосредственным заданием значения, так и некой переменной процесса) и описание связей между [.dfn .term]_функциями_. Каждая [.dfn .term]_функция_ имеет собственный набор данных (обычно - в формате XML), отображающих ее настройки и любые дополнительные данные.

[.dfn .term]_Функции_ и связи между ними могут иметь собственные названия и описания для улучшения читаемости [.dfn .term]_бизнес-процесса_.

Экземпляры каждой [.dfn .term]_функции_ могут выполняться как параллельно (при установке соответствующего свойства), так и последовательно, что означает использование одних и тех же данных для выполнения [.dfn .term]_функции_ при ее повторном запуске (например, в циклах). Последовательное выполнение экземпляров [.dfn .term]_функции_ подразумевает, что её повторный запуск не будет произведен, пока не будет завершено исполнение предыдущего экземпляра.

[.dfn .term]_Функция_ может быть, как независимой (выполняться без взаимодействия с внешними системами), так и привязанной к одной или нескольким внешним системам при помощи [.dfn .term]_шлюзов_. Привязка к [.dfn .term]_шлюзам_ декларируется [.dfn .term]_функцией_ на программном уровне и проверяется на этапе добавления [.dfn .term]_функции_ в процесс.

== Шлюзы

[.dfn .term]_Шлюз_ представляет собой совокупность программных компонент, предназначенных для обеспечения взаимодействия [.dfn .term]_СУБП_ с внешними системами.

Основными функциями [.dfn .term]_шлюза_ являются:

* обмен данными между прикладной системой и СУБП;
* маршрутизация ссылки на объект прикладной системы в функциях СУБП;
* специализированная обработка прикладного объекта в рамках процесса.

[.dfn .term]_Шлюзы_ также предоставляют свой набор типов переменных, которыми можно оперировать в [.dfn .term]_СУБП_ наряду с обычными переменными. Под типами переменных подразумеваются все возможные виды объектов, которыми может оперировать [.dfn .term]_шлюз_. Например, [.dfn .term]_шлюз_ к файловой системе оперирует двумя типами объектов – файлами и папками файловой системы. Соответственно, данный [.dfn .term]_шлюз_ предоставляет [.dfn .term]_бизнес-процессам_ два типа переменных – `Папка ФС` и `Файл     ФС`.

Выбор механизма использования уникальных значений и отображаемых значений переменных, поставляемых конкретным [.dfn .term]_шлюзом_, выбирается разработчиком [.dfn .term]_шлюза_. Например, в рассмотренном выше [.dfn .term]_шлюзе_ к файловой системе, в качестве уникальных значений используются полные физические пути к файлам и папкам, а в качестве отображаемых значений – их частичные имена.

== См. также

* xref:WorkflowDevManualComponents.adoc[Программные компоненты СУБП]

*На уровень выше:* xref:../pages/dm_wf.adoc[Разработка в среде СУБП]
