= Отладка сценариев

Отладка _сценариев_ представляет собой процесс тестирования разработанного кода _сценария_ с последующим включением его в разработанный _бизнес-процесс_. Отладку можно условно разделить на две стадии:

* отладка на стадии компиляции;
* отладка на стадии исполнения.

При обработке экземпляра _СУБП_ исполнение всех _функций_ _сценария_ проходит две фазы: компиляция и непосредственное исполнение. Компиляция производится при первом обращении к _функции_ и осуществляется при помощи стандартного компилятора, входящего в состав Microsoft .NET Framework.

Если компиляция кода _сценария_ завершилась с одной (или несколькими) ошибками, то дальнейшее выполнение _бизнес-процесса_ считается невозможным, и работа _бизнес-процесса_ завершается с ошибкой. Подробное описание возникших ошибок можно найти в журнале соответствующего экземпляра _бизнес-процесса_ (они будут помечены именем функции сценария, компиляция которой не удалась) или в общем журнале работы _СУБП_ -- если такой журнал ведется.

[NOTE]
====
[.note__title]#Прим.:# Подробнее о журнале работы можно узнать в документе "Руководство по установке и администрированию" (раздел "Журнал сообщений сервиса Workflow"), а также в документе "Руководство по настройке" (раздел _{wf}_).
====

Проверить компиляцию сценария можно непосредственно из окна ввода текста сценария, нажатием кнопки [.ph .uicontrol]*Компилировать*.

В случае, если компиляция завершена успешно, производится исполнение _сценария_. Исполнение производится последовательно, если структурой кода не предусмотрено иное. После завершения исполнения всего кода _сценария_ сервис _СУБП_ переходит к обработке следующей функции _бизнес-процесса_.

Для упрощения отладки _бизнес-процесса_ на этапе исполнения можно использовать механизм сообщений. _Сценарий_ может выводить произвольные сообщения в журнал _бизнес-процесса_ при помощи функции LogMessage класса xref:api/DocsVision/Workflow/Runtime/ProcessInfo_CL.adoc[ProcessInfo]. Сообщения могут носить декларативный характер (например, сообщать о корректном выполнении тех или иных участков кода) или информировать о состоянии данных (например, значениях переменных).

[NOTE]
====
[.note__title]#Прим.:# Запись сообщений, необязательных для работы _сценария_, после тестирования предпочтительно удалить из кода -- это значительно упростит поиск информации в журнале в будущем.
====

_Сценарии_ могут использовать для организации корректной работы стандартный механизм исключений. Исключения могут возникать в результате ошибок исполнения _сценария_, либо принудительно вызываться в коде для выполнения необходимых действий. Все возможные исключения _сценарий_ должен обрабатывать самостоятельно и в зависимости от этого реализовывать тот или иной вариант работы (например, записать информацию об исключении в журнал или выполнить другой участок кода).

Если исключение не было обработано в _сценарии_, то оно обрабатывается сервисом _СУБП_, и _сценарий_ считается завершенным с непредвиденной ошибкой. Обработка процесса в этом случае прерывается на _функции_, вызвавшей исключение.

Сценарий считается завершенным успешно (исполнение процесса продолжается), если:

* компиляция сценария завершена без ошибок;
* все возникшие во время исполнения исключения обработаны самим сценарием;

Сценарий считается завершенным с ошибкой (исполнение бизнес-процесса прерывается), если:

* возникла одна или более ошибок при компиляции кода сценария (синтаксические, семантические ошибки или не удалось подключить дополнительные библиотеки);
* были необработанные исключения.

== См. далее

* xref:WorkflowDevManualComponents34.adoc[Сохранение сценария в виде сборки]
