= Серверный компонент шлюза

Серверный компонент [.dfn .term]_шлюза_ реализуется в виде .NET-сборки, и используется сервисом [.dfn .term]_СУБП_ при работе с объектами [.dfn .term]_шлюза_ (переменными). Компонент реализует следующую функциональность:

* предоставление программного интерфейса для обработки объектов [.dfn .term]_шлюза_;
* создание экземпляров объектов;
* удаление экземпляров объектов;
* сравнение объектов;
* дополнительные функции (свои для каждого шлюза).

Компонент реализует стандартный интерфейс xref:../api/DocsVision/Workflow/Gates/IGate_IN.adoc[IGate], содержащий методы, вызываемые сервисом [.dfn .term]_СУБП_ или [.dfn .term]_функциями_ процесса.

Кроме этого интерфейса, серверный компонент [.dfn .term]_шлюза_ определяет собственные интерфейсы для всех типов переменных, реализуемых [.dfn .term]_шлюзом_. Каждый объект [.dfn .term]_шлюза_ реализует стандартный интерфейс xref:../api/DocsVision/Workflow/Gates/IGateVariable_IN.adoc[IGateVariable] для совместимости с другими [.dfn .term]_шлюзами_, а также, возможно, некоторые специфические для данного типа методы. Например, тип `Пользователь` может, кроме стандартных свойств, содержать такие специфические свойства как `ФИО`, `Дата     рождения` и другие.

Серверный компонент шлюза реализуется на любом из языков платформы .NET – C# или Visual Basic .NET.

== См. также

* xref:WorkflowDevManualComponents2.adoc[Функции]

*На уровень выше:* xref:../pages/WorkflowDevManualComponents1.adoc[Шлюзы]
