= Клиентский компонент шлюза

Клиентский компонент [.dfn .term]_шлюза_ представляет собой стандартный COM-компонент, реализующий ряд предопределенных интерфейсов, в частности:

* интерфейс xref:WorkflowDevManualAppendix.html#concept_gjt_m4p_zp__IObjectUI[IObjectUI] – стандартный для всех клиентских объектов [.dfn .term]_СУБП_ ([.dfn .term]_функций_ и [.dfn .term]_шлюзов_) интерфейс, который определяет наличие у объекта идентификатора, названия, иконки и хранимых данных;
* интерфейс link:WorkflowDevManualAppendix.html#concept_gjt_m4p_zp__IGateUI[IGateUI] – стандартный интерфейс клиентского компонента шлюза. Реализует свойства и методы для работы с доступными типами переменных (объектов шлюза). Например, шлюз к файловой системе может обрабатывать два типа переменных – файлы и папки файловой системы;
* интерфейс link:WorkflowDevManualAppendix.html#concept_gjt_m4p_zp__IDVObjectUI[IDVObjectUI] (необязательный) – стандартный интерфейс для компонент, использующих объекты Docsvision. Позволяет получить доступ к текущей сессии и окну Windows-клиента.

Наиболее важными в реализации клиентского компонента шлюза являются следующие методы:

* [.keyword .apiname]#GetObjectTypes# – возвращает коллекцию описаний регистрируемых шлюзом типов переменных;
* [.keyword .apiname]#GetMethods# – возвращает коллекцию описаний методов, предоставляемых шлюзом для манипуляций над объектами;
* [.keyword .apiname]#SelectObject# – выбор значения переменной указанного типа. Обычно, вызов данного метода влечет за собой открытие одного или нескольких диалоговых окон;
* [.keyword .apiname]#GetObjectDisplayValue# – возвращает отображаемое значение переменной указанного типа по её числовому значению.

[.dfn .term]_Шлюз_ может иметь собственные хранимые данные (например, настройки соединения с внешней системой или иные необходимые настройки), которые могут меняться в зависимости от того, в каком процессе используется [.dfn .term]_шлюз_. В таком случае эти данные передаются и возвращаются при помощи свойства `Data` интерфейса [.keyword .apiname]#IObjectUI# и сохраняются в базе данных Docsvision. Пользовательский интерфейс для изменения этих настроек (при необходимости) также реализуется клиентским компонентом [.dfn .term]_шлюза_ при помощи страниц свойств.

Для передачи [.dfn .term]_шлюзу_ настроек, общих для всех экземпляров [.dfn .term]_шлюза_ одного типа, также предусмотрен интерфейс [.keyword .apiname]#IGateInit#. В существующих шлюзах он используется для установки xml-описания [.dfn .term]_шлюза_.

Для разработки страниц свойств рекомендуется использовать компонент Property Page Designer ([.ph .filepath]`DDPropPageD.ocx`), входящий в комплект поставки Docsvision.

Настройки (данные) [.dfn .term]_шлюза_ используются в дальнейшем в серверном компоненте [.dfn .term]_шлюза_ при его инициализации.

При занесении шлюза в справочник необходимо указать программный идентификатор (`ProgID`) разработанного клиентского компонента.

Клиентский компонент может быть разработан с использованием Visual Basic или Visual C++.

== См. далее

* link:WorkflowDevManualComponents12.adoc[Серверный компонент шлюза]

*На уровень выше:* xref:../pages/WorkflowDevManualComponents1.adoc[Шлюзы]
