= Общие сведения

Платформа {dv} и приложение _Управление процессами_ представляют собой систему описания сложных процессов обработки информации в организации и полнофункциональный Workflow-сервер. _СУБП_ представляет собой решение на основе платформы {dv}, предназначенное для создания бизнес-процессов любой сложности и управления ими.

Ключевыми объектами в терминологии _СУБП_ являются *бизнес-процесс*, *переменные процесса*, _функции_ и _шлюзы_.

== Бизнес-процесс

_Бизнес-процесс_ представляет собой формальное описание бизнес-процесса организации, которое строится из набора атомарных операций (_функций_), составляющих процесс, и связей между ними, определяющих порядок выполнения операций. _Функции_ _бизнес-процесса_ оперируют данными внешних систем с помощью _шлюзов_ и обмениваются данными через _переменные процесса_.

_Бизнес-процесс_ должен обязательно включать в себя специальную _функцию_, инициирующую выполнение процесса, а также одну или несколько _функций_, завершающих выполнение процесса. Остальные _функции_ могут быть связаны между собой произвольным количеством связей, которые определяют порядок их выполнения в _бизнес-процесса_. Возможно наличие в процессе циклов, условных и безусловных переходов.

Физически _бизнес-процесс_ состоит из набора данных, хранящихся в базе данных {dv}, набора свойств и методов для операций с этими данными, а также карточки {dv} типа _Бизнес-процесс_, реализующей пользовательский интерфейс для управления данными процесса.

== Переменные процесса

_Переменные процесса_ являются сущностями, которыми оперируют _функции_ процесса, обеспечивая единый способ обмена информацией между _функциями_ процесса.

Каждая переменная имеет уникальный идентификатор (в формате строки), который позволяет отличить её от остальных переменных _бизнес-процесса_: имя, значение (величину или набор данных, которые характеризуют переменную) и отображаемое значение, которое может как соответствовать значению, так и характеризовать переменную для пользователя более явным образом. Например, для переменной, представляющей карточку {dv}, значением является идентификатор карточки, а отображаемым значением – её название.

[IMPORTANT]
====
Имена переменных в бизнес-процессе являются регистро-зависимыми.
====

Все _переменные процесса_ являются строго типизированными. К стандартным (системным) типам переменных относятся следующие типы:

* Строка;
* Целое;
* Дробное;
* Логическое значение (Да/Нет);
* Дата/Время;
* Перечисление – при формировании шаблона процесса можно описать поля типа перечисления и задать все возможные значения. Все значения перечисления в процессе – строковые.

Кроме этих стандартных типов, в процесс могут быть добавлены переменные шлюзов. Каждый зарегистрированный в системе шлюз поставляет собственные типы переменных.

Автоматического преобразования типов не предусмотрено. Для преобразования экземпляра переменной из одного типа в другой (если это предусмотрено) необходимо использовать специальные функции, либо воспользоваться *сценарием* (см. далее).

== Функции

Описание процесса содержит набор принадлежащих ему _функций_, настройки их свойств (свойства _функции_ могут быть проинициализированы как непосредственным заданием значения, так и некой переменной процесса) и описание связей между _функциями_. Каждая _функция_ имеет собственный набор данных (обычно -- в формате XML), отображающих ее настройки и любые дополнительные данные.

_Функции_ и связи между ними могут иметь собственные названия и описания для улучшения читаемости _бизнес-процесса_.

Экземпляры каждой _функции_ могут выполняться как параллельно (при установке соответствующего свойства), так и последовательно, что означает использование одних и тех же данных для выполнения _функции_ при ее повторном запуске (например, в циклах). Последовательное выполнение экземпляров _функции_ подразумевает, что её повторный запуск не будет произведен, пока не будет завершено исполнение предыдущего экземпляра.

_Функция_ может быть, как независимой (выполняться без взаимодействия с внешними системами), так и привязанной к одной или нескольким внешним системам при помощи _шлюзов_. Привязка к _шлюзам_ декларируется _функцией_ на программном уровне и проверяется на этапе добавления _функции_ в процесс.

== Шлюзы

_Шлюз_ представляет собой совокупность программных компонент, предназначенных для обеспечения взаимодействия _СУБП_ с внешними системами.

Основными функциями _шлюза_ являются:

* обмен данными между прикладной системой и СУБП;
* маршрутизация ссылки на объект прикладной системы в функциях СУБП;
* специализированная обработка прикладного объекта в рамках процесса.

_Шлюзы_ также предоставляют свой набор типов переменных, которыми можно оперировать в _СУБП_ наряду с обычными переменными. Под типами переменных подразумеваются все возможные виды объектов, которыми может оперировать _шлюз_. Например, _шлюз_ к файловой системе оперирует двумя типами объектов – файлами и папками файловой системы. Соответственно, данный _шлюз_ предоставляет _бизнес-процессам_ два типа переменных – `Папка ФС` и `Файл     ФС`.

Выбор механизма использования уникальных значений и отображаемых значений переменных, поставляемых конкретным _шлюзом_, выбирается разработчиком _шлюза_. Например, в рассмотренном выше _шлюзе_ к файловой системе, в качестве уникальных значений используются полные физические пути к файлам и папкам, а в качестве отображаемых значений – их частичные имена.

== См. также

* xref:WorkflowDevManualComponents.adoc[Программные компоненты СУБП]
