= Отладка сценариев

Отладка [.dfn .term]_сценариев_ представляет собой процесс тестирования разработанного кода [.dfn .term]_сценария_ с последующим включением его в разработанный [.dfn .term]_бизнес-процесс_. Отладку можно условно разделить на две стадии:

* отладка на стадии компиляции;
* отладка на стадии исполнения.

При обработке экземпляра [.dfn .term]_СУБП_ исполнение всех [.dfn .term]_функций_ [.dfn .term]_сценария_ проходит две фазы: компиляция и непосредственное исполнение. Компиляция производится при первом обращении к [.dfn .term]_функции_ и осуществляется при помощи стандартного компилятора, входящего в состав Microsoft .NET Framework.

Если компиляция кода [.dfn .term]_сценария_ завершилась с одной (или несколькими) ошибками, то дальнейшее выполнение [.dfn .term]_бизнес-процесса_ считается невозможным, и работа [.dfn .term]_бизнес-процесса_ завершается с ошибкой. Подробное описание возникших ошибок можно найти в журнале соответствующего экземпляра [.dfn .term]_бизнес-процесса_ (они будут помечены именем функции сценария, компиляция которой не удалась) или в общем журнале работы [.dfn .term]_СУБП_ - если такой журнал ведется.

[NOTE]
====
[.note__title]#Прим.:# Подробнее о журнале работы можно узнать в документе "Руководство по установке и администрированию" (раздел "Журнал сообщений сервиса Workflow"), а также в документе "Руководство по настройке" (раздел "Управление процессами").
====

Проверить компиляцию сценария можно непосредственно из окна ввода текста сценария, нажатием кнопки [.ph .uicontrol]*Компилировать*.

В случае, если компиляция завершена успешно, производится исполнение [.dfn .term]_сценария_. Исполнение производится последовательно, если структурой кода не предусмотрено иное. После завершения исполнения всего кода [.dfn .term]_сценария_ сервис [.dfn .term]_СУБП_ переходит к обработке следующей функции [.dfn .term]_бизнес-процесса_.

Для упрощения отладки [.dfn .term]_бизнес-процесса_ на этапе исполнения можно использовать механизм сообщений. [.dfn .term]_Сценарий_ может выводить произвольные сообщения в журнал [.dfn .term]_бизнес-процесса_ при помощи функции [.keyword .apiname]#LogMessage# класса xref:../api/DocsVision/Workflow/Runtime/ProcessInfo_CL.adoc[ProcessInfo]. Сообщения могут носить декларативный характер (например, сообщать о корректном выполнении тех или иных участков кода) или информировать о состоянии данных (например, значениях переменных).

[NOTE]
====
[.note__title]#Прим.:# Запись сообщений, необязательных для работы [.dfn .term]_сценария_, после тестирования предпочтительно удалить из кода - это значительно упростит поиск информации в журнале в будущем.
====

[.dfn .term]_Сценарии_ могут использовать для организации корректной работы стандартный механизм исключений. Исключения могут возникать в результате ошибок исполнения [.dfn .term]_сценария_, либо принудительно вызываться в коде для выполнения необходимых действий. Все возможные исключения [.dfn .term]_сценарий_ должен обрабатывать самостоятельно и в зависимости от этого реализовывать тот или иной вариант работы (например, записать информацию об исключении в журнал или выполнить другой участок кода).

Если исключение не было обработано в [.dfn .term]_сценарии_, то оно обрабатывается сервисом [.dfn .term]_СУБП_, и [.dfn .term]_сценарий_ считается завершенным с непредвиденной ошибкой. Обработка процесса в этом случае прерывается на [.dfn .term]_функции_, вызвавшей исключение.

Сценарий считается завершенным успешно (исполнение процесса продолжается), если:

* компиляция сценария завершена без ошибок;
* все возникшие во время исполнения исключения обработаны самим сценарием;

Сценарий считается завершенным с ошибкой (исполнение бизнес-процесса прерывается), если:

* возникла одна или более ошибок при компиляции кода сценария (синтаксические, семантические ошибки или не удалось подключить дополнительные библиотеки);
* были необработанные исключения.

== См. далее

* xref:WorkflowDevManualComponents34.adoc[Сохранение сценария в виде сборки]

*На уровень выше:* xref:../pages/WorkflowDevManualComponents3.adoc[Сценарии]
