= Функции

Пользовательские _функции_ разрабатываются как дополнение к системе управления бизнес-процессами при решении задач расширения функциональности _СУБП_, которые не могут быть решены при помощи сценариев. Чаще всего, пользовательские _функции_ реализуют механизмы работы со специфическими (пользовательскими) _шлюзами_ и поставляются вместе с ними.

Все пользовательские _функции_ заносятся в _справочник функций_. После добавления в _справочник функция_ становится доступной в объектной модели и появляется на панели инструментов в карточке бизнес-процесса.

Реализация пользовательской _функции_ включает в себя два основных компонента:

* клиентский компонент, реализующий пользовательский интерфейс для настройки параметров _функции_ (если таковые предусмотрены);
* серверный компонент, работающий в рамках сервиса _СУБП_ и реализующий логику работы _функции_.

_Функция_ может быть независимой от _шлюза_ (глобальной функцией _СУБП_), либо требовать для своего исполнения наличия в процессе одного (либо нескольких) предустановленных _шлюзов_. Эти требования определяются на этапе разработки _функции_. Например, функция копирования файлов может требовать для своей работы наличия в процессе _шлюза_ к файловой системе.

Каждая _функция_ имеет собственный уникальный идентификатор (`ID`), задаваемый на этапе разработки. Этот идентификатор заносится в справочник и используется в дальнейшем для обеспечения уникальности _функций_ в системе.

.В данном разделе
* xref:WorkflowDevManualComponents21.adoc[Клиентский компонент функции]
* xref:WorkflowDevManualComponents22.adoc[Серверный компонент функции]

