= Функции

Пользовательские [.dfn .term]_функции_ разрабатываются как дополнение к системе управления бизнес-процессами при решении задач расширения функциональности [.dfn .term]_СУБП_, которые не могут быть решены при помощи сценариев. Чаще всего, пользовательские [.dfn .term]_функции_ реализуют механизмы работы со специфическими (пользовательскими) [.dfn .term]_шлюзами_ и поставляются вместе с ними.

Все пользовательские [.dfn .term]_функции_ заносятся в [.dfn .term]_справочник функций_. После добавления в [.dfn .term]_справочник функция_ становится доступной в объектной модели и появляется на панели инструментов в карточке бизнес-процесса.

Реализация пользовательской [.dfn .term]_функции_ включает в себя два основных компонента:

* клиентский компонент, реализующий пользовательский интерфейс для настройки параметров [.dfn .term]_функции_ (если таковые предусмотрены);
* серверный компонент, работающий в рамках сервиса [.dfn .term]_СУБП_ и реализующий логику работы [.dfn .term]_функции_.

[.dfn .term]_Функция_ может быть независимой от [.dfn .term]_шлюза_ (глобальной функцией [.dfn .term]_СУБП_), либо требовать для своего исполнения наличия в процессе одного (либо нескольких) предустановленных [.dfn .term]_шлюзов_. Эти требования определяются на этапе разработки [.dfn .term]_функции_. Например, функция копирования файлов может требовать для своей работы наличия в процессе [.dfn .term]_шлюза_ к файловой системе.

Каждая [.dfn .term]_функция_ имеет собственный уникальный идентификатор (`ID`), задаваемый на этапе разработки. Этот идентификатор заносится в справочник и используется в дальнейшем для обеспечения уникальности [.dfn .term]_функций_ в системе.

== В этом подразделе

* xref:WorkflowDevManualComponents21.adoc[Клиентский компонент функции]
* xref:WorkflowDevManualComponents22.adoc[Серверный компонент функции]

* *xref:../pages/WorkflowDevManualComponents21.adoc[Клиентский компонент функции]* +
* *xref:../pages/WorkflowDevManualComponents22.adoc[Серверный компонент функции]* +

*На уровень выше:* xref:../pages/WorkflowDevManualComponents.adoc[Программные компоненты СУБП]
