= Взаимодействие с объектной моделью Workflow

Основные объекты, которыми оперирует функция сценария, – это внутренние объекты сервиса _СУБП_, специфические для исполняемого процесса. К ним относятся _переменные процесса_, _шлюзы_, журнал процесса и др. Необходимые типы данных собраны в пространстве имен DocsVision.Workflow.Runtime.

Главный способ получения данных бизнес-процесса -- это обращение к соответствующим свойствам объекта типа xref:api/DocsVision/Workflow/Runtime/ProcessInfo_CL.adoc[ProcessInfo], который содержит данные о текущем процессе:

* коллекция шлюзов, доступных процессу;
* коллекция переменных процесса;
* ссылка на справочники;
* ссылка на карточку процесса;
* журнал процесса.

Кроме того, ProcessInfo содержит методы:

* получение шлюза с указанным именем;
* получение переменной с указанным именем;
* запись информационного сообщения в журнал процесса.

Экземпляр данного класса выступает в качестве входного параметра _функции_ _сценария_.

== Работа со шлюзами

Коллекция _шлюзов_ процесса (переменная ProcessInfo.Gates) содержит типизированные экземпляры серверных классов _шлюзов_, реализующих общий интерфейс xref:api/DocsVision/Workflow/Gates/IGate_IN.adoc[IGate]. Для получения конкретного _шлюза_ из коллекции, необходимо знать его название или тип.

[NOTE]
====
[.note__title]#Прим.:# Тип шлюза (уникальный идентификатор) задается в процессе его разработки и в дальнейшем не должен изменяться.
====

Для организации взаимодействия с объектами внешней системы _сценарий_ может общаться с этой системой напрямую (при помощи ее собственного API), либо с помощью _шлюза_, который может содержать вспомогательные классы для работы с каждым из объектов внешней системы. Например, при работе со _Справочником сотрудников_ разработчик _сценария_ может работать напрямую с данными справочника, либо использовать соответствующие объекты _шлюза_ к Docsvision. Однако чаще всего объекты _шлюза_ служат внутренним целям (для организации работы стандартных функций), и могут не иметь всех свойств и методов по сравнению с API Docsvision. Поэтому при наличии возможности, рекомендуется работать с внешней системой через API Docsvision.

Пример работы с объектами из _сценария_ с использованием API Docsvision:

[source,csharp]
----
public void Execute (ProcessInfo process, PassState passInfo)
{
 // Получение шлюза к Docsvision
 DVGate dvGate = (DVGate)process.Gates[DVGate.GateID];

 // Получение сессии для доступа к API
 UserSession userSession = dvGate.UserSession;

 // Получение данных карточки с идентификатором 00000000-0000-0000-0000-000000000000
 CardData data = userSession.CardManager.GetCardData(new Guid("00000000-0000-0000-0000-000000000000"));

 // ...
}
----

Сессия может быть получена из самого сценария:

[source,csharp]
----
public void Execute (ProcessInfo process, PassState passInfo)
{
 // Получение сессии процесса
 UserSession userSession = process.Session;

   // ...
}
----

== Работа с переменными

_Переменные процесса_ могут быть получены из переменной ProcessInfo.Variables, которая содержит объекты типа xref:api/DocsVision/Workflow/Runtime/ProcessVariable_CL.adoc[ProcessVariable]. Данный тип предоставляет следующие данные:

* уникальный идентификатор переменной, ее название, тип и значение;
* отображаемое значение объекта, хранящегося в переменной;
* идентификатор шлюза, которому принадлежит переменная;
* коллекция строчных значений (для переменных типа "Перечисление");

При работе с переменными простых типов ("Строка", "Целое", "Дробное" и др.), значение переменной может быть получено непосредственно из свойства ProcessVariable.Value. Для прочих типов (переменные шлюзов) в качестве значения переменной будет возвращена ссылка на соответствующий типизированный объект шлюза. Например:

[source,csharp]
----
// Получение переменной простого типа (тип "Строка")
ProcessVariable varStr = process.GetVariableByName("ПростоСтрока");
string strValue = (string)varStr.Value;

// Получение переменной, тип которой предоставлен шлюзом
ProcessVariable varDoc = process.GetVariableByName("Карточка");
DVCard card = (DVCard)varDoc.Value;
----

Присвоение значений переменным выполняется аналогично: переменные простых типов получают непосредственное значение, тогда как шлюзовые переменные в качестве нового значения могут получать только объекты шлюза. Например:

[source,csharp]
----
// Получение переменной простого типа (тип "Строка") и присвоение ей значения
ProcessVariable varStr = process.GetVariableByName("ПростоСтрока");
varStr.Value = "Новое значение";

// Получение шлюза к Docsvision
DVGate dvGate = (DVGate)process.Gates[DVGate.GateID];

// Получение переменной, тип которой предоставлен шлюзом, и присвоение ей значения
ProcessVariable varDoc = process.GetVariableByName("Карточка");
varDoc.Value = dvGate.GetVariable((int)DVVariableType.DOCUMENT, "ID_карточки");
----

== См. далее

* xref:WorkflowDevManualComponents33.adoc[Отладка сценариев]
