= Серверный компонент функции

Серверный компонент [.dfn .term]_функции_ реализуется в виде .NET-сборки и определяет внутреннюю логику работы [.dfn .term]_функции_. Компонент реализует следующую функциональность:

* доступ к настройкам (параметрам) [.dfn .term]_функции_;
* проверка возможности выполнения [.dfn .term]_функции_;
* реализация действий, требуемых от данной [.dfn .term]_функции_.

Серверный компонент [.dfn .term]_функции_ реализует интерфейс xref:../api/DocsVision/Workflow/Functions/IFunction_IN.adoc[IFunction], методы которого вызываются сервисом [.dfn .term]_СУБП_ во время исполнения [.dfn .term]_функции_.

До начала непосредственного исполнения [.dfn .term]_функция_ получает заданные пользователем настройки в виде строки (свойство `Data`) и производится повторная проверка на их достаточность и полноту (метод [.keyword .apiname]#AllowExecute#). Далее вызывается метод [.keyword .apiname]#Execute#, реализующий непосредственно логику [.dfn .term]_функции_.

Серверный компонент [.dfn .term]_функции_ реализуется на любом из языков платформы .NET – C# или Visual Basic .NET.

== См. также

* xref:WorkflowDevManualComponents3.adoc[Сценарии]

*На уровень выше:* xref:../pages/WorkflowDevManualComponents2.adoc[Функции]
