= Серверный компонент функции

Серверный компонент _функции_ реализуется в виде .NET-сборки и определяет внутреннюю логику работы _функции_. Компонент реализует следующую функциональность:

* доступ к настройкам (параметрам) _функции_;
* проверка возможности выполнения _функции_;
* реализация действий, требуемых от данной _функции_.

Серверный компонент _функции_ реализует интерфейс xref:..xref:api/DocsVision/Workflow/Functions/IFunction_IN.adoc[IFunction], методы которого вызываются сервисом _СУБП_ во время исполнения _функции_.

До начала непосредственного исполнения _функция_ получает заданные пользователем настройки в виде строки (свойство `Data`) и производится повторная проверка на их достаточность и полноту (метод [.keyword .apiname]#AllowExecute#). Далее вызывается метод [.keyword .apiname]#Execute#, реализующий непосредственно логику _функции_.

Серверный компонент _функции_ реализуется на любом из языков платформы .NET – C# или Visual Basic .NET.

== См. также

* xref:WorkflowDevManualComponents3.adoc[Сценарии]
