= Шлюзы

Пользовательские [.dfn .term]_шлюзы_ разрабатываются как дополнение к системе управления [.dfn .term]_бизнес-процессами_ при решении задач интеграции [.dfn .term]_СУБП_ с внешними системами, взаимодействие с которыми не предусмотрено в стандартной поставке Docsvision. К таким системам можно отнести сторонние системы документооборота, EPR-системы, бухгалтерские системы и прочие.

Все пользовательские [.dfn .term]_шлюзы_ заносятся в [.dfn .term]_справочник шлюзов_. После занесения в [.dfn .term]_справочник шлюз_ становится доступен в объектной модели и в карточке бизнес-процесса.

Реализация пользовательского [.dfn .term]_шлюза_ включает в себя, как минимум, два основных компонента:

* клиентский компонент, реализующий пользовательский интерфейс для отображения и выбора объектов [.dfn .term]_шлюза_;
* серверный компонент, работающий в рамках сервиса [.dfn .term]_СУБП_ и реализующий программный интерфейс для работы с объектами [.dfn .term]_шлюза_.

Каждый [.dfn .term]_шлюз_ имеет собственный уникальный идентификатор, задаваемый на этапе разработки. Этот идентификатор заносится в справочник и используется в дальнейшем для обеспечения уникальности [.dfn .term]_шлюзов_ в системе.

== В этом подразделе

* xref:WorkflowDevManualComponents11.adoc[Клиентский компонент шлюза]
* xref:WorkflowDevManualComponents12.adoc[Серверный компонент шлюза]

* *xref:../pages/WorkflowDevManualComponents11.adoc[Клиентский компонент шлюза]* +
* *xref:../pages/WorkflowDevManualComponents12.adoc[Серверный компонент шлюза]* +

*На уровень выше:* xref:../pages/WorkflowDevManualComponents.adoc[Программные компоненты СУБП]
