= Шлюзы

Пользовательские _шлюзы_ разрабатываются как дополнение к системе управления _бизнес-процессами_ при решении задач интеграции _СУБП_ с внешними системами, взаимодействие с которыми не предусмотрено в стандартной поставке {dv}. К таким системам можно отнести сторонние системы документооборота, EPR-системы, бухгалтерские системы и прочие.

Все пользовательские _шлюзы_ заносятся в _справочник шлюзов_. После занесения в _справочник шлюз_ становится доступен в объектной модели и в карточке бизнес-процесса.

Реализация пользовательского _шлюза_ включает в себя, как минимум, два основных компонента:

* клиентский компонент, реализующий пользовательский интерфейс для отображения и выбора объектов _шлюза_;
* серверный компонент, работающий в рамках сервиса _СУБП_ и реализующий программный интерфейс для работы с объектами _шлюза_.

Каждый _шлюз_ имеет собственный уникальный идентификатор, задаваемый на этапе разработки. Этот идентификатор заносится в справочник и используется в дальнейшем для обеспечения уникальности _шлюзов_ в системе.

.В данном разделе
* xref:WorkflowDevManualComponents11.adoc[Клиентский компонент шлюза]
* xref:WorkflowDevManualComponents12.adoc[Серверный компонент шлюза]
