= Разработка сценариев

Разработка _сценариев_ включает в себя следующие этапы:

* написание кода _сценария_;
* отладка кода _сценария_;
* сохранение готового _сценария_ в процессе или подпроцессе.

Код сценарий может быть написан непосредственно в диалоговом окне [.keyword .wintitle]*Редактирование скрипта* Написание кода _сценария_ можно производить как непосредственно в диалоговом окне _функции_ _сценария_, так и в любом другом редакторе или при помощи Visual Studio.NET -- с последующей вставкой полученного кода в _функцию_ процесса.

К _сценарию_ автоматически добавляется коллекция необходимых сборок:

* `Mscorlib.dll`
* `System.dll`
* `System.Core.dll`
* `System.Data.dll`
* `System.ServiceModel.dll`
* `System.Xml.dll`
* `DocsVision.Platform.dll`
* `DocsVision.Platform.CardLib.dll`
* `DocsVision.Platform.ObjectManager.dll`
* `DocsVision.Platform.ObjectModel.dll`
* `DocsVision.ObjectManager.Interop.dll` -- данная библиотека может быть пропущена, если в настройках сценария будет выставлен флаг "Не добавлять ссылку на DocsVision.ObjectManager.Interop.dll". Будет подключена сборка `DocsVision.Platform.ObjectManager.dll`.
* `DocsVision.Workflow.Interfaces.dll`
* `DocsVision.Workflow.Objects.dll`
* `DocsVision.Workflow.Runtime.dll`
* `DocsVision.Workflow.Functions.dll`
* `DocsVision.Workflow.Gates.dll`
* `DocsVision.BackOffice.ObjectModel.dll`
* `DocsVision.SecurityManager.Interop.dll`
* `DocsVision.HelperAPI.Interop.dll`

[IMPORTANT]
====
В сценариях, приведенных далее, будет использоваться сборка `DocsVision.Platform.ObjectManager.dll` (в параметрах сценария установлен флаг "Не добавлять ссылку на DocsVision.ObjectManager.Interop.dll") -- нужно учитывать при указании типа переменных.
====

При добавлении в карточку бизнес-процесса сценария, автоматически формируется стандартная структура класса сценария -- DVScript, со стандартной точкой входа -- метод Execute:

[source,csharp]
----
class DVScript
{
 // стандартная функция, которая будет вызвана подсистемой СУБП
 //
 // входные параметры функции:
 //
 // process -- информация о процессе. содержит коллекции
 //     Gates -- коллекция шлюзов процесса
 //     Variables -- коллекция переменных процесса
 // passInfo -- информация о текущем проходе
 //
 public void Execute (ProcessInfo process, PassState passInfo)
 {
  try
  {
   // пример: получение переменной процесса с именем Var1
   ProcessVariable oVar = process.GetVariableByName("Var1");
   
   // присвоение переменной нового значения
   oVar.Value = "Scripted";

   // запись в журнал процесса
   process.LogMessage ("Значение переменной изменено");
  }
  catch (Exception ex)
  {
   // запись в журнал ошибки исполнения
   process.LogMessage("Ошибка выполнения скрипта:" + ex.Message);
  }
  return;
 }
}
----

Если в сценарии идет обращение к контексту объектов, то вместо его создания (из пользовательской сессии) достаточно изменить точку входа (также необходимо подключить пространство имен DocsVision.Platform.ObjectModel):

[source,csharp]
----
public void Execute (ProcessInfo process, PassState passInfo, ObjectContext objectContext)
----

Помимо приведенных сигнатур метода, можно использовать точку входа, возвращающую результат выполнения:

[source,csharp]
----
public ExecResultEnum Execute(ProcessInfo process, PassState passInfo)
----

Вариант с xref:api/DocsVision/Workflow/Functions/ExecResultEnum_EN.adoc[ExecResultEnum] позволяет после завершения сценария оставить функцию активной или ожидающей какого-то события -- сценарий будет запущен повторно после наступления события или (в зависимости от ExecResultEnum) при следующем проходе.

[NOTE]
====
В ранних версиях {dv} подобное поведение можно было организовать при помощи вызова в сценарии исключения типа FunctionResultException#.
====

Сигнатура приведенного метода не является жесткой -- список параметров может формироваться разработчиком _сценария_. Допускается использование параметров определенных типов, указанных ниже.

[width="100%",cols="25%,75%",options="header"]
|===
|Тип |Привязка к объекту
|ProcessInfo |Расширенная объектная модель текущего бизнес-процесса.
|Process |Объектная модель текущего бизнес-процесса.
|ProcFunction |Объектная модель над данными текущей выполняемой функции.
|PassState |Объектная модель текущего прохода исполняемой функции.
|ScriptFunction |Исполняемая функция "Сценарий".
|IFunction |Интерфейс IFunction# текущей исполняемой функции.
|IFunction2 |Интерфейс IFunction2# текущей исполняемой функции.
|IWorkflowRuntime |Объект представляющий текущий WorkflowRuntime. В первую очередь рекомендуется использовать его при необходимости максимально эффективно запустить новый бизнес-процесс.
|UserSession |Пользовательская сессия, в контексте которой работает текущий бизнес-процесс. Эта сессия не имеет отношения к сессии, хранящейся в шлюзе к {dv}, текущего бизнес-процесса.
|ObjectContext |Проинициализированный контекст для работы с объектной моделью над данными, доступной через библиотеку DocsVision.Platform.ObjectModel. В передаваемом ObjectContext будут добавлены сервисы, достаточные для работы с объектами BackOffice.
|DVGate |Шлюз к {dv} текущего бизнес-процесса.
|ExGate |Шлюз к почте текущего бизнес-процесса.
|FSGate |Шлюз к файловой системе текущего бизнес-процесса.
|BasicGate |Шлюз к базовым типам текущего бизнес-процесса.
|AxaptaGate |Шлюз к Axapta\Dynamics Ax текущего бизнес-процесса.
|SPGate |Шлюз к SharePoint текущего бизнес-процесса.
|1CGate |Шлюз к 1C текущего бизнес-процесса.
|Тип стороннего _шлюза_ |Любой сторонний шлюз, который реализует интерфейс IGate и доступен в _бизнес-процессе_.
|===

Кроме того, предусмотрено использование переменной типа xref:api/DocsVision/Workflow/Runtime/ProcessVariable_CL.adoc[ProcessVariable] -- переменная процесса. В этом случае алгоритм получения значения переменной следующий:

. У параметра осуществляется поиск атрибута типа `VariableNameAtrribute`, в значении которого должно быть указано название переменной бизнес-процесса, которую требуется передать в выполняемый _сценарий_. Если такой атрибут у параметра отсутствует, то в качестве имени переменной принимается имя самого параметра метода.
. Если переменная с полученным именем не найдена в _бизнес-процессе_, то в качестве значения параметра будет передан null.
. Если значение параметра определить не удалось, то в качестве его значения принимается DefaultValue данного параметра. Если DefaultValue равно DBValue.Null, то оно принимается равным null.

Использование нескольких параметров, в том числе переменных процессов, позволяет реализовать следующий сценарий:

[source,csharp]
----
// Подключение системных библиотек
using System;
using System.Xml;

// Подключение библиотек СУБП
using DocsVision.Workflow.Objects;
using DocsVision.Workflow.Runtime;
using DocsVision.Workflow.Gates;
using DocsVision.Platform.HelperAPI;

// Подключение дополнительных пространств имен
using DocsVision.Workflow.Functions;
using DocsVision.Platform.ObjectManager;

namespace DVScriptHost
{
 class DVScript
 {   
  // Стандартная функция, которая будет вызвана подсистемой СУБП
  public ExecResultEnum Execute(
   ProcessInfo process                                       // Текущий процесс
   , PassState passInfo                                      // Описание состояния функции в процессе
   , UserSession session                                     // Сессия текущего процесса
   , DVGate gate                                     // Шлюз к {dv} текущего процесса
   , [VariableName("Input card")] ProcessVariable inputCard  // Переменная текущего БП с именем "Input card", т.к. присутствует атрибут VariableName
   , ProcessVariable outputCard                              // Переменная текущего БП с именем "outputCard"
  )
  {
  
   // Выполнение операций, предусмотренных бизнес-логикой

   return ExecResultEnum.Done;
  }
 }
}
----

В приведенном примере метод Execute принимает несколько параметров, два из которых (`inputCard`, `outputCard`) будут получены их переменных процесса. Переменные процесса будут получены по схеме приведенной выше. Сам метод Execute будет вызван при запуске _функции_, в которой он определен. После выполнения операций, предусмотренных бизнес-логикой, метод должен вернуть результат свой работы, например, ExecResultEnum.Done ("Функция успешно выполнилась"). Параметр `passInfo` используется для передачи в метод контекста выполнения (см. описание типаxref:api/DocsVision/Workflow/Objects/PassState_CL.adoc[PassState]) _функции_. При повторном вызове _функции_ в метод будут переданы новые данные.

== См. далее

* xref:WorkflowDevManualComponents32.adoc[Взаимодействие с объектной моделью Workflow]
