= Клиентский компонент функции

Клиентский компонент [.dfn .term]_функции_ представляет собой COM-компонент, имеющий пользовательский интерфейс для настройки её свойств.

Клиентский компонент функции реализует ряд предопределенных интерфейсов:

* интерфейс xref:WorkflowDevManualAppendix.html#concept_gjt_m4p_zp__IObjectUI[IObjectUI] – стандартный для всех клиентских объектов СУБП – содержит свойства, возвращающие идентификатор объекта, его название, иконку и хранимые данные;
* интерфейс link:WorkflowDevManualAppendix.html#concept_gjt_m4p_zp__IFunctionUI[IFunctionUI] – стандартный интерфейс клиентского компонента функции – определяет свойства и методы, вызываемые карточкой бизнес-процесса при использовании функции;
* интерфейс link:WorkflowDevManualAppendix.html#concept_gjt_m4p_zp__IExportableFunctionUI[IExportableFunctionUI] (необязательный) – интерфейс, предназначенный для [.dfn .term]_функций_, обладающих специфическим механизмом экспорта/импорта. Методы данного интерфейса используются для корректной работы функции при загрузке и выгрузке процесса в XML;
* интерфейс link:WorkflowDevManualAppendix.html#concept_gjt_m4p_zp__IStateFunctionUI[IStateFunctionUI] (необязательный) – данный интерфейс должен быть реализован в [.dfn .term]_функциях_, имеющих собственный набор состояний (например, таких как [.dfn .term]_функция_ _Задание_ ). Свойства и методы данного интерфейса позволяют определить для каждого состояния функции собственный цвет, название и иконку, которые будут отображаться на графе бизнес-процесса.

Наиболее важными в реализации клиентского компонента [.dfn .term]_функции_ являются следующие методы:

* [.keyword .apiname]#GetRequiredGates# – возвращает список необходимых для работы [.dfn .term]_функции_ [.dfn .term]_шлюзов_ (идентификаторы [.dfn .term]_шлюзов_, разделенные запятой). При разработке [.dfn .term]_функции_, данные идентификаторы должны быть известны;
* [.keyword .apiname]#AllowExecute# – разрешает или запрещает исполнение [.dfn .term]_функции_. В зависимости от того, все ли необходимые для запуска функции параметры указаны, функция может разрешить или запретить создание экземпляра процесса. Вызов данного метода производится из карточки бизнес-процесса;
* [.keyword .apiname]#Convert# – позволяет преобразовать настройки [.dfn .term]_функции_ при преобразовании процесса к более поздней версии.

Все настройки [.dfn .term]_функции_ сохраняются в строчном формате, передаются и возвращаются при помощи свойства `Data` интерфейса [.keyword .apiname]#IObjectUI# и сохраняются в базе данных Docsvision. Для удобства сохранения настроек функции рекомендуется использовать формат XML.

При реализации визуального интерфейса настройки параметров [.dfn .term]_функции_ рекомендуется использовать [.dfn .term]_механизм страниц свойств_ (Property Pages). Тогда уникальные страницы свойств [.dfn .term]_функции_ будут добавлены к стандартным страницам свойств в карточке бизнес-процесса. При разработки страниц свойств рекомендуется использовать компонент Property Page Designer ([.ph .filepath]`DDPropPageD.ocx`), входящий в комплект поставки Docsvision.

При занесении [.dfn .term]_функции_ в справочник необходимо указать программный идентификатор (`ProgID`) разработанного клиентского компонента.

Клиентский компонент функции может быть разработан с использованием Visual Basic или Visual C++.

== См. далее

* link:WorkflowDevManualComponents22.adoc[Серверный компонент функции]

*На уровень выше:* xref:../pages/WorkflowDevManualComponents2.adoc[Функции]
