= ICryptService.AddCryptAccount -- метод (X509Certificate2, Guid, String)

Предоставляет доступ указанному сотруднику к зашифрованному файлу.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void AddCryptAccount(X509Certificate2 certificate, Guid fileId, string accountName)
----

Параметры::
certificate:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]`
+
Сертификат шифрования, которым зашифрован файл

fileId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор зашифрованного файла

accountName:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Учетная запись сотрудника, которому предоставляется доступ к зашифрованному файлу

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `certificate` или `accountName`.
|`http://msdn.microsoft.com/ru-ru/library/system.invalidoperationexception.aspx[System.InvalidOperationException]` |Ошибка возвращается в случае, если файл с указанным идентификатором не существует, либо у указанного сотрудника уже имеется доступ к файлу, либо у указанного сотрудника отсутствует открытый ключ шифрования.
|===

== Заметки

В том случае, если файл не является зашифрованным, будет произведено шифрование сертификатом `certificate`, поэтому вызывать метод `ICryptService.EncryptFile` не требуется.

== Примеры

В приведенном ниже примере (скрипт вызываемый из карточки приложения "{dm}"), выполняется шифрование основных файлов текущей карточки ключами сотрудников предопределённой группы

[source,csharp]
----
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Windows.Forms;

using DocsVision.BackOffice.ObjectModel;
using DocsVision.BackOffice.ObjectModel.Services;
using DocsVision.BackOffice.WinForms;
using DocsVision.BackOffice.WinForms.Controls;
using DocsVision.Platform.ObjectManager;

namespace BackOffice
{
 public class CardDocumentТестScript : CardDocumentДокументУДScript
 {
  private void ЗашифроватьДляГруппы_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
  {
   bool cancel = false;

   X509Certificate2 certificate = SelectCertificateForm.SelectCertificate(ref cancel, base.CardControl.ObjectContext); <.>
   if (cancel) return;

   ICryptService cryptService = base.CardControl.ObjectContext.GetService<ICryptService>(); <.>
   IStaffService staffService = base.CardControl.ObjectContext.GetService<IStaffService>();
   
   IEnumerable<DocumentFile> mainFiles = (base.BaseObject as Document).Files.Where<DocumentFile>(t => t.FileType = DocumentFileType.Main); <.>

   StaffGroup staffGroup = staffService.GetGroup(new Guid("00000000-0000-0000-0000-000000000000")); <.>

   foreach (DocumentFile item in mainFiles)
   {

    foreach (StaffEmployee employee in staffGroup.Employees) <.>
    {
     cryptService.AddCryptAccount(certificate, item.FileVersionRowId, employee.AccountName);
    }
   }
  }
 }
}
----
<.> Вызов формы для получения сертификата текущего сотрудника.
<.> Получения сервиса шифрования базовых объектов и сервиса для работы со справочником сотрудников.
<.> Получение основных файлов карточки.
<.> Получение группы с идентификатором.
<.> Предоставление доступа к текущему файлу сотрудникам, входящих в группу сотрудников. Отдельного вызова шифрования файла не требуется, т.к. при в том случае, если файл не зашифрован, шифрование будет произведено автоматически.
