= IStaffService.CreateUnitFolder -- метод (StaffUnit)

Создаёт корневую папку для указанного подразделения.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
FoldersFolder CreateUnitFolder(StaffUnit unit)
----

Параметры::
unit:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffUnit_CL.adoc[StaffUnit]`
+
Подразделение, для которого требуется создать корневую папку

Возвращаемое значение::
Тип: `xxref:Platform-SystemCards:ObjectModel/FoldersFolder_CL.adoc[FoldersFolder]`
+
Созданная папка

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `unit`.
|===

== Заметки

Название созданной папки будет совпадать с названием подразделения, для которого она будет создана.
