= IStaffService.AddNewUnit -- метод (StaffUnit)

Добавляет вложенное подразделение в указанную организацию.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StaffUnit AddNewUnit(StaffUnit parentUnit)
----

Параметры::
parentUnit:::
Тип: `xref:BackOffice-ObjectModel:StaffUnit_CL.adoc[StaffUnit]`
+
Организация, в которую добавляется подразделение

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:StaffUnit_CL.adoc[StaffUnit]`
+
Добавленное подразделение

== Заметки

Если параметр parentUnit не задан, организация будет добавлена в корень _Справочника сотрудников_.

== Примеры

Ниже приведен пример добавления новой организации в _Справочник сотрудников_

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

StaffUnit unit = staffService.AddNewUnit(null);
unit.Type = StaffUnitType.Organization;
unit.Name = "ООО \"Василёк\""; <.>
objectContext.SaveObject(unit);
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Добавление новой организации (тип `StaffUnitType.Organization`).
