= IStaffService.AddEmployeeToGroup -- метод (StaffGroup, StaffEmployee)

Добавляет указанного сотрудника в группу сотрудников.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StaffGroupItem AddEmployeeToGroup(StaffGroup group, StaffEmployee employee)
----

Параметры::
group:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffGroup_CL.adoc[StaffGroup]`
+
Группа, в которую включается сотрудника

employee:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffEmployee_CL.adoc[StaffEmployee]`
+
Добавляемый сотрудник

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffGroupItem_CL.adoc[StaffGroupItem]`
+
Сотрудник, включенный в группу

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `group` или `employee`.
|===

== Примеры

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

StaffGroup group = staffService.GetGroup(new Guid("00000000-0000-0000-0000-000000000000")); <.>

StaffEmployee employee = staffService.Get(new Guid("00000000-0000-0000-0000-000000000001")); <.>

staffService.AddEmployeeToGroup(group, employee); <.>
objectContext.SaveObject(group);
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение группы, в которую добавляется сотрудник.
<.> Получение сотрудника.
<.> Добавление сотрудника.
