= IStaffService.RemoveGroupEmployee -- метод (StaffGroup, StaffEmployee)

Удаляет сотрудника из группы _справочника сотрудников_.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool RemoveGroupEmployee(StaffGroup group, StaffEmployee employee)
----

Параметры::
group:::
Тип: `xref:BackOffice-ObjectModel:StaffGroup_CL.adoc[StaffGroup]`
+
Группа, из которой удаляется сотрудник

employee:::
Тип: `xref:BackOffice-ObjectModel:StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудник, удаляемый из группы

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- если удаляемый элемент был найден и удален, иначе -- `false`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `group` или `employee`.
|===
