= IStaffService.AddNewGroup -- метод (StaffGroup)

Данный метод позволяет добавить новою подгруппу в существующую группу сотрудников.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StaffGroup AddNewGroup(StaffGroup parentGroup)
----

Параметры::
parentGroup:::
Тип: `xref:BackOffice-ObjectModel:StaffGroup_CL.adoc[StaffGroup]`
+
Группа пользователей, в которую осуществляется добавление новой группы

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:StaffGroup_CL.adoc[StaffGroup]`
+
Объектная модель новой группы пользователей

== Заметки

Если parentGroup не задан, группа будет добавлена в корневой узел групп, в _Справочнике сотрудников_.

== Примеры

Ниже приведен пример простого добавления нового подразделения в корневой узел, в _Справочник сотрудников_

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

StaffUnit staffUnit = staffService.AddNewUnit(null);
staffUnit.Name = "Подразделение компании"; <.>

objectContext.SaveObject(staffUnit); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса для работы со Справочником сотрудников.
<.> Добавление подразделения.
<.> Сохранение изменений.
