= IStaffService.LoadEmployeeFromAD -- метод (StaffEmployee)

Загружает данные сотрудника из Active Directory.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
List<string> LoadEmployeeFromAD(StaffEmployee employee)
----

Параметры::
employee:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудник, для которого загружаются данные

Возвращаемое значение::
Тип: `https://msdn.microsoft.com/ru-ru/library/6sh2ey19.aspx[System.Collections.Generic.List]<string>`
+
Список обновленных атрибутов

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `employee`.
|===

== Примеры

Ниже приведен пример загрузки данных текущего сотрудника из Active Directory в _справочник сотрудников_.

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

staffService.LoadEmployeeFromAD(staffService.GetCurrentEmployee()); <.>
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Загрузка данных сотрудника из AD.
