= IStaffService.AddRoleEmployee -- метод (StaffRole, StaffEmployee)

Добавляет сотрудника в роль.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StaffContain AddRoleEmployee(StaffRole role, StaffEmployee employee)
----

Параметры::
role:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffRole_CL.adoc[StaffRole]`
+
Роль

employee:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудник, добавляемый в роль

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffContain_CL.adoc[StaffContain]`
+
Контейнер роли

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `role` или `employee`.
|===

== Примеры

Далее приведён пример добавления роли указанному сотруднику

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>();

StaffRole role = objectContext.GetObject<StaffRole>(new Guid("00000000-0000-0000-0000-000000000000"));
StaffEmployee employee = objectContext.GetObject<StaffEmployee>(new Guid("00000000-0000-0000-0000-000000000001"));

StaffContain result = staffService.AddRoleEmployee(role, employee);
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
