= IStaffService.SynchronizeRoleWithActiveDirectory -- метод (StaffRole, IADSynchronizationSettings, ILongProcessManager)

Синхронизирует данные роли _справочника сотрудников_ с Active Directory.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void SynchronizeRoleWithActiveDirectory(StaffRole role, IADSynchronizationSettings settings, ILongProcessManager syncManager)
----

Параметры::
role:::
Тип: `xref:BackOffice-ObjectModel:StaffRole_CL.adoc[StaffRole]`
+
Синхронизируемая роль

settings:::
Тип: `xref:BackOffice-ObjectModel-Services-Entities:Entities/ActiveDirectory/ADSync/IADSynchronizationSettings_IN.adoc[IADSynchronizationSettings]`
+
Параметры синхронизации

syncManager:::
Тип: `xref:BackOffice-ObjectModel-Services-Entities:Entities/ILongProcessManager_IN.adoc[ILongProcessManager]`
+
Менеджер длительных процессов

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `role`, `settings` или `syncManager`.
|===

== Заметки

Пример инициализации менеджера длительных процессов см. в xref:samples:object-model/staff-sync-ad.adoc[примере].
