= IStaffService.FindCompanyByNameOnServer -- метод (StaffUnit, String)

Выполняет поиск подразделения с заданным названием.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StaffUnit FindCompanyByNameOnServer(StaffUnit parentUnit, string unitName)
----

Параметры::
parentUnit:::
Тип: `xref:BackOffice-ObjectModel:StaffUnit_CL.adoc[StaffUnit]`
+
Подразделение, в котором выполняется поиск подразделения

unitName:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Название искомого подразделения

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:StaffUnit_CL.adoc[StaffUnit]`
+
Искомое подразделение

== Заметки

Значение `unitName` должно полностью соответствовать названию подразделения.

Поиск среди дочерних (к `parentUnit`) подразделений не производится.

При `parentUnit` равным null, поиск будет выполнен на корневом уровне дерева подразделений.
