= IStaffService.AddGroupFolder -- метод (StaffGroup, Guid, Boolean)

Добавляет папку в папки группы указанной группе сотрудников.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StaffGroupFolder AddGroupFolder(StaffGroup staffGroup, Guid folderId, bool showInTab)
----

Параметры::
staffGroup:::
Тип: `xref:BackOffice-ObjectModel:StaffGroup_CL.adoc[StaffGroup]`
+
Группа, которой добавляется папка группы

folderId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор добавляемой папки

showInTab:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- папка будет отображаться в области _моих папок_ пользователя, иначе -- `false`

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:StaffGroupFolder_CL.adoc[StaffGroupFolder]`
+
Папка группы

== Примеры

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

StaffGroup group = staffService.GetGroup(new Guid("00000000-0000-0000-0000-000000000000")); <.>

staffService.AddGroupFolder(group, new Guid("00000000-0000-0000-0000-000000000001"), true); <.>
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение группы.
<.> Добавление к группе существующей папки с идентификатором `00000000-0000-0000-0000-000000000001`.
