= IStaffService.AddEmployeesToGroup -- метод (StaffGroup, IEnumerable<StaffEmployee>)

Добавляет указанных сотрудников в группу сотрудников.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
List<StaffGroupItem> AddEmployeesToGroup(StaffGroup group, IEnumerable<StaffEmployee> employees)
----

Параметры::
group:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffGroup_CL.adoc[StaffGroup]`
+
Группа сотрудников, в которую добавляются сотрудники

employees:::
Тип: `http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StaffEmployee>`
+
Коллекция сотрудников `xref:BackOffice-ObjectModel-Staff:StaffEmployee_CL.adoc[StaffEmployee]`

Возвращаемое значение::
Тип: `https://msdn.microsoft.com/ru-ru/library/6sh2ey19.aspx[System.Collections.Generic.List]<StaffGroupItem>`
+
Список сотрудников, представленных в группе. Тип `xref:BackOffice-ObjectModel-Staff:StaffGroupItem_CL.adoc[StaffGroupItem]`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `group` или `employees`.
|===

== Примеры

Ниже приведен пример копирования всех сотрудников одной группы в другую с использованием метода `AddEmployeesToGroup`

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

StaffGroup groupSource = staffService.GetGroup(new Guid("00000000-0000-0000-0000-000000000000")); <.>

StaffGroup groupRecipient = staffService.GetGroup(new Guid("00000000-0000-0000-0000-000000000001")); <.>

IEnumerable<StaffEmployee> employees = staffService.GetGroupEmployees(groupSource); <.>

staffService.AddEmployeesToGroup(groupRecipient, employees); <.>
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
<.> Получения сервиса.
<.> Получение группы, из которой выбираются сотрудники для копирования.
<.> Получение группы, в которую осуществляется копирование.
<.> Получение всех сотрудников из первой группы.
<.> Добавление сотрудников в группу-получатель.
