= IStaffService.DeleteEmployee -- метод (StaffEmployee)

Удаляет сотрудника из _справочника сотрудников_.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void DeleteEmployee(StaffEmployee employee)
----

Параметры::
employee:::
Тип: `xref:xref:BackOffice-ObjectModel-Staff:StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудника, для которого создается персональная папка

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `employee`.
|===

== Примеры

Пример удаления уволенных сотрудников из группы.

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

StaffGroup group = staffService.GetGroup(new Guid("00000000-0000-0000-0000-000000000000")); <.>

foreach (StaffEmployee employee in group.Employees)
{
 if (employee.Status = StaffEmployeeStatus.Discharged` || employee.Status = StaffEmployeeStatus.DischargedNoRestoration) <.>
 {
  staffService.DeleteEmployee(employee);
 }
}
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение группы, из которой удаляются сотрудники.
<.> Если сотрудник уволен (в т.ч. без возможности восстановления), удаляем.
