= IStaffService.FindRoleWithSameName -- метод (StaffRole, String)

Осуществляет поиск роли по названию с исключением указанной роли из результатов.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StaffRole FindRoleWithSameName(StaffRole role, string roleName)
----

Параметры::
role:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffRole_CL.adoc[StaffRole]`
+
Роль, которая должна быть исключена из результатов

roleName:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Название искомой роли

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffRole_CL.adoc[StaffRole]`
+
Роль с названием roleName

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `role`, либо передан пустой параметр `roleName`.
|===

== Заметки

Метод может быть полезен при поиске возможных дубликатов роли `role`.
