= IStaffService.AddDeputy -- метод (StaffEmployee)

Добавляет указанному сотруднику заместителя.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StaffDeputy AddDeputy(StaffEmployee employee)
----

Параметры::
employee:::
Тип: `xref:xref:BackOffice-ObjectModel-Staff:StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудник, которому будет добавлен заместитель

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffDeputy_CL.adoc[StaffDeputy]`
+
Заместитель

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `employee`.
|===

== Примеры

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

StaffEmployee employee = staffService.Get(new Guid("00000000-0000-0000-0000-000000000000")); <.>

StaffDeputy deputy = staffService.AddDeputy(employee); <.>

deputy.Employee = staffService.Get(new Guid("00000000-0000-0000-0000-000000000001")); <.>
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение сотрудника, которому добавляется заместитель.
<.> Добавление заместителя с минимальным набором прав.
<.> Определение сотрудника, являющегося заместителем.
