= IPartnersService.AddNewEmployee -- метод (PartnersCompany)

Добавляет нового сотрудника в указанную организацию/подразделение.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
PartnersEmployee AddNewEmployee(PartnersCompany unit)
----

Параметры::
unit:::
Тип: `xref:BackOffice-ObjectModel:PartnersCompany_CL.adoc[PartnersCompany]`
+
Подразделение, в которое добавляется сотрудник

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:PartnersEmployee_CL.adoc[PartnersEmployee]`
+
Сотрудник, добавленный в организацию

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `unit`.
|===

== Примеры

[source,csharp]
----
<.>

IPartnersService partnersService = objectContext.GetService<IPartnersService>(); <.>

PartnersCompany partnersCompany = objectContext.GetObject<PartnersCompany>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

PartnersEmployee partnersEmployee = partnersService.AddNewEmployee(partnersCompany);
partnersEmployee.LastName = "Иванов";
objectContext.SaveObject(partnersEmployee); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса для работы с контрагентами.
<.> Получение организации, в которую добавляется сотрудник.
<.> Добавление и сохранение сотрудника.
