= IPowerOfAttorneyService -- интерфейс

Интерфейс предоставляет методы для работы с системной карточкой доверенности.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public interface IPowerOfAttorneyService
----

== Методы

[cols=",",options="header"]
|===
|Имя |Описание

|`PowerOfAttorney CreatePowerOfAttorney(PowerOfAttorneyData, StaffEmployee, StaffEmployee, Guid);`
a|Создаёт новую СКД для представителя -- физического лица

.Параметры:
* `powerOfAttorneyData` -- Данные доверенности
* `representative` -- Представитель
* `signer` -- Подписант
* `powerOfAttorneyType` -- Идентификатор типа доверенности

Возвращаемое значение: карточка доверенности

|`PowerOfAttorney CreatePowerOfAttorney(PowerOfAttorneyData, StaffUnit, StaffEmployee, Guid);`
a|Создаёт новую СКД для представителя -- юридического лица

.Параметры:
* `powerOfAttorneyData` -- Данные доверенности
* `representative` -- Представитель
* `signer` -- Подписант
* `powerOfAttorneyType` -- Идентификатор типа доверенности

Возвращаемое значение: карточка доверенности

|`PowerOfAttorney RetrustPowerOfAttorney(PowerOfAttorneyData, StaffEmployee, StaffEmployee, PowerOfAttorney);`
a|Создаёт СКД в рамках передоверия для представителя -- физического лица

.Параметры:
* `powerOfAttorneyData` -- Данные доверенности
* `representative` -- Представитель
* `signer` -- Подписант
* `parentPowerOfAttorney` -- Доверенность, на основании которой осуществляется передоверие

Возвращаемое значение: карточка доверенности

|`PowerOfAttorney RetrustPowerOfAttorney(PowerOfAttorneyData, StaffUnit, StaffEmployee, PowerOfAttorney);`
a|Создаёт СКД в рамках передоверия для представителя -- юридического лица

.Параметры:
* `powerOfAttorneyData` -- Данные доверенности
* `representative` -- Представитель
* `signer` -- Подписант
* `parentPowerOfAttorney` -- Доверенность, на основании которой осуществляется передоверие

Возвращаемое значение: карточка доверенности

|`PowerOfAttorney ImportPowerOfAttorney(string,
byte[],
StaffEmployee,
StaffEmployee,
PowersPowerOfAttorneyFormat,
PowerOfAttorneySignatureFormat,
Func<string, ObjectContext, PowersCode>);`

a|Создаёт новую СКД для представителя -- физического лица из файла МЧД

.Параметры:
* `machineReadableData` -- Содержимое МЧД с электронной подписью
* `signatureData` -- Данные электронной подписи для формата CADES
* `representative` -- Представитель
* `signer` -- Подписант
* `powerOfAttorneyFormat` -- Формат доверенности
* `signatureFormat` -- Формат подписи
* `powersCodeResolve` -- Функция получения кода полномочия Справочника полномочий по коду полномочия из МЧД

Возвращаемое значение: Карточка доверенности

Примечание: при формате подписи XMLSIG, `signatureData` не передаётся

|`PowerOfAttorney ImportPowerOfAttorney(string,
byte[],
StaffEmployee,
StaffEmployee,
PowerOfAttorney,
PowerOfAttorneySignatureFormat,
Func<string, ObjectContext, PowersCode>);`

a|Создаёт новую СКД для представителя -- физического лица из файла МЧД

.Параметры:
* `machineReadableData` -- Содержимое МЧД с электронной подписью
* `signatureData` -- Данные электронной подписи для формата CADES
* `representative` -- Представитель
* `signer` -- Подписант
* `parentPowerOfAttorney` -- Доверенность, на основании которой осуществляется передоверие
* `signatureFormat` -- Формат подписи
* `Функция получения кода полночия Справочника полномочий по коду полночия из МЧД` -- Карточка доверенности

Возвращаемое значение: Карточка доверенности

Примечание: при формате подписи XMLSIG, `signatureData` не передаётся

|`PowerOfAttorney ImportPowerOfAttorney(string,
byte[],
StaffUnit,
StaffEmployee,
PowersPowerOfAttorneyFormat,
PowerOfAttorneySignatureFormat,
Func<string, ObjectContext, PowersCode>);`

a|Создаёт новую СКД для представителя -- юридического лица из файла МЧД

.Параметры:
* `machineReadableData` -- Содержимое МЧД с электронной подписью
* `signatureData` -- Данные электронной подписи для формата CADES
* `representative` -- Представитель
* `signer` -- Подписант
* `powerOfAttorneyFormat` -- Формат доверенности
* `signatureFormat` -- Формат подпис
* `powersCodeResolve` -- Функция получения кода полночия Справочника полномочий по коду полночия из МЧД

Возвращаемое значение: Карточка доверенности

Примечание: При формате подписи XMLSIG, signatureData не передаётся

|`PowerOfAttorney ImportPowerOfAttorney(string,
byte[],
StaffUnit,
StaffEmployee,
PowerOfAttorney,
PowerOfAttorneySignatureFormat,
Func<string, ObjectContext, PowersCode>);`

a|Создаёт новую СКД для представителя -- юридического лица из файла МЧД

.Параметры:
* `machineReadableData` -- Содержимое МЧД с электронной подписью
* `signatureData` -- Данные электронной подписи для формата CADES
* `representative` -- Представитель
* `signer` -- Подписант
* `parentPowerOfAttorney` -- Доверенность, на основании которой осуществляется передоверие
* `signatureFormat` -- Формат подписи
* `powersCodeResolve` -- Функция получения кода полномочия Справочника полномочий по коду полномочия из МЧД

Возвращаемое значение: Карточка доверенности

Примечание: При формате подписи XMLSIG, signatureData не передаётся

|`void SignPowerOfAttorney(PowerOfAttorney, X509Certificate2, PowerOfAttorneySignatureFormat signatureFormat);`
a|Подписывает СКД

.Параметры:
* `powerOfAttorney` -- СКД
* `certificate` -- Сертификат подписи
* `signatureFormat` -- Формат хранения подписи

Примечание: СКД должна быть в статусе "Подготовка";
текущий пользователь должен быть указан "Подписантом" в СКД;
статус доверенности будет изменён на "Действует".

|`void AttachSignature(PowerOfAttorney, byte[]);`
a|Загружает в СКД подпись в формате CADES

.Параметры:
* `powerOfAttorney` -- СКД
* `signature` -- Данные подписи

Примечание: СКД должна быть в статусе "Подготовка";
текущий пользователь должен быть указан "Подписантом" в СКД;
статус доверенности будет изменён на "Действует".

|`void RequestRevocation(PowerOfAttorney);`
a|Создаёт запрос на отзыв доверенности

.Параметры:
* `powerOfAttorney` -- СКД

Примечание: СКД должна быть в статусе "Действует"

|`void Revoke(PowerOfAttorney, bool withChildsPowerOfAttorney);`
a|Отзывает доверенность

.Параметры:
* `powerOfAttorney` -- СКД
* `withChildsPowerOfAttorney` -- Включить отзыв дочерних доверенностей

Примечание: отзыв доверенности должен быть запрошен с помощью метода `RequestRevocation`.

Если включен отзыв дочерних доверенностей, то также будут отозваны дочерние доверенности, которые не были отозваны ранее. +
Если дочерняя доверенность была отозвана ранее, то она, а также все её дочерние доверенности не будут отозваны повторно.

|`void ExportMachineReadablePowerOfAttorney(PowerOfAttorney, string, bool);`
a|Выгружает содержимое МЧД в указанную папку

.Параметры:
* `powerOfAttorney` -- СКД
* `folder` -- Папка для сохранения
* `withSignature` -- Включает выгрузку МЧД с подписью

Примечание: при выгрузке МЧД с подписью в формате `XMLDSIG` будет выгружен архив с одним файлом подписанной МЧД

|`string GetPowerOfAttorneyDisplayString(PowerOfAttorney);`
a|Возвращает отображаемое название СКД

.Параметры:
* `powerOfAttorney` -- СКД

Возвращаемое значение: отображаемое название

|`string GetMachineReadablePowerOfAttorneyFileData(PowerOfAttorney, out string);`
a|Возвращает данные машиночитаемой доверенности

.Параметры:
* `powerOfAttorney` -- СКД
* `fileName` -- Идентификатор файла машиночитаемой доверенности

Возвращаемое значение: данные машиночитаемой доверенности

|`IEnumerable<PowerOfAttorneyDigest> SearchPowerOfAttorney(StaffEmployee, Guid?, Guid?, Func<PowerOfAttorney, bool>);`
a|Выполняет поиск доверенностей по условиям

.Параметры:
* `employee` -- Сотрудник, для которого ищутся доверенности
* `powerOfAttorneyType` -- Идентификатор типа доверенности
* `representativePowerCode` -- Код требуемого полномочия по доверенности
* `filter` -- Дополнительные условия фильтрации найденных доверенностей

Возвращаемое значение: информация о найденных доверенностях
|===
