= Разработка объектной модели карточки

В объектной модели карточки должны быть перечислены все (или необходимые) её секции.

Базовым классом карточки выступает всё тот же класс `ObjectBase`.

В качестве примера реализуем объектную модель карточки, содержащую секции, рассмотренные xref:develop/cards/object-model/card-section-lines.adoc[ранее]. Регистрация секций в карточке, аналогична регистрации полей в секции:

[source,csharp]
----
public class SampleCard : ObjectBase
{
 //
<.>
 public static readonly ObjectProperty StructSectionProperty; <.>
 public static readonly ObjectProperty CollectionSectionProperty; <.>
 public static readonly ObjectProperty TreeSectionProperty; <.>

 public SampleCardStructSection StructSection <.>
 {
  get
  {
   if (((ObjectCollection<SampleCardStructSection>)base.GetValue(SampleCard.StructSectionProperty)).Count = 0) <.>
   {
    ((ObjectCollection<SampleCardStructSection>)base.GetValue(SampleCard.StructSectionProperty)).Add(new SampleCardStructSection());
   }
   return ((ObjectCollection<SampleCardStructSection>)base.GetValue(SampleCard.StructSectionProperty)).First<SampleCardStructSection>(); <.>
  }
 }

 public ObjectCollection<SampleCardCollectionSection> CollectionSection <.>
 {
  get { return (ObjectCollection<SampleCardCollectionSection>)base.GetValue(SampleCard.CollectionSectionProperty); }
 }

 public ObjectCollection<SampleCardTreeSection> TreeSection
 {
  get { return (ObjectCollection<SampleCardTreeSection>)base.GetValue(SampleCard.TreeSectionProperty); }

  set { base.SetValue(SampleCard.TreeSectionProperty, value); } <.>
 }

 static SampleCard()
 {
  SampleCard.StructSectionProperty = ObjectProperty.Register("StructSection", typeof(ObjectCollection<SampleCardCollectionSection>), typeof(SampleCard));
  SampleCard.CollectionSectionProperty = ObjectProperty.Register("CollectionSection", typeof(ObjectCollection<SampleCardCollectionSection>), typeof(SampleCard));
  SampleCard.TreeSectionProperty = ObjectProperty.Register("TreeSection", typeof(ObjectCollection<SampleCardTreeSection>), typeof(SampleCard));
 }

 protected internal SampleCard() <.>
 {
 }
 protected internal SampleCard(ObjectInitializationData data): base(data)
 {
 }
}
----
<.> Объявляются секции карточки.
<.> Плоская секция.
<.> Коллекционная секция.
<.> Иерархическая секция.
<.> Предоставляется доступ к секциям, а точнее к их строчкам.
<.> Если секция пустая (не содержит строчек), в ней создаётся строчка. Необязательно.
<.> Т.к. в секции может быть несколько строчек, для плоской секции возвращается только первая строчка.
<.> Коллекционная секция возвращает весь список своих строчек.
<.> Добавляется возможность записывать значение секции напрямую. Необязательно.
<.> Конструкторы для новой карточки и для существующей карточки.

Реализация объектной модели справочника ничем не отличается от реализации для карточки.

В библиотеке карточек _{bo}_ базовым классом карточки является класс xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[`BaseCard`], дополняющий функциональность класса `ObjectBase`. Базовый класс также можно использовать в качестве базового для объектной модели свой карточки. Для справочников в данном случае базовым классом выступает xref:api/DocsVision/BackOffice/ObjectModel/BaseDictionaryCard_CL.adoc[`BaseDictionaryCard`].
