= Разработка компонента карточки

[NOTE]
====
Исходный код компонента карточки расположен в подкаталоге `NetstatSolutionCard` приложенного xref:ROOT:attachment$netstatSolution.zip[архива].
====

Поскольку пример разработки компонента карточки приведён в разделе xref:solutions:cards/card-component/component.adoc[Разработка компонента карточки], здесь отмечены только ключевые моменты его реализации для _Модуля учета сетевых устройств_.

Реализация интерфейса карточки в компоненте не планируется, вместо этого в _Конструкторе разметок_ будет настроена её разметка, с последующей выгрузкой этих настроек (рассмотрено в разделе xref:solution/card-sql-package.adoc[Формирование "CardPackage" и "SqlPackage"]) для размещения в пакете установки. Чтобы разметка карточки могла быть настроена в конструктора, класс компонента карточки отмечен специальным атрибутом `Customizable`.

В конструктор класса компонента карточки добавим простой алгоритм проверки лицензионного ключа, значение которого считывается из реестра Windows. Для ввода лицензионного ключа предполагается использовать _SnapIn_, который будет разработан позднее.

[NOTE]
====
Проверку лицензии при необходимости можно реализовать несколькими методами (см. xref:solution/license.adoc[Лицензирование]).
====

Класс компонента должен быть отмечен атрибутом `Guid`, значение которого соответствует _Идентификатору COM-компонента карточки_ (см. xref:solution/card-lib/card-metadata-scheme.adoc[Создание схемы метаданных карточки]).

[source,csharp]
----
using DocsVision.BackOffice.WinForms;
using DocsVision.Platform.CardHost;
using System;
using System.Runtime.InteropServices;

namespace NetstatSolutionCard
{
 [ComVisible(true)]
 [Customizable(true)]
 [Guid("053B0CA1-95FD-4DDA-95FA-6043AFACCC1F")]
 [ClassInterface(ClassInterfaceType.None)]
 public partial class MainControl : DocsVision.BackOffice.WinForms.BaseCardControl
 {
  public MainControl()
  {
   if (!CheckLicense())
   {
    throw new Exception("Отсутствует лицензия для Модуля учета сетевых устройств"); <.>
   }

   InitializeComponent();
  }

  private bool CheckLicense() <.>
  {
   bool result = false;
  
   return result; <.>
  }
 }
} 
----
<.> В случае отсутствия лицензии, при открытии карточки будет выдано сообщение об ошибке.
<.> Алгоритм проверки лицензии.
<.> Логику проверки смотрите в исходном коде проекта.

[NOTE]
====
Если вы работаете с исходными кодами проекта, то компонент карточки собирается первым.
====
