= Разработка компонента библиотеки карточек

[NOTE]
====
Исходный код компонента библиотеки карточек расположен в подкаталоге `CardLib` приложенного xref:ROOT:attachment$netstatSolution.zip[архива].
====

Компонент библиотеки карточек является обязательной частью решения, он определяет корректность установки решения в целом, а его отсутствие является сигналом {wincl}у о необходимости установки клиентской части.

При большом размере и количестве схем карточек, зарегистрированных в библиотеке, а также большом числе клиентов {dv}, компонент библиотеки карточек выполняет роль статического кэша на стороне клиента со схемами и ресурсами карточек, что предполагает выигрыш в части снижения нагрузки на сервер {dv}.

[NOTE]
====
Пример разработки компонента библиотеки карточек на C# приведён в Руководстве разработчика в разделе xref:solutions:cards/card-component/library.adoc[].
//В статье https://docsvision.zendesk.com/entries/80645519[Создание компонента библиотеки карточек на C++] рассмотрен пример разработки компонента библиотеки на языке C++.
====

[CAUTION]
====
В версии модуля {pl} 5.5.2 требования к компоненту библиотеки карточек были изменены.
====

Компонент библиотеки карточек (C++) проще всего создать на основе готового шаблона с заменой отдельных частей кода на собственные значения. Например, использовать в основе код компонента данной библиотеки и заменить идентификаторы библиотеки карточек и карточек.

[NOTE]
====
При разработке компонента без использования шаблона, требования к реализации остаются стандартными:

* Должны быть реализованы интерфейсы `ICardLibraryInfo` и `ICardLibraryInfo2`.
* Должны быть загружены ресурсы: схемы карточек и библиотеки карточек, а также их иконки.
* Компонент библиотеки должен быть реализован как COM-компонент.
====

.Полный алгоритм создания готового компонента на основе шаблона можно разбить на следующие шаги:
. Укажите действительную _Версию библиотеки карточек_ в файле `dvver.h`, в определении идентификатора сборки `VERSION_BUILD`. В этом же файле можно заменить авторство сборки.
. Добавьте в файл ресурсов (`CardLib.rc`) следующие ресурсы:
+
* В `XMLDEF` добавляются все схемы карточек, включенных в данную библиотеку, а также схема самой библиотеки карточек.
* В Icon добавляются иконки карточек и библиотеки карточек.
+
При необходимости добавьте в файл с идентификаторами ресурсов (`Resource.h`) идентификаторы новых ресурсов.
+
. Измените скрипт регистрации `CardLib.rgs`:
+
* В `CLSID` и `ForceRemove` нужно указать _идентификатор компонента библиотеки карточек_, который был указан при разработке схемы библиотеки карточек в параметре `Activation string`.
* В `TypeLib` нужно указать произвольный (сгенерировать самостоятельно) _идентификатор библиотеки типов_ -- заменить `NetstatSolution` на собственное название для регистрации COM-компонента.
+
. В файле `CardLib.def` укажите название файла сборки.
. В файле `CardLib.idl` необходимо указать _идентификатор компонента библиотеки карточек_ и _идентификатор библиотеки типов_, которые были использованы на шаге 3.
. В файле `CardLibInfo.cpp`:
+
* В массиве `GetCardType.Cards` перечислите идентификаторы всех карточек библиотеки (соблюдайте формат), их схемы (название ресурса) и иконки.
* В методе `get_Version` в `sCardLibDef` нужно указать собственное название ресурса со схемой библиотеки карточек.
+
. В свойствах проекта укажите необходимое название для сборки.

[NOTE]
====
Если вы работаете с исходными кодами проекта, то компонент библиотеки карточки собирается вторым.
====
