= PowerOfAttorneyFNSDOVELData.PrincipalInfo -- класс

Сведения о доверителе (СвДоверит)

* *Пространство имён:* `xref:Entities/Entities_NS.adoc[DocsVision.BackOffice.ObjectModel.Services.Entities]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public class PrincipalInfo
----

== Методы

[cols=",",options="header"]
|===
|Имя |Описание

|`PrincipalInfo(RussianLegalEntityPrincipalInfo, FIO)` |Заполняет Сведения о доверителе (СвДоверит)

.Параметры:
* `russianLegalEntityPrincipal` -- Сведения о доверителе -- российском юридическом лице
* `signer` -- Сведения о физическом лице, подписывающем доверенность от имени доверителя (российской организации / иностранной организации) без доверенности или сведения о физическом лице, подписывающем доверенность от своего имени/законном представителе физического лица

|`PrincipalInfo(ForeignLegalEntityPrincipalInfo, FIO)` |Заполняет Сведения о доверителе (СвДоверит)

.Параметры:
* `foreignLegalEntityPrincipal` -- Сведения о доверителе -- иностранном юридическом лице
* `signer` -- Сведения о физическом лице, подписывающем доверенность от имени доверителя (российской организации / иностранной организации) без доверенности или сведения о физическом лице, подписывающем доверенность от своего имени/законном представителе физического лица

|`PrincipalInfo(SoleProprietorInfo0, FIO)` |Заполняет Сведения о доверителе (СвДоверит)

.Параметры:
* `soleProprietor` -- Сведения о доверителе -- индивидуальном предпринимателе
* `signer` -- Сведения о физическом лице, подписывающем доверенность от имени доверителя (российской организации / иностранной организации) без доверенности или сведения о физическом лице, подписывающем доверенность от своего имени/законном представителе физического лица</param>

|`PrincipalInfo(IndividualPrincipalInfo, FIO)` |Заполняет Сведения о доверителе (СвДоверит)

.Параметры:
* `individualPrincipal` -- Сведения о доверителе -- физическом лице
* `signer` -- Сведения о физическом лице, подписывающем доверенность от имени доверителя (российской организации / иностранной организации) без доверенности или сведения о физическом лице, подписывающем доверенность от своего имени/законном представителе физического лица
|===
