= PowerOfAttorneyFNSDOVBBData.DelegatedAuthorityPrincipalInfo -- класс

Сведения о лице, передавшем полномочия (СвЛицПередПолн)

* *Пространство имён:* `xref:Entities/Entities_NS.adoc[DocsVision.BackOffice.ObjectModel.Services.Entities]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public class DelegatedAuthorityPrincipalInfo
----

== Методы

[cols=",",options="header"]
|===
|Имя |Описание

|`DelegatedAuthorityPrincipalInfo(LegalEntityInfo, FIO)`
a|Заполняет Сведения о лице, передавшем полномочия (СвЛицПередПолн)

.Параметры:
* `legalEntity` -- Сведения о лице, передавшем полномочия – российском юридическом лице
* `signer` -- Сведения о физическом лице, подписывающем доверенность от имени лица, передавшего полномочия(российской организации) или сведения о физическом лице, подписывающем доверенность от своего имени

|`DelegatedAuthorityPrincipalInfo(SoleProprietorInfo0, FIO)`
a|Заполняет Сведения о лице, передавшем полномочия (СвЛицПередПолн)

.Параметры:
* `soleProprietor` -- Сведения о лице, передавшем полномочия – индивидуальном предпринимателе
* `signer` -- Сведения о физическом лице, подписывающем доверенность от имени лица, передавшего полномочия(российской организации) или сведения о физическом лице, подписывающем доверенность от своего имени

|`DelegatedAuthorityPrincipalInfo(IndividualDelegatedAuthorityInfo, FIO)`
a|Заполняет Сведения о лице, передавшем полномочия (СвЛицПередПолн)

.Параметры:
* `individual` -- Сведения о лице, передавшем полномочия – физическом лице
* `signer` -- Сведения о физическом лице, подписывающем доверенность от имени лица, передавшего полномочия(российской организации) или сведения о физическом лице, подписывающем доверенность от своего имени

|===
