= PowerOfAttorneyFNSDOVBBData.RepresentativePowerInfo -- класс

Сведения о полномочиях представителя (представителей) (СвПолнТип)

* *Пространство имён:* `xref:Entities/Entities_NS.adoc[DocsVision.BackOffice.ObjectModel.Services.Entities]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public class RepresentativePowerInfo
----

== Методы

[cols=",",options="header"]
|===
|Имя |Описание

|`RepresentativePowerInfo(PowersCode, string, string)`
a|Заполняет Сведения о полномочиях представителя (представителей) (СвПолнТип)

.Параметры:
* `powersCode` -- Код полномочий уполномоченного представителя
* `content` -- Содержание полномочий уполномоченного представителя
* `additionalInfo` -- Дополнительное описание полномочий уполномоченного представителя

|`RepresentativePowerInfo(string, string, string)`
a|Заполняет Сведения о полномочиях представителя (представителей) (СвПолнТип)

.Параметры:
* `powersDescription` -- Текстовое описание полномочий уполномоченного представителя
* `content` -- Содержание полномочий уполномоченного представителя
* `additionalInfo` -- Дополнительное описание полномочий уполномоченного представителя

|===
