= PowerOfAttorneyFNSDOVELData.ElectronicDocumentTransferMethod -- класс

Способ передачи электронного нотариального документа (СпПрдЭНотДок)

* *Пространство имён:* `xref:Entities/Entities_NS.adoc[DocsVision.BackOffice.ObjectModel.Services.Entities]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public class ElectronicDocumentTransferMethod
----

== Методы

[cols=",",options="header"]
|===
|Имя |Описание

|`ElectronicDocumentTransferMethod(bool?, bool?, bool?, bool? fromAttorneyToFNP, string, string)` |Заполняет Способ передачи электронного нотариального документа (СпПрдЭНотДок)

.Параметры:
* `fromPrincipalToEPGU` -- Направление сформированного электронного документа в ЛК доверителя на сайте ЕПГУ
* `fromAttorneyToEPGU` -- Направление сформированного электронного документа в ЛК поверенного на сайте ЕПГУ
* `fromDeclarantToFNP` -- Направление сформированного электронного документа в ЛК заявителя на сайте ФНП
* `fromAttorneyToFNP` -- Направление сформированного электронного документа в ЛК поверенного на сайте ФНП
* `otherSystem` -- Другая информационная система
* `otherIssueWay` -- Другой способ выдачи

|===
