= Разработка сервиса для работы с карточкой

Поскольку ранее было решено вынести бизнес-логику карточки за пределы её класса в сервис, разработаем его.

. Создаем интерфейс, описывающий функциональность будущего сервиса:
+
[source,csharp]
----
public interface INetstatSolutionService
{
 NetstatSolutionCard.ObjectModel.NetstatSolutionCard CreateCard(string name, string address, int type); <.>

 ObjectModel.NetstatSolutionCardJournal AddJournalEntry(NetstatSolutionCard.ObjectModel.NetstatSolutionCard card, DateTime date, bool result); <.>
}
----
<.> Создание новой карточки.
<.> Добавление результата проверки в журнал.
+
. Добавляем класс, реализующий интерфейс `INetstatSolutionService` и наследующий от `ContextService` -- базовый класс сервисов объектной модели:
+
[source,csharp]
----
internal class NetstatSolutionService : ContextService, INetstatSolutionService
----
+
Специально ограничиваем область видимости класса, т.к. контекст объектов предоставляет сервис по его интерфейсу.
+
. Реализуем функциональность, описанную интерфейсом `INetstatSolutionService`.
+
Реализацию смотрите в проекте решения.
+
. Создаем фабрику сервисов в виде класса, наследующего от `ServiceFactory`. Фабрика предоставляет экземпляр сервиса по его типу.
+
[source,csharp]
----
public class NetstatSolutionServiceFactory : ServiceFactory
{
 protected override object GetService(Type serviceType)
 {
  if (serviceType = typeof(INetstatSolutionService)) <.>
  {
   return new NetstatSolutionService();
  }
  return null;
 }
}
----
<.> Метод должен вернуть экземпляр класса, реализующего `INetstatSolutionService`, по интерфейсу.

После реализации фабрики сервисов, можно собрать проект и подключить библиотеку, содержащую сервис (интерфейс, реализацию) и фабрику сервисов, к проекту и запросить данный сервис из контекста объектов, если фабрика сервисов зарегистрирована в контексте объектов (см. xref:samples/object-model/init-context.adoc[пример] инициализации контекста объектов).

[NOTE]
====
Типы и интерфейс, разработанные для сервиса, собраны в папке `Services` проекта `NetstatSolutionCard`.
====
