= IBaseCardService.BeforeBusinessProcessStart -- событие

Происходит перед непосредственным запуском бизнес-процесса.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
event EventHandler<BusinessProcessCancelEventArgs> BeforeBusinessProcessStart
----

== Заметки

Аргумент события содержит свойство Cancel, установка которого в значение `true` позволяет предотвратить запуск БП

== Примеры

Ниже приведён пример перехвата запуска БП у которого приоритет выше 2.

[source,csharp]
----
<.>

IBaseCardService baseCardService = objectContext.GetService<IBaseCardService>(); <.>

baseCardService.BeforeBusinessProcessStart += (s, e) => <.>
{
 if (e.Process.Priority > 2) <.>
 {
  e.Cancel = false;
 }
};

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

KindsCardProcess kindsCardProcess = objectContext.GetObject<KindsCardProcess>(new Guid("00000000-0000-0000-0000-000000000001")); <.>

baseCardService.StartBusinessProcess(document, kindsCardProcess); <.>
----
<.> Инициализация контекста объектов.
<.> Получаем необходимые сервисы.
<.> Подключаемся к событию.
<.> Определяем приоритет и если выше `2`, блокируем запуск.
<.> Получаем документ, вид которого позволяет запускать бизнес-процесс вида `00000000-0000-0000-0000-000000000001`.
<.> Получаем вид бизнес-процесса.
<.> запуск БП.
