= IBaseCardService.StartBusinessProcess -- метод (BaseCard, KindsCardProcess)

Запускает бизнес-процесс указанного вида.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
Process StartBusinessProcess(BaseCard baseCard, KindsCardProcess kindsCardProcess)
----

Параметры::
baseCard:::
Тип: `xref:xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Карточка

kindsCardProcess:::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardProcess_CL.adoc[KindsCardProcess]`
+
Вид бизнес-процесса

Возвращаемое значение::
Тип: `xref:Workflow:Objects/Process_CL.adoc[Process]`
+
Бизнес-процесс

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `baseCard` или `kindsCardProcess`.
|`DocsVision.Platform.StorageServer.StorageServerException` |Возвращается в случае появления ошибки на стороне сервера.
|===

== Заметки

Если текущий сотрудник не определен, то бизнес-процесс будет создан, но не будет запущен. Запуск БП может быть отменен по результатам обработки события `IBaseCardService.BeforeBusinessProcessStart`, но только в случае запуска процесса из сервиса `IBaseCardService`.

== Примеры

Ниже приведен пример запуска бизнес-процесса, определённого в виде карточки

[source,csharp]
----
<.>

IBaseCardService baseCardService = objectContext.GetService<IBaseCardService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

KindsCardProcess kindsCardProcess = objectContext.GetObject<KindsCardProcess>(new Guid("00000000-0000-0000-0000-000000000001")); <.>

baseCardService.StartBusinessProcess(document, kindsCardProcess); <.>
----
<.> Инициализация контекста объектов.
<.> Получаем необходимый сервис.
<.> Получаем документ, вид которого позволяет запускать бизнес-процесс вида `00000000-0000-0000-0000-000000000001`.
<.> Получение вида бизнес-процесса.
<.> Запускаем БП.
