= IBaseCardService.CanStartBusinessProcesses -- метод (BaseCard, IEnumerable<KindsCardProcess>)

Проверяет допустимость запуска коллекции бизнес-процессов и возвращает список ошибок.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
IEnumerable<StartBusinessProcessErrorInfo> CanStartBusinessProcesses(BaseCard baseCard, IEnumerable<KindsCardProcess> kindsCardProcesses)
----

Параметры::
baseCard:::
Тип: `xref:xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Проверяемая карточка

kindsCardProcesses:::
Тип: `http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<KindsCardProcess>`
+
Коллекция видов бизнес-процессов типа `xref:BackOffice-ObjectModel-Kinds:KindsCardProcess_CL.adoc[KindsCardProcess]`

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StartBusinessProcessErrorInfo>`
+
Коллекция ошибок типа `xref:BackOffice-ObjectModel-Services-Entities:Entities/StartBusinessProcessErrorInfo_CL.adoc[StartBusinessProcessErrorInfo]`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `baseCard` или `processSettings`.
|===

== Заметки

Метод выполняет последовательный вызов метода `IBaseCardService.CanStartBusinessProcess` для каждого элемента коллекции `kindsCardProcesses`.
