= IBaseCardService.GetBusinessProcessesToStop -- метод (BaseCard)

Получает список видов бизнес-процесса карточки, который может быть остановлен.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
IEnumerable<KindsCardProcess> GetBusinessProcessesToStop(BaseCard baseCard)
----

Параметры::
baseCard:::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Карточка

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<KindsCardProcess>`
+
Коллекция видов типа `xref:BackOffice-ObjectModel-Kinds:KindsCardProcess_CL.adoc[KindsCardProcess]`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `baseCard`.
|===

== Заметки

Возможность остановки БП определяется исходя из наличия у карточки активных экземпляров БП.
