= IBaseCardService.InitializeSystemInfo -- метод (BaseCard, KindsCardKind)

Инициализирует системную информацию карточки.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void InitializeSystemInfo(BaseCard baseCard, KindsCardKind cardKind)
----

Параметры::
baseCard:::
Тип: `xref:BackOffice-ObjectModel:BaseCard_CL.adoc[BaseCard]`
+
Карточка

cardKind:::
Тип: `xref:BackOffice-ObjectModel:KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид карточки. Используется в случае невозможности получения данных вида карточки из самой карточки

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.invalidoperationexception.aspx[System.InvalidOperationException]` |Ошибка возникает в случае невозможности получения вида карточки -- не определен `baseCard.SystemInfo.CardKind` и не задан `cardKind`. Может также возникнуть, если в справочнике состояний не указано начальное состояние вида карточки.
|===

== Заметки

Метод выполняется в том случае, если `baseCard.SystemInfo` не является `null`. Фактически метод задает значение вида карточки, если не задано, и устанавливает текущее состояние карточки в начальное значение.
