= IBaseCardService.GetPartSignatureInfo -- метод (BaseCardSignaturePart signaturePart, Stream contentStream, X509Certificate2 certificate)

Возвращает информацию о части подписи документа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`

* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
SignatureInfo GetPartSignatureInfo(BaseCardSignaturePart signaturePart, Stream contentStream, X509Certificate2 certificate);
----

Параметры::
signaturePart:::
Тип: `xref:BackOffice-ObjectModel:BaseCardSignaturePart_CL.adoc[BaseCardSignaturePart]`
+
Часть подписи, для которой запрашивается информация

contentStream:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.io.stream.aspx[Stream]`
+
Поток подписываемых данных

certificate:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]`
+
Сертификат подписи

Возвращаемое значение::
Тип: `xref:BackOffice-DigitalSignature:SignatureInfo_CL.adoc[SignatureInfo]`
+
Информация о подписи.
