= ObjectContext.AddObject - метод (ObjectBase)

Добавляет объект в контекст объектов.

* [.keyword]*Пространство имен:* xref:ObjectModel_NS.adoc[DocsVision.Platform.ObjectModel]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public void AddObject(ObjectBase objectInstance)
----

Параметры

objectInstance::
  Тип: xref:ObjectBase_CL.adoc[ObjectBase]
  +
  Объект типа ObjectBase

== Исключения

[cols=",",options="header",]
|===
|Исключение |Условие
|http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException] |Ошибка возвращается в случае, если не задан параметр objectInstance.
|===

== Заметки

Многие методы и сервисы самостоятельно добавляют созданные объекты в контекст - смотрите заметки к методам и сервисам.

При добавлении объекта в контекст объектов, он (объект) становится доступен в рамках данного контекста. Для сохранения такого объекта в базе данных используйте методы [.keyword .apiname]#AcceptChanges# и [.keyword .apiname]#SaveObject#.

*На уровень выше:* xref:../../../../api/DocsVision/Platform/ObjectModel/ObjectContext_CL.adoc[ObjectContext - класс]
