= ObjectContext.FindObject<T> - метод (QueryObject)

Возвращает первый результат поиска, удовлетворяющий заданным условиям.

* *Пространство имен:* xref:api/DocsVision/Platform/ObjectModel/ObjectModel_NS.adoc[DocsVision.Platform.ObjectModel]
* *Сборка:* `DocsVision.Platform.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public T FindObject<T>(QueryObject query) where T : ObjectBase
----

Параметры типа

T::
Тип объекта поиска, унаследованный от xref:api/DocsVision/Platform/ObjectModel/ObjectBase_CL.adoc[ObjectBase]

*Параметры*

query::
Тип: xref:api/DocsVision/Platform/ObjectModel/Search/QueryObject_CL.adoc[QueryObject]
+
Поисковый запрос

Возвращаемое значение::
Тип: T
+
Объект, являющийся результатом поиска

== Примеры

В приведенном примере выполняется поиск сотрудника с названием учетной записи "DOMAIN\\IvanovII"

[source,csharp]
----
//Инициализация контекста объектов

// Формирование поискового запроса по полю AccountName
QueryObject query = new QueryObject(StaffEmployee.AccountNameProperty.Name, "DOMAIN\\IvanovII");

// Выполнение запроса
StaffEmployee staff = objectContext.FindObject<StaffEmployee>(query);
----
