= ObjectContext.FindObject<T> - метод (QueryObject)

Возвращает первый результат поиска, удовлетворяющий заданным условиям.

* [.keyword]*Пространство имен:* xref:ObjectModel_NS.adoc[DocsVision.Platform.ObjectModel]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public T FindObject<T>(QueryObject query) where T : ObjectBase
----

Параметры типа

T::
  Тип объекта поиска, унаследованный от xref:ObjectBase_CL.adoc[ObjectBase]

Параметры

query::
  Тип: xref:Search/QueryObject_CL.adoc[QueryObject]
  +
  Поисковый запрос

Возвращаемое значение

::
  Тип: T
  +
  Объект, являющийся результатом поиска

== Примеры

В приведенном примере выполняется поиск сотрудника с названием учетной записи "DOMAIN\\IvanovII"

[source,pre,codeblock,language-csharp]
----
//Инициализация контекста объектов

// Формирование поискового запроса по полю AccountName
QueryObject query = new QueryObject(StaffEmployee.AccountNameProperty.Name, "DOMAIN\\IvanovII");

// Выполнение запроса
StaffEmployee staff = objectContext.FindObject<StaffEmployee>(query);
----

*На уровень выше:* xref:../../../../api/DocsVision/Platform/ObjectModel/ObjectContext_CL.adoc[ObjectContext - класс]
