= ObjectProperty.Register - метод (String, Type, Type)

Статический метод регистрации свойств.

* [.keyword]*Пространство имен:* xref:ObjectModel_NS.adoc[DocsVision.Platform.ObjectModel]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public static ObjectProperty Register(string name, Type propertyType, Type ownerType)
----

Параметры

name::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Псевдоним свойства
propertyType::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.type.aspx[System.Type]
  +
  Тип регистрируемого свойства. Может быть как стандартным, например System.Guid, так и типом объектной модели секции карточки.
ownerType::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.type.aspx[System.Type]
  +
  Тип владельца свойства. Как правило - класс, в котором осуществляется регистрация свойства.

Возвращаемое значение

::
  Тип: xref:ObjectProperty_CL.adoc[ObjectProperty]
  +
  Зарегистрированное свойство

*На уровень выше:* xref:../../../../api/DocsVision/Platform/ObjectModel/ObjectProperty_CL.adoc[ObjectProperty - класс]
