= ObjectContext.CopyObject<T> - метод (T, ObjectCollection<T>, Action<T>)

Копирует указанный объект в нового владельца.

* [.keyword]*Пространство имен:* xref:ObjectModel_NS.adoc[DocsVision.Platform.ObjectModel]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public T CopyObject<T>(T objectInstance, ObjectCollection<T> newParentCollection, Action<T> initAction) where T : ObjectBase
----

Параметры типа

T::
  Тип копируемого объекта, ограничен классом унаследованным от базового типа xref:ObjectBase_CL.adoc[ObjectBase]

Параметры

objectInstance::
  Тип: T
  +
  Экземпляр копируемого объекта
newParentCollection::
  Тип: xref:ObjectCollection_CL.adoc[ObjectCollection]<T>
  +
  Коллекция потомков объекта в который производится копирование. В данную коллекцию будет добавлен копируемый objectInstance
initAction::
  Тип: http://msdn.microsoft.com/ru-ru/library/018hxwa8.aspx[System.Action]<T>
  +
  Делегат на метод, который будет вызван после создания копии в целевом объекте newParentCollection, но до сохранения изменений методом xref:ObjectContext.AcceptChanges_MT.adoc[ObjectContext.AcceptChanges]

Возвращаемое значение

::
  Тип: T
  +
  Созданная копия объекта objectInstance

== Заметки

Данный метод применим исключительно при копировании объектов, имеющих родителей: строки справочников. В остальных случаях используйте метод xref:../ObjectManager/CardData.Copy_MT.adoc[CardData.Copy] базового API.

*На уровень выше:* xref:../../../../api/DocsVision/Platform/ObjectModel/ObjectContext_CL.adoc[ObjectContext - класс]
