= ObjectContext.RollbackChanges -- метод

Отменяет все изменения в контексте объектов, которые не были сохранены методом AcceptChanges, SaveObject<T>(T)# или SaveObjects<T>(IEnumerable<T>)#.

* *Пространство имен:* xref:api/DocsVision/Platform/ObjectModel/ObjectModel_NS.adoc[DocsVision.Platform.ObjectModel]
* *Сборка:* `DocsVision.Platform.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public void RollbackChanges()
----

== Заметки

Отменяются изменения объектов, имеющих следующие флаги в состояний (xref:api/DocsVision/Platform/ObjectModel/ObjectStateFlags_EN.adoc[ObjectStateFlags]): ObjectStateFlags.Modified, ObjectStateFlags.Added или ObjectStateFlags.Deleted. Перед непосредственной отменой изменений, метод взывает событие ObjectContext.BeforeRollback, которое может быть использовано для прекращения процедуры отката.

После вызова xref:api/DocsVision/Platform/ObjectModel/ObjectContext.AcceptChanges_MT.adoc[ObjectContext.AcceptChanges] отмена принятых изменений будет невозможна.

== Примеры

В качестве примера приведен код получения двух документов, в каждый из которых вносится определенное изменение. Изменения могут быть отменены при проверке флага `roolback`

[source,csharp]
----
//Инициализация контекста объектов
        
// Получение и изменение документа       
Document documentA = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000"));
documentA.Description = "Описание не корректно";

Document documentB = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000001"));
documentB.MainInfo.Name = "Название не корректно";

// Флаг разрешающий откат изменений
if (roolback)
{

 // Отмена всех изменений
 objectContext.RollbackChanges();
}
----
