= KindsCardExtendedSettingGroupSettingCollection.SetSetting - метод (String, Object)

Устанавливает значение указанной настройки расширения.

* [.keyword]*Пространство имен:* xref:ObjectModel_NS.adoc[DocsVision.BackOffice.ObjectModel]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public KindsCardExtendedSettingGroupSetting SetSetting(string name, object value)
----

Параметры

name::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Название свойства
value::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.object.aspx[System.Object]
  +
  Значение свойства

Возвращаемое значение

::
  Тип: xref:KindsCardExtendedSettingGroupSetting_CL.adoc[KindsCardExtendedSettingGroupSetting]
  +
  Измененное или созданное свойство

== Заметки

Если свойство с указанным названием отсутствует, то оно будет создано.

*На уровень выше:* xref:../../../../api/DocsVision/BackOffice/ObjectModel/KindsCardExtendedSettingGroupSettingCollection_CL.adoc[KindsCardExtendedSettingGroupSettingCollection - класс]
