= StaffUnit.Manager -- свойство

Задает или возвращает сотрудника, который является руководителем организации.

* *Пространство имён:* `xref:api/DocsVision/Platform/ObjectModel/ObjectModel_NS.adoc[DocsVision.BackOffice.ObjectModel]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public StaffEmployee Manager { get; set; }
----

Значение свойства::
Тип: `xref:api/DocsVision/BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee]`
+
Руководитель организации/подразделения

== Заметки

Руководитель подразделения или организации может быть задан, например, в _Справочнике сотрудников_.

== Примеры

В примере выполняется проверка того, что текущий сотрудника является руководителем подразделения, в котором числиться.

[source,csharp]
----
<.>

IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

StaffEmployee employee = staffService.GetCurrentEmployee(); <.>

StaffEmployee manager = employee.Unit.Manager; <.>
bool isManager = (employee = manager);
----
<.> Инициализация контекста объектов.
<.> Получение сервиса для работы со Справочником сотрудников.
<.> Получения текущего сотрудника.
<.> Получение руководителя подразделения, в котором числиться сотрудник.
