= CardActivatedEventArgs - конструктор (ActivateMode, ActivateFlags, Object)

Инициализирует новый экземпляр класса CardActivatedEventArgs с помощью указанных значений.

* [.keyword]*Пространство имен:* xref:WinForms_NS.adoc[DocsVision.Platform.WinForms]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.WinForms.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
 public CardActivatedEventArgs(DocsVision.Platform.CardHost.ActivateMode activateMode, DocsVision.Platform.CardHost.ActivateFlags activateFlags, object activateParams)
----

Параметры

activateMode::
  Тип:xref:../CardHost/ActivateMode_EN.adoc[ActivateMode]
  +
  Режим активации карточки.
activateFlags::
  Тип:xref:../CardHost/ActivateFlags_EN.adoc[ActivateFlags]
  +
  Дополнительные флаги активации карточки.
activateParams::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.object.aspx[Object]
  +
  Дополнительные флаги активации карточки.

*На уровень выше:* xref:../../../../api/DocsVision/Platform/WinForms/CardActivatedEventArgs_CL.adoc[CardActivatedEventArgs - класс]
