= CardControl.KeyPreview - свойство

Признак получения события нажатия клавиши формой карточки, до передачи его элементу управления имеющему фокус.

* [.keyword]*Пространство имен:* xref:WinForms_NS.adoc[DocsVision.Platform.WinForms]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.WinForms.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
[ResCategory("Behavior")]
[Browsable(true)]
[DefaultValue(false)]
public bool KeyPreview { get; set; }
----

Значение свойства

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[Boolean]
  +
  Признак контроля

== Заметки

Возвращает или задает значение, указывающее, будет ли форма карточки получать события клавиш до того, как событие передастся элементу управления, имеющему фокус. Значение true, если форма карточки получит все события клавиш; значение false, если выбранный в настоящее время элемент управления получает события клавиш.

*На уровень выше:* xref:../../../../api/DocsVision/Platform/WinForms/CardControl_CL.adoc[CardControl - класс]
