= NavExtension.LookupNames - метод (NavPickerNameFormat, NavPickerNameFormat, String[], String[])

Формирует по заданным учетным данным коллекцию учетных данных заданного формата.

* [.keyword]*Пространство имен:* xref:WinForms_NS.adoc[DocsVision.Platform.WinForms]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.WinForms.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
protected virtual void LookupNames(NavPickerNameFormat formatOffered, NavPickerNameFormat formatDesired, string[] accountNames, string[] resultNames)
----

Параметры

formatOffered::
  Тип: xref:../Extensibility/NavPickerNameFormat_EN.adoc[NavPickerNameFormat]
  +
  Формат входящих учетных данных.
formatDesired::
  Тип: xref:../Extensibility/NavPickerNameFormat_EN.adoc[NavPickerNameFormat]
  +
  Формат итоговых учетных данных.
accountNames::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String][]
  +
  Массив имен учетных записей.
resultNames::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String][]
  +
  Массив сформированных данных.

*На уровень выше:* xref:../../../../api/DocsVision/Platform/WinForms/NavExtension_CL.adoc[NavExtension - класс]
