= NavExtension.LookupNames -- метод (NavPickerNameFormat, NavPickerNameFormat, String[], String[])

Формирует по заданным учетным данным коллекцию учетных данных заданного формата.

* *Пространство имен:* xref:api/DocsVision/Platform/WinForms/WinForms_NS.adoc[DocsVision.Platform.WinForms]
* *Сборка:* `DocsVision.Platform.WinForms.dll`

== Синтаксис

[source,csharp]
----
protected virtual void LookupNames(NavPickerNameFormat formatOffered, NavPickerNameFormat formatDesired, string[] accountNames, string[] resultNames)
----

*Параметры*

formatOffered::
Тип: xref:api/DocsVision/Platform/Extensibility/NavPickerNameFormat_EN.adoc[NavPickerNameFormat]
+
Формат входящих учетных данных.
formatDesired::
Тип: xref:api/DocsVision/Platform/Extensibility/NavPickerNameFormat_EN.adoc[NavPickerNameFormat]
+
Формат итоговых учетных данных.
accountNames::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String][]
+
Массив имен учетных записей.
resultNames::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String][]
+
Массив сформированных данных.
