= NavExtension.LookupSids - метод (SecurityIdentifier[], String[], String[], NavPickerAccountTypes[])

Формирует коллекцию учетных записей из заданной коллекции идентификаторов безопасности SID.

* [.keyword]*Пространство имен:* xref:WinForms_NS.adoc[DocsVision.Platform.WinForms]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.WinForms.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
protected virtual void LookupSids(SecurityIdentifier[] accountSids, string[] accountNames, string[] commonNames, NavPickerAccountTypes[] accountTypes)
----

Параметры

accountSids::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.security.principal.securityidentifier.aspx[System.Security.Principal.SecurityIdentifier][]
  +
  Массив идентификаторов безопасности SID.
accountNames::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String][]
  +
  Массив имен учетных записей.
commonNames::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String][]
  +
  Массив полных имена учетных записей.
accountTypes::
  Тип: xref:../Extensibility/NavPickerAccountTypes_EN.adoc[NavPickerAccountTypes][]
  +
  Массив типов учетных записей.

*На уровень выше:* xref:../../../../api/DocsVision/Platform/WinForms/NavExtension_CL.adoc[NavExtension - класс]
