= IBaseUniversalService.AddItem -- метод (BaseUniversalItemType, BaseUniversalItem)

Добавляет строку в указанный узел справочника.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseUniversalItem AddItem(BaseUniversalItemType itemType, BaseUniversalItem item)
----

Параметры::
itemType:::
Тип: `xref:BackOffice-ObjectModel-BaseUniversal:BaseUniversalItemType_CL.adoc[BaseUniversalItemType]`
+
Узел справочника

item:::
Тип: `xref:BackOffice-ObjectModel-BaseUniversal:BaseUniversalItem_CL.adoc[BaseUniversalItem]`
+
Добавляемая строка

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-BaseUniversal:BaseUniversalItem_CL.adoc[BaseUniversalItem]`
+
Ссылка на строку

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `itemType` или `item`.
|===

== Заметки

В случае, если узел itemType уже содержит значение item, будет возвращен null.
