= IBaseUniversalService.AddNewItemType -- метод (BaseUniversalItemType)

Создает дочерний узел в указанном узле справочника.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseUniversalItemType AddNewItemType(BaseUniversalItemType parentItemType)
----

Параметры::
parentItemType:::
Тип: `xref:BackOffice-ObjectModel-BaseUniversal:BaseUniversalItemType_CL.adoc[BaseUniversalItemType]`
+
Родительский узел

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-BaseUniversal:BaseUniversalItemType_CL.adoc[BaseUniversalItemType]`
+
Добавленный узел

== Заметки

Если parentItemType не задан, то узел будет создан в корневом узле дерева справочника.

== Примеры

[source,csharp]
----
<.>

IBaseUniversalService baseUniversalService = objectContext.GetService<IBaseUniversalService>(); <.>

BaseUniversalItemType baseUniversalItemType = baseUniversalService.AddNewItemType(null);
baseUniversalItemType.Name = "Узел справочника";
baseUniversalItemType.Description = "Узел справочника созданный из кода"; <.>

baseUniversalItemType.UseOrder = true; <.>

objectContext.SaveObject<BaseUniversalItemType>(baseUniversalItemType); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервисов.
<.> Создаем новый узел в корне справочника.
<.> Элементы узла будут использовать порядковые номера.
<.> Сохранение.
