= Разработка в среде СУБП

Данный раздел содержит информацию, предназначенную для разработчиков, создающих решение на платформе {dv} с использованием приложения _{wf}_. В разделе раскрываются вопросы связанные с созданием дополнительных _функций_ СУБП, _сценариев_, _шлюзов_ и других объектов системы, расширяющих её функциональные возможности по реализации специфических бизнес-процессов.

.В данном разделе освещаются следующие темы:
* Правила разработки пользовательских _функций_ и _шлюзов_.
* Правила разработки, отладки и использования _сценариев_.

== Общие сведения

Платформа {dv} и приложение _{wf}_ представляют собой систему описания сложных процессов обработки информации в организации и полнофункциональный Workflow-сервер. _СУБП_ представляет собой решение на основе платформы {dv}, предназначенное для создания бизнес-процессов любой сложности и управления ими.

Ключевыми объектами в терминологии _СУБП_ являются _бизнес-процесс_, _переменные процесса_, _функции_ и _шлюзы_.

=== Бизнес-процесс

_Бизнес-процесс_ представляет собой формальное описание бизнес-процесса организации, которое строится из набора атомарных операций (_функций_), составляющих процесс, и связей между ними. Связи между функциями определяют порядок выполнения операций. _Функции_ _бизнес-процесса_ оперируют данными внешних систем с помощью _шлюзов_ и обмениваются данными через _переменные процесса_.

_Бизнес-процесс_ должен обязательно включать в себя специальную _функцию_, инициирующую выполнение процесса, а также одну или несколько _функций_, завершающих выполнение процесса. Остальные _функции_ могут быть связаны между собой произвольным количеством связей, которые определяют порядок их выполнения в _бизнес-процессе_. Возможно наличие в процессе циклов, условных и безусловных переходов.

Физически _бизнес-процесс_ состоит из набора данных, хранящихся в базе данных {dv}, набора свойств и методов для операций с этими данными, а также карточки {dv} типа _Бизнес-процесс_, реализующей пользовательский интерфейс для управления данными процесса.

=== Переменные процесса

_Переменные процесса_ являются сущностями, которыми оперируют _функции_ процесса. Переменные обеспечивают единый способ обмена информацией между _функциями_ процесса.

Каждая переменная имеет уникальный идентификатор в формате строки. Индетификатор строки позволяет отличить её от остальных переменных _бизнес-процесса_: имя, значение, величину или набор данных, характеризующих переменную, и отображаемое значение, которое может как соответствовать значению, так и характеризовать переменную для пользователя более явным образом. Например, для переменной, представляющей карточку {dv}, значением является идентификатор карточки, а отображаемым значением -- её название.

[WARNING]
====
Имена переменных в бизнес-процессе являются регистрозависимыми.
====

Все _переменные процесса_ являются строго типизированными. К стандартным (системным) типам переменных относятся следующие типы:

* Строка.
* Целое.
* Дробное.
* Логическое значение ("Да/Нет").
* Дата/Время.
* Перечисление -- при формировании шаблона процесса можно описать поля типа перечисления и задать все возможные значения. Все значения перечисления в процессе -- строковые.

Кроме этих стандартных типов, в процесс могут быть добавлены переменные шлюзов. Каждый зарегистрированный в системе шлюз поставляет собственные типы переменных.

Автоматического преобразования типов не предусмотрено. Для преобразования экземпляра переменной из одного типа в другой (если это предусмотрено) необходимо использовать специальные функции, либо воспользоваться _сценарием_.

=== Функции

Описание процесса содержит набор принадлежащих ему _функций_, настройки их свойств. Свойства _функции_ могут быть проинициализированы как непосредственным заданием значения, так и некой переменной процесса. Описание процесса также содержит описание связей между _функциями_. Каждая _функция_ имеет собственный набор данных (обычно -- в формате XML), отображающих её настройки и любые дополнительные данные.

_Функции_ и связи между ними могут иметь собственные названия и описания для улучшения читаемости _бизнес-процесса_.

Экземпляры каждой _функции_ могут выполняться как параллельно при установке соответствующего свойства, так и последовательно, что означает использование одних и тех же данных для выполнения _функции_ при её повторном запуске, например в циклах. Последовательное выполнение экземпляров _функции_ подразумевает, что её повторный запуск не будет произведен, пока не будет завершено исполнение предыдущего экземпляра.

_Функция_ может быть как независимой -- выполняться без взаимодействия с внешними системами, так и привязанной к одной или нескольким внешним системам при помощи _шлюзов_. Привязка к _шлюзам_ декларируется _функцией_ на программном уровне и проверяется на этапе добавления _функции_ в процесс.

=== Шлюзы

_Шлюз_ представляет собой совокупность программных компонент, предназначенных для обеспечения взаимодействия _СУБП_ с внешними системами.

.Основными функциями шлюза являются:
* Обмен данными между прикладной системой и СУБП.
* Маршрутизация ссылки на объект прикладной системы в функциях СУБП.
* Специализированная обработка прикладного объекта в рамках процесса.

_Шлюзы_ также предоставляют свой набор типов переменных, которыми можно оперировать в _СУБП_ наряду с обычными переменными. Под переменными шлюза подразумеваются все возможные виды объектов, которыми может оперировать _шлюз_. Например, _шлюз_ к файловой системе оперирует двумя типами объектов -- файлами и папками файловой системы. Соответственно, данный _шлюз_ предоставляет _бизнес-процессам_ два типа переменных -- `Папка файловой системы` и `Файл файловой системы`.

Выбор механизма использования уникальных значений и отображаемых значений переменных, поставляемых конкретным _шлюзом_, выбирается разработчиком _шлюза_. Например, в рассмотренном выше _шлюзе_ к файловой системе, в качестве уникальных значений используются полные физические пути к файлам и папкам, а в качестве отображаемых значений -- их частичные имена.
