= Клиентский компонент функции

Клиентский компонент _функции_ представляет собой COM-компонент, имеющий пользовательский интерфейс для настройки её свойств.

.Клиентский компонент функции реализует ряд предопределённых интерфейсов:
* Интерфейс `xref:com-interfaces.adoc#IObjectUI[IObjectUI]` -- стандартный для всех клиентских объектов СУБП -- содержит свойства, возвращающие идентификатор объекта, его название, иконку и хранимые данные.
* Интерфейс `xref:com-interfaces.adoc#IFunctionUI[IFunctionUI]` -- стандартный интерфейс клиентского компонента функции -- определяет свойства и методы, вызываемые карточкой бизнес-процесса при использовании функции.
* Интерфейс `xref:com-interfaces.adoc#IExportableFunctionUI[IExportableFunctionUI]` (необязательный) -- интерфейс, предназначенный для _функций_, обладающих специфическим механизмом экспорта/импорта. Методы данного интерфейса используются для корректной работы функции при загрузке и выгрузке процесса в XML.
* Интерфейс `xref:com-interfaces.adoc#IStateFunctionUI[IStateFunctionUI]` (необязательный) -- данный интерфейс должен быть реализован в _функциях_, имеющих собственный набор состояний (например, таких, как _функция_ _Задание_). Свойства и методы данного интерфейса позволяют определить для каждого состояния функции собственный цвет, название и иконку, которые будут отображаться на графе бизнес-процесса.

.Наиболее важными в реализации клиентского компонента _функции_ являются следующие методы:
* `GetRequiredGates` -- возвращает список необходимых для работы _функции_ _шлюзов_ (идентификаторы _шлюзов_, разделенные запятой). При разработке _функции_, данные идентификаторы должны быть известны.
* `AllowExecute` -- разрешает или запрещает исполнение _функции_. В зависимости от того, все ли необходимые для запуска функции параметры указаны, функция может разрешить или запретить создание экземпляра процесса. Данный метод вызывается из карточки бизнес-процесса.
* `Convert` -- позволяет преобразовать настройки _функции_ при преобразовании процесса к более поздней версии.

Все настройки _функции_ сохраняются в строчном формате, передаются и возвращаются при помощи свойства `Data` интерфейса `IObjectUI` и сохраняются в базе данных {dv}. Для удобства сохранения настроек функции рекомендуется использовать формат XML.

При реализации визуального интерфейса настройки параметров _функции_ рекомендуется использовать _механизм страниц свойств_ (Property Pages). Тогда уникальные страницы свойств _функции_ будут добавлены к стандартным страницам свойств в карточке бизнес-процесса. При разработке страниц свойств рекомендуется использовать компонент Property Page Designer (`DDPropPageD.ocx`), входящий в комплект поставки {dv}.

При занесении _функции_ в справочник необходимо указать программный идентификатор (`ProgID`) разработанного клиентского компонента.

Клиентский компонент функции может быть разработан с использованием Visual Basic или Visual C++.
