= Взаимодействие с объектной моделью Workflow

Основные объекты, которыми оперирует функция сценария, -- это внутренние объекты сервиса _СУБП_, специфические для исполняемого процесса. К ним относятся _переменные процесса_, _шлюзы_, журнал процесса и др. Необходимые типы данных собраны в пространстве имён DocsVision.Workflow.Runtime.

Главный способ получения данных бизнес-процесса -- это обращение к соответствующим свойствам объекта типа `xref:Workflow:Runtime/ProcessInfo_CL.adoc[ProcessInfo]`, который содержит данные о текущем процессе:

* Коллекция шлюзов, доступных процессу.
* Коллекция переменных процесса.
* Ссылка на справочники.
* Ссылка на карточку процесса.
* Журнал процесса.

.Кроме того, `ProcessInfo` содержит методы:
* Получение шлюза с указанным именем.
* Получение переменной с указанным именем.
* Запись информационного сообщения в журнал процесса.

Экземпляр данного класса выступает в качестве входного параметра _функции_ _сценария_.

== Работа со шлюзами

Коллекция _шлюзов_ процесса (переменная `ProcessInfo.Gates`) содержит типизированные экземпляры серверных классов _шлюзов_, реализующих общий интерфейс `xref:Workflow:Gates/IGate_IN.adoc[IGate]`. Для получения конкретного _шлюза_ из коллекции, необходимо знать его название или тип.

[NOTE]
====
Тип шлюза (уникальный идентификатор) задается в процессе его разработки и в дальнейшем не должен изменяться.
====

Для организации взаимодействия с объектами внешней системы _сценарий_ может общаться с этой системой напрямую (при помощи её собственного API), либо с помощью _шлюза_, который может содержать вспомогательные классы для работы с каждым из объектов внешней системы.

Например, при работе со _Справочником сотрудников_ разработчик _сценария_ может работать напрямую с данными справочника, либо использовать соответствующие объекты _шлюза_ к {dv}. Однако чаще всего объекты _шлюза_ служат внутренним целям (для организации работы стандартных функций), и могут не иметь всех свойств и методов по сравнению с API {dv}. Поэтому по возможности, рекомендуется работать с внешней системой через API {dv}.

.Пример работы с объектами из сценария с использованием API {dv}:
[source,csharp]
----
public void Execute (ProcessInfo process, PassState passInfo)
{
 DVGate dvGate = (DVGate)process.Gates[DVGate.GateID]; <.>

 UserSession userSession = dvGate.UserSession; <.>

 CardData data = userSession.CardManager.GetCardData(new Guid("00000000-0000-0000-0000-000000000000")); <.>

 // ...
}
----
<.> Получение шлюза к {dv}.
<.> Получение сессии для доступа к API.
<.> Получение данных карточки с идентификатором 00000000-0000-0000-0000-000000000000.

.Сессия может быть получена из самого сценария:
[source,csharp]
----
public void Execute (ProcessInfo process, PassState passInfo)
{
 UserSession userSession = process.Session; <.>

   // ...
}
----
<.> Получение сессии процесса.

== Работа с переменными

_Переменные процесса_ могут быть получены из переменной `ProcessInfo.Variables`, которая содержит объекты типа `xref:Workflow:Runtime/ProcessVariable_CL.adoc[ProcessVariable]`.

.Данный тип предоставляет следующие данные:
* Уникальный идентификатор переменной, её название, тип и значение.
* Отображаемое значение объекта, хранящегося в переменной.
* Идентификатор шлюза, которому принадлежит переменная.
* Коллекция строчных значений (для переменных типа "Перечисление").

При работе с переменными простых типов ("Строка", "Целое", "Дробное" и др.), значение переменной может быть получено непосредственно из свойства `ProcessVariable.Value`. Для прочих типов (переменные шлюзов) в качестве значения переменной будет возвращена ссылка на соответствующий типизированный объект шлюза:

[source,csharp]
----
ProcessVariable varStr = process.GetVariableByName("ПростоСтрока");
string strValue = (string)varStr.Value; <.>

ProcessVariable varDoc = process.GetVariableByName("Карточка");
DVCard card = (DVCard)varDoc.Value; <.>
----
<.> Получение переменной простого типа (тип "Строка").
<.> Получение переменной, тип которой предоставлен шлюзом.

Присвоение значений переменным выполняется аналогично: переменные простых типов получают непосредственное значение, тогда как шлюзовые переменные в качестве нового значения могут получать только объекты шлюза:

[source,csharp]
----
ProcessVariable varStr = process.GetVariableByName("ПростоСтрока");
varStr.Value = "Новое значение"; <.>

DVGate dvGate = (DVGate)process.Gates[DVGate.GateID]; <.>

ProcessVariable varDoc = process.GetVariableByName("Карточка"); <.>
varDoc.Value = dvGate.GetVariable((int)DVVariableType.DOCUMENT, "ID_карточки");
----
<.> Получение переменной простого типа (тип "Строка") и присвоение ей значения.
<.> Получение шлюза к {dv}.
<.> Получение переменной, тип которой предоставлен шлюзом, и присвоение ей значения.
