= CertificateInfo -- конструктор (string serialNumber, string subjectName, DateTime notBefore, DateTime notAfter, string issuerName)

Инициализирует новый экземпляр класса `xref:api/DocsVision/BackOffice/DigitalSignature/CertificateInfo_CL.adoc[CertificateInfo]`.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/DigitalSignature/DigitalSignature_NS.adoc[DocsVision.BackOffice.DigitalSignature]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public CertificateInfo(string serialNumber, string subjectName, DateTime notBefore, DateTime notAfter, string issuerName)
----

Параметры::
serialNumber:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[String]`
+
Серийный номер сертификата
subjectName:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[String]`
+
Имя того, кому выдан сертификат
notBefore:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.datetime.aspx[System.DateTime]`
+
Дата и время, с которых сертификат считается действительным
notAfter:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.datetime.aspx[System.DateTime]`
+
Дата и время, с которых сертификат считается недействительным

issuerName:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[String]`
+
Имя компании, выдавшей сертификат
