= TimestampInfo - конструктор (DateTime creationDate, DateTime expireDate, CertificateInfo certificate, TimestampType timestampType)

Инициализирует новый экземпляр класса xref:api/DocsVision/BackOffice/DigitalSignature/TimestampInfo_CL.adoc[TimestampInfo].

* *Пространство имен:* xref:api/DocsVision/BackOffice/DigitalSignature/DigitalSignature_NS.adoc[DocsVision.BackOffice.DigitalSignature]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

[[TimestampInfo_CT__section_jct_3ds_mpb]]
== Синтаксис

[source,csharp]
----
public TimestampInfo(DateTime creationDate, DateTime expireDate, CertificateInfo certificate, TimestampType timestampType)
----

[[TimestampInfo_CT__section_nyy_4fs_mpb]]
Параметры

creationDate::
Тип: http://msdn.microsoft.com/ru-ru/library/system.datetime.aspx[System.DateTime]
+
Дата и время формирования штампа времени
expireDate::
Тип: http://msdn.microsoft.com/ru-ru/library/system.datetime.aspx[System.DateTime]
+
Дата и время истечения срока действия штампа времени
timestampType::
Тип: xref:api/DocsVision/BackOffice/DigitalSignature/TimestampType_EN.adoc[TimestampType]
+
Тип штампа
