= TimestampInfo - конструктор (DateTime creationDate, DateTime expireDate, CertificateInfo certificate, TimestampType timestampType)

Инициализирует новый экземпляр класса xref:TimestampInfo_CL.adoc[TimestampInfo].

* [.keyword]*Пространство имен:* xref:DigitalSignature_NS.adoc[DocsVision.BackOffice.DigitalSignature]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

[[TimestampInfo_CT__section_jct_3ds_mpb]]
== Синтаксис

[source,pre,codeblock,language-csharp]
----
public TimestampInfo(DateTime creationDate, DateTime expireDate, CertificateInfo certificate, TimestampType timestampType)
----

[[TimestampInfo_CT__section_nyy_4fs_mpb]]
Параметры

creationDate::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.datetime.aspx[System.DateTime]
  +
  Дата и время формирования штампа времени
expireDate::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.datetime.aspx[System.DateTime]
  +
  Дата и время истечения срока действия штампа времени
timestampType::
  Тип: xref:TimestampType_EN.adoc[TimestampType]
  +
  Тип штампа

*На уровень выше:* xref:../../../../api/DocsVision/BackOffice/DigitalSignature/TimestampInfo_CL.adoc[TimestampInfo - класс]
