= Блокировка и снятие блокировки

Чтобы предупредить возникновение конфликтных ситуаций, вытекающих из одновременной работы нескольких пользователей с одним объектом, платформа {dv} предлагает использовать механизм блокировок, который защищает отдельный объект (карточку или строку) от изменений из сессий других пользователей, оставляя его доступным на чтение.

.Система предлагает два варианта блокировки:
* Временная, ограниченная сроком существования пользовательской сессии, из которой блокировка была установлена. Такая блокировка снимается автоматически после завершения пользовательской сессии, если объект не был освобожден пользователем самостоятельно.
* Постоянная, действующая во время существования пользовательской сессии, из которой блокировка установлена, а также после её завершения. Данная блокировка может быть снята только явно -- тем, кто её установил, либо администратором системы.

== Базовый API

Базовый API предоставляет методы для установки блокировки на карточку, строку и файл.

.На карточку может быть установлена как временная, так и постоянная блокировка:
[source,csharp]
----
CardData cardData = userSession.CardManager.GetCardData(cardId); <.>

card.PlaceLock(); <.>

card.PlaceLock(true); <.>
----
<.> Получаем карточку.
<.> Устанавливаем временную блокировку.
<.> Устанавливаем постоянную блокировку.

.Аналогичным образом устанавливается временна или постоянная блокировка на строку секции:
[source,csharp]
----
SectionData section = card.Sections[sectionId] <.>

section.FirstRow.PlaceLock() <.>
----
<.> Получаем секцию, содержащую блокируемую строку.
<.> Для примера, устанавливаем временную блокировку на первую строку секции.

.Таким же образом работает блокировка файлов (не путать с карточками файла с версиями и файлами документов):
[source,csharp]
----
FileData fileData = userSession.FileManager.GetFile(fileId); <.>

fileData.PlaceLock(true); <.>
----
<.> Получаем файл.
<.> Устанавливаем постоянную блокировку.

Помимо методов блокировки, классы карточек (`CardData`), строк (`RowData`) и файлов (`FileData`) содержат методы снятия блокировки, определяемые интерфейсом `xref:api/DocsVision/Platform/ObjectManager/ILockable_IN.adoc[ILockable]`:

* `RemoveLock` -- снимает блокировку с объекта, установленную в собственной сессии.
* `ForceUnlock` -- принудительно снимает блокировку, в т.ч. установленную другим пользователем -- необходимы административные права.

.Также интерфейс `ILockable` определяет несколько свойств:
* `LockStatus` -- состояние блокировки.
* `LockOwner` -- учетная запись сотрудника, выполнившего блокировку.

Устанавливать блокировку на объект рекомендуется во всех сценариях, связанных с изменением данных, непосредственно после получения объекта. В сочетании с проверкой состояния блокировки код может быть следующим:

[source,charp]
----
if (cardData.LockStatus = LockStatus.Free) <.>
{

 cardData.PlaceLock(); <.>
}else
{
 MessageBox.Show("Карточка заблокирована пользователем " + cardData.LockOwner);
}
----
<.> Проверяем наличие блокировки у карточки.
+
`cardData` -- карточка, которая должна быть заблокирована.
+
<.> Установка временной блокировки.

Помимо методов, которые предлагают классы карточек, строк и файлов, базовый API предоставляет специальный объект для работы с блокировками -- _менеджер блокировок_.

.Менеджер блокировок можно получить из сессии пользователя:
[source,csharp]
----
LockManager lockManager = userSession.LockManager;
----

.Менеджер блокировок предлагает два метода:
* `GetLockableObject` -- возвращает интерфейс `ILockable` для карточки с определённым идентификатором.
* `GetLockedObjects` -- предоставляет заблокированные объекты определённого типа, с возможностью получения объектов, заблокированных только текущим пользователем.

== Объектная модель

.API данного уровня предоставляет две точки доступа к механизму блокировки:
* Методы _контекста объектов_:
** `xref:api/DocsVision/Platform/ObjectModel/ObjectContext.LockObject_1_MT.adoc[ObjectContext.LockObject]` -- установка блокировки, в т.ч. постоянной.
** `xref:api/DocsVision/Platform/ObjectModel/ObjectContext.UnlockObject_MT.adoc[ObjectContext.UnlockObject]` -- снятие собственной блокировки.

.Заблокировать карточку, используя методы _контекста объектов_, можно следующим образом:
[source,csharp]
----
BaseCard card = objectContext.GetObject<BaseCard>(cardId); <.>

objectContext.LockObject(card, true); <.>
----
<.> Получаем карточку (или строку).
<.> Устанавливаем постоянную блокировку.

.Таким же образом блокируется строка карточки:
[source,csharp]
----
BaseCardSectionRow row = objectContext.GetObject<BaseCardSectionRow>(rowId); <.>
objectContext.LockObject(row, true); <.>
----
<.> `rowId` -- идентификатор блокируемой строки.
<.> Методы сервиса для работы с блокировками -- xref:api/DocsVision/BackOffice/ObjectModel/Services/ILockService_IN.adoc[ILockService]:
* `LockObject` -- устанавливает на объект временную блокировку.
* `UnlockObject` -- снимает с объекта временную блокировку.

Далее приведен пример, в котором документ (карточка типа _Документ_) блокируется для изменения, после чего блокировка снимается.
+
[source,csharp]
----
//
ILockService lockService = objectContext.GetService<ILockService>(); <.>

//
Document document = objectContext.GetObject<Document>(cardId); <.>

//
if (!(lockService.IsObjectLockedByAnotherUser(document) && <.> lockService.IsObjectLockedByAnotherUser(document)))
{
 //
 lockService.LockObject(document); <.>
 
 //
 document.MainInfo.Name = "Новое название документа"; <.>
 objectContext.SaveObject(document);

 //
 lockService.UnlockObject(document); <.>
}
----
<.> Получение сервиса для работы с блокировками.
<.> Получение изменяемого документа.
<.> Проверяем, что объект не заблокирован.
<.> Блокируем документ для изменения.
<.> Вносим изменение. В качестве примера, изменяется название документа.
+
Блокировка и снятие блокировки со строк выполняется аналогично.
