= Подключение к серверу {dv}

Первым шагом на пути разработки внешнего, по отношению к серверу и клиенту ({wincl}у) {dv}, приложению является подключение к серверу {dv}. При этом должен быть получен экземпляр _пользовательской сессии_ (или сессии пользователя) -- главный объект базового API, обеспечивающий единую точку доступа к остальным функциям API данного уровня. При разработке скриптов карточки (в _Конструкторе скриптов_, либо в _Конструкторе разметок_) и бизнес-процессов создавать пользовательскую сессию не требуется -- готовую сессию можно получить из класса скрипта карточки, а также из параметров вызываемых в бизнес-процессе методов.

С физической точки зрения, сессия -- контекст сеанса связи с сервером для конкретного пользователя. Сессия ассоциируется с конкретной доменной учетной записью, от имени которой установлено соединение, и в дальнейшем все привилегии на доступ к данным из этой сессии будут проверяться именно для этой учетной записи.

[IMPORTANT]
====
Для выполнения операции с привилегиями другого пользователя необходимо явно указать его данные при создании сессии.
====

С точки зрения разработки, _пользовательская сессия_ -- экземпляр класса xref:api/DocsVision/Platform/ObjectManager/UserSession_CL.adoc[`UserSession`]), который создается следующим образом:

[source,csharp]
----
UserSession CreateUserSession()
{ <.>
 SessionManager sessionManager = SessionManager.CreateInstance();

 string connectionString = "ConnectAddress=http://{SERVERNAME}/DocsVision/StorageServer/StorageServerService.asmx;UserName={USERNAME};Password={PASSWORD}"; <.> <.>

 sessionManager.Connect(connectionString); <.>

 UserSession userSession = sessionManager.CreateSession(); <.>

 return userSession;
}
----
<.> Создаем экземпляр менеджера сессий.
<.> `SERVERNAME` -- имя сервера {dv}.
<.> `USERNAME` и `PASSWORD` -- данные учетной записи для подключения к серверу {dv}.
<.> Передаем менеджеру сессий параметры подключения к серверу (описание см. по ссылке).
<.> Создаем сессию пользователя.

.Чтобы использовать приведенные в коде типы, потребуется:
. Добавить в проект сборку Docsvision:
+
`DocsVision.Platform.ObjectManager.dll`.
+
Указанный DLL-файл входит в состав клиента и сервера Docsvision.
+
. Подключить пространство имен:
+
[source,csharp]
----
using DocsVision.Platform.ObjectManager;
----
+
В приведенном выше примере строка подключения к серверу содержит логин и пароль пользователя, если эти сведения не указываются, подключение будет выполнено от имени пользователя, запустившего программу. Полный список параметров соединения с сервером {dv} приведен в разделе xref:appendix/server-connection-parameters.adoc[Параметры соединения с сервером Docsvision].

Каждая пользовательская сессия обладает набором определённых параметров, значение которых устанавливается автоматическию Значение некоторых параметров можно изменить, но только на время работы в сессии. Значение определённого параметра пользовательской сессии можно получить из массива `UserSession.Properties`.

[NOTE]
====
Описание доступных параметров приведено в разделе xref:appendix/user-session-properties.adoc[Список свойств пользовательской сессии].
====

.Для работы с пользовательскими сессиями могут быть полезны два других метода _менеджера сессий_:
* `CloseSession(Guid)` -- принудительно закрывает любую пользовательскую сессию (требуются права администратора системы).
* `GetOpenSessions` -- возвращает список всех открытых сессий.
