= Создание нового экземпляра карточки

== Базовый API

_Менеджер карточек_ базового API предоставляет метод `CreateCardData` для создания новых экземпляров карточек определённого типа. В качестве примера, новый экземпляр _карточки файла с версиями_ может быть создан следующим образом:

[source,csharp]
----
CardData card = userSession.CardManager.CreateCardData(new Guid("6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3")); <.> <.>
----
<.> `userSession` -- xref:cards/connect-to-dv-server.adoc[пользовательская сессия].
<.> `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3` -- идентификатор карточки типа _Карточка файла с версиями_.

[NOTE]
====
Идентификатор типа карточки можно посмотреть в разделе xref:DM_StandartCards.adoc[Описание полей стандартной карточки], либо в схеме карточки, например, используя программу "CardManager" из комплекта "Resource Kit".
====

Если необходимо создать карточку с определённым идентификатором, можно воспользоваться соответствующей перегрузкой метода:

[source,csharp]
----
CardData card = userSession.CardManager.CreateCardData(new Guid("6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3"), newCardId); <.>
----
<.> `newCardId` -- идентификатор создаваемой карточки.

После создания экземпляра карточки, если необходимо, её данные могут быть изменены по аналогии с примером, приведенным в разделе xref:cards/edit-card.adoc[Изменение данных карточки]. Возможность изменения определённых данных карточки, а также тип этих данных определяются типом карточки, описание которых приведено в разделе xref:DM_StandartCards.adoc[Описание полей стандартной карточки].

== Объектная модель

API данного уровня не предлагает отдельного метода для создания нового экземпляра карточки. Данная задача распределена между преобразователем данных соответствующего типа карточки и xref:cards/connect-to-dv-server.adoc[сервисом] для работы с этим типом карточек.

[NOTE]
====
Полное описание _сервисов_, предоставляемых в рамках базовой поставки {dv}, было приведено в разделе xref:cards/general-information.adoc#services[Сервисы объектной модели], также можно обращаться к описанию интерфейсов сервисов в разделе xref:api/Intro.adoc[Библиотека классов].
====

Далее приведен пример использования методов для создания карточек типа документ и задание:

[source,csharp]
----
IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>
ITaskService taskService = objectContext.GetService<ITaskService>(); <.>

Document document = documentService.CreateDocument(); <.>

Task taks = taskService.CreateTask(); <.>

objectContext.AcceptChanges(); <.>
----
<.> Получаем из xref:cards/connect-to-dv-server.adoc[контекста объектов] два сервиса: для работы с документами и для работы с заданиями.
<.> Метод xref:api/DocsVision/Platform/ObjectModel/ObjectContext.GetService_MT.adoc[`GetService`] возвращает сервис по его интерфейсу.
<.> Создаем экземпляр карточки типа _Документ_.
<.> Создаем экземпляр карточки типа _Задание_.
<.> Сохраняем все изменения xref:cards/connect-to-dv-server.adoc[контекста объектов].

.Как видно из примера, типовой сценарий создания экземпляра карточки включает три шага:
. Получение сервиса для работы с карточками определённого типа.
. Вызов метода, отвечающего за создание карточки.
. Сохранение изменений методами `ObjectContext.AcceptChanges` или `ObjectContext.SaveObject`.

Перед сохранением данных, если необходимо, можно xref:cards/edit-card.adoc[изменить данные карточки].
