= Изменение данных карточки

Под изменением данных карточки обычно подразумевается изменение значения полей её секций, т.к. именно поля выступают основным хранилищем её данных. Последовательность доступа к полям карточки в этом случае абсолютно аналогична приведенной в xref:cards/get-section.adoc[Получение данных из секции карточки].

== Базовый API

.Изменение данных карточки в обычном режиме:
[source,csharp]
----
//
CardData card = userSession.CardManager.GetCardData(cardId); <.>

//
RowData sectionRow = card.Sections[sectionId].FirstRow; <.>

//
sectionRow["Field"] = "Новое значение поля"; <.>
----
<.> Получаем данные карточки с идентификатором `cardId`.
<.> В качестве примера получим первую строку секции с идентификатором `sectionId`.
<.> Изменяем содержимое поля с псевдонимом `Field`.

Если необходимо изменить значения нескольких полей, то предварительно рекомендуется активировать xref:dm_delayedchanges.adoc[режим отложенных изменений]:

[source,csharp]
----
CardData card = userSession.CardManager.GetCardData(cardId);

card.BeginUpdate(); <.>
RowData sectionRow = card.Sections[sectionId].FirstRow;

sectionRow["FieldFirst"] = "Новое значение первого поля"; <.>
sectionRow["FieldSecond"] = "Новое значение второго поля"; <.>

card.EndUpdate(); <.>
----
<.> Включаем режим отложенных изменений.
<.> Изменяем значение поля с псевдонимом `FieldFirst`.
<.> Изменяем значение поля с псевдонимом `FieldSecond`.
<.> Фиксируем изменения в базе данных.

Если в сценарии изменения данных предполагается изменение одного поля, то активировать режим отложенных изменений не требуется

== Объектная модель

На высоком уровне API сценарий изменения данных зависит от способа  xref:cards/get-section.adoc[представления секции] в объектной модели карточки.

Если сущность секции представлена в объектной модели карточки в виде свойства, то код изменяющий, к примеру, название карточки типа _Документ_ будет следующим:

[source,csharp]
----
Document card = objectContext.GetObject<Document>(cardId); <.>

card.MainInfo.Name = "Новое название документа";<.>

objectContext.SaveObject(card); <.>
----
<.> Получаем карточку типа _Документ_.
<.> Изменяем значение поля.
<.> Сохраняем изменения.

Если необходимо, вместо сохранения изменений одного объекта, можно сохранить все изменения контекста объектов:

[source,csharp]
----
objectContext.AcceptChanges();
----

Если объектная модель карточки не предоставляет непосредственного доступа к секции, можно воспользоваться методом `GetSection` базового класса xref:api/DocsVision/BackOffice/ObjectModel/BaseCard_CL.adoc[`BaseCard`]:

[source,csharp]
----
BaseCard baseCard = objectContext.GetObject<BaseCard>(cardId); <.>

BaseCardSectionRow row = (BaseCardSectionRow)baseCard.GetSection(new Guid("30EB9B87-822B-4753-9A50-A1825DCA1B74"))[0]; <.>

row["Name"] = "Новое название документа"; <.>

objectContext.SaveObject(row); <.>
----
<.> Получаем карточку.
<.> Получаем первую строку секции.
<.> Переданный идентификатор соответствует идентификатору секция `Основная информация` карточки типа _Документ_.
<.> Изменяем значение поля.
