= ITaskGroupService.CreateChildTaskGroup -- метод (Task, KindsCardKind, BaseCard, TaskList)

Создаёт новую подчиненную группу заданий.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroup CreateChildTaskGroup(Task parentTask, KindsCardKind kind, BaseCard parentCard, TaskList taskList)
----

Параметры::
parentTask:::
Тип: `xref:BackOffice-ObjectModel-Task:Task_CL.adoc[Task]`
+
Задание, в которое может быть добавлена группа. Может быть передан `null`, тогда группа заданий будет добавлена в `taskList`

kind:::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид группы заданий

parentCard:::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardKind_CL.adoc[KindsCardKind]`
+
Карточка, в которую будет добавлена группы заданий

taskList:::
Тип: `xref:BackOffice-ObjectModel-Task:TaskList_CL.adoc[TaskList]`
+
Список подписей, к которому будет прикреплена новая группа заданий

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Task:TaskGroup_CL.adoc[TaskGroup]`
+
Созданная группа заданий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `kind`, `parentCard` или `taskList`.
|===

== Примеры

Ниже приведён пример создания группы заданий в существующем документе

[source,csharp]
----
<.>

ITaskGroupService taskGroupService = objectContext.GetService<ITaskGroupService>(); <.>

KindsCardKind kind = objectContext.GetObject<KindsCardKind>(new Guid("6D76D0A7-5434-40F2-912E-6370D33C3151")); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

taskGroupService.CreateChildTaskGroup(null, kind, document, document.MainInfo.Tasks);
objectContext.AcceptChanges(); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса для работы с группой заданий.
<.> Получение вида группы заданий (например, "Группа заданий УД").
<.> Получение документа, в который будет добавлена группа заданий.
<.> Добавление группы заданий.
