= ITaskGroupService.AddDelegatePreset -- метод (TaskGroupPresets, StaffUnit)

Добавляет подразделение в число исполнителей в индивидуальные настройки исполнителя группы заданий.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroupPresetsDelegate AddDelegatePreset(TaskGroupPresets presets, StaffUnit unit)
----

Параметры::
presets:::
Тип: `xref:BackOffice-ObjectModel-Task:TaskGroupPresets_CL.adoc[TaskGroupPresets]`
+
Группа заданий

unit:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffUnit_CL.adoc[StaffUnit]`
+
Подразделение

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Task:TaskGroupPresetsDelegate_CL.adoc[TaskGroupPresetsDelegate]`
+
Индивидуальные настройки исполнителя группы заданий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `presets`.
|===
