= ITaskGroupService.SendToPerformance -- метод (TaskGroup, KindsCardKind, KindsCardKind)

Отправляет группу заданий на исполнение.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void SendToPerformance(TaskGroup taskGroup, KindsCardKind taskKind, KindsCardKind taskKindResponsiblePerformer)
----

Параметры::
taskGroup:::
Тип: `xref:BackOffice-ObjectModel:TaskGroup_CL.adoc[TaskGroup]`
+
Отправляемая на исполнение группа заданий

taskKind:::
Тип: `xref:BackOffice-ObjectModel:KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид заданий, отправляемых исполнителям

taskKindResponsiblePerformer:::
Тип: `xref:BackOffice-ObjectModel:KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид задания, отправляемого ответственному исполнителю

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `taskGroup`, `taskKind` или `taskKindResponsiblePerfomer`.
|===
