= ITaskGroupService.AddSelectedPerformer -- метод (TaskGroup, Guid)

Добавляет поисковое слово в число выбранных исполнителей группы заданий.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroupSelectedPerformer AddSelectedPerformer(TaskGroup routeStage, Guid searchWordId)
----

Параметры::
routeStage:::
Тип: `xref:BackOffice-ObjectModel-Task:TaskGroup_CL.adoc[TaskGroup]`
+
Группа заданий, в список выбранных исполнителей которой добавляется сотрудник

searchWordId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор поискового слова

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Task:TaskGroupSelectedPerformer_CL.adoc[TaskGroupSelectedPerformer]`
+
Выбранный исполнитель

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `routeStage`.
|===

== Заметки

Идентификаторы основных поисковых слов предоставляет класс `xref:BackOffice-ObjectModel-Services-Entities:Entities/PerformerSearchWordsManager_CL.adoc[PerformerSearchWordsManager]`.
