= ITaskGroupService.AddSelectedPerformer -- метод (TaskGroup, StaffUnit)

Добавляет подразделение в число выбранных исполнителей группы заданий.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroupSelectedPerformer AddSelectedPerformer(TaskGroup routeStage, StaffUnit unit)
----

Параметры::
routeStage:::
Тип: `xref:BackOffice-ObjectModel:TaskGroup_CL.adoc[TaskGroup]`
+
Группа заданий, в список выбранных исполнителей которой добавляется сотрудник

unit:::
Тип: `xref:BackOffice-ObjectModel:StaffUnit_CL.adoc[StaffUnit]`
+
Добавляемое подразделение

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:TaskGroupSelectedPerformer_CL.adoc[TaskGroupSelectedPerformer]`
+
Выбранный исполнитель

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `routeStage` или `unit`.
|===
