= ITaskGroupService.GetKindSettings -- метод (KindsCardKind)

Возвращает настройки вида группы заданий.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroupSetting GetKindSettings(KindsCardKind kind)
----

Параметры::
kind:::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид группы заданий, для которого получаем настройки

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Services-Entities:Entities/KindSetting/TaskGroupSetting_CL.adoc[TaskGroupSetting]`
+
Настройки вида

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `kind`.
|===

== Заметки

В данном случае имеются в виду настройки, которые были установлены в _справочнике видов карточек_ у вида группы заданий.
