= ITaskGroupService.AddDelegatePreset -- метод (TaskGroupPresets, StaffRole)

Добавляет роль в число исполнителей в индивидуальные настройки исполнителя группы заданий.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroupPresetsDelegate AddDelegatePreset(TaskGroupPresets presets, StaffRole role)
----

Параметры::
presets:::
Тип: `xref:BackOffice-ObjectModel-Task:TaskGroupPresets_CL.adoc[TaskGroupPresets]`
+
Группа заданий

role:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffRole_CL.adoc[StaffRole]`
+
Роль

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Task:TaskGroupPresetsDelegate_CL.adoc[TaskGroupPresetsDelegate]`
+
Индивидуальные настройки исполнителя группы заданий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `presets`.
|===
