= ITaskGroupService.AddSelectedPerformer -- метод (TaskGroup, StaffEmployee)

Добавляет сотрудника в список выбранных исполнителей группы заданий.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskGroupSelectedPerformer AddSelectedPerformer(TaskGroup routeStage, StaffEmployee employee)
----

Параметры::
routeStage:::
Тип: `xref:BackOffice-ObjectModel:TaskGroup_CL.adoc[TaskGroup]`
+
Группа заданий, в список выбранных исполнителей которой добавляется сотрудник

employee:::
Тип: `xref:BackOffice-ObjectModel:StaffEmployee_CL.adoc[StaffEmployee]`
+
Добавляемый сотрудник

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:TaskGroupSelectedPerformer_CL.adoc[TaskGroupSelectedPerformer]`
+
Выбранный исполнитель

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `routeStage` или `employee`.
|===

== Примеры

Ниже приведен пример добавления текущего сотрудника в список выбранных исполнителей группы заданий.

[source,csharp]
----
<.>

ITaskGroupService taskGroupService = objectContext.GetService<ITaskGroupService>();
IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

TaskGroup taskGroup = objectContext.GetObject<TaskGroup>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

TaskGroupSelectedPerformer selectedPerformer = taskGroupService.AddSelectedPerformer(taskGroup, staffService.GetCurrentEmployee()); <.>
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
<.> Получение сервисов.
<.> Получение группы заданий.
<.> Добавление исполнителя.
