= CardArchiveGroup

Помещает несколько карточек в архив.

[NOTE]
====
Карточки, у которых установлен запрет на архивирование (в метаданных типа карточки установлен флаг "Non-archival"), не могут быть архивированы.
====

== Запрос

[source,python]
----
POST /DocsVision/StorageServer/StorageServerService.asmx HTTP/1.1
Host: DOCSVISION_SERVER.COM
Content-Type: text/xml; charset=utf-8
Content-Length: length
SOAPAction: "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/CardArchiveGroup"

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <CardArchiveGroup xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <sessionId>guid</sessionId>
      <items>string</items>
      <options>int</options>
    </CardArchiveGroup>
  </soap:Body>
</soap:Envelope>
----

Параметры::
sessionId:::
Идентификатор пользовательской сессии
items:::
Идентификаторы архивируемых карточек
options:::
Флаг архивирования карточек. См. описание параметра options в `xref:webservice/cards/CardArchive.adoc[CardArchive]`

Строка `items` должна соответствовать формату элемента `GroupOperation`, приведенному в схеме `ServerRequests.xsd`:

[source,xml]
----
<xsd:element name="GroupOperation">
  <xsd:complexType>
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="Item">
        <xsd:complexType>
          <xsd:attribute name="ID" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
----

== Ответ

[source,python]
----
HTTP/1.1 200 OK
Content-Type: text/xml; charset=utf-8
Content-Length: length

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <CardArchiveGroupResponse xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <failedItems>string</failedItems>
    </CardArchiveGroupResponse>
  </soap:Body>
</soap:Envelope>
----

Ответ содержит идентификаторы карточек, которые не были перемещены в архив.

== Пример запроса

[source,python]
----
session.headers['SOAPAction'] = "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/CardArchiveGroup" <.>

body = """<?xml version="1.0" encoding="utf-8"?>
 <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
     <CardArchiveGroup xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
       <sessionId>1d29bba9-6c8c-e511-9417-90e6ba57b9f8</sessionId>
       <items>&lt;GroupOperation&gt;&lt;Item ID=&quot;DC35AB36-628C-E511-9417-90E6BA57B9F8&quot;/&gt;&lt;Item ID=&quot;D30BA878-578C-E511-9417-90E6BA57B9F8&quot;/&gt;&lt;/GroupOperation&gt;</items>
       <options>0</options>
     </CardArchiveGroup>
   </soap:Body>
 </soap:Envelope>""" <.>

response = session.post(url,  data=body) <.>
----
<.> Изменяем цель запроса в заголовке запроса.
<.> SOAP-сообщение.
<.> Отправляем SOAP-сообщение.
