= DVGate.ImportCardIntoFolder - метод (String, DVFolder, ProcessVariable)

Импортирует карточку из XML и создаёт ярлык.

* [.keyword]*Пространство имен:* xref:Gates_NS.adoc[DocsVision.Workflow.Gates]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Workflow.Gates.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public DVCard ImportCardIntoFolder(string cardXml, DVFolder folder, ProcessVariable outShortcut) 
----

cardXml::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  XML-документ с данными импортируемой карточки
folder::
  Тип: [.keyword .apiname]#DVFolder#
  +
  Папка для создания ярлыка
outShortcut::
  Тип: xref:../Runtime/ProcessVariable_CL.adoc[ProcessVariable]
  +
  Переменная процесса, в которую будет сохранен ярлык. Ярлык (тип [.keyword .apiname]#DVShortcut#) сохраняется в `outShortcut.Value`.

Возвращаемое значение

::
  Тип: [.keyword .apiname]#DVCard#
  +
  Импортированная карточка

*На уровень выше:* xref:../../../../api/DocsVision/Workflow/Gates/DVGate_CL.adoc[DVGate - класс]
