= DVGate.CreateDVFileFromFSFileInFolder - метод (FSFile, DVFolder, ProcessVariable)

Создает карточку версионного файла на основе файла, полученного из шлюза к файловой системе, и ярлык на карточку.

* [.keyword]*Пространство имен:* xref:Gates_NS.adoc[DocsVision.Workflow.Gates]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Workflow.Gates.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public DVFileCard CreateDVFileFromFSFileInFolder(FSFile File, DVFolder Folder, ProcessVariable OutShortcut)
----

Параметры

File::
  Тип: [.keyword .apiname]#FSFile#
  +
  Сущность файла, полученного через шлюз к файловой системе
Folder::
  Тип: [.keyword .apiname]#DVFolder#
  +
  Папка для размещения ярлыка
OutShortcut::
  Тип: xref:../Runtime/ProcessVariable_CL.adoc[ProcessVariable]
  +
  Переменная бизнес-процесса, в значение которой будет записан созданный ярлык. Если не требуется - передать null.

Возвращаемое значение

::
  Тип: [.keyword .apiname]#DVFileCard#
  +
  Карточка файла с версиями

*На уровень выше:* xref:../../../../api/DocsVision/Workflow/Gates/DVGate_CL.adoc[DVGate - класс]
