= DVGate.DeleteVariable - метод (Int32, String)

Удаляет переменную шлюза.

* [.keyword]*Пространство имен:* xref:Gates_NS.adoc[DocsVision.Workflow.Gates]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Workflow.Gates.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public void DeleteVariable(int Type, string ID)
----

Параметры

Type::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.int32.aspx[System.Int32]
  +
  Тип переменной шлюза: xref:DVVariableType_EN.adoc[DVVariableType.DOCUMENT], [.keyword .apiname]#DVVariableType.FILE#, [.keyword .apiname]#DVVariableType.DATAROW#, [.keyword .apiname]#DVVariableType.FOLDER#, [.keyword .apiname]#DVVariableType.SHORTCUT#, [.keyword .apiname]#DVVariableType.PRINCIPAL#, [.keyword .apiname]#DVVariableType.ROLE#, [.keyword .apiname]#DVVariableType.GROUP#, [.keyword .apiname]#DVVariableType.DEPARTMENT#
ID::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]
  +
  Идентификатор удаляемой переменной. В зависимости от типа удаляемой переменной, указываются: идентификатор карточки, файла, папки или ярлыка; идентификатор строки, соответствующей сотруднику, группе или роли.

*На уровень выше:* xref:../../../../api/DocsVision/Workflow/Gates/DVGate_CL.adoc[DVGate - класс]
