= IGate.GetVariableInternalReference -- метод (Int32, String)

Возвращает ссылку на переменную шлюза во внутреннем формате.

* *Пространство имён:* `xref:api/DocsVision/Workflow/Gates/Gates_NS.adoc[DocsVision.Workflow.Gates]`
* *Сборка:* `DocsVision.Workflow.Interfaces.dll`

== Синтаксис

[source,csharp]
----
object GetVariableInternalReference(int Type, string ID);
----

Параметры::
Type:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.int32.aspx[System.Int32]`
+
Тип переменной
ID:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Идентификатор переменной

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.object.aspx[System.Object]`
+
Ссылка

== Заметки

Идентификатор объекта, переданный в `ID`, не обязательно содержит действительный идентификатор объекта в целевой системе. К примеру, в шлюзе к {dv} при работе со строкой секции в `ID` содержатся идентификаторы карточки, секции и собственно строки. Метод GetVariableInternalReference в таком случае позволяет получить корректный идентификатор строки.
