= ISubscriptionChannel.Subscribe -- метод (Int32, Guid, Guid)

Выполняет подписку на событие шлюза Workflow.

* *Пространство имен:* xref:api/DocsVision/Workflow/Gates/Gates_NS.adoc[DocsVision.Workflow.Gates]
* *Сборка:* `DocsVision.Workflow.Interfaces.dll`

== Синтаксис

[source,csharp]
----
void Subscribe(int messageType, Guid processId, Guid functionId)
----

Параметры::
messageType:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.int32.aspx[System.Int32]
+
Тип события
processId:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
+
Идентификатор бизнес-процесса, из которого выполняется подписка
functionId:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
+
Идентификатор функции бизнес-процесса, которая выполняет подписку

== Заметки

Набор доступных типов событий индивидуален для каждого шлюза. Например, для шлюза к {dv}, разрешены подписки на следующие типы событий:

* изменение определенной карточки;
* изменение любой карточки определенного типа;
* разблокировка объекта;
* блокировка объекта.
