= AttributiveSearch - класс

Предоставляет методы для выполнения атрибутивного поиска.

* [.keyword]*Пространство имен:* xref:SearchModel_NS.adoc[DocsVision.Platform.ObjectManager.SearchModel]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public abstract class AttributiveSearch
----

== Свойства

[cols=",",options="header",]
|===
|Имя |Описание
|xref:AttributiveSearch.SearchQuery_PR.adoc[SearchQuery] |Возвращает экземпляр поискового запроса.
|xref:AttributiveSearch.CardTypeQueries_PR.adoc[CardTypeQueries] |Возвращает параметры поиска по типу карточки.
|===

== Заметки

Атрибутивный поиск позволяет осуществлять выборку по различным данным карточек.

== Примеры

[source,pre,codeblock,language-csharp]
----
const string ID_CARDTYPE = "{C1FED883-08DE-420F-8FB4-C16CEFFC1630}"; 
const string ID_SECTION = "{8C77892A-21CC-4972-AD71-A9919BCA8187}"; 
SearchQuery searchQuery = session.CreateSearchQuery(); 

// Поиск по типу карточки 
CardTypeQuery typeQuery = searchQuery.AttributiveSearch.CardTypeQueries.AddNew(new Guid(ID_CARDTYPE)); 

// Поиск по секции 
SectionQuery sectionQuery = typeQuery.SectionQueries.AddNew(new Guid(ID_SECTION)); 

//Поиск по значению поля 
sectionQuery.ConditionGroup.Conditions.AddNew("Name", FieldType.Unistring, ConditionOperation.StrEquals, "Doc1"); 

//Получение текста запроса 
string query = searchQuery.GetXml(true, null); 

//Выполнение запроса 
CardDataCollection coll = session.CardManager.FindCards(query);
----

* *xref:../../../../../api/DocsVision/Platform/ObjectManager/SearchModel/AttributiveSearch.CardTypeQueries_PR.adoc[AttributiveSearch.CardTypeQueries - свойство]* +
* *xref:../../../../../api/DocsVision/Platform/ObjectManager/SearchModel/AttributiveSearch.SearchQuery_PR.adoc[AttributiveSearch.SearchQuery - свойство]* +

*На уровень выше:* xref:../../../../../api/DocsVision/Platform/ObjectManager/SearchModel/SearchModel_NS.adoc[DocsVision.Platform.ObjectManager.SearchModel - пространство имен]
