= ICardHost.CreateCard - метод (Guid, Guid, ParameterCollection, Boolean)

Создает карточку, используя переданные параметры.

* [.keyword]*Пространство имен:* xref:CardHost_NS.adoc[DocsVision.Platform.CardHost]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.CardHost.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
Guid CreateCard(Guid creatorEntryId, Guid initialCardInstanceId, ParameterCollection parameters, bool showUI)
----

Параметры

creatorEntryId::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Идентификатор режима создания карточки из [.dfn .term]_справочника видов карточек_
initialCardInstanceId::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Идентификатор карточки, создающий карточку
parameters::
  Тип: xref:ParameterCollection_CL.adoc[ParameterCollection]
  +
  Параметры активации карточки
showUI::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  При true, после создания, карточка будет открыта на редактирование

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Идентификатор созданной карточки

== Заметки

Для корректной работы, метод необходимо вызвать из скрипта карточки.

Содержимое parameters зависит от типа создаваемой карточки, а точнее от принимаемых ею параметров.

*На уровень выше:* xref:../../../../api/DocsVision/Platform/CardHost/ICardHost_IN.adoc[ICardHost - интерфейс]
