= ICardHost.ActivateFolder -- метод (Guid, Boolean)

При переопределении в производном классе производит позиционирование курсора на указанной папке.

* *Пространство имён:* `xref:api/DocsVision/Platform/CardHost/CardHost_NS.adoc[DocsVision.Platform.CardHost]`
* *Сборка:* `DocsVision.Platform.CardHost.dll`

== Синтаксис

[source,csharp]
----
void ActivateFolder(Guid folderId, bool showSubfolders)
----

Параметры::
folderId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор папки, на которой будет выполнено позиционирование курсора
showSubfolders:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Зарезервированный параметр

== Заметки

Данный метод позволяет осуществить установку курсора на папке в приложении {wincl}. Может быть использован, к примеру, при реализации расширения {wincl}а.

== Примеры

Пример создания расширения {wincl}а, использующего данный метод, приведен в разделе xref:samples/use-api/cursor-on-folder.adoc[Позиционирование курсора на папке]
