= IReusableCardComponent - интерфейс

Определяет возможность переиспользования компонента карточки.

* *Пространство имен:* xref:api/DocsVision/Platform/CardHost/CardHost_NS.adoc[DocsVision.Platform.CardHost]
* *Сборка:* `DocsVision.Platform.CardHost.dll`

== Синтаксис

[source,csharp]
----
public interface IReusableCardComponent
----

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание
|xref:api/DocsVision/Platform/CardHost/IReusableCardComponent.CanBeReused_PR.adoc[CanBeReused] |Возвращает признак того, что компонент может быть переиспользован.
|xref:api/DocsVision/Platform/CardHost/IReusableCardComponent.Mode_PR.adoc[Mode] |Возвращает режим переиспользования компонента карточки.
|===

== Заметки

Переиспользуемый компонент кэшируется во внутреннем хранилище контейнера карточек и при следующем обращении (в т.ч. к карточке аналогичного типа) запрашивается из кэша, вместо повторного создания.

Если установлен режим [.keyword .apiname]#Mode.OwnLogic#, то контейнер карточек получает признак переиспользования компонента из переменной [.keyword .apiname]#CanBeReused#, если режим [.keyword .apiname]#Mode.CardHostLogic#, то необходимость переиспользования компонента определяется самим контейнером карточек, исходя из внутренней логики. В режиме [.keyword .apiname]#Mode.NoReusage# компонент не кэшируется, а создается каждый раз повторно.

Необходимость использования данной функциональности определяется разработчиком.

