= Разработка расширений Docsvision

Полноценный процесс кастомизации решения не может обойтись без создания дополнений в клиентской или серверной части продукта. Организации может потребоваться внести в интерфейс {wincl}а изменения не реализуемые в рамках объектной модели, например, возможность формирования файла экспорта определенного формата непосредственно из {wincl}а. Также, может потребоваться выполнять определенные методы в контексте сервера и с его привилегиями. Разработка расширений с использованием объектной модели {dv} не сложнее процесса разработки карточки, а преимущество такого похода, через создание плагинов, неоспоримо.

Методика разработки расширений для {wincl}а, во многом похожа на разработку карточек и описана в разделе xref:develop/dm_extension_navigator.adoc[Расширение {wincl}а].

Типы объектной модели, требующие реализации в процессе разработки серверных расширений, перечислены в разделе xref:develop/DM_ServerPlugins.adoc[Серверные расширения].

Раздел xref:develop/DM_ConsolePlugin.adoc[Модуль расширения Консоли настройки] освещает создание специфического компонента для Консоли настройки сервера Docsvision.

== См. далее

* xref:develop/dm_extension_navigator.adoc[Расширение {wincl}а]

.В данном разделе
* xref:develop/DM_ServerPlugins.adoc[Серверные расширения]
* xref:develop/DM_ConsolePlugin.adoc[Модуль расширения Консоли настройки]
