= Разработка компонента карточки

После завершения проектирования схемы данных карточки и загрузки её в базу данных {dv} необходимо разработать соответствующий программный компонент карточки.

[NOTE]
====
Карточка может и не иметь пользовательского интерфейса, например если она используется только в качестве хранилища данных для других карточек. В этом случае данный этап может быть пропущен.
====

Программный компонент карточки представляет собой элемент управления ActiveX, предоставляющий пользовательский интерфейс для работы с данными карточки. Элемент управления вызывается {wincl}ом при активации карточки ("открытии") или выполнении команд карточки.

.Можно выделить несколько типов программных компонент карточек:
* *Карточки документов* -- программные компоненты, реализующие только интерфейс для ввода и редактирования данных.
+
Типичными примерами карточек документов являются карточки библиотеки "{bo}": _Документ_, _Задание_ и другие.
+
* *Карточки справочников* -- программные компоненты, предназначенные для редактирования данных справочников.
+
Помимо средств для ввода и редактирования данных, предоставляют специальный интерфейс для выбора элементов справочника.
+
* *Карточки расширения* -- программные компоненты, реализующие расширения функциональности {wincl}а.
+
Например, при помощи карточек расширения можно реализовать специфические механизмы поиска, экспорта и импорта данных или интеграции с внешними системами.
+
* *Специализированные карточки* -- системные карточки, служебные компоненты или утилиты, предназначенные для использования в составе других карточек или реализации специфической функциональности.
+
К числу таких карточек можно отнести системную карточку файла, карточку _Список файлов_ из библиотеки "{bo}" и другие.

.Разработка программного компонента состоит из нескольких этапов:
* Реализация стандартных интерфейсов -- программирование кода карточки в соответствии со стандартами платформы {dv} для обеспечения её корректной работы в системе.
* Реализация пользовательского интерфейса -- включает в себя проектирование и реализацию вариантов взаимодействия кода карточки с пользователем, дизайн и расположение элементов управления на форме карточки.
* Реализация дополнительной функциональности -- дополнительные функции карточки, связанные с её назначением.
* Отладка и тестирование -- проверка корректной работы разработанного компонента в составе системы.

В качестве инструмента для создания карточки может быть использована любая среда программирования, позволяющая реализовывать компоненты стандарта ActiveX и осуществлять взаимодействие с COM-компонентами.

.Примерный перечень сред и языков, в которых может быть разработана карточка Docsvision:
[NOTE]
====
* Microsoft Visual Studio 6.0 (Visual Basic, Visual C++);
* Microsoft Visual Studio 2003, 2005, 2008, 2010 (VB.NET, C#);
* Borland Delphi и другие.

_В данном Руководстве примеры кода приведены для Microsoft .NET (C#)._
====
