= Фоновый поток исполнения бизнес-логики при открытии карточки

Базовый класс `xref:BackOffice-WinForms:BaseCardControl_CL.adoc[BaseCardControl]` содержит методы и события, которые позволяют вынести часть логики, исполняемой при открытии карточки, в отдельный поток. Данная возможность может быть востребована, к примеру, если необходимо дополнить процесс открытия карточки собственным алгоритмом, исполнение которого может занять продолжительное время.

Чтобы вынести исполнения дополнительной логики в отдельный поток достаточно переопределить два метода базового класса:

* `OnCardActivatedAsync` -- здесь размещается бизнес-логика карточки, которая должна быть выполнена в отдельном потоке.
* `OnCardActivatedAsyncCompleted` -- здесь может размещаться дополнительная функциональность, связанная с обновлением интерфейса.

[NOTE]
====
При реализации аналогичной логики в скрипте карточки (с использованием _конструктора разметок_), соответствующая логику привязывается к событиям `CardActivatedAsync` и `CardActivatedAsyncCompleted`.
====
