= INavReportExtension.CreateReport -- метод (Object, InfoRowCollection, Guid)

При переопределении в производном классе запускает механизм экспорта.

* *Пространство имён:* `xref:api/DocsVision/Platform/Extensibility/Extensibility_NS.adoc[DocsVision.Platform.Extensibility]`
* *Сборка:* `DocsVision.Platform.Extensibility.dll`

== Синтаксис

[source,csharp]
----
void CreateReport(object grid, InfoRowCollection rowCollection, Guid folderId)
----

Параметры::
grid:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.object.aspx[System.Object]
+
Ссылка на элемент управления JanusGrid, используемый для отображения данных представления в {wincl}е. Не рекомендуется записывать какие-либо данные непосредственно в JanusGrid или изменять его настройки -- это может привести к сбоям в работе {wincl}а.
rowCollection:::
Тип: xref:api/DocsVision/Platform/ObjectManager/InfoRowCollection_CL.adoc[InfoRowCollection]
+
Данные текущего представления
folderId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор текущей папки
