= Конструктор состояний

[cols=","]
|===
|Назначение
|Позволяет описать жизненный цикл карточки.

|Класс карточки
|xref:api/DocsVision/BackOffice/ObjectModel/StatesDictionary_CL.adoc[`DocsVision.BackOffice.ObjectModel.StatesDictionary`]
|===

Для работы с карточкой предназначен сервис xref:api/DocsVision/BackOffice/ObjectModel/Services/IStateService_IN.adoc[`IStateService`], с помощью которого можно работать с автоматом состояний. Он предоставляет возможность управления операциями, состояниями, ветвями перехода между состояниями и диаграммой состояний. Помимо этого, с помощью данного сервиса можно узнать, какие операции доступны для заданной карточки и в какое состояние её можно перевести.

.Доступные операции:
* Создание ветки перехода из одного состояния в другое.
* Создание операции для смены состояния.
* Создание состояния.
* Получение состояний доступности операций.
* Создание разметки диаграммы состояний.
* Поиск ветки перехода.
* Поиск операций.
* Поиск состояний.
* Получение объекта настройки прав для вида карточки.
* Получение списка операций для вида карточки.
* Получение списка ветвей перехода.
* Получение разметки диаграммы состояний.
* Получение списка состояний.
* Удаление объекта настройки прав для вида карточки.
* Локализация названия операции.
* Локализация названия состояния.
* Определение возможности удаления операции.

В примере выведем в консоль названия всех состояний для вида документа _Внутренний_

[source,csharp]
----
IStateService stateService = objectContext.GetService<IStateService>(); <.>

KindsCardKind kind = objectContext.GetObject<KindsCardKind>(new Guid("7db9044e-91b7-447d-8caa-5e5a4967b8d4")); <.>

IList<StatesState> states = stateService.GetStates(kind);
foreach (var item in states)
{
 Console.WriteLine(item.DefaultName); <.>
}
----
<.> Инициализация контекста объектов и получение сервиса для работы со справочником состояний.
<.> Получение вида документа _Внутренний_.
<.> Получение допустимых состояний для данного вида и вывод на консоль.

См. также пример из раздела xref:cards/bo-lib/task.adoc["Задание"]
