= ObjectMap -- класс

Поставляет данные для преобразователя данных.

* *Пространство имён:* `xref:api/DocsVision/Platform/ObjectModel/Mapping/Mapping_NS.adoc[DocsVision.Platform.ObjectModel.Mapping]`
* *Сборка:* `DocsVision.Platform.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public class ObjectMap
----

== Конструкторы

[cols=",",options="header"]
|===
|Имя |Описание
|`ObjectMap()` |Инициализирует новый экземпляр класса ObjectMap.
|===

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание
|`Collections` |Возвращает коллекцию секций.
|`Fields` |Возвращает коллекцию полей.
|`ObjectTypeId` |Задает или возвращает идентификатор регистрируемого объекта.
|`ParentObjectId` |Задает или возвращает идентификатор родительского, по отношению к регистрируемому, объекта.
|`References` |Возвращает коллекцию ссылочных полей карточки (для типа `refid`).
|===

== Методы

[cols=",",options="header"]
|===
|Имя |Описание
|`Collection(ObjectProperty, Guid)` |Связывает свойство с секцией.
|`Field(ObjectProperty, String)` |Связывает свойство с полем.
|`Reference(ObjectProperty, String)` |Связывает свойство со ссылочным полем карточки.
|===

== Примеры

Ниже приведен пример части преобразователя данных для карточки "Документ", в котором выполняется привязка идентификатора секции к свойству `Document.MainInfoProperty`

[source,csharp]
----
protected override ObjectMap GetObjectMap()
{
 ObjectMap objectMap = new ObjectMap();
 
 objectMap.ObjectTypeId = CardDocument.ID; <.>
 
 objectMap.Collection(Document.MainInfoProperty, CardDocument.MainInfo.ID); <.>
 return objectMap;
}
----
<.> Идентификатор объекта -- идентификатор карточки типа "Документ" (в нашем случает он уже статически присвоен объекту `CardDocument.ID`).
<.> Выполнение связки свойства `Document.MainInfoProperty` с секцией, имеющей идентификатор `CardDocument.MainInfo.ID` (статический, уже присвоен) .
