= ObjectMapperFactory -- класс

Базовый класс _фабрики преобразователей данных_.

* *Пространство имен:* xref:api/DocsVision/Platform/ObjectModel/Mapping/Mapping_NS.adoc[DocsVision.Platform.ObjectModel.Mapping]
* *Сборка:* `DocsVision.Platform.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public abstract class ObjectMapperFactory : IObjectMapperFactory
----

== Конструкторы

[cols=",",options="header"]
|===
|Имя |Описание
|ObjectMapperFactory(ObjectContext) |Инициализирует новый экземпляр класса ObjectMapperFactory с помощью указанного значения.
|===

== Методы

[cols=",",options="header"]
|===
|Имя |Описание
|GetObjectMapper(Type) |Возвращает _преобразователь данных_ указанного типа.
|RegisterObjectMapper(Type, Type) |Регистрирует новый _преобразователь данных_ в _фабрике преобразователей данных_
|===

== Примеры

В качестве примера приведена часть класса _SystemCardsMapperFactory_ (_фабрика преобразователей данных_ библиотеки "Системные карточки")

[source,csharp]
----
public sealed class SystemCardsMapperFactory : ObjectMapperFactory
{
 public SystemCardsMapperFactory(ObjectContext context) : base(context)
 {

  // Производится регистрация преобразователя данных для "Карточки папок"
  base.RegisterObjectMapper(typeof(Folders), typeof(FoldersMapper));
 }
}
----
