= AccessInfo -- класс

Результат проверки доступности операции для вида карточки и набора исполняемых ролей.

* *Пространство имён:* `xref:Platform-ObjectModel:ObjectModel_NS.adoc[DocsVision.BackOffice.ObjectModel]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public sealed class AccessInfo
----

== Конструкторы

[cols=",",options="header"]
|===
|Имя |Описание
|`xref:AccessInfo_CT.adoc[AccessInfo()]` |Инициализирует новый экземпляр класса `AccessInfo`.
|===

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание
|`xref:AccessInfo.Operations_PR.adoc[Operations]` |Возвращает список всех доступных для карточки операций и признак разрешения запуска согласно ролевой модели.
|`xref:AccessInfo.Roles_PR.adoc[Roles]` |Возвращает коллекцию ролей, у которых есть доступ к карточке.
|===

== Методы

[cols=",",options="header"]
|===
|Имя |Описание
|`xref:AccessInfo.Load_MT.adoc[Load(XmlReader)]` |Загружает параметры доступа из XML.
|`xref:AccessInfo.Save_MT.adoc[Save(XmlWriter)]` |Сохраняет параметры доступа в XML.
|===

== Примеры

Ниже приведён пример вывода в консоль информации по доступности операций документа с идентификатором `00000000-0000-0000-0000-000000000000`.

[source,csharp]
----
<.>

IServerExtensionProxyService iServerExtensionProxyService = objectContext.GetService<IServerExtensionProxyService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

string accessInfoString = iServerExtensionProxyService.GetAccessInfo(objectContext.GetObjectRef<Document>(document).Id,
 objectContext.GetObjectRef<KindsCardKind>(document.SystemInfo.CardKind).Id,
 objectContext.GetObjectRef<StatesState>(document.SystemInfo.State).Id); <.>

AccessInfo accessInfo = new AccessInfo();
accessInfo.Load(new XmlTextReader(new StringReader(accessInfoString))); <.>

foreach (var item in accessInfo.Operations) <.>
{
 string operationName = objectContext.GetObject<StatesOperation>(item.OperationId).LocalizedName;
 Console.WriteLine(string.Format("Operation {0} is {1}", operationName, item.Result)); <.>
}
----
<.> Инициализация контекста объектов.
<.> Получение необходимых сервисов.
<.> Получение документа.
<.> Получение прав в формате XML, статус и вид карточки забираем из самой карточки.
<.> Заполнение `AccessInfo` данными.
<.> Обрабатываем только операции.
<.> Получение локализованного названия операции, вывод в консоль вместе с признаком разрешения.
