= AccessInfoOperationResult -- перечисление

Определяет режим доступа к операции.

* *Пространство имён:* `xref:Platform-ObjectModel:ObjectModel_NS.adoc[DocsVision.BackOffice.ObjectModel]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public enum AccessInfoOperationResult
----

== Члены

[cols=",",options="header"]
|===
|Имя члена |Описание
|`None` |Не задан (не запрещен или разрешён).
|`Allowed` |Операция разрешена.
|`Denied` |Операция запрещена.
|===

== Заметки

`AccessInfoOperationResult` получает значение в результате загрузки информации по операциям методом `AccessInfoOperation.Load`, и может быть получен из свойства `AccessInfoOperation.Result`.

== Примеры

Ниже приведён пример получения `AccessInfoOperationResult` из информации по первой операции документа

[source,csharp]
----
<.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>
            
string accessInfoString = iServerExtensionProxyService.GetAccessInfo(objectContext.GetObjectRef<Document>(document).Id,
 objectContext.GetObjectRef<KindsCardKind>(document.SystemInfo.CardKind).Id,
 objectContext.GetObjectRef<StatesState>(document.SystemInfo.State).Id); <.>

AccessInfo accessInfo = new AccessInfo();
accessInfo.Load(new XmlTextReader(new StringReader(accessInfoString))); <.>

AccessInfoOperationResult result = accessInfo.Operations.FirstOrDefault().Result; <.>
----
<.> Инициализация контекста объектов.
<.> Получение документа.
<.> Получение прав в формате XML, статус и вид карточки забираем из самой карточки.
<.> Заполнение `AccessInfo` данными.
<.> Получение результата по первой операции.
