= ITaskService.CreateTask -- метод (KindsCardKind)

Создает новое задание указанного вида.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
Task CreateTask(KindsCardKind kind)
----

Параметры::
kind:::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид создаваемого задания

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Task:Task_CL.adoc[Task]`
+
Созданное задание

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `kind`.
|===

== Примеры

Ниже приведен пример создания нового задания вида "На исполнение".

[source,csharp]
----
<.>

ITaskService taskService = objectContext.GetService<ITaskService>();
IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

QueryObject query = new QueryObject(RefKinds.CardKinds.Name, "На исполнение");
KindsCardKind cardKind = objectContext.FindObject<KindsCardKind>(query); <.>

Task newTask = taskService.CreateTask(cardKind);
newTask.MainInfo.Name = newTask.Description = "Новое задание"; <.>

taskService.InitializeDefaults(newTask); <.>
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
<.> Получение сервисов.
<.> Получение вида На исполнение.
<.> Создание задания.
<.> Инициализация основных параметров задания.
