= ITaskService.AddSelectedPerformer -- метод (TaskMainInfo, StaffUnit)

Добавляет выбранного исполнителя задания в формате подразделения.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskSelectedPerformer AddSelectedPerformer(TaskMainInfo mainInfo, StaffUnit unit)
----

Параметры::
mainInfo:::
Тип: `xref:BackOffice-ObjectModel-Task:TaskMainInfo_CL.adoc[TaskMainInfo]`
+
Основная информация карточки

role:::
Тип: `xref:BackOffice-ObjectModel-Staff:StaffUnit_CL.adoc[StaffUnit]`
+
Подразделение

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Task:TaskSelectedPerformer_CL.adoc[TaskSelectedPerformer]`
+
Сущность выбранного исполнителя

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `mainInfo` или `unit`.
|===
