= ITaskService.CompleteTask -- метод (Task, String)

Завершает указанное задание.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BuiltInState CompleteTask(Task task, string comments)
----

Параметры::
task:::
Тип: `xref:BackOffice-ObjectModel-Task:Task_CL.adoc[Task]`
+
Задание

comments:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Комментарий к завершению задания

Возвращаемое значение::
Тип: `BackOffice-ObjectModel-BuiltIn:BuiltInState_CL.adoc[BuiltInState]`
+
Состояние завершения

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `task`.
|===

== Заметки

Данный метод завершает задание от имени владельца сессии; дополнительно требуется вызвать `xref:BackOffice-ObjectModel-Services-IStateService:IStateService.ChangeState_MT.adoc[IStateService.ChangeState]` для изменения фактического состояния карточки.

== Примеры

[source,csharp]
----
<.>

ITaskService taskService = objectContext.GetService<ITaskService>(); <.>

Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

BuiltInState state = taskService.CompleteTask(task, "Все документы получены"); <.>

IStateService stateService = objectContext.GetService<IStateService>();
stateService.ChangeState(task, stateService.FindStateByBuiltIn(state, task)); <.>
objectContext.AcceptChanges();    
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение задания.
<.> Завершение задания.
<.> Изменение состояния карточки.
