= ITaskService.AddLinkOnParentCard -- метод (Task, TaskSetting, BaseCard)

Добавляет в задание ссылку на родительскую карточку.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void AddLinkOnParentCard(Task task, TaskSetting taskSetting, BaseCard card)
----

Параметры::
task:::
Тип: `xref:BackOffice-ObjectModel:Task_CL.adoc[Task]`
+
Задание, в список ссылок которого будет добавлена ссылка на карточку

taskSetting:::
Тип: `xref:BackOffice-ObjectModel-Services-Entities:Entities/KindSetting/TaskSetting_CL.adoc[TaskSetting]`
+
Настройки вида задания

card:::
Тип: `xref:BackOffice-ObjectModel:BaseCard_CL.adoc[BaseCard]`
+
Карточка, на которую добавляется ссылка

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `task`, `taskSetting` или `card`.
|===

== Заметки

При добавлении в задание ссылки на карточку `card`, в самой карточке ссылка на задание не формируется.

== Примеры

[source,csharp]
----
<.>

ITaskService taskService = objectContext.GetService<ITaskService>(); <.>

Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000"));
BaseCard card = objectContext.GetObject<BaseCard>(new Guid("00000000-0000-0000-0000-000000000001")); <.>

TaskSetting taskSetting = taskService.GetKindSettings(task.SystemInfo.CardKind); <.>

taskService.AddLinkOnParentCard(task, taskSetting, card); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение карточек задание и его родительской карточки.
<.> Получение настроек вида задания.
<.> Добавление ссылки.
