= ITaskService.AddSelectedPerformer -- метод (TaskMainInfo, StaffRole)

Добавляет выбранного исполнителя задания в формате роли.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskSelectedPerformer AddSelectedPerformer(TaskMainInfo mainInfo, StaffRole role)
----

Параметры::
mainInfo:::
Тип: `xref:BackOffice-ObjectModel:TaskMainInfo_CL.adoc[TaskMainInfo]`
+
Основная информация карточки

role:::
Тип: `xref:BackOffice-ObjectModel:StaffRole_CL.adoc[StaffRole]`
+
Роль

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:TaskSelectedPerformer_CL.adoc[TaskSelectedPerformer]`
+
Сущность выбранного исполнителя

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `mainInfo` или `role`.
|===
