= ITaskService.VerifySignature -- метод (Task, BaseCardSignature, X509Certificate2, Boolean, IEnumerable<CardFieldSetting>)

Выполняет верификацию ЭЦП, установленной на полях карточки Задание, а также на Документах, связанных с заданием.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BaseCardSignatureVerification VerifySignature(Task task, BaseCardSignature signature, X509Certificate2 certificate, bool signDocument, IEnumerable<CardFieldSetting> fields)
----

Параметры::
task:::
Тип: `xref:BackOffice-ObjectModel-Task:Task_CL.adoc[Task]`
+
Задание, содержащий подписанные данные

signature:::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BaseCardSignature_CL.adoc[BaseCardSignature]`
+
Проверяемая подпись

certificate:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.security.cryptography.x509certificates.x509certificate2.aspx[System.Security.Cryptography.X509Certificates.X509Certificate2]`
+
Сертификат ЭЦП сотрудника, чей сертификат использовался при подписании

signDocument:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Параметр не проверяется

fields:::
Тип: `http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<CardFieldSetting>`
+
Коллекция полей типа `xref:BackOffice-ObjectModel-Services-Entities:Entities/KindSetting/CardFieldSetting_CL.adoc[CardFieldSetting]`, у которых должна быть проверена подпись. Список подписываемых полей задается в Справочнике видов карточек

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Services-Entities:Entities/BaseCardSignatureVerification_CL.adoc[BaseCardSignatureVerification]`
+
Результат проверки ЭЦП

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `task` или `signature`.
|===

== Примеры

[source,csharp]
----
using System.Linq;
using System.Windows.Forms.Design;

using DocsVision.BackOffice.ObjectModel;
using DocsVision.BackOffice.ObjectModel.Services;
using DocsVision.BackOffice.WinForms.Controls;
using DocsVision.Platform.ObjectModel;

namespace BackOffice
{
 public class CardTaskТестScript : CardTaskНа_ознакомлениеScript
 {
  private void VerifySignature_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
  {
   ObjectContext objectContext = base.CardControl.ObjectContext;
   Task task = (base.BaseObject as Task);

   ITaskService taskService = objectContext.GetService<ITaskService>();
   IUIService uiService = objectContext.GetService<IUIService>(); <.>

   bool cancel = false;

   var certificate = SelectCertificateForm.SelectCertificate(ref cancel, base.CardControl.ObjectContext);
   if (cancel) return; <.>

   var taskSetting = taskService.GetKindSettings(task.SystemInfo.CardKind); <.>

   var signatureSetting = taskSetting.OperationSignatures.First(t => t.SignatureName = "SignOperation"); <.>

   BaseCardSignature lastSignature = task.MainInfo.SignatureList.Signatures.Last(); <.>

   var result = taskService.VerifySignature(task, lastSignature, certificate, true, signatureSetting.Fields); <.>

   if (result.IsValid) <.>
   {
    uiService.ShowMessage("Задание является надежным");
   } else {
    uiService.ShowError("Задание не является надежным");
   }
  }
 }
}
----
<.> Получение сервисов для работы с заданиями и интерфейсом пользователя.
<.> Получение сертификата.
<.> Получение настроек вида карточки.
<.> Получение настроек (с названием `SignOperation`) подписания операции, которые определены в Справочнике видов карточек
+
При проверке подписей установленных на поля карточки, будет использован список полей из настроек.
+
<.> Получение последней установленной подписи.
<.> Проверка подписи.
<.> Оповещение пользователя о результате проверки ЭЦП.
