= ITaskService.AddDelegatePreset -- метод (Task, StaffEmployee)

Добавляет сотрудника в список делегатов, выбираемых из задания, при делегировании задания вручную.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
TaskPresetDelegate AddDelegatePreset(Task task, StaffEmployee employee)
----

Параметры::
task:::
Тип: `xref:BackOffice-ObjectModel-Task:Task_CL.adoc[Task]`
+
Задание, в которое добавляется настройка выбора делегата

employee:::
Тип: `xref:xref:BackOffice-ObjectModel-Staff:StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудник для делегирования задания

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Task:TaskPresetDelegate_CL.adoc[TaskPresetDelegate]`
+
Настройки делегирования

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `task`.
|===
