= ITaskService.CreateChildTask -- метод (Task, KindsCardKind, BaseCard, TaskList)

Создаёт дочернее задание.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
Task CreateChildTask(Task parentTask, KindsCardKind kind, BaseCard parentCard, TaskList parentCardTaskList)
----

Параметры::
parentTask:::
Тип: `xref:BackOffice-ObjectModel-Task:Task_CL.adoc[Task]`
+
Основное задание

kind:::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид создаваемого задания

parentCard:::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Родительская карточка

parentCardTaskList:::
Тип: `xref:BackOffice-ObjectModel-Task:TaskList_CL.adoc[TaskList]`
+
Список подчинённых заданий из родительской карточки

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Task:Task_CL.adoc[Task]`
+
Подчиненное задание

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `kind`, `parentCard` или `parentCardTaskList`.
|===

== Примеры

[source,csharp]
----
<.>

ITaskService taskService = objectContext.GetService<ITaskService>(); <.>

Task parentTask = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

Task childTask = taskService.CreateChildTask(parentTask, parentTask.SystemInfo.CardKind, parentTask, parentTask.MainInfo.ChildTaskList); <.>
childTask.MainInfo.Name = "Подчиненное задание";
objectContext.AcceptChanges();
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение основного задания.
<.> Создание дочернего задания.
