= IReusableCardComponent -- интерфейс

Определяет возможность повторного использования компонента карточки.

* *Пространство имён:* `xref:CardHost/CardHost_NS.adoc[DocsVision.Platform.CardHost]`
* *Сборка:* `DocsVision.Platform.CardHost.dll`

== Синтаксис

[source,csharp]
----
public interface IReusableCardComponent
----

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание
|`xref:CardHost/IReusableCardComponent.CanBeReused_PR.adoc[CanBeReused]` |Возвращает признак того, что компонент может быть повторно использован.
|`xref:CardHost/IReusableCardComponent.Mode_PR.adoc[Mode]` |Возвращает режим повторного использования компонента карточки.
|===

== Заметки

Повторно используемый компонент кэшируется во внутреннем хранилище контейнера карточек и при следующем обращении (в т.ч. к карточке аналогичного типа) запрашивается из кэша, вместо повторного создания.

Если установлен режим `Mode.OwnLogic`, то контейнер карточек получает признак повторного использования компонента из переменной CanBeReused, если режим `Mode.CardHostLogic`, то необходимость повторного использования компонента определяется самим контейнером карточек, исходя из внутренней логики. В режиме `Mode.NoReusage` компонент не кэшируется, а создается каждый раз повторно.

Необходимость использования данной функциональности определяется разработчиком.
