= IADSynchronizationSettings -- интерфейс

Определяет в производном классе параметры синхронизации с доменом.

* *Пространство имен:* xref:api/DocsVision/BackOffice/ObjectModel/Services/Entities/ActiveDirectory/ADSync/ADSync_NS.adoc[DocsVision.BackOffice.ObjectModel.Services.Entities.ActiveDirectory.ADSync]
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public interface IADSynchronizationSettings
----

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание
|CreateFolders |Возвращает признак создания папок.
|DeleteItems |Возвращает признак возможности удаления объектов.
|LoadCertificates |Возвращает признак необходимости загрузки сертификатов.
|LoadDisabled |Возвращает признак загрузки заблокированных учетных записей.
|NotCheckDomain |Возвращает признак отмены проверки домена сотрудников.
|SynchronizationMode |Возвращает направление синхронизации.
|SynchronizeChildren |Возвращает признак необходимости синхронизации дочерних объектов.
|SynchronizeDepartments |Возвращает признак необходимости синхронизации подразделений.
|SynchronizeGroups |Возвращает признак необходимости синхронизации групп.
|SynchronizeNewMoved |Возвращает признак добавления и переноса объектов.
|SynchronizeRoles |Возвращает признак необходимости синхронизации ролей.
|===

== Примеры

Ниже приведен пример реализованного класса, которым предусмотрена синхронизация исключительно подразделений в справочнике {dv} информацией, полученной из Active Directory

[source,csharp]
----
class SynchronizationDepartmentsSettings : IADSynchronizationSettings
{
 public bool CreateFolders { get { return false; } }
 public bool DeleteItems { get { return false; } }
 public bool LoadCertificates { get { return false; } }
 public bool LoadDisabled { get { return false; } }
 public bool NotCheckDomain { get { return false; } }

 public ADSynchronizationMode SynchronizationMode
 {
  get { return ADSynchronizationMode.FromADToDictionary; } //Задаем направление в Справочник сотрудников
 }
 public bool SynchronizeChildren { get { return false; } }

 public bool SynchronizeDepartments
 {
  get { return true; } // Разрешаем синхронизировать подразделения
 }
 public bool SynchronizeGroups { get { return false; } }

 public bool SynchronizeNewMoved
 {
  get { return true; } // Разрешаем создание и перемещение объектов
 }
 public bool SynchronizeRoles { get { return false; } }
}
----
