= Управление режимом загрузки данных и кэширование

Режим загрузки данных устанавливается для всех секций карточки на этапе создания её схемы, но может быть переопределен свойствами: xref:api/DocsVision/Platform/ObjectManager/CardData_CL.adoc[CardData.FetchMode] (действует на всю карточку) и xref:api/DocsVision/Platform/ObjectManager/SectionData_CL.adoc[SectionData.FetchMode] (действует на конкретную секцию).

В приведенном примере Схема карточки определяет механизм загрузки её данных из базы данных, Схема карточки определяет режим загрузки её данных из базы данных. Для сценариев, связанных с получением данных карточки, актуально такое понятие, как режим загрузки данных, который определяет порцию информации, загружаемой с сервера {dv}, за одно обращение. Режим загрузки может иметь одно из следующих значений (см. описание перечисления xref:api/DocsVision/Platform/ObjectManager/Metadata/FetchMode_EN.adoc[FetchMode]):

* Card -- будут загружены данные всех секций карточки (актуально только для карточки в целом);
* Section -- при обращении к какой либо строке секции будут загружены все её строки, в т.ч. данные её подсекций;
* SubSection -- будут загружены данные одной подсекции, к которой идет обращение;
* Level -- будут загружен данные только запрашиваемого уровня иерархической секции.

Для повышения производительности данные читаются не по одной строке, а блоками -- уровнями или подсекциями. Сделано это по вполне очевидным соображениям: задержки на передачу данных содержат в себе константу -- стоимость сетевого вызова. Таким образом, иногда выгоднее получить больше данных за один раз, чем несколько раз обращаться к серверу за маленькими порциями. С другой стороны, могут существовать карточки, которые содержат сотни тысяч строк (например, справочники). Попытка загрузить все данные такой карточки за один вызов приведёт к чрезмерной задержке, поэтому в такой ситуации более оптимальным было бы получать данные несколькими мелкими порциями, по мере их востребованности.

Режим загрузки данных определяется для всей карточки в целом на этапе создания схемы данных в программе "CardManager" (входит в Resource Kit) и распространяется на все её секции. Однако, в режиме исполнения (runtime) разработчик может переопределить это поведение (для карточки или для конкретных секций). Для этого служит свойство FetchMode объектов xref:api/DocsVision/Platform/ObjectManager/CardData_CL.adoc[CardData] и xref:api/DocsVision/Platform/ObjectManager/SectionData_CL.adoc[SectionData].

[NOTE]
====
Режим построчной загрузки (FetchMode.Row) в данный момент не реализован. Однако получить данные для отдельных строк все же можно -- для этого у объекта SectionData есть набор методов, работающих с одиночной строкой. Их использование позволяет не загружать на клиента ненужную информацию, что, конечно же, предпочтительнее с точки зрения производительности.
====

В зависимости от того к каким данным карточки требуется доступ, можно выделить несколько объектов реализующих его:

* xref:api/DocsVision/Platform/ObjectManager/CardData_CL.adoc[CardData] -- точка входа к основным данным карточки (контейнеру);
* xref:api/DocsVision/Platform/ObjectManager/SectionData_CL.adoc[SectionData] -- доступ к секциям карточки;
* xref:api/DocsVision/Platform/ObjectManager/SubSectionData_CL.adoc[SubSectionData] -- доступ к подсекциям карточки;

== Кэширование данных

Говоря про загрузку данных, нельзя не упомянуть про кэширование. В *ObjectManager* имеется кэш на чтение и, таким образом, повторное чтение строк вернёт уже загруженные данные. При этом надо понимать, что строки в кэше могли быть изменены на сервере, а это может привести к тому, что на клиенте окажутся неактуальные данные. Для этого в ObjectManager предусмотрен механизм обновления строк:

* Явный -- у всех объектов есть метод Refresh (возможно, с параметрами), с помощью которого можно обновить данные вручную;
* Неявный -- при получении карточки (xref:api/DocsVision/Platform/ObjectManager/CardData_CL.adoc[CardData]) производится проверка наличия данных карточки в кэше. Если данные есть, но они потеряли актуальность (на сервере произошло изменение строки, принадлежащей карточке) -- вызывается процедура обновления.

Неявный характер обновления данных во втором случае нужно всегда иметь в виду и избегать частого переполучения данных карточки, так как в этом случае всегда производится серверный вызов — обновляется информация о статусе карточки (естественно, если такая карточка уже получалась ранее).

Существует также возможность очистить весь кэш одним вызовом – для этого предназначен метод PurgeCache экземпляра xref:api/DocsVision/Platform/ObjectManager/CardManager_CL.adoc[CardManager].

== См. также

* xref:development-manual/dm_delayedchanges.adoc[Режим отложенных изменений]
