= Создание нового экземпляра карточки

== Базовый API

_Менеджер карточек_ базового API предоставляет метод CreateCardData для создания новых экземпляров карточек определенного типа. В качестве примера, новый экземпляр _карточки файла с версиями_ может быть создан следующим образом:

[source,csharp]
----
CardData card = userSession.CardManager.CreateCardData(new Guid("6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3"));
----

Здесь:

* userSession -- xref:development-manual/connect-to-dv-server.adoc[пользовательская сессия];
* 6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3 -- идентификатор карточки типа _Карточка файла с версиями_.

[NOTE]
====
Идентификатор типа карточки можно посмотреть в разделе xref:DM_StandartCards.adoc[Описание полей стандартной карточки], либо в схеме карточки, например, используя программу "CardManager" из комплекта Resource Kit.
====

Если необходимо создать карточку с определенным идентификатором, можно воспользоваться соотвествующей перегрузкой метода:

[source,csharp]
----
// newCardId -- идентификатор создаваемой карточки
CardData card = userSession.CardManager.CreateCardData(new Guid("6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3"), newCardId);
----

После создания экземпляра карточки, если необходимо, её данные могут быть изменены по аналогии с примером, приведенным в разделе xref:development-manual/dm_operations_editcard.adoc[Изменение данных карточки]. Возможность изменения определенных данных карточки, а также тип этих данных определяются типом карточки, описание которых приведено в разделе xref:DM_StandartCards.adoc[Описание полей стандартной карточки].

== Объектная модель

API данного уровня не предлагает отдельного метода для создания нового экземпляра карточки. Данная задача распределена между преобразователем данных соответствующего типа карточки и сервисом для работы с этим типом карточек (понятие преобразователя и сервиса приведено в разделе xref:development-manual/connect-to-dv-server.adoc[Подключение к серверу Docsvision]).

[NOTE]
====
Полное описание _сервисов_, предоставляемых в рамках базовой поставки {dv}, было приведено в разделе xref:development-manual/general-information.adoc#services[Сервисы объектной модели], также можно обращаться к описанию интерфейсов сервисов в разделе xref:api/Intro.adoc[Библиотека классов].
====

Далее приведен пример использования методов для создания карточек типа документ и задание:

[source,csharp]
----
// Получаем из контекста объектов два сервиса: для работы с документами и для работы с заданиями
IDocumentService documentService = objectContext.GetService<IDocumentService>();
ITaskService taskService = objectContext.GetService<ITaskService>();

// Создаем экземпляр карточки типа Документ
Document document = documentService.CreateDocument();

// Создаем экземпляр карточки типа Задание
Task taks = taskService.CreateTask();

// Сохраняем все изменения контекста объектов
objectContext.AcceptChanges();
----

Здесь:

* objectContext -- xref:development-manual/connect-to-dv-server.adoc[контекст объектов];
* Метод xref:api/DocsVision/Platform/ObjectModel/ObjectContext.GetService_MT.adoc[GetService] возвращает сервис по его интерфейсу.

Как видно из примера, типовой сценарий создания экземпляра карточки включает три шага:

. Получение сервиса для работы с карточками определенного типа.
. Вызов метода, отвечающего за создание карточки.
. Сохранение изменений методами ObjectContext.AcceptChanges или ObjectContext.SaveObject.

Перед сохранением данных, если необходимо, можно изменить данные карточки (см. xref:development-manual/dm_operations_editcard.adoc[Изменение данных карточки]).

== См. далее

* xref:development-manual/dm_operations_deleteobject.adoc[Удаление объектов]
