= Получение экземпляра карточки из базы данных

Платформа {dv} предоставляет несколько способов получения карточки: её можно запросить по уникальному идентификатору (в формате http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[Guid]), либо получить из результата работы поискового запроса (будет рассмотрено в разделе xref:development-manual/dm_search.adoc[Поиск]). В данном разделе рассмотрен первый способ, для которого необходимо знать идентификатор получаемой карточки. Идентификатор карточки может быть получен, как минимум, двумя способами:

* Значение можно посмотреть в свойствах карточки в Windows-клиенте, где идентификатор приведен в строке *Ссылка*.
* Найти карточку при помощи программы "Docsvision Explorer". Идентификатор указан в строке *Selected card ID*.

== Базовый API

Получить данные карточки методами базового API можно следующим образом:

[source,csharp]
----
CardData card = userSession.CardManager.GetCardData(cardId)
----

Здесь:

* userSession -- пользовательская сессия (см. xref:development-manual/connect-to-dv-server.adoc[Подключение к серверу Docsvision]);
* CardManager -- _менеджер карточек_, в котором собрана основная функциональность базового API для работы с карточками (см. описание типа xref:api/DocsVision/Platform/ObjectManager/CardManager_CL.adoc[CardManager]);
* cardId -- идентификатор запрашиваемой карточки. Обычно (как и GetCardData) методы принимают идентификаторы, приведенные к типу http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]:
+
[source,pre,codeblock]
----
Guid cardId = new Guid("00000000-0000-0000-0000-000000000000");
----

После получения данных карточки, можно:

* xref:development-manual/dm_operations_getsection.adoc[получить данные из её секций];
* xref:development-manual/dm_cardlock.adoc[установить или снять блокировку];
* xref:development-manual/dm_cardarchive.adoc[отправить карточку в архив или извлечь из архива];
* xref:development-manual/dm_exportimportprint.adoc[экспортировать данные карточки в формате XML в файл];
* xref:development-manual/dm_downloadmode.adoc[при необходимости изменить режим чтения данных].

[NOTE]
====
Полный список доступных методов и свойств см. в описании типа xref:api/DocsVision/Platform/ObjectManager/CardData_CL.adoc[CardData].
====

== Объектная модель

Для получения данных карточки, а точнее её объектной модели, _контекст объектов_ предоставляет метод GetObject, который может быть вызван следующим образом:

[source,csharp]
----
BaseCard card = objectContext.GetObject<BaseCard>(cardId);
----

Здесь:

* objectContext -- проинициализированный _контекст объектов_ (см. xref:development-manual/connect-to-dv-server.adoc[Подключение к серверу Docsvision]);
* BaseCard -- класс объектной модели карточки. Здесь использован базовый класс карточек библиотеки _{bo}_. В любом случае указываемый тип должен быть наследником типа xref:api/DocsVision/Platform/ObjectModel/ObjectBase_CL.adoc[ObjectBase] -- базовый класс для всех сущностей данного уровня API.
+
[NOTE]
====
Список классов объектных моделей карточек библиотеки _{bo}_ приведен в подразделе xref:development-manual/dm_baseobjectscards.adoc[Библиотека карточек 'Базовые объекты'].
====
* cardId -- идентификатор запрашиваемой карточки.

[NOTE]
====
Метод GetObject достаточно универсален и может вернуть из _контекста объектов_ любой объект, для которого разработана объектная модель и в контексте объектов зарегистрирован _преобразователь данных_ (будет рассмотрен позднее).
====

После получения объектной модели карточки, можно:

* xref:development-manual/dm_operations_getsection.adoc[получить данные из её секций], если класс объектной модели карточки был унаследован от класса BaseCard или его потомком. Если класс карточки наследуется напрямую от ObjectBase, то функциональность получения данных секций потребуется реализовать самостоятельно.
* получить объектную модель секций, если это предусмотрено объектной моделью карточки;
+
[NOTE]
====
Объектная модель секции карточки, а точнее её строк, позволяется работать с секцией как с объектом, обладающим набором определенных свойств, представляющих поля карточки. Это отличает данный способ от ранее приведенного, идеология которого ближе к принципам работы с секциями в базовом API, при которых необходимо знать идентификаторы секций и точные названий полей.
====

== См. далее

* xref:development-manual/dm_operations_getsection.adoc[Получение данных из секции карточки]
