= Удаление объектов

Платформа {dv} позволяет удалять не только карточки, но и отдельные строки их секций. Для этого каждый уровень API предлагает собственные методы.

== Удаление объекта методами базового API

Для удаления экземпляра карточки на уровне базового API предназначен метод DeleteCard _менеджера карточек_, принимающий идентификатор удаляемой карточки:

[source,csharp]
----
userSession.CardManager.DeleteCard(cardId);
----

Здесь:

* userSession -- пользовательская сессия.
* cardId -- идентификатор удаляемой карточки.

Приведенный выше код удаляет карточку без возможности восстановления, при этом другая перегрузка метода позволяет пометить карточку как удаленную (в Windows-клиенте отображается курсивом) без фактического удаления:

[source,csharp]
----
// Для возможности восстановления второй параметр должен иметь значение false
userSession.CardManager.DeleteCard(cardId, false);
----

Для восстановления карточки, помеченной к удалению используйте метод RestoreCard:

[source,csharp]
----
userSession.CardManager.RestoreCard(cardId);
----

Чтобы удалить строку из секции карточки необходимо использовать метод DeleteRow сущности секции. В качестве примера, удалим первую строку из секции карточки:

[source,csharp]
----
// Получаем карточку, из которой удаляется строка
CardData card = userSession.CardManager.GetCardData(cardId);

// Получаем сущность секции
SectionData section = card.Sections[sectionId];

// Получаем идентификатор первой строки
Guid firstRowId = section.FirstRow.Id;

// Выполняем удаление
section.DeleteRow(firstRowId);
----

Здесь:

* sectionId -- идентификатор секции, из которой удаляет строка. Для получения идентификатора секции стандартных карточек обратитесь к разделу xref:DM_StandartCards.adoc[Описание полей стандартной карточки].

Обычно заранее известен идентификатор удаляемой строки, поэтому фактически удаление можно привести к виду:

[source,csharp]
----
card.Sections[sectionId].DeleteRow(rowId);
----

== Удаление объекта на уровне объектной модели

Данный уровень API предлагает использовать для удаления объектов единый метод контекста объектов -- xref:api/DocsVision/Platform/ObjectModel/ObjectContext.DeleteObject_MT.adoc[DeleteObject]. В качестве примера его применения, удалим один из файлов документа (карточка типа Документ):

[source,csharp]
----
// Получаем карточку типа Документа
Document document = objectContext.GetObject<Document>(cardId);

// Для простоты, выбираем для удаления первый файл по списку
DocumentFile file = document.Files.First();

// Удаляем файл и сохраняем изменения
objectContext.DeleteObject(file);
objectContext.AcceptChanges();
----

Данный код фактически выполняет удаление строки из секции "Файлы" карточки _Документ_, по аналогии с рассмотренным выше примером для базового API. Аналогичным образом может быть удален и сам документ.

Метод DeleteObject удаляет объект без возможности восстановления. Если требуется пометить карточку как удаленную, используйте базовый API.

Контекст объектов предлагает функциональность по отмене изменений объекта до его сохранения (вызова метода AcceptChanges или SaveObject), основанную на использовании методов RollbackChanges и RollBackObject (см. xref:development-manual/dm_delayedchanges.adoc[Режим отложенных изменений]).

== См. далее

* xref:development-manual/dm_cardlock.adoc[Блокировка и снятие блокировки]
