= События элемента управления файлами документа

Элемент управления файлами документа реализует интерфейс xref:api/DocsVision/BackOffice/Cards/CardDocument/IFilesViewWithPreview_IN.adoc[IFilesViewWithPreview], который добавляет подписку на события:

* BeforeFileOpened, AfterFileOpened -- перед/после открытия файла (основного или дополнительного);
* BeforeMainFileAdded, MainFileAdded -- перед/после добавления основного файла;
* BeforeAdditionalFileAdded, AdditionalFileAdded -- перед/после добавления дополнительного файла;
* BeforeMainFileRemoved, MainFileRemoved -- перед/после удаления основного файла;
* BeforeAdditionalFileRemoved, AdditionalFileRemoved -- перед/после удаления дополнительного файла;
* MainFileSelected -- при выборе основного файла;
* AdditionalFileSelected -- при выборе дополнительного файла;
* DocumentUnlocking, DocumentUnlocked -- перед/после снятия блокировки с файла (основного или дополнительного).

Для подписки на событие в скрипте карточки, достаточно получить из компонента карточки элемент управления файлами, возвращаемый из свойства FilesViewWithPreview. К примера подпишемся на событие, вызываемое перед открытием любого файла:

[source,csharp]
----
// Указываем дополнительные пространства имен
using DocsVision.BackOffice.ObjectModel.Services.Entities;
using DocsVision.BackOffice.Cards.CardDocument;


/* часть кода пропущена */

// Подписываемся на события элемента управления при активации карточки
private void CardDocument_CardActivated(System.Object sender, DocsVision.Platform.WinForms.CardActivatedEventArgs e) {

 // Приводим тип компонента карточки к типу компонента карточки Документ
 var documentCardControl = this.CardControl as DocsVision.BackOffice.Cards.CardDocument.MainControl;
 if (documentCardControl.FilesViewWithPreview != null) {
  // Получаем элемент управления файлами
  IFilesViewWithPreview filesViewWithPreview = documentCardControl.FilesViewWithPreview;

  // Подписываемся на событие перед открытием файла 
  filesViewWithPreview.BeforeFileOpened += new EventHandler<DocumentOpenFileEventArgs>(FilesViewWithPreview_BeforeFileOpened);
 }
}

private void FilesViewWithPreview_BeforeFileOpened(object sender, DocumentOpenFileEventArgs e) {
 if (e.File.FileType = DocumentFileType.Main) {
  MessageBox.Show("Открытие файла прервано");
  
  // Прерываем открытие
  e.Cancel = true;
 }
}
----

[NOTE]
====
[.note__title]#Прим.:# Чтобы пример заработал нужно подключить дополнительную сборку: DocsVision.BackOffice.Cards.dll
====

В обработчиках событий, срабатывающих до исполнения соответствующей команды, можно добавить логику прерывания команды -- установить e.Cancel в значение true.
