= Клиентская фильтрация

Клиентская фильтрация позволяет осуществить выборку строк с использованием XPath-выражений. Её имеет смысл применять в тех случаях, когда данные уже загружены на клиента и выполнять серверный поиск нет необходимости.

Фильтрация поддерживается для данных секций (SectionData и SubSectionData), а также для произвольных коллекций строк (RowDataCollection#).

Выражения для поиска строятся стандартным для XPath способом (описание синтаксиса XPath-запросов можно найти в http://www.w3.org/TR/xpath[оригинальном стандарте], в http://msdn2.microsoft.com/en-us/library/ms256115.aspx[MSDN] или в http://www.raleigh.ru/XML/w3schools/xpath/[специализированных изданиях]).

В качестве элементов XPath-запроса могут выступать поля секции, по которой осуществляется поиск (как собственные поля секции, так и связанные поля секций других карточек). Полный перечень этих полей для стандартных типов карточек можно посмотреть:

* при помощи утилиты "CardManager" (входит в Resource Kit), открыв схему соответствующей карточки (схемы всех базовых типов карточек входят в состав пакета разработчика);
* в документе "Описание полей стандартных карточек" (входит в состав пакета разработчика).

Другим простым способом, который может помочь в построении XPath-запроса, является получение непосредственно данных секции в формате XML на примере любой карточки интересующего типа (при помощи команды *Экспорт и печать* в Windows-клиенте). Используя эти данные как образец, можно строить запросы непосредственно на базе этого XML-документа.

[NOTE]
====
Клиентская фильтрация возвращает только один результат (строку). Это всегда первая по порядку строка, удовлетворяющая условиям поиска (если таким условиям удовлетворяет несколько строк).
====

Пример кода: поиск сотрудника в справочнике сотрудников по его фамилии:

[source,csharp]
----
const string ID_CARDTYPE = "{6710B92A-E148-4363-8A6F-1AA0EB18936C}";
const string ID_SECTION  = "{DBC8AE9D-C1D2-4D5E-978B-339D22B32482}";

//Фамилия сотрудника
string name = "Иванов";

//Клиентская фильтрация
CardData card = session.CardManager.GetDictionaryData(new Guid(ID_CARDTYPE));
SectionData section = card.Sections[new Guid(ID_SECTION)];
RowData row = section.FindRow("@SurName=\"" + strName + "\"");
----

Для поиска строк в коллекции (RowDataCollection#) параметры и способ использования метода абсолютно аналогичны соответствующему методу для секций. Единственное отличие заключается в том, что метод Filter может возвращать более чем один результат (RowDataCollection#).

== См. также

* xref:development-manual/dm_search_api_save.adoc[Сохранение поискового запроса]
