= Возможности поиска в контексте объектов

_Контекст объектов_ предоставляет достаточно простой и функциональный механизм поисковых запросов -- метод FindObject контекста объектов, принимающий тип искомого объекта.

[source,csharp]
----
BaseCard foundCard = objectContext.FindObject<BaseCard>(query);
----

Здесь:

* objectContext -- контекст объектов.
* BaseCard -- тип возвращаемого объекта. В качестве типа возвращаемого объекта может быть передан тип объектной модели карточки или строки.
* query -- поисковый запрос типа xref:api/DocsVision/Platform/ObjectModel/Search/QueryObject_CL.adoc[QueryObject]

К примеру, для поиска в _Справочнике сотрудников_, сотрудника с определенной учетной записью, воспользуйтесь примером, приведенным далее, в котором параметры поискового запроса передаются непосредственно в конструктор класса QueryObject.

[source,csharp]
----
// Формируем поисковый запрос по полю AccountName
QueryObject query = new QueryObject(StaffEmployee.AccountNameProperty.Name, "MYDOMAIN\\KukoffSA");

// Получаем сотрудника с искомой учетной записью
StaffEmployee employee = objectContext.FindObject<StaffEmployee>(query);
----

Здесь:

* StaffEmployee.AccountNameProperty.Name -- возвращает название поля, по которому выполняется поиск.
* "MYDOMAIN\\KukoffSA" -- искомое значение.
* xref:api/DocsVision/BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee] -- класс (объектной модели) искомого объекта.

Также возможно более сложные поисковые запросы, которые включают несколько критериев поиска. К примеру, далее приведен код запроса, выполняющего поиск контрагента по названию и типу (организация или подразделение).

[source,csharp]
----
QueryObject query = new QueryObject();

// Добавляем критерий поиска по названию контрагента
query.AddCriterion(PartnersCompany.NameProperty.Name, "ООО Берег");

// Ограничиваем поиск только среди организаций
query.AddCriterion(PartnersCompany.TypeProperty.Name, (int)PartnersCompanyType.Organization, CompareOperation.Equals);

// Определяем логическую операцию И, применяемую к результатам поиска
query.Operation = QueryOperation.And;

// Получаем контрагента, соответствующего критериям
PartnersCompany partnersCompany = objectContext.FindObject<PartnersCompany>(query);
----

Приведенные выше примеры используют метод FindObject, который предназначен для возврата единственного результата. Если в результате поиска будет найдено более одного объекта, будет возвращена ошибка, т.е. данный метод следует использовать только в случае, когда точно известно, что будет возвращен максимум один объект. Если ожидается возвращение нескольких объектов, используйте метод FindObjects, который возвращает коллекцию объектов. Метод вызывается аналогично первому.

== См. далее

* xref:development-manual/dm_exportimportprint.adoc[Экспорт, импорт и подготовка карточек к печати]
