= CardManager.GetCardData -- метод (Guid, Boolean)

Возвращает по идентификатору карточки объект для работы с её данными, с обновлением кэша.

* *Пространство имён:* `xref:Platform-ObjectManager-Metadata:ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]`
* *Сборка:* `DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,csharp]
----
public abstract CardData GetCardData(Guid cardId, bool refresh)
----

Параметры::
cardId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[Guid]`
+
Идентификатор карточки

refresh:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[Boolean]`
+
`true` -- обновить кэш карточек; `false` -- не обновлять

Возвращаемое значение::
Тип: `xref:Platform-ObjectManager-CardData:CardData_CL.adoc[CardData]`
+
Карточка

== Заметки

Параметр `refresh` не влияет на обновление данных карточки при наличии незавершённых обновления. В этом случае рекомендуется выполнить принудительное обновление -- вызвать метод `CardData.Refresh`.
