= FolderCard.DeleteCard - метод (Guid, Boolean)

Помечает к удалению, либо удаляет карточку с заданным идентификатором.

* [.keyword]*Пространство имен:* xref:SystemCards_NS.adoc[DocsVision.Platform.ObjectManager.SystemCards]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public abstract void DeleteCard(Guid cardId, bool permanently)
----

Параметры

cardId::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Идентификатор карточки
permanently::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]
  +
  true - производит стандартное удаление; при false - помечает карточку к удалению

== Заметки

Карточка удаляет с учетом существующих ярлыков.

== Примеры

В примере, карточка с идентификатором 00000000-0000-0000-0000-000000000000 помечает к удалению. userSession - текущая сессия пользователя

[source,pre,codeblock,language-csharp]
----
//Получаем карточку папок
FolderCard folderCard = (FolderCard)userSession.CardManager.GetDictionary(new Guid("DA86FABF-4DD7-4A86-B6FF-C58C24D12DE2"));

//Помечаем карточку к удалению
folderCard.DeleteCard(new Guid("00000000-0000-0000-0000-000000000000"), false);
----

*На уровень выше:* xref:../../../../../api/DocsVision/Platform/ObjectManager/SystemCards/FolderCard_CL.adoc[FolderCard - класс]
