= LockStatus -- перечисление

Состояние блокировки объекта.

* *Пространство имён:* `xref:Platform-ObjectManager-Metadata:ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]`
* *Сборка:* `DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,csharp]
----
public enum LockStatus
----

== Члены

[cols=",",options="header"]
|===
|Имя члена |Описание
|`Free` |Блокировка отсутствует.
|`Locked` |Установлена временная блокировка другим пользователем.
|`CheckedOut` |Установлена постоянная блокировка другим пользователем.
|`OwnerLocked` |Установлена временная блокировка текущим пользователем.
|`OwnerCheckedOut` |Установлена постоянная блокировка текущим пользователем.
|===

== Примеры

[source,csharp]
----
CardData card = session.CardManager.GetCardData(new System.Guid("идентификатор_карточки")); <.>
if (card.LockStatus != LockStatus.Free) <.>
{
    if (card.LockStatus = LockStatus.OwnerLocked) <.>
    {
        card.RemoveLock();
    }
    else
    {
        MessageBox.Show("Объект заблокирован пользователем " + card.LockOwner);
    }
}
----
<.> Получение с сервера данных карточки с известным идентификатором.
<.> Проверка блокировки на карточке.
<.> Объект заблокирован -- проверка владельца.
