= ISearchWordResolverService.ExtractSearchWord -- метод (ObjectContext, Guid, Guid, Guid)

Возвращает сотрудников, найденных по поисковому слову.

* *Пространство имён:* `xref:ObjectModel/Services/Services_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel.Services]`
* *Сборка:* `DocsVision.ApprovalDesigner.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
IEnumerable<StaffEmployee> ExtractSearchWord(ObjectContext context, Guid searchWordId, Guid initiatorId, Guid registratorId)
----

Параметры::
context:::
Тип: `xref:Platform-ObjectModel:ObjectContext_CL.adoc[ObjectContext]`
+
Текущий контекст объектов

searchWordId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор поискового слова, по которому ищутся сотрудники

initiatorId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор инициатора согласования

registratorId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`
+
Идентификатор согласующего

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StaffEmployee>`
+
Найденные сотрудники. Тип элемента -- `xref:BackOffice-ObjectModel-Staff:StaffEmployee_CL.adoc[StaffEmployee]`
