= IStateService.AddOperation -- метод (StatesCardKindStateSetting, String, Boolean)

Добавляет операцию в настройки автомата состояний вида карточки.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StatesOperation AddOperation(StatesCardKindStateSetting kindStateSettings, string name, bool editModeOnly)
----

Параметры::
kindStateSettings:::
Тип: `xref:BackOffice-ObjectModel-States:StatesCardKindStateSetting_CL.adoc[StatesCardKindStateSetting]`
+
Настройки автомата состояний вида карточки в _конструкторе состояний_

name:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Название добавляемой операции

editModeOnly:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Если `true`, то операция доступна только в режиме редактирования

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-States:StatesOperation_CL.adoc[StatesOperation]`
+
Добавленное состояние

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `kindStateSettings`.
|===
