= IStateService.ChangeState -- метод (BaseCard, StatesState, Boolean, String)

Изменяет состояние карточки.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void ChangeState(BaseCard card, StatesState endState, bool startBusinessProcess, out string startBusinessProcessErrors)
----

Параметры::
card:::
Тип: `xref:xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Карточка, для которой выполняется смена состояния

endState:::
Тип: `xref:BackOffice-ObjectModel-States:StatesState_CL.adoc[StatesState]`
+
Конечное состояние карточки

startBusinessProcess:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Если true, то будут запущены бизнес-процессы, связанные с изменением состояния карточки

startBusinessProcessErrors:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Журнал ошибок запуска бизнес-процессов
