= IStateService.IsOperationAllowedFull -- метод (StatesOperation, BaseCard)

Определяет возможность выполнения операции (_конструктора состояний_), применительно к определённой карточке, с учетом прав доступа.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool IsOperationAllowedFull(StatesOperation operation, BaseCard baseCard)
----

Параметры::
operation:::
Тип: `xref:BackOffice-ObjectModel-States:StatesOperation_CL.adoc[StatesOperation]`
+
Операция из _конструктора состояний_

baseCard:::
Тип: `xref:xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Карточка, для которой выполняется проверка

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- операция допустима, иначе -- `false`

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `operation` или `baseCard`.
|===
