= IStateService.FindBranchByBuiltIn -- метод (BuiltInBranch, StatesState)

Возвращает переход автомата состояний, соответствующий определённому начальному состоянию и указанному встроенному переходу.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StatesStateMachineBranch FindBranchByBuiltIn(BuiltInBranch builtInBranch, StatesState state)
----

Параметры::
builtInBranch:::
Тип: `BackOffice-ObjectModel-BuiltIn:BuiltInBranch_CL.adoc[BuiltInBranch]`
+
Встроенный переход

state:::
Тип: `xref:BackOffice-ObjectModel-States:StatesState_CL.adoc[StatesState]`
+
Начальное состояние

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-States:StatesStateMachineBranch_CL.adoc[StatesStateMachineBranch]`
+
Переход состояний, представленный в _Конструкторе состояний_

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `builtInBranch` или `state`.
|===

== Примеры

Ниже приведён пример использования метода `FindBranchByBuiltIn` для получения перехода из состояния Отложено в Отклонено, для карточки задания вида _На исполнение_

[source,csharp]
----
<.>

IStateService stateService = objectContext.GetService<IStateService>();
KindsCardKind cardKind = objectContext.GetObject<KindsCardKind>(new Guid("AB801854-70AF-4B6C-AB48-1B59B5D11AA9")); <.>

StatesState state = stateService.FindStateByBuiltIn(Task.DeferredState, cardKind); <.>

StatesStateMachineBranch branch = stateService.FindBranchByBuiltIn(Task.DeferredToRejectedByReject, state); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение состояния "Отложено".
<.> Получение перехода из "Отложено" в "Отклонено".
