= IStateService.ChangeState -- метод (BaseCard, StatesStateMachineBranch)

Изменяет состояние карточки.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
void ChangeState(BaseCard card, StatesStateMachineBranch branch)
----

Параметры::
card:::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Карточка, для которой выполняется смена состояния

branch:::
Тип: `xref:BackOffice-ObjectModel-States:StatesStateMachineBranch_CL.adoc[StatesStateMachineBranch]`
+
Переход автомата состояний

== Примеры

Далее приведён пример завершения исполнения карточки, следуя переходу состояний -- "Начато-Завершено"

[source,csharp]
----
<.>

IStateService stateService = objectContext.GetService<IStateService>(); <.>

Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

stateService.ChangeState(task, stateService.FindBranchByBuiltIn(Task.NotStartedToCompletedByComplete, task.SystemInfo.State)); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Задание, у которого изменяется состояние.
<.> Смена состояния.
