= IStateService.FindStateByBuiltIn -- метод (BuiltInState, BaseCard)

Возвращает состояние карточки, представленное в _Конструкторе состояний_ и соответствующее переданному встроенному состоянию.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StatesState FindStateByBuiltIn(BuiltInState builtInState, BaseCard baseCard)
----

Параметры::
builtInState:::
Тип: `xref:BackOffice-ObjectModel:BuiltInState_CL.adoc[BuiltInState]`
+
Встроенное состояние

baseCard:::
Тип: `xref:BackOffice-ObjectModel:BaseCard_CL.adoc[BaseCard]`
+
Карточка, для которой выполняется

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:StatesState_CL.adoc[StatesState]`
+
Состояние, определённое в _Конструкторе состояний_

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `builtInState`.
|===

== Заметки

Параметр `baseCard` используется для получения вида карточки, из параметров которого может быть найдено соответствие с переданным состоянием `builtInState`.

== Примеры

[source,csharp]
----
<.>

IStateService stateService = objectContext.GetService<IStateService>(); <.>

Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

StatesState state = stateService.FindStateByBuiltIn(Task.RejectedState, task); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение задания.
<.> Состояние карточки, соответствующее `builtInState`.
