= IStateService.FindOperationByBuiltIn -- метод (BuiltInOperation, BaseCard)

Возвращает операцию _конструктора состояний_, соответствующую указанной встроенной операции.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
StatesOperation FindOperationByBuiltIn(BuiltInOperation builtInOperation, BaseCard baseCard)
----

Параметры::
builtInOperation:::
Тип: `BackOffice-ObjectModel-BuiltIn:BuiltInOperation_CL.adoc[BuiltInOperation]`
+
Встроенная операция

baseCard:::
Тип: `xref:xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Карточка, относительно типа которой определяется переход

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-States:StatesOperation_CL.adoc[StatesOperation]`
+
Операция _конструктора состояний_

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `builtInOperation`.
|===
