= IVersionedFileCardService.Download -- метод (VersionedFileCard)

Сохраняет последнюю версию версионного файла на диск.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
string Download(VersionedFileCard versionedFileCard)
----

Параметры::
versionedFileCard:::
Тип: `xref:Platform-ObjectManager:SystemCards/VersionedFileCard_CL.adoc[VersionedFileCard]`
+
Карточка файла с версиями

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Расположение выгруженного файла

== Заметки

Возвращает текущую версию файла. Блокировки не производится.

== Примеры

[source,csharp]
----
<.>

IVersionedFileCardService versionedFileCardService = objectContext.GetService<IVersionedFileCardService>(); <.>

VersionedFileCard versionedFileCard = versionedFileCardService.OpenCard(new Guid("00000000-0000-0000-0000-000000000000")); <.>

string path = versionedFileCardService.Download(versionedFileCard); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение существующей карточки файла с версиями.
<.> Выгрузка файла.
