= DocumentPropertyDirection - перечисление

Определяет направление синхронизации свойств документа и полей карточки.

Это перечисление имеет атрибут FlagsAttribute, поддерживающий побитовое соединение составляющих его значений.

* [.keyword]*Пространство имен:* xref:Entities_NS.adoc[DocsVision.BackOffice.ObjectModel.Services.Entities]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
[Flags]
public enum DocumentPropertyDirection
----

== Члены

[cols=",",options="header",]
|===
|Имя члена |Описание
|None |Не задано. Значение 0x00.
|Forward |Из карточки. Значение 0x01.
|Backward |В карточку. Значение 0x02.
|Both |В обе стороны. Значение 0x03.
|===

== Заметки

Для документов в формате MS Office в системе Docsvision имеется ряд дополнительных возможностей. В частности, при вложении файлов формата MS Office в карточку Документ пользовательского вида, допускается копирование свойств файла в карточку и свойств карточки в файл. Данная операция в рамках системы Docsvision называется Синхронизация свойств полей.

*На уровень выше:* xref:../../../../../../api/DocsVision/BackOffice/ObjectModel/Services/Entities/Entities_NS.adoc[DocsVision.BackOffice.ObjectModel.Services.Entities - пространство имен]
