= ICategoryListService.AddCategory -- метод (CategoryList, CategoriesCategory)

Добавляет категорию в заданный список категорий.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
CategoryListCategory AddCategory(CategoryList categoryList, CategoriesCategory category)
----

Параметры::
categoryList:::
Тип: `xref:BackOffice-ObjectModel:CategoryList_CL.adoc[CategoryList]`
+
Список категорий, в который осуществляется добавление

category:::
Тип: `xref:BackOffice-ObjectModel-Categories:CategoriesCategory_CL.adoc[CategoriesCategory]`
+
Категория, в которую осуществляется добавление

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel:CategoryListCategory_CL.adoc[CategoryListCategory]`
+
Добавленная категория, представленная в списке категорий

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `categoryList` или `category`.
|===
