= Формирование "CardPackage" и "SqlPackage"

На этапе установки решения, в {dv} могут быть импортированы определённые данные, например: данные справочников, карточки и бизнес-процессы, для чего должен быть подготовлен специальный пакет -- `CardPackage`, содержащий файлы с данными карточек и т.д., а также файл со ссылками на эти файлы.

Один из сценариев использования пакета `CardPackage` -- настроить разметку своего типа карточки в _Конструкторе разметок_, после чего выгрузить эту разметку и распространить её с пакетом установки на целевые сервера {dv}. Аналогично можно поступить с _Конструктором состояний_ и _Конструктором ролей_.

[NOTE]
====
Файлы пакета `CardPackage` расположены в подкаталоге `CardPackage` приложенного xref:ROOT:attachment$netstatSolution.zip[архива].
====

[WARNING]
====
Все действия, связанные с формированием пакетов `CardPackage` и `SqlPackage`, должны выполняться на отдельном сервере {dv}.
====

== Предварительная подготовка

Прежде всего необходимо загрузить библиотеку карточек в базу данных {dv} (см. раздел xref:solutions:cards/scheme/load-scheme.adoc[Загрузка схем карточек в базу данных]), а также разместить на клиенте компоненты карточки и библиотеки карточек.

Компонент карточки на данном этапе достаточно разместить в каталоге {dv} {wincl}.

Компонент библиотеки карточек должен быть зарегистрирован командой: `regsvr32.exe Полный-путь-к-сборке`, к примеру, `regsvr32.exe NetstatSolutionCardLib.dll`.

[NOTE]
====
Для регистрации библиотеки с использованием утилиты `regsvr32` необходимы права администратора.
====

== Формирование данных

Когда в {dv} был загружен новый тип карточки, настраиваем его при помощи конструкторов, заполняем справочник, если решение его содержит, первоначальными данными, создаем необходимые бизнес-процессы и карточки.

.Тип "Карточка учета сетевого оборудования" была настроен с использованием:
* _Конструктора разметок_ -- создана разметка с привязкой к данным карточки.
* _Конструктора состояний_ -- добавлено начальное состояние.
* _Конструктора ролей_ -- добавлены типовые права на работу с карточкой.

Также были внесены изменения (создан корневой вид карточки) в _Справочник видов карточек_.

Дополнительно был сформирован пустой (реализация бизнес-процесса выходит за рамки примера) бизнес-процесс "Проверка доступности сетевых узлов", а также экземпляр карточки _учета сетевого оборудования_.

Все эти данные предполагается автоматически загружать в {dv} при установке решения.

== Выгрузка данных

Сформированные данные необходимо выгрузить из {dv} в формате XML, т.к. при установке решения они просто импортируются средствами платформы.

Карточки (включая бизнес-процессы) экспортируются стандартными средствами {dv} {wincl}.

Также возможно выгрузить данные из справочников и конструкторов.

//Для выгрузки данных из справочников и конструкторов рекомендуется использовать специализированную утилиту для экспорта решения -- _CardTypeExtractor_, которая доступна на сайте https://docsvision.zendesk.com/entries/22151452-%D0%AD%D0%BA%D1%81%D0%25%22[Портале технической поддержки {dv}].
//
//[NOTE]
//====
//Для удобства, утилита _CardTypeExtractor_ предоставляется вместе с исходным кодом данного решения и расположена в каталоге `Other` архива.
//====

== Создание "CardPackage"

Чтобы закончить формирование пакета `CardPackage`, требуется создать файл `CardPackage.xml` следующего формата:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<CardPackage>
 <Card Path="относительный_путь_к_файлу_XML" ID="ID_карточки" Replace=""/> <.>
 …
</CardPackage> 
----
Replace="1" если карточка должна заменить существующую, `0` -- если дополнить.

// [NOTE]
// ====
// Если для выгрузки данных использовалась утилита _CardTypeExtractor_, то файл `CardPackage.xml` будет сформирован автоматически, но в него потребуется добавить записи о карточках, выгруженных из _{wincl}а_ самостоятельно.
// ====

== Создание "SqlPackage"

[NOTE]
====
Готовый файл (`NetstatSolutionInstall.xml`) пакета "SqlPackage" содержится в каталоге `Database` приложенного xref:ROOT:attachment$netstatSolution.zip[архива].
====

Помимо `CardPackage`, для пакета установки решения требуется создать пакет `SqlPackage`, состоящий из единственного файла, в котором указано расположение файлов со схемами метаданных библиотек карточек. Файл должен быть загружен в базу данных при установке решения.

."CardPackage" должен соответствовать формату:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<SqlPackage>
 <SqlFile>"относительный_путь_к_файлу_XML"</SqlFile>
 ...
</SqlPackage>
----

[NOTE]
====
Как правило `SqlPackage` содержит одну единственную ссылку на файл со схемой библиотеки карточек.
====
