= Элемент управления "CardChooseBox"

Элемент управления `_CardChooseBox_` является специализированной версией `_ChooseBox_`, предназначенной *только* для выбора карточек.

Этот элемент управления не поддерживает технологию Data Binding, поэтому для его использования потребуется вручную написать код для инициализации существующих данных, и для сохранения результата выбора. Вместе с тем данный элемент управления предоставляет большую гибкость по сравнению с `_BoundChooseBox_`, за счет того, что позволяет разработчику управлять особенностями своей работы. `_CardChooseBox_`  позволяет указывать поисковый запрос для фильтрации карточек, доступных на выбор. Это позволит, например, ограничить область выбора конкретным типом карточек.

Для указания фильтра используется свойство `*CardsFilter*`, которое доступно только программно (в runtime). В качестве значения свойства необходимо установить ссылку на предварительно созданный объект `_SearchQuery_` (подробнее об использовании поиска в xref:cards/search.adoc[соответствующей главе]).

Остальные свойства элемента управления `_CardChooseBox_` соответствуют аналогичным свойствам `_BoundChooseBox_`.

Для чтения выбранного значения из элемента управления можно использовать свойства `*Text*` (отображаемое значение) и `*Value*` (идентификатор выбранного значения), а также событие `*OnValueChanged(object sender, System.EventArgs e*`) -- которое инициируется после завершения нового выбора.

Пример инициализации элемента управления `_CardChooseBox_` ограничивающий возможность выбора только карточками файла:

[source,csharp]
----
const string FILE_CARD_TYPE = "{2BBD0A41-265E-4FF8-82D6-C6342F34B1AF}";
SearchQuery query = session.CreateSearchQuery();
query.AttributiveSearch.CardTypeQueries.AddNew(new Guid(FILE_CARD_TYPE));
cardChooseBox1.CardsFilter = query;
----
