= IMetadataProvider -- интерфейс

Предоставляет доступ к метаданным карточек, секций, и полей.

* *Пространство имен:* xref:api/DocsVision/Platform/Data/Metadata/Metadata_NS.adoc[DocsVision.Platform.Data.Metadata]
* *Сборка:* `DocsVision.Platform.StorageServer.dll`

== Синтаксис

[source,csharp]
----
public interface IMetadataProvider
----

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание
|Cards |Возвращает коллекцию метаданных карточек, зарегистрированных на сервере.
|Libraries |Возвращает коллекцию метаданных библиотек карточек, зарегистрированных на сервере.
|===

== Методы

[cols=",",options="header"]
|===
|Имя |Описание
|GetCard(Guid) |Возвращает метаданные карточки с заданным идентификатором.
|GetField(Guid) |Возвращает метаданные поля с заданным идентификатором.
|GetLibrary(Guid) |Возвращает метаданные библиотеки карточек с заданным идентификатором.
|GetSection(Guid) |Возвращает метаданные секции с заданным идентификатором.
|===

== Заметки

Код регистрация провайдера метаданных выглядит следующим образом:

[source,csharp]
----
IMetadataProvider metadataProvider = DocsVisionObjectFactory.CreateMetadataProvider(userSession);
objectContext.AddService<IMetadataManager>(DocsVisionObjectFactory.CreateMetadataManager(metadataProvider, userSession));
objectContext.AddService<IMetadataProvider>(metadataProvider);    
----

Доступ к поставщику метаданных аналогичен получения сервиса:

[source,csharp]
----
IMetadataProvider iMetadataProvider = objectContext.GetService<IMetadataProvider>();
----
