= DocsVision.ApprovalDesigner -- пространство имён

Пространство имён `DocsVision.ApprovalDesigner` содержит типы и методы приложения _{ad}_.

== Пространства имён

[cols=",",options="header"]
|===
|Пространство имён |Описание
|`xref:Platform-ObjectModel:ObjectModel_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel]` |Содержит типы объектной модели модуля {ad}.
|===

== Заметки

Для возможности получения или создания сущностей пространства имён `DocsVision.ApprovalDesigner` в xref:samples:object-model/init-context.adoc[контексте объектов] помимо стандартных должны быть зарегистрированы дополнительные фабрики из сборки `DocsVision.ApprovalDesigner.ObjectModel.dll`:

* Фабрика преобразователей данных `ApprovalDesignerMapperFactory`.
* Фабрика сервисов `ApprovalDesignerServiceFactory`.

[source,csharp]
----
using DocsVision.ApprovalDesigner.ObjectModel.Mapping;
// ...

var serviceFactoryRegistry = objectContext.GetService<IServiceFactoryRegistry>();
serviceFactoryRegistry.RegisterFactory(typeof(ApprovalDesignerServiceFactory));

var mapperFactoryRegistry = objectContext.GetService<IObjectMapperFactoryRegistry>();
mapperFactoryRegistry.RegisterFactory(typeof(ApprovalDesignerMapperFactory));
----
