= IReferenceListService.GetReferenceDescription -- метод (ReferenceListReference)

Возвращает описание для объекта, на который установлена ссылка.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
string GetReferenceDescription(ReferenceListReference reference)
----

Параметры::
reference:::
Тип: `xref:BackOffice-ObjectModel:ReferenceListReference_CL.adoc[ReferenceListReference]`
+
Ссылка

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Описание объекта

== Заметки

Метод возвращает:

* Для ссылки на карточку: название типа карточки;
* Для ссылки на папку: название папки;
* Для url-адреса: сформированную HTML-ссылку.

== Примеры

[source,csharp]
----
<.>
IReferenceListService referenceListService = objectContext.GetService<IReferenceListService>();

ReferenceListReference reference = objectContext.GetObject<ReferenceListReference>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

string description = referenceListService.GetReferenceDescription(reference);  <.>
----
<.> Инициализация контекста объектов.
<.> Получение ссылки.
<.> Получение описания объекта.
