= IReferenceListService.CreateReference -- метод (ReferenceList, LinksLinkType, BaseCard, String, Boolean)

Добавляет ссылку на карточку в _список ссылок_.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
ReferenceListReference CreateReference(ReferenceList referenceList, LinksLinkType linkType, BaseCard cardObject, string cardDescription, bool hardlink)
----

Параметры::
referenceList:::
Тип: `xref:BackOffice-ObjectModel-RoleModel:ReferenceList_CL.adoc[ReferenceList]`
+
Список ссылок на карточки, в который добавляется ссылка

linkType:::
Тип: `xref:BackOffice-ObjectModel-Layouts:LinksLinkType_CL.adoc[LinksLinkType]`
+
Тип ссылки

cardObject:::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Карточка, на которую создаётся ссылка

cardDescription:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Описание ссылки

hardlink:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Если `true`, то жесткая ссылка

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-RoleModel:ReferenceListReference_CL.adoc[ReferenceListReference]`
+
Ссылка

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `referenceList` или `cardObject`.
|===
