= IReferenceListService.CreateReference -- метод (ReferenceList, LinksLinkType, String)

Добавляет ссылку на URL-адрес в _список ссылок_.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
ReferenceListReference CreateReference(ReferenceList referenceList, LinksLinkType linkType, string url)
----

Параметры::
referenceList:::
Тип: `xref:BackOffice-ObjectModel-RoleModel:ReferenceList_CL.adoc[ReferenceList]`
+
Список ссылок на карточки, в который добавляется ссылка

linkType:::
Тип: `xref:BackOffice-ObjectModel-Layouts:LinksLinkType_CL.adoc[LinksLinkType]`
+
Тип ссылки

url:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Добавляемый адрес

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-RoleModel:ReferenceListReference_CL.adoc[ReferenceListReference]`
+
Ссылка

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `referenceList` или `url`.
|===
