= CardManager.GetViewData -- метод (ViewSource, string, QueryParameterCollection)

Возвращает данные представления с учетом приведенного описания, с указанием параметров поиска.

* *Пространство имен:* xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]
* *Сборка:* `DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,csharp]
----
public InfoRowCollection GetViewData(ViewSource viewSource, string viewXml, QueryParameterCollection parameters)
----

Параметры::
viewSource:::
Тип: xref:api/DocsVision/Platform/ObjectManager/ViewSource_CL.adoc[ViewSource]
+
Источника данных представления
viewXml:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[String]
+
Описание представления
parameters:::
Тип: xref:api/DocsVision/Platform/ObjectManager/QueryParameterCollection_CL.adoc[QueryParameterCollection]
+
Параметры запроса

Возвращаемое значение::
Тип: xref:api/DocsVision/Platform/ObjectManager/InfoRowCollection_CL.adoc[InfoRowCollection]
+
Коллекция данных
