= CardManager.GetLinksToCard -- метод (Guid, LinkType, int)

Возвращает коллекцию карточек, ссылающихся на данную, с заданным типом ссылки и глубиной вложенности.

* *Пространство имён:* `xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]`
* *Сборка:* `DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,csharp]
----
public abstract CardDataCollection GetLinksFromCard(Guid cardId, LinkType linkType, int recurseDepth)
----

Параметры::
cardId:::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[Guid]
+
Идентификатор карточки
linkType:::
Тип: xref:api/DocsVision/Platform/ObjectManager/LinkType_EN.adoc[LinkType]
+
Тип ссылки
recurseDepth:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.int32.aspx[System.Int32]`
+
Глубина рекурсии

Возвращаемое значение::
Тип: xref:api/DocsVision/Platform/ObjectManager/CardDataCollection_CL.adoc[CardDataCollection]
+
Коллекция карточек

== Заметки

Параметр recurseDepth определяет на сколько шагов ссылающиеся карточки могут отстоять от данной.
