= CardManager.GetViewData - метод (ViewSource, Guid, QueryParameterCollection)

Возвращает данные сохраненного представления с указанным идентификатором, с указанием параметров поиска.

* [.keyword]*Пространство имен:* xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public InfoRowCollection GetViewData(ViewSource viewSource, Guid viewId, QueryParameterCollection parameters)
----

Параметры

viewSource::
  Тип: xref:ViewSource_CL.adoc[ViewSource]
  +
  Источника данных представления
viewId::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[Guid]
  +
  Идентификатор представления
parameters::
  Тип: xref:QueryParameterCollection_CL.adoc[QueryParameterCollection]
  +
  Параметры запроса

Возвращаемое значение

::
  Тип: xref:InfoRowCollection_CL.adoc[InfoRowCollection]
  +
  Коллекция данных

*На уровень выше:* xref:../../../../api/DocsVision/Platform/ObjectManager/CardManager_CL.adoc[CardManager - класс]
