= CardManager.GetViewData - метод (ViewSource, string, QueryParameterCollection)

Возвращает данные представления с учетом приведенного описания, с указанием параметров поиска.

* [.keyword]*Пространство имен:* xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public InfoRowCollection GetViewData(ViewSource viewSource, string viewXml, QueryParameterCollection parameters)
----

Параметры

viewSource::
  Тип: xref:ViewSource_CL.adoc[ViewSource]
  +
  Источника данных представления
viewXml::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.string.aspx[String]
  +
  Описание представления
parameters::
  Тип: xref:QueryParameterCollection_CL.adoc[QueryParameterCollection]
  +
  Параметры запроса

Возвращаемое значение

::
  Тип: xref:InfoRowCollection_CL.adoc[InfoRowCollection]
  +
  Коллекция данных

*На уровень выше:* xref:../../../../api/DocsVision/Platform/ObjectManager/CardManager_CL.adoc[CardManager - класс]
