= ExtensionManager.GetExtensionMethod -- метод (String, String)

Получает объект для вызова метода серверного расширения.

* *Пространство имён:* `xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]`
* *Сборка:* `DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,csharp]
----
public abstract ExtensionMethod GetExtensionMethod(string extensionName, string methodName)
----

Параметры::
extensionName:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Имя расширения. Данное имя должно быть записано в реестре сервера

methodName:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Имя вызываемого метода

Возвращаемое значение::
Тип: `xref:api/DocsVision/Platform/ObjectManager/ExtensionMethod_CL.adoc[ExtensionMethod]`
+
Объект для доступа к методу расширения

== Заметки

В случае отсутствия указанного в параметрах расширения или метода, `GetExtensionMethod` вернет ошибку.

== Примеры

В приведенном примере, вызывается метод `GetFileContent` расширения `SampleExtension`, с передачей в качестве параметра расположения файла на диске.

[source,csharp]
----
ExtensionMethod method = session.ExtensionManager.GetExtensionMethod("SampleExtension", "GetFileContent"); <.>

method.Parameters.AddNew("FilePath", ParameterValueType.String).Value = "C:\\Test.txt"; <.>
    
string content = method.Execute().ToString(); <.>
----
<.> Получаем метод расширения.
<.> Добавляем параметр метода.
<.> Вызов метода.
