= IUpdatable.MarkCardForDeletion - метод (Guid)

При переопределении в производном классе требует удаление указанной карточки при отмене изменений, если задействован режим отложенных изменений.

* [.keyword]*Пространство имен:* xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
void MarkCardForDeletion(Guid cardId)
----

Параметры

cardId::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[Guid]
  +
  Идентификатор удаляемой карточки

== Заметки

При отмене пакета изменений (в режиме отложенных изменений), карточка будет автоматически удалена. Этот метод позволяет избавить разработчика от необходимости самому следить за жизненным циклом объектов, которые он создает в режиме отложенных изменений.

*На уровень выше:* xref:../../../../api/DocsVision/Platform/ObjectManager/IUpdatable_IN.adoc[IUpdatable - интерфейс]
