= IXmlExportable.SaveXml - метод (Stream, ExportFlags, ExportCardInspector)

При переопределении в производном классе, метод сохраняет представление данных объекта в формате XML, в соответствии с установленными флагами экспорта и заданной логикой экспорта.

* [.keyword]*Пространство имен:* xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
void SaveXml(Stream stream, ExportFlags exportFlags, ExportCardInspector inspector)
----

Параметры

stream::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.io.stream.aspx[Stream]
  +
  Поток для данных
exportFlags::
  Тип: xref:ExportFlags_EN.adoc[ExportFlags]
  +
  Флаги экспорта
inspector::
  Тип: xref:ExportCardInspector_CL.adoc[ExportCardInspector]
  +
  Логика экспорта

*На уровень выше:* xref:../../../../api/DocsVision/Platform/ObjectManager/IXmlExportable_IN.adoc[IXmlExportable - интерфейс]
