= LicenseManager -- класс

Класс LicenseManager содержит функциональность по работе с дополнительными опциями лицензии {dv}, в которых присутствует ограничение по количеству соединений.

* *Пространство имен:* xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]
* *Сборка:* `DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,csharp]
----
public abstract class LicenseManager
----

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание
|Session |Возвращает сессию пользователя.
|===

== Методы

[cols=",",options="header"]
|===
|Имя |Описание
|DecrementFeatureUsage(Guid) |Уменьшает число активных соединений в счетчике дополнительной опции лицензии.
|IncrementFeatureUsage(Guid) |Увеличивает число активных соединений в счетчике дополнительной опции лицензии.
|===

== Заметки

На основе методов DecrementFeatureUsage и IncrementFeatureUsage реализуется механизм контроля числа пользователей, использующих определённый модуль {dv}, если для данного модуля предусмотрено лицензионное ограничение на количество одновременно работающих пользователей.

== Примеры

К примеру, при осуществлении доступа к дополнительному модулю {dv}, необходимо выполнить проверку того, не достигнут ли предел подключений пользователей:

[source,csharp]
----
// userSession -- сессия пользователя
// featureId -- идентификатор дополнительной опции в лицензии {dv}
private void Take(UserSession userSession, Guid featureId)
{
 try
 {
  // Увеличение числа соединений с модулем
  userSession.LicenseManager.IncrementFeatureUsage(featureId);
  return;
 } catch (StorageServerException ex)
 {
  // если достигнут предел подключений..
  if (ex.ErrorCode = (int)ErrorCode.FeatureLimit)
  {
   /* Вывод сообщения о превышении количества пользователей */
   return;
  } else
  {
   /* Вывод сообщения о прочей ошибке */
   return;
  }
 }
}
----

После выхода пользователя из модуля, соединение должно быть освобождено:

[source,csharp]
----
private void Release(UserSession userSession, Guid featureId)
{
 try
 {
  // Уменьшение числа соединений с модулем
  userSession.LicenseManager.DecrementFeatureUsage(featureId);
  return;
 } catch (StorageServerException ex)
 {
  /* Вывод сообщения о прочей ошибке */
  return;
 }
}
----
