= LogManager.GetMessage -- метод (Int32)

Возвращает сообщение из журнала согласно заданному идентификатору.

* *Пространство имён:* `xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]`
* *Сборка:* `DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,csharp]
----
public abstract InfoRowCollection GetMessage(int messageId)
----

Параметры::
messageId:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.int32.aspx[System.Int32]`
+
Идентификатор сообщения

Возвращаемое значение::
Тип: `xref:api/DocsVision/Platform/ObjectManager/InfoRowCollection_CL.adoc[InfoRowCollection]`
+
Коллекция нетипизированных данных

== Заметки

Состав полей в возвращаемой коллекции:

* *ID* -- идентификатор сообщения в журнале;
* *ResourceID* -- идентификатор объекта;
* *TypeID* -- тип объекта;
* *ParentID* -- идентификатор родительского объекта;
* *Date* -- дата операции;
* *Type* -- тип операции;
* *Operation* -- код операции;
* *Data* -- дополнительная информация.
