= SectionData.FetchMode - свойство

Возвращает или задает режим загрузки данных.

* [.keyword]*Пространство имен:* xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public abstract FetchMode FetchMode {get; set;}
----

Значение свойства

::
  Тип: xref:Metadata/FetchMode_EN.adoc[FetchMode]
  +
  Режим загрузки

== Заметки

Режим построчной загрузки (FetchMode.Row) в данный момент не реализован. Однако получить данные для отдельных строк все же можно - для этого у объекта xref:SectionData_CL.adoc[SectionData] есть набор методов, работающих с одиночной строкой. Их использование позволяет не загружать на клиента ненужную информацию, что, конечно же, предпочтительнее с точки зрения производительности

*На уровень выше:* xref:../../../../api/DocsVision/Platform/ObjectManager/SectionData_CL.adoc[SectionData - класс]
