= SectionData.FindRows -- метод (String)

Осуществляет поиск строк в секции карточки (справочника).

* *Пространство имён:* `xref:api/DocsVision/Platform/ObjectManager/ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]`
* *Сборка:* `DocsVision.Platform.ObjectManager.dll`

== Синтаксис

[source,csharp]
----
public abstract RowDataCollection FindRows(string queryXml)
----

Параметры::
queryXml:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[String]`
+
Поисковый запрос

Возвращаемое значение::
Тип: `xref:api/DocsVision/Platform/ObjectManager/RowDataCollection_CL.adoc[RowDataCollection]`
+
Коллекция найденных строк

== Примеры

Приведенный далее пример демонстрирует использование серверного поиска при получении сотрудников определённого подразделения

[source,csharp]
----
<.>
                
SectionQuery sectionQuery = userSession.CreateSectionQuery(); <.>

Guid departmentID = new Guid(" 00000000-0000-0000-0000-000000000000"); <.>

sectionQuery.ConditionGroup.Conditions.AddNew("ParentRowID", FieldType.UniqueId, ConditionOperation.Equals, departmentID); <.>

CardData staffData = userSession.CardManager.GetDictionaryData(RefStaff.ID);
SectionData employeesSection = staffData.Sections[RefStaff.Employees.ID]; <.>

RowDataCollection employees = employeesSection.FindRows(sectionQuery.GetXml()); <.>
----
<.> Инициализация контекста объектов.
<.> Поиск по секции.
<.> Подразделение, из которого осуществляется выборка сотрудников.
<.> Добавление условия поиска сотрудников в подразделении `departmentId`.
<.> Получение Справочника сотрудников и секции "Сотрудники".
<.> Выполнение поиска.
