= Архивирование и извлечение карточки из архива

Чтобы убрать из списка карточки, работа с которыми завершена, их можно поместить в архив.

За архивацию карточек на уровне базового API отвечает метод `Archive`, который предоставляется классом карточки -- `CardData`:

[source,csharp]
----
CardData cardData = userSession.CardManager.GetCardData(cardId); <.>

cardData.Archive(ArchiveOptions.None); <.>
----
<.> Получаем данные карточки.
<.> Помещаем карточку в архив.

Второй метод класса `CardData` позволяет извлечь карточку из архива:

[source,csharp]
----
cardData.Dearchive(ArchiveOptions.None)
----

Параметр, передаваемый в методы, определяет сценарий помещения и извлечения карточки из архива. Данный параметр может принимать значения:

* `ArchiveOptions.None` -- без дополнительных параметров.
* `ArchiveOptions.Delay` -- архивирование будет выполнено с задержкой.
* `ArchiveOptions.IncludeLinkedCards` -- будут также архивированы карточки, связанные с архивируемой.
* `ArchiveOptions.IncludeLinkedFiles` -- будут также архивированы файлы, связанные с архивируемой карточкой.

Объектная модель не предлагает методов для работы с архивом. При необходимости воспользуйтесь методами базового API.
