= Получение экземпляра карточки из базы данных

Платформа {dv} предоставляет несколько способов получения карточки: её можно запросить по уникальному идентификатору в формате http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[`Guid`], либо xref:work-cards/search.adoc[получить] из результата работы поискового запроса. Здесь рассмотрен первый способ, для которого необходимо знать идентификатор получаемой карточки.

.Идентификатор карточки может быть получен, как минимум, двумя способами:
* Значение можно посмотреть в свойствах карточки в Windows-клиенте, где идентификатор приведен в строке _Ссылка_.
* Найти карточку при помощи программы "Docsvision Explorer". Идентификатор указан в строке `Selected card ID`.

== Базовый API

.Получить данные карточки методами базового API можно следующим образом:
[source,csharp]
----
CardData card = userSession.CardManager.GetCardData(cardId) <.> <.> <.>
----
<.> `userSession` -- xref:work-cards/connect-to-dv-server.adoc[пользовательская сессия].
<.> `CardManager` -- xref:api/DocsVision/Platform/ObjectManager/CardManager_CL.adoc[менеджер карточек], в котором собрана основная функциональность базового API для работы с карточками.
<.> `cardId` -- идентификатор запрашиваемой карточки. Обычно (как и `GetCardData`) методы принимают идентификаторы, приведенные к типу http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[`System.Guid`]:
+
[source,csharp]
----
Guid cardId = new Guid("00000000-0000-0000-0000-000000000000");
----

.После получения данных карточки, можно:
* xref:work-cards/get-section.adoc[Получить] данные из её секций.
* xref:work-cards/card-lock.adoc[Установить] или снять блокировку.
* xref:work-cards/card-archive.adoc[Отправить] карточку в архив или извлечь из архива.
* xref:work-cards/export-import-print.adoc[Экспортировать] данные карточки в формате XML в файл.
* При необходимости xref:dm_downloadmode.adoc[изменить] режим чтения данных.

[NOTE]
====
Полный список доступных методов и свойств см. в описании типа xref:api/DocsVision/Platform/ObjectManager/CardData_CL.adoc[`CardData`].
====

== Объектная модель

Для получения данных карточки, а точнее её объектной модели, _контекст объектов_ предоставляет метод `GetObject`, который может быть вызван следующим образом:

[source,csharp]
----
BaseCard card = objectContext.GetObject<BaseCard>(cardId); <.> <.> <.>
----
<.> `objectContext` -- проинициализированный _контекст объектов_ (см. xref:work-cards/connect-to-dv-server.adoc[Подключение к серверу Docsvision]).
<.> `BaseCard` -- класс объектной модели карточки. Здесь использован базовый класс карточек библиотеки _{bo}_. В любом случае указываемый тип должен быть наследником типа xref:api/DocsVision/Platform/ObjectModel/ObjectBase_CL.adoc[`ObjectBase`] -- базовый класс для всех сущностей данного уровня API.
+
Список классов объектных моделей карточек библиотеки _{bo}_ приведен в разделе xref:work-cards/bo-lib/library.adoc[Библиотека карточек "Базовые объекты"].
+
<.> `cardId` -- идентификатор запрашиваемой карточки.

[NOTE]
====
Метод `GetObject` достаточно универсален и может вернуть из _контекста объектов_ любой объект, для которого разработана объектная модель и в контексте объектов зарегистрирован _преобразователь данных_ (будет рассмотрен позднее).
====

.После получения объектной модели карточки, возможно:
* xref:work-cards/get-section.adoc[Получить] данные из её секций, если класс объектной модели карточки был унаследован от класса `BaseCard` или его потомков.
+
Если класс карточки наследуется напрямую от `ObjectBase`, функциональность получения данных секций потребуется реализовать самостоятельно.
+
* Получить объектную модель секций, если это предусмотрено объектной моделью карточки.
+
[NOTE]
====
Объектная модель секции карточки, а точнее её строк, позволяется работать с секцией как с объектом, обладающим набором определенных свойств, представляющих поля карточки. Это отличает данный способ от ранее приведенного, идеология которого ближе к принципам работы с секциями в базовом API. В базовом API необходимо знать идентификаторы секций и точные названий полей.
====
