= Элемент управления "Preview"

Элемент управления `_Preview_` предназначен для просмотра содержимого файла без открытия файла. Соответствует элементу управления `_Предпросмотр файла_` _Конструктора разметок_.

`_Preview_` не содержит элементов управления.

== Свойства

* `FileName` -- возвращает название открытого файла.

== Методы

* `ClosePreview` -- освобождает ресурсы и очищает область предварительного просмотра. Вызывается автоматически, перед вызовом ShowPreview.
* `SetText(String)` -- передает текст для отображения в окно предварительного просмотра.
* `ShowPreview(String)` -- формирует предварительный просмотр файла, расположенного по указанному пути.
* `ShowPreview(String, IStream)` -- формирует предварительный просмотр файла, расположенного по указанному пути. Должен быть использован, если `SupportStreaming` возвращает `true`.
* `SupportStreaming(String)` -- определяет поддержку обработчиком, формирующим предварительный просмотр файла, чтение файла из потока.

== События

* `*PreviewCompleted*` -- событие вызывается после отображения пользователю содержимого файла (используется метод `ShowPreview`).

.Пример использования `Preview` для отображения содержимого документа Microsoft Word:
[source,csharp]
----
private void ShowButton_Click(object sender, EventArgs e)
{
 if (!this.preview.ShowPreview(@"X:\Sample.docx"))
  this.preview.SetText("Предварительный просмотр недоступен");
}
----

[NOTE]
====
Для формирования предварительного просмотра, необходимо наличие на компьютере средств открытия файла.
====
