= Параметры соединения с сервером Docsvision

* `ConnectAddress` -- адрес сервера. В зависимости от используемого протокола, может принимать одно из следующих значений (адрес однозначно определяет протокол, и наоборот):
** `Web service (HTTP + SOAP)`: `\http://SERVERNAME/FOLDERNAME/StorageServer/StorageServerService.asmx`
** `WCF service (HTTP + SOAP)`: `\http://SERVERNAME/StorageServer/StorageServerService.svc`
** `WCF TCP Service`: `net.tcp://SERVERNAME:8080/StorageServer/StorageServerService.svc`
** `WCF Named Pipes`: `net.pipe://SERVERNAME/StorageServer/StorageServerService.svc`
* `BaseName` -- псевдоним базы данных (имя, под которым она подключена к серверу). Данный параметр является опциональным -- если его значение не указать, то будет использована база данных по умолчанию.
* `UserName` -- имя пользователя (при использовании базовой аутентификации).
* `Password` -- пароль (при использовании базовой аутентификации).
* `Proxy` -- адрес прокси-сервера (при использовании прокси). Если адрес прокси-сервера *не* указан, то будут использованы настройки Internet Explorer.
* `ProxyBypass`– список имён серверов, при соединении с которыми не будет использован прокси-сервер (таким образом, если нужно соединяться с сервером {dv} в обход прокси, то его имеет смысл добавить сюда).
* `AllowAutoProxy` -- использовать скрипт автоматического определения прокси, заданный в настройках Internet Explorer (используется для протокола HTTP).
* `Timeout` -- таймаут ожидания ответа сервера (при установке соединения, а также при выполнении всех последующих операций). Задается в миллисекундах. Значение `0` указывает на необходимость использования значения по умолчанию, которое равно 3 минуты).
* `IgnoreInvalidCert` -- игнорировать неправильный сертификат сервера при использовании SSL.
* `ClientCertificate` -- клиентский сертификат (если используется SSL с требованием клиентского сертификата).
