= SessionGetList

Возвращает список открытых подключений к серверу.

Для получения списка сессий, необходимы права администратора {dv}.

== Запрос

[source,charp]
----
POST /DocsVision/StorageServer/StorageServerService.asmx HTTP/1.1
Host: DOCSVISION_SERVER.COM
Content-Type: text/xml; charset=utf-8
Content-Length: length
SOAPAction: "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/SessionGetList"

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <SessionGetList xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <baseName>string</baseName>
    </SessionGetList>
  </soap:Body>
</soap:Envelope>
----

Параметры::
baseName:::
Название базы данных. Если не указана, возвращается список подключений к базе данных по умолчанию.

== Ответ

[source,charp]
----
HTTP/1.1 200 OK
Content-Type: text/xml; charset=utf-8
Content-Length: length

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <SessionGetListResponse xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <sessions>string</sessions>
    </SessionGetListResponse>
  </soap:Body>
</soap:Envelope>
----

.Ответ содержит сведения о всех подключениях к базе данных и предоставляет следующую информацию:
* Идентификатор сессии.
* Учетная запись сотрудника, выполнившего подключение.
* Дата и время подключения, а также последнего запроса к серверу.
* Название и адрес компьютера, с которого выполнено подключение, если эти данные были переданы при открытии сессии.

== Пример запроса

[source,python]
----
<.>

session.headers['SOAPAction'] = "http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/SessionGetList" <.>

body = """<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <SessionGetList xmlns="http://schemas.docsvision.com/Platform/2009-02-03/StorageServer/">
      <baseName></baseName>
    </SessionGetList>
  </soap:Body>
</soap:Envelope>""" <.>

response = session.post(url, data=body) <.>

print(response.content) <.>
----
<.> Подключение модулей Python и открытие сессии к серверу {dv} (см. код по ссылке).
<.> Изменяем цель запроса в заголовке запроса.
<.> SOAP-сообщение.
<.> Отправляем SOAP-сообщение.
<.> Ответ SOAP.
