= Библиотека классов

Библиотека классов {dv} содержит описание объектов и методов предоставляемых API {dv}.

[NOTE]
====
Руководство по разработке находится в процессе наполнения, т.е. библиотека классов не содержит описание всех сущностей, возможны некоторые неточности, которые будут исправлены в будущих версиях.
====

API {dv} (версии 5.4) представлен объектами, которые были унаследованы от предыдущих версий платформы (4.X и раньше) и объектами созданными для 5 версии, которые в основном определены в пространстве имён `xref:BackOffice-ObjectModel-Mapping:ObjectModel_NS.adoc[DocsVision.BackOffice.ObjectModel.ObjectModel]`, на описание сущностей которого был сделан основной упор.

Объектная модель 5.X работает поверх 4.X, поэтому если Вам не достает методов и свойств новой версии, попробуйте обратиться к старой. Старая объектная модель -- это в основном `xref:Platform-ObjectManager-Metadata:ObjectManager_NS.adoc[DocsVision.Platform.ObjectManager]`, при том что многие классы, например отвечающие за работу с объектами безопасности, могут быть реализованы в других сборках и пространствах имён.

== Пространства имён

[cols=",",options="header"]
|===
|Пространство имён |Описание
|`xref:DocsVision/DocsVision_NS.adoc[DocsVision]` |Основное пространство имён, содержащее все сущности объектной модели {dv}.

Включает подпространства имён в которых реализованы методы доступа к карточкам и бизнес-процессам, а также представлены функции управления доступом в рамках трёх моделей безопасности.
|===
