= IReusableLayoutItem - интерфейс

Интерфейс IReusableLayoutItem определяет явную поддержку в компоненте элемента управления механизма переиспользования разметки.

* [.keyword]*Пространство имен:* xref:LayoutItems_NS.adoc[DocsVision.BackOffice.WinForms.Design.LayoutItems]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.WinForms.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public interface IReusableLayoutItem
----

== Методы

[cols=",",options="header",]
|===
|Имя |Описание
|xref:IReusableLayoutItem.OnLayoutLoad_MT.adoc[OnLayoutLoad] |Вызывается при первоначальной загрузке разметки.
|xref:IReusableLayoutItem.OnLayoutReuse_MT.adoc[OnLayoutReuse] |Вызывается при переиспользовании разметки. Вызывается раньше, чем передается контекст в свойство [.keyword .apiname]#ObjectContext# элемента управления.
|===

== Заметки

Данный интерфейс реализуется в компоненте элемента управления, если требуется дополнительно обработать события загрузки и переиспользования разметки в элементе управления.

Реализуемые в компоненте элемента управления методы будут вызваны при первоначальной загрузке разметки и при переиспользовании соответственно. Методы будут вызваны только, если разметка поддерживает переиспользование.

== Примеры

[source,pre,codeblock,language-csharp]
----
public partial class HtmlBrowser : PanelControl, IReusableLayoutItem
{

 // ...

 // Обрабатываем в элементе управления событие первой загрузки разметки
 // Здесь можно не выполнять никаких действий
 public void OnLayoutLoad()
 {
  cardDataExportCache.Clear();
 }

 // Обрабатываем в элементе управления событие переиспользования (второй и последующих загрузок) разметки
 // Здесь нужно очищать данные, которые "достались" от предыдущего использования данного компонента, 
 // и которые могут помещать корректной работе или корректному отображению данных
 public void OnLayoutReuse()
 {
  cardDataExportCache.Clear();
  cardData = null;
  ReflectChanges();
 }
}
----

* *xref:../../../../../../api/DocsVision/BackOffice/WinForms/Design/LayoutItems/IReusableLayoutItem.OnLayoutLoad_MT.adoc[IReusableLayoutItem.OnLayoutLoad - метод]* +
* *xref:../../../../../../api/DocsVision/BackOffice/WinForms/Design/LayoutItems/IReusableLayoutItem.OnLayoutReuse_MT.adoc[IReusableLayoutItem.OnLayoutReuse - метод]* +

*На уровень выше:* xref:../../../../../../api/DocsVision/BackOffice/WinForms/Design/LayoutItems/LayoutItems_NS.adoc[LayoutItems - пространство имен]
