= IReusableLayoutItem -- интерфейс

Интерфейс `IReusableLayoutItem` определяет явную поддержку в компоненте элемента управления механизма повторного использования разметки.

* *Пространство имён:* `xref:api/DocsVision/BackOffice/WinForms/Design/LayoutItems/LayoutItems_NS.adoc[DocsVision.BackOffice.WinForms.Design.LayoutItems]`
* *Сборка:* `DocsVision.BackOffice.WinForms.dll`

== Синтаксис

[source,csharp]
----
public interface IReusableLayoutItem
----

== Методы

[cols=",",options="header"]
|===
|Имя |Описание
|`xref:api/DocsVision/BackOffice/WinForms/Design/LayoutItems/IReusableLayoutItem.OnLayoutLoad_MT.adoc[OnLayoutLoad]` |Вызывается при первоначальной загрузке разметки.
|`xref:api/DocsVision/BackOffice/WinForms/Design/LayoutItems/IReusableLayoutItem.OnLayoutReuse_MT.adoc[OnLayoutReuse]` |Вызывается при повторном использовании разметки. Вызывается раньше, чем передается контекст в свойство `ObjectContext` элемента управления.
|===

== Заметки

Данный интерфейс реализуется в компоненте элемента управления, если требуется дополнительно обработать события загрузки и повторного использования разметки в элементе управления.

Реализуемые в компоненте элемента управления методы будут вызваны при первоначальной загрузке разметки и при повторном использовании соответственно. Методы будут вызваны только, если разметка поддерживает повторное использование.

== Примеры

[source,csharp]
----
public partial class HtmlBrowser : PanelControl, IReusableLayoutItem
{

 // ...

 public void OnLayoutLoad() <.>
 {
  cardDataExportCache.Clear();
 }

 public void OnLayoutReuse() <.>
 {
  cardDataExportCache.Clear(); <.>
  cardData = null;
  ReflectChanges();
 }
}
----
<.> Обрабатываем в элементе управления событие первой загрузки разметки. +
Здесь можно не выполнять никаких действий.
+
<.> Обрабатываем в элементе управления событие повторного использования (второй и последующих загрузок) разметки.
<.> Здесь нужно очищать данные, которые "достались" от предыдущего использования данного компонента и могут помещать корректной работе или корректному отображению данных.
