= ITableControl - интерфейс

Определяет дополнительные возможности элемента управления типа [.dfn .term]_Таблица_ в [.dfn .term]_Конструкторе разметок_.

* [.keyword]*Пространство имен:* xref:LayoutItems_NS.adoc[DocsVision.BackOffice.WinForms.Design.LayoutItems]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.BackOffice.WinForms.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public interface ITableControl
----

== Свойства

[cols=",",options="header",]
|===
|Имя |Описание
|FocusedCellIndex |Задает или возвращает номер выделенной ячейки таблицы.
|FocusedRowIndex |Задает или возвращает номер выделенной строки таблицы.
|FocusedRowItem |Задает или возвращает выделенную строку таблицы.
|GridColumns |Возвращает коллекцию колонок таблицы.
|Item |Возвращает элемент таблицы с заданным номером строки.
|RowCount |Возвращает количество строк таблицы.
|===

== Методы

[cols=",",options="header",]
|===
|Имя |Описание
|AddRow(BaseCard) |Добавляет новую строку в таблицу.
|GetControl |Возвращает элемент управления.
|RefreshRow(Int32) |Обновляет строку с заданным идентификатором.
|RemoveRow(BaseCard, BaseCardProperty) |Удаляет указанную строку.
|RemoveRow(BaseCard, Int32) |Удаляет строку с указанным номером.
|===

== События

[cols=",",options="header",]
|===
|Имя |Описание
|CellValueChanged |Событие вызывается при изменении значения ячейки.
|===

== Примеры

Ниже приведен пример использования интерфейса [.keyword .apiname]#ITableControl# при добавлении строки в элемент управления типа "Таблица"

[source,pre,codeblock,language-csharp]
----
private void Add_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
 // Получение доступа к разметке 
 ICustomizableControl customizable = CardControl as ICustomizableControl;

 // Поиск элемента управления типа "Таблица" с названием "Список"
 ITableControl table = customizable.FindPropertyItem<ITableControl>("Список");

 // Добавление строки
 BaseCardProperty property = table.AddRow(this.BaseObject);

 // Присвоение значения первой ячейке
 property[property.Fields[0].Alias] = "Добавленное значение";

 // Обновление строки для отображения присвоенного значения в интерфейсе
 table.RefreshRow(table.RowCount - 1);
}
----

*На уровень выше:* xref:../../../../../../api/DocsVision/BackOffice/WinForms/Design/LayoutItems/LayoutItems_NS.adoc[LayoutItems - пространство имен]
