= IBinaryStorage.Create -- метод (IFileInfo, StoragePartitionType)

Формирует во внешнем хранилище путь к добавляемому файлу.

* *Пространство имён:* `xref:api/DocsVision/Platform/StorageServer/StorageServer_NS.adoc[DocsVision.Platform.StorageServer]`
* *Сборка:* `DocsVision.Platform.StorageServer.dll`

== Синтаксис

[source,csharp]
----
string Create(IFileInfo fileInfo, StoragePartitionType onPartition = StoragePartitionType.Primary)
----

Параметры::
fileInfo:::
Тип: `xref:api/DocsVision/Platform/StorageServer/Files/IFileInfo_IN.adoc[IFileInfo]`
+
Информация о файле

onPartition:::
Тип: `xref:api/DocsVision/Platform/StorageServer/StoragePartitionType_EN.adoc[StoragePartitionType]`
+
Раздела хранилища, в который записывается файл

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Уникальный идентификатор файла в хранилище

== Заметки

Метод Create не записывает бинарные данные во внешнее хранилище, а только возвращает уникальный идентификатор для файла в данном хранилище. По полученному идентификатору {dv} будет получать файл из хранилища. Способ формирования идентификатора определяется программистом. Запись бинарных данных в хранилище осуществляет метод `xref:api/DocsVision/Platform/StorageServer/IBinaryStorage.Write_MT.adoc[Write]`.
