= Клиентский компонент шлюза

Клиентский компонент _шлюза_ представляет собой стандартный COM-компонент, реализующий ряд предопределённых интерфейсов, в частности:

* Интерфейс xref:workflow/com-interfaces.adoc#IObjectUI[`IObjectUI`] -- стандартный для всех клиентских объектов _СУБП_ (_функций_ и _шлюзов_) интерфейс, который определяет наличие у объекта идентификатора, названия, иконки и хранимых данных.
* Интерфейс xref:workflow/com-interfaces.adoc#IGateUI[`IGateUI`] -- стандартный интерфейс клиентского компонента шлюза. Реализует свойства и методы для работы с доступными типами переменных (объектов шлюза). Например, шлюз к файловой системе может обрабатывать два типа переменных -- файлы и папки файловой системы.
* Интерфейс xref:workflow/com-interfaces.adoc#IDVObjectUI[`IDVObjectUI`] (необязательный) -- стандартный интерфейс для компонент, использующих объекты {dv}. Позволяет получить доступ к текущей сессии и окну {wincl}а.

.Наиболее важными в реализации клиентского компонента шлюза являются следующие методы:
* `GetObjectTypes` -- возвращает коллекцию описаний регистрируемых шлюзом типов переменных.
* `GetMethods` -- возвращает коллекцию описаний методов, предоставляемых шлюзом для манипуляций над объектами.
* `SelectObject` -- выбор значения переменной указанного типа. Обычно, вызов данного метода влечет за собой открытие одного или нескольких диалоговых окон.
* `GetObjectDisplayValue` -- возвращает отображаемое значение переменной указанного типа по её числовому значению.

_Шлюз_ может иметь собственные хранимые данные (например, настройки соединения с внешней системой или иные необходимые настройки), которые могут меняться в зависимости от того, в каком процессе используется _шлюз_. В таком случае эти данные передаются и возвращаются при помощи свойства `Data` интерфейса `IObjectUI` и сохраняются в базе данных {dv}. Пользовательский интерфейс для изменения этих настроек (в случае необходимости) также реализуется клиентским компонентом _шлюза_ с помощью страниц свойств.

Для передачи _шлюзу_ настроек, общих для всех экземпляров _шлюза_ одного типа, также предусмотрен интерфейс `IGateInit`. В существующих шлюзах он используется для установки xml-описания _шлюза_.

Для разработки страниц свойств рекомендуется использовать компонент Property Page Designer (`DDPropPageD.ocx`), входящий в комплект поставки {dv}.

Настройки (данные) _шлюза_ используются в дальнейшем в серверном компоненте _шлюза_ при его инициализации.

При занесении шлюза в справочник необходимо указать программный идентификатор (`ProgID`) разработанного клиентского компонента.

Клиентский компонент может быть разработан с использованием Visual Basic или Visual C++.
