= Серверный компонент шлюза

Серверный компонент _шлюза_ реализуется в виде .NET-сборки, и используется сервисом _СУБП_ при работе с объектами _шлюза_ (переменными). Компонент реализует следующую функциональность:

* Предоставление программного интерфейса для обработки объектов _шлюза_.
* Создание экземпляров объектов.
* Удаление экземпляров объектов.
* Сравнение объектов.
* Дополнительные функции (свои для каждого шлюза).

Компонент реализует стандартный интерфейс `xref:api/DocsVision/Workflow/Gates/IGate_IN.adoc[IGate]`, содержащий методы, вызываемые сервисом _СУБП_ или _функциями_ процесса.

Кроме этого интерфейса, серверный компонент _шлюза_ определяет собственные интерфейсы для всех типов переменных, реализуемых _шлюзом_. Каждый объект _шлюза_ реализует стандартный интерфейс `xref:api/DocsVision/Workflow/Gates/IGateVariable_IN.adoc[IGateVariable]` для совместимости с другими _шлюзами_, а также, возможно, некоторые специфические для данного типа методы. Например, тип `Пользователь` может, кроме стандартных свойств, содержать такие специфические свойства как `ФИО`, `Дата рождения` и другие.

Серверный компонент шлюза реализуется на любом из языков платформы .NET -- C# или Visual Basic .NET.
