= Запуск экземпляра бизнес-процесса

Далее приведен пример кода скрипта ("Конструктор скриптов"), определенного типа карточки, в котором из существующего шаблона создается, а затем запускает экземпляр бизнес-процесса. Шаблон бизнес-процесса имеет одну переменную (типа `Строка`), в которую передается отображаемое имя сотрудника, выполнившего запуск скрипта. Предполагается, что скрипт запускается из карточки типа "Документ".

--
[source,csharp]
----
//
private void Button_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e) <.>
{
 //
 Library library = new Library(base.Session); <.>
 
 //
 Process template = library.GetProcess(new Guid("00000000-0000-0000-0000-000000000000")); <.>
 
 //
 Process process = library.CreateProcess(template); <.>

 //
 process.InitialDocument = base.CardData.Id.ToString("B"); <.>

 //
 process.Variables[new Guid("00000000-0000-0000-0000-000000000001")].Value = (base.BaseObject as Document).MainInfo.Author.DisplayName; <.>
 
 //
 process.Start(base.Session.Properties["AccountName"].Value.ToString(), library.Dictionary,  ExecutionModeEnum.Automatic, true); <.>
}
----
<.> Создание экземпляра БП на основе существующего шаблона с его последующим запуском.
<.> Инициализация объекта для работы с библиотекой карточкой СУБП.
+
`userSession` -- пользовательская сессия.
+
<.> Получение существующего шаблона бизнес-процесса . `00000000-0000-0000-0000-000000000000` -- идентификатор шаблона бизнес-процесса.
<.> Создание нового экземпляра бизнес-процесса.
<.> Сохранение инициирующего документа.
<.> Присвоение значения переменной бизнес-процесса. `00000000-0000-0000-0000-000000000001` -- идентификатор переменной бизнес-процесса, может быть получен из шаблона БП при помощи утилиты {dv} Explorer.
+
Поле "ID" в секции "Переменные" карточки БП, используемой в качестве шаблона.
+
<.> Запуск экземпляра бизнес-процесса.
+
`AccountName` -- учетная запись пользователя, от имени которого производится запуск БП.
+
`Library` -- ссылка на справочники Workflow (`Assemblies`, `Functions`, `Gates`).
+
`executionMode` -- режим исполнения процесса.
+
`suppressExecuteModeCompution` -- флаг, позволяющий отложить вычисление режима исполнения процесса.
--

.К скрипту требуется подключить дополнительные сборки:
* `DocsVision.Workflow.Objects.dll`
* `DocsVision.Workflow.Interfaces.dll`

.Также необходимо добавить ссылку на пространство имен `DocsVision.Workflow.Objects`:
[source,csharp]
----
using DocsVision.Workflow.Objects;
----
