= Часто задаваемые вопросы

Каким образом получить родительский объект имея подчиненный?::
Для этого предназначен метод `xref:Platform-ObjectModel:ObjectHelper.GetParent_MT.adoc[ObjectHelper.GetParent]`.

.Метод, к примеру, можно использовать для получения документа, которому принадлежит файл:
[source,csharp]
----
Document document = ObjectHelper.GetParent<Document>(documentFile); <.>
----
<.> `documentFile` -- файл (тип `DocumentFile`) искомого документа.

Как изменить значение в элементе управления в карточке::
Для доступа к элементу управления из скрипта карточки, достаточно обратиться к методу `FindPropertyItem` базового класса карточки `xref:BackOffice-WinForms:BaseCardControl_CL.adoc[BaseCardControl]`, передав название элемента управления:

[source,csharp]
----
ICustomizableControl control = CardControl;

ILayoutPropertyItem layoutItem = control.FindPropertyItem<ILayoutPropertyItem>("Theme"); <.>

layoutItem.ControlValue = "Новое значение"; <.>

layoutItem.Commit(); <.>
----
<.> Получение элемента управления.
<.> Установка нового значения.
<.> Сохранение.

Название элемента можно посмотреть в _Конструкторе разметок_.

Пример работы с {dv} из Powershell::
В приведенном ниже примере, создаётся скрипт, выполняющий подключение к серверу {dv}, и получение номера из карточки Нумератора.

[source,powershell]
----
Add-Type -Path с:\DocsVision.Platform.dll
Add-Type -Path с:\DocsVision.Platform.ObjectManager.dll <.>

$connectionString = "ConnectAddress=http://docsvision.domain.com/DocsVision/StorageServer/StorageServerService.asmx" <.>
$sessionManager = [DocsVision.Platform.ObjectManager.SessionManager]::CreateInstance($connectionString)
$userSession = $sessionManager.CreateSession()

[GUID]$numeratorCardID = "00000000-0000-0000-0000-000000000000" <.>
[DocsVision.Platform.ObjectManager.SystemCards.NumeratorCard]$numeratorCard = $userSession.CardManager.GetCard($numeratorCardID)
[GUID]$outId = [GUID]::Empty

$number = $numeratorCard.Zones[0].GetNumber([GUID]::Empty, 1, [ref] $outId); <.>

write $number <.>
----
<.> Требуется указать действительный путь к используемым библиотекам {dv}.
<.> Требуется указать действительный адрес подключения к {dv}.
<.> Требуется передать действительный адрес Нумератора.
<.> Получение номера из первой зоны нумерации.
<.> Вывод полученного номера.

Аналогичная задача может быть решена без объектной модели -- прямым обращением к сервису {dv}

[source,csharp]
----
$serverUri = "http://docsvision.domain.com/DocsVision/StorageServer/StorageServerService.asmx" <.>

[GUID]$numeratorCardID = "00000000-0000-0000-0000-000000000000"
$zoneName = "Zone" <.>

$result = 0
[GUID]$numberId = [GUID]::Empty
[GUID]$userID = [GUID]::Empty

$client = New-WebServiceProxy -Uri $serverUri"?WSDL" -UseDefaultCredential

[GUID]$sessionId = $client.SessionLogin("","", [ref]$result) <.>

$number = $client.NumGetFirstFree($sessionId, $numeratorCardID, $zoneName, $userID, [ref]$numberId) <.>
----
<.> Адрес сервиса {dv}.
<.> Идентификатор карточки нумератора и название зоны, в которых будет резервироваться номер.
<.> Открытие сессии.
<.> Получение номера.

[NOTE]
====
Полное описание методов сервиса приведено в разделе xref:appendix:webservice/methods.adoc[Методы веб-сервиса {dv}].
====

Как узнать идентификатор карточки::
Узнать идентификатор существующий карточки можно несколькими способами:

* Посмотреть в {wincl}е -- идентификатор карточки отображается в её свойствах.
* Используя утилиту {dv} Explorer, входящей в {rk} -- идентификатор карточки отображается в поле `Selected card ID`.

Получить идентификатор созданной карточки, используя объектную модель::
Для получения идентификатора объекта (например, объект document типа `DocsVision.BackOffice.ObjectModel.Document)` можно воспользоваться методом `ObjectContext.GetObjectRef(ObjectBase)`:

[source,csharp]
----
Guid id_document = objectContext.GetObjectRef(document).Id;
или так (начиная с НО9):
Guid id_document = document.GetObjectId();
----

[NOTE]
====
Корректный идентификатор нового объекта может быть получен только после сохранения объекта в _контексте объектов_.
====

Получить отображаемое имя текущего сотрудника::
[source,csharp]
----
StaffEmployee currentEmployee = objectContext.GetService<IStaffService>().GetCurrentEmployee();
string displayName = currentEmployee.DisplayName;
----

Получить карточку сотрудника по его идентификатору (id_empl)::
[source,csharp]
----
StaffEmployee staffEmployee = staffService.Get(new Guid("id_empl"));
----

Считывание данных с элемента управления типа коллекция, например "Сотрудники"::
Для сотрудников, в `ControlValue` соответствующего элемента управления содержится коллекция идентификатором выбранных сотрудников -- `IEnumerable<Guid>`. Для записи, в `ControlValue` передается массив таких идентификаторов (`Guid[]`).

Доступ к значению поля::

[source,csharp]
----
int? result = userSession.CardManager.GetCardData(cardID).Sections[sectionID].FirstRow.GetInt32(fieldAlias); <.>
----
<.> `cardID` -- идентификатор карточки; `sectionID` -- идентификатор секции; `fieldAlias` -- псевдоним поля.

С точки зрения доступа, динамические поля не отличаются от статических, поэтому получение значения такого поля может выглядеть следующим образом

[source,csharp]
----
Guid cardID = new Guid("00000000-0000-0000-0000-000000000000"); <.>

string sectionAlias = "DynSection"; <.>

string fieldAlias = "DynField"; <.>

CardType type = userSession.CardManager.GetCardData(cardID).Type; <.>

Guid sectionID = type.Sections[sectionAlias].Id; <.>

int? result = userSession.CardManager.GetCardData(cardID).Sections[sectionID].FirstRow.GetInt32(fieldAlias); <.>
   
Document document = objectContext.GetObject<Document>(cardID); <.>
result = (((BaseCardSectionRow)document.GetSection(sectionID)[0])[fieldAlias] as int?);
----
<.> Идентификатор карточки.
<.> Название динамической секции.
<.> Название динамического поля.
<.> Получение типа карточки.
<.> Получение идентификатора.
<.> Получение значения поля через старую объектную модель.
<.> Или даже так, если через новую объектную модель.

Как узнать идентификатор определённого вида карточки::
Воспользуйтесь утилитой {dv} Explorer, входящей в {rk}.

. Нажать *Card types*. В открывшемся окне определить идентификатор типа карточки (идентификатор в "Selected type ID"), также идентификатор можно найти в разделе xref:schemas:ROOT:index.adoc[Описание полей стандартной карточки] (идентификатор указан вначале описания конкретной карточки).
. Нажать *Cards*. В списке типов карточек выбрать "Справочник видов карточек", после чего нажать *Search*.
. Выбрать найденный справочник (будет в единственном экземпляре). В справочнике нужно найти строку с найденным ранее идентификатором типа карточки (по содержимому поля "CardTypeId").
. Нажать *Enter section*.
. Найти в дереве видов карточек нужный вид по названию. В значении поля RowID будет искомый идентификатор вида карточки.

Получение сертификата сотрудника::
Сертификаты используются при подписании, шифровании и расшифровке данных карточек, а также при верификации установленных подписей. Сертификат сотрудника может быть получен несколькими способами:

. Вне контекста {wincl}а:
+
[source,csharp]
----
IUserProfileCardService iUserProfileCardService = objectContext.GetService<IUserProfileCardService>();
X509Certificate2 certificate = iUserProfileCardService.GetCertificate(@"DOMAIN\IvanovII");
----
+
Для получения сертификата сотрудника с использованием метода `GetCertificate`, сертификат должен быть указан в соответствующем поле (см. Руководство по настройке), в "xref:desdirs:staff:employees/main-tab.adoc#certificate[Справочнике сотрудников]".
+
[[get-certificate]]
Другой вариант -- получения сертификата из хранилища сертификатов ОС Windows. В примере получаем первый сертификат с закрытым ключом.
+
[source,csharp]
----
X509Certificate2 GetCertificate()
{
 X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
 store.Open(OpenFlags.OpenExistingOnly);
 foreach (var item in store.Certificates)
 {
  if (item.HasPrivateKey) return item;
 }
 return null;
}
----
+
. В контексте {wincl}а (например, в скрипте карточки)
+
[source,csharp]
----
bool cancel = false;
X509Certificate2 certificate = DocsVision.BackOffice.WinForms.Controls.SelectCertificateForm.SelectCertificate(ref cancel, objectContext);
if(cancel) return;
----
+
В данном случае, сотруднику будет выведено окно выбора сертификата.
