= IApprovalPathService.AddDocumentState - метод (ApprovalPath, KindsCardKind, StatesState)

Добавляет итоговое состояние документа в Маршрут согласования.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.ApprovalDesigner.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
ApprovalPathState AddDocumentState(ApprovalPath approvalPath, KindsCardKind kind, StatesState state)
----

Параметры

approvalPath::
  Тип: xref:../ApprovalPath_CL.adoc[ApprovalPath]
  +
  Маршрут согласования
kind::
  Тип: xref:../../../BackOffice/ObjectModel/KindsCardKind_CL.adoc[KindsCardKind]
  +
  Вид карточки Документ
state::
  Тип: xref:../../../BackOffice/ObjectModel/StatesState_CL.adoc[StatesState]
  +
  Состояние документа

Возвращаемое значение

::
  Тип: xref:../ApprovalPathState_CL.adoc[ApprovalPathState]
  +
  Добавленное состояние документа

*На уровень выше:* xref:../../../../../api/DocsVision/ApprovalDesigner/ObjectModel/Services/IApprovalPathService_IN.adoc[IApprovalPathService - интерфейс]
