= IApprovalStageService.ReorderSelectedApprovers - метод (ObjectCollection<ApprovalStageApprover>)

Сортирует список, содержащий согласующих, по порядковому номеру согласующего.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.ApprovalDesigner.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
void ReorderSelectedApprovers(ObjectCollection<ApprovalStageApprover> selectedApprovers)
----

Параметры

selectedApprovers::
  Тип: xref:../../../Platform/ObjectModel/ObjectCollection_CL.adoc[ObjectCollection]<ApprovalStageApprover>
  +
  Согласующие. Тип элемента - xref:../ApprovalStageApprover_CL.adoc[ApprovalStageApprover]

== Заметки

Метод [.keyword .apiname]#ReorderSelectedApprovers# просто сортирует коллекцию `selectedApprovers` по значению `Order` элементов коллекции.

*На уровень выше:* xref:../../../../../api/DocsVision/ApprovalDesigner/ObjectModel/Services/IApprovalStageService_IN.adoc[IApprovalStageService - интерфейс]
