= IApprovalStageService.CopyApproversFromDocument -- метод (ApprovalStage, Document)

Получает согласующих из согласуемого документа.

* *Пространство имен:* xref:api/DocsVision/ApprovalDesigner/ObjectModel/Services/Services_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel.Services]
* *Сборка:* `DocsVision.ApprovalDesigner.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
IEnumerable<ApprovalStageApprover> CopyApproversFromDocument(ApprovalStage approvalStage, Document document)
----

Параметры::
approvalStage:::
Тип: xref:api/DocsVision/ApprovalDesigner/ObjectModel/ApprovalStage_CL.adoc[ApprovalStage]
+
Этап согласования, в который копируются согласующие
document:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/Document_CL.adoc[Document]
+
Документ

Возвращаемое значение:::
Тип: xref:api/DocsVision/ApprovalDesigner/ObjectModel/ApprovalStageApprover_CL.adoc[ApprovalStageApprover]
+
Добавленные согласующие

== Заметки

Метод CopyApproversFromDocument возвращает согласующих, полученных из документа `document`. Согласующие выбираются из поля секции, определённого в настройках этапа согласования `approvalStage`, в `MainInfo.ApproversField`.
