= IApprovalStageService.CopyApproversFromDocument - метод (ApprovalStage, Document)

Получает согласующих из согласуемого документа.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.ApprovalDesigner.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IEnumerable<ApprovalStageApprover> CopyApproversFromDocument(ApprovalStage approvalStage, Document document)
----

Параметры

approvalStage::
  Тип: xref:../ApprovalStage_CL.adoc[ApprovalStage]
  +
  Этап согласования, в который копируются согласующие
document::
  Тип: xref:../../../BackOffice/ObjectModel/Document_CL.adoc[Document]
  +
  Документ

Возвращаемое значение

::
  Тип: xref:../ApprovalStageApprover_CL.adoc[ApprovalStageApprover]
  +
  Добавленные согласующие

== Заметки

Метод [.keyword .apiname]#CopyApproversFromDocument# возвращает согласующих, полученных из документа `document`. Согласующие выбираются из поля секции, определенного в настройках этапа согласования `approvalStage`, в `MainInfo.ApproversField`.

*На уровень выше:* xref:../../../../../api/DocsVision/ApprovalDesigner/ObjectModel/Services/IApprovalStageService_IN.adoc[IApprovalStageService - интерфейс]
