= IApprovalStageService.AddSelectedApprover - метод (ApprovalStage, Guid)

Добавляет согласующего по поисковому слову в этап согласования.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.ApprovalDesigner.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
ApprovalStageApprover AddSelectedApprover(ApprovalStage approvalStage, Guid searchWord)
----

Параметры

approvalStage::
  Тип: xref:../ApprovalStage_CL.adoc[ApprovalStage]
  +
  Этап согласования
searchWord::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Идентификатор поискового слова, по которому будут выбираться согласующие

Возвращаемое значение

::
  Тип: xref:../ApprovalStageApprover_CL.adoc[ApprovalStageApprover]
  +
  Согласующий этапа

*На уровень выше:* xref:../../../../../api/DocsVision/ApprovalDesigner/ObjectModel/Services/IApprovalStageService_IN.adoc[IApprovalStageService - интерфейс]
