= IApprovalPathService.AddDocumentState -- метод (ApprovalPath, KindsCardKind, StatesState)

Добавляет итоговое состояние документа в Маршрут согласования.

* *Пространство имен:* xref:api/DocsVision/ApprovalDesigner/ObjectModel/Services/Services_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel.Services]
* *Сборка:* `DocsVision.ApprovalDesigner.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
ApprovalPathState AddDocumentState(ApprovalPath approvalPath, KindsCardKind kind, StatesState state)
----

Параметры::
approvalPath:::
Тип: xref:api/DocsVision/ApprovalDesigner/ObjectModel//ApprovalPath_CL.adoc[ApprovalPath]
+
Маршрут согласования
kind:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/KindsCardKind_CL.adoc[KindsCardKind]
+
Вид карточки Документ
state:::
Тип: xref:api/DocsVision/BackOffice/ObjectModel/StatesState_CL.adoc[StatesState]
+
Состояние документа

Возвращаемое значение:::
Тип: xref:api/DocsVision/ApprovalDesigner/ObjectModel/ApprovalPathState_CL.adoc[ApprovalPathState]
+
Добавленное состояние документа
