= ISearchWordResolverService.ExtractSearchWord -- метод (ObjectContext, Guid, Guid, Guid, Int32)

Возвращает сотрудников, найденных по поисковому слову.

* *Пространство имен:* xref:api/DocsVision/ApprovalDesigner/ObjectModel/Services/Services_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel.Services]
* *Сборка:* `DocsVision.ApprovalDesigner.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
IEnumerable<DocsVision.BackOffice.ObjectModel.StaffEmployee> ExtractSearchWord(ObjectContext context, Guid searchWordId, Guid initiatorId, Guid registratorId, int hierarchyLevel)
----

Параметры

context::
Тип: xref:api/DocsVision/Platform/ObjectModel/ObjectContext_CL.adoc[ObjectContext]
+
Текущий контекст объектов
searchWordId::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
+
Идентификатор поискового слова, по которому ищутся сотрудники
initiatorId::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
+
Идентификатор инициатора согласования
registratorId::
Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
+
Идентификатор согласующего
hierarchyLevel::
Тип: http://msdn.microsoft.com/ru-ru/library/system.int32.aspx[System.Int32]
+
Уровень иерархии при получении руководителей

Возвращаемое значение::
Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StaffEmployee>
+
Найденные сотрудники. Тип элемента -- xref:api/DocsVision/BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee]
