= ISearchWordResolverService.ExtractSearchWord - метод (ObjectContext, Guid, Guid, Guid)

Возвращает сотрудников, найденных по поисковому слову.

* [.keyword]*Пространство имен:* xref:Services_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel.Services]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.ApprovalDesigner.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
IEnumerable<StaffEmployee> ExtractSearchWord(ObjectContext context, Guid searchWordId, Guid initiatorId, Guid registratorId)
----

Параметры

context::
  Тип: xref:../../../Platform/ObjectModel/ObjectContext_CL.adoc[ObjectContext]
  +
  Текущий контекст объектов
searchWordId::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Идентификатор поискового слова, по которому ищутся сотрудники
initiatorId::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Идентификатор инициатора согласования
registratorId::
  Тип: http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]
  +
  Идентификатор согласующего

Возвращаемое значение

::
  Тип: http://msdn.microsoft.com/ru-ru/library/9eekhta0.aspx[System.Collections.Generic.IEnumerable]<StaffEmployee>
  +
  Найденные сотрудники. Тип элемента - xref:../../../BackOffice/ObjectModel/StaffEmployee_CL.adoc[StaffEmployee]

*На уровень выше:* xref:../../../../../api/DocsVision/ApprovalDesigner/ObjectModel/Services/ISearchWordResolverService_IN.adoc[ISearchWordResolverService - интерфейс]
