= DocsVision.ApprovalDesigner -- пространство имен

Пространство имен DocsVision.ApprovalDesigner содержит типы и методы приложения _Конструктор согласований_.

== Пространства имен

[cols=",",options="header"]
|===
|Пространство имен |Описание
|xref:api/DocsVision/Platform/ObjectModel/ObjectModel_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel] |Содержит типы объектной модели приложения Конструктор согласований.
|===

== Заметки

Для возможности получения или создания сущностей пространства имен DocsVision.ApprovalDesigner в xref:DM_FullContextInit.adoc[контексте объектов] помимо стандартных должны быть зарегистрированы дополнительные фабрики из сборки `DocsVision.ApprovalDesigner.ObjectModel.dll`:

* фабрика преобразователей данных ApprovalDesignerMapperFactory
* и фабрика сервисов ApprovalDesignerServiceFactory

[source,csharp]
----
using DocsVision.ApprovalDesigner.ObjectModel.Mapping;
// ...

var serviceFactoryRegistry = objectContext.GetService<IServiceFactoryRegistry>();
serviceFactoryRegistry.RegisterFactory(typeof(ApprovalDesignerServiceFactory));

var mapperFactoryRegistry = objectContext.GetService<IObjectMapperFactoryRegistry>();
mapperFactoryRegistry.RegisterFactory(typeof(ApprovalDesignerMapperFactory));
----
