= IBarcodeService -- интерфейс

Определяет методы генерации и печати штрих-кодов карточки

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public interface IBarcodeService
----

== Методы

[cols=",",options="header"]
|===
|Имя |Описание
|`xref:IBarcodeService.ChangeBarcode_MT.adoc[ChangeBarcode(Document, String)]` |Задает значение штрих-кода карточки документа.
|`xref:IBarcodeService.GenerateBarcode_MT.adoc[GenerateBarcode(Document)]` |Формирует штрих-код для заданной карточки документа.
|`xref:IBarcodeService.GenerateBarcode_1_MT.adoc[GenerateBarcode(Document, DateTime)]` |Формирует штрих-код для заданной карточки документа.
|`xref:IBarcodeService.GetBarcodePrintSettings_MT.adoc[GetBarcodePrintSettings(StaffEmployee, KindsCardKind)]` |Возвращает системные настройки печати.
|`xref:IBarcodeService.PrintBarcode_MT.adoc[PrintBarcode(Document, BarcodePrintSettings, PrinterSettings)]` |Отправляет на печать штрих-код документа.
|===

== Заметки

Настройки формата осуществляются в справочнике системных настроек, раздел "Штрих-коды".

== Примеры

Пример генерации штрих-кода для карточки "Документ" (вид карточки должен поддерживать использование штрих-кода, иначе при назначении вернется ошибка).

[source,csharp]
----
IBarcodeService barcodeService = objectContext.GetService<IBarcodeService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

string barcode = barcodeService.GenerateBarcode(document); <.>

barcodeService.ChangeBarcode(document, barcode); <.>
----
<.> Инициализация контекста объектов и получение сервиса штрих-кодов.
<.> Получение некого существующего Документа с идентификатором `00000000-0000-0000-0000-000000000000`.
<.> Получаем штрих-код на основе настроек из справочника системных настроек.
<.> Присваиваем полученный штрих-код документу.

== Заметки

Метод `GetBarcodePrintSettings` в большинстве случаев в настроенной системе содержит один объект, но возможны ситуации, когда таких настроек больше чем одна, в таком случае необходимо реализовать логику выбора необходимой настройки. Если настроек нет, то следует использовать настройки печати по умолчанию, которые содержатся в `BarcodePrintSettings.DefaultSettings`.
