= IBarcodeService.GetBarcodePrintSettings -- метод (StaffEmployee, KindsCardKind)

Возвращает системные настройки печати.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
BarcodePrintSettingsCollection GetBarcodePrintSettings(StaffEmployee employee, KindsCardKind cardKind)
----

Параметры::
employee:::
Тип: `xref:xref:BackOffice-ObjectModel-Staff:StaffEmployee_CL.adoc[StaffEmployee]`
+
Сотрудник, для которого выбираются настройки

cardKind:::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardKind_CL.adoc[KindsCardKind]`
+
Вид документа, для которого выбираются настройки

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BarcodePrintSettingsCollection_CL.adoc[BarcodePrintSettingsCollection]`
+
Настройки печати, представленные коллекцией элементов типа `xref:BackOffice-ObjectModel-BaseCard:BarcodePrintSettings_CL.adoc[BarcodePrintSettings]`

== Заметки

Настроек, проходящих выборку, может быть несколько, поэтому итоговое решение, по применению той или иной настройки, принимается разработчиком.

== Примеры

Ниже приведен пример скрипта карточки, позволяющий определить необходимость печати штрих-кода (определена в системных настройках)

[source,csharp]
----
private void Button_Click(System.Object sender, System.EventArgs e)
{
 IBarcodeService iBarcodeService = CardControl.ObjectContext.GetService<IBarcodeService>();
 IStaffService staffService = CardControl.ObjectContext.GetService<IStaffService>(); <.>

 BarcodePrintSettingsCollection printSettingsCollection = iBarcodeService.GetBarcodePrintSettings(staffService.GetCurrentEmployee(), 
            BaseObject.SystemInfo.CardKind); <.>
        
 if (printSettingsCollection.Count() > 0)
 {
  BarcodePrintSettings printSettings = printSettingsCollection.FirstOrDefault(); <.>

  bool isPrinting = printSettings.IsPrinting; <.>
 }
}
----
<.> Получение сервисов.
<.> Получение настроек печати штрих-кода, для текущего пользователя.
<.> Получение первой подходящей настройки.
<.> Если `false` -- установлен признак "Не печатать штрих код".
