= Удаление объектов

Платформа {dv} позволяет удалять не только карточки, но и отдельные строки их секций. Для этого каждый уровень API предлагает собственные методы.

== Удаление объекта методами базового API

Для удаления экземпляра карточки на уровне базового API предназначен метод `DeleteCard` _менеджера карточек_, принимающий идентификатор удаляемой карточки:

[source,csharp]
----
userSession.CardManager.DeleteCard(cardId); <.> <.>
----
<.> `userSession` -- пользовательская сессия.
<.> `cardId` -- идентификатор удаляемой карточки.

Приведенный выше код удаляет карточку без возможности восстановления, при этом другая перегрузка метода позволяет пометить карточку как удалённую (в {wincl}е отображается курсивом) без фактического удаления:

[source,csharp]
----
userSession.CardManager.DeleteCard(cardId, false); <.>
----
<.> Для возможности восстановления второй параметр должен иметь значение `false`.

Чтобы восстановить карточку, помеченную к удалению, используйте метод `RestoreCard`:

[source,csharp]
----
userSession.CardManager.RestoreCard(cardId);
----

Чтобы удалить строку из секции карточки, необходимо использовать метод `DeleteRow` сущности секции. В качестве примера, удалим первую строку из секции карточки:

[source,csharp]
----
CardData card = userSession.CardManager.GetCardData(cardId); <.>

SectionData section = card.Sections[sectionId]; <.>

Guid firstRowId = section.FirstRow.Id; <.>

section.DeleteRow(firstRowId); <.>
----
<.> Получаем карточку, из которой удаляется строка.
<.> Получаем сущность секции.
+
`sectionId` -- идентификатор секции, из которой удаляется строка. Чтобы получить идентификатор секции стандартных карточек, обратитесь к разделу xref:schemas:standard-card-fields.adoc[Описание полей стандартной карточки].
+
<.> Получаем идентификатор первой строки.
<.> Выполняем удаление.

Обычно идентификатор удаляемой строки заранее известен, поэтому фактически удаление можно привести к виду:

[source,csharp]
----
card.Sections[sectionId].DeleteRow(rowId);
----

== Удаление объекта на уровне объектной модели

Данный уровень API предлагает использовать для удаления объектов единый метод контекста объектов -- `xref:Platform-ObjectModel:ObjectContext.DeleteObject_MT.adoc[DeleteObject]`. В качестве примера его применения, удалим один из файлов документа (карточка типа _Документ_):

[source,csharp]
----
Document document = objectContext.GetObject<Document>(cardId); <.>

DocumentFile file = document.Files.First(); <.>

objectContext.DeleteObject(file); <.>
objectContext.AcceptChanges();
----
<.> Получаем карточку типа _Документ_.
<.> Для простоты, выбираем для удаления первый файл по списку.
<.> Удаляем файл и сохраняем изменения.

Данный код фактически выполняет удаление строки из секции `Файлы` карточки _Документ_, по аналогии с рассмотренным выше примером для базового API. Аналогичным образом может быть удалён и сам документ.

Метод `DeleteObject` удаляет объект без возможности восстановления. Если требуется пометить карточку как удалённую, используйте базовый API.

Контекст объектов предлагает функциональность по отмене изменений объекта до его сохранения (вызова метода `AcceptChanges` или `SaveObject`), основанную на использовании методов `RollbackChanges` и `RollBackObject` (см. xref:views:delayed-changes.adoc[Режим отложенных изменений]).
