= ObjectContext.FindObject<T> -- метод (QueryObject)

Возвращает первый результат поиска, удовлетворяющий заданным условиям.

* *Пространство имён:* `xref:ObjectModel_NS.adoc[DocsVision.Platform.ObjectModel]`
* *Сборка:* `DocsVision.Platform.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public T FindObject<T>(QueryObject query) where T : ObjectBase
----

Параметры типа

T::
Тип объекта поиска, унаследованный от `xref:ObjectBase_CL.adoc[ObjectBase]`

Параметры::
query:::
Тип: `xref:Search/QueryObject_CL.adoc[QueryObject]`
+
Поисковый запрос

Возвращаемое значение::
Тип: `T`
+
Объект, являющийся результатом поиска

== Примеры

В приведенном примере выполняется поиск сотрудника с названием учетной записи "DOMAIN\\IvanovII"

[source,csharp]
----
<.>

QueryObject query = new QueryObject(StaffEmployee.AccountNameProperty.Name, "DOMAIN\\IvanovII"); <.>
StaffEmployee staff = context.FindObject<StaffEmployee>(query); <.>
----
<.> Инициализация контекста объектов.
<.> Формирование поискового запроса по полю `AccountName`.
<.> Выполнение запроса.

Если сотрудника с учетной записью `DOMAIN\IvanovII` нет в справочнике, поиск вернет `null`. Можно проверить, добавив скрипт на кнопку:

[source,csharp]
----
    ObjectContext context = this.CardControl.ObjectContext;
		QueryObject query = new QueryObject(StaffEmployee.AccountNameProperty.Name, "DOMAIN\\IvanovII");
		StaffEmployee staff = context.FindObject<StaffEmployee>(query);
		if (staff == null)
			MessageBox.Show("Не найдено");
		else
			MessageBox.Show(staff.DisplayString);
----
