= ObjectContext.GetObject -- метод (IObjectRef, IDictionary<String, Object>)

Получает объект по переданной ссылки. Также передаются дополнительные параметры получения объекта.

* *Пространство имён:* `xref:ObjectModel_NS.adoc[DocsVision.Platform.ObjectModel]`
* *Сборка:* `DocsVision.Platform.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public ObjectBase GetObject(IObjectRef objectRef, IDictionary<string, object> parameters)
----

Параметры::
objectRef:::
Тип: `xref:IObjectRef_IN.adoc[IObjectRef]`
+
Ссылка на объект

parameters:::
Тип: `https://msdn.microsoft.com/ru-ru/library/s4ys34ea.aspx[System.Collections.Generic.IDictionary]<String, Object>`
+
Дополнительные параметры, используемые при загрузке в контекст объектов отсутствующего объекта

Возвращаемое значение::
Тип: `xref:ObjectBase_CL.adoc[ObjectBase]`
+
Искомый объект

== Заметки

Параметр `parameters` может быть использован для изменения данных загружаемой карточки, до её непосредственной загрузки в контекст. Если объект был загружен в контекст ранее, то передача параметра `parameters` не возымеет эффекта.

== Примеры

Ниже приведён пример использования перегрузки метода GetObject с целью подмены примечания к карточке Документ

[source,csharp]
----
<.>

IObjectRef objectRef = objectContext.GetObjectRef(typeof(Document), new Guid("00000000-0000-0000-0000-000000000000"));  <.>

IDictionary<string, object> properties = new Dictionary<string, object>();
properties.Add(Document.DescriptionProperty.Name, "OverrideDescription"); <.>

Document document = (Document)objectContext.GetObject(objectRef, properties); <.>

Console.WriteLine(document.Description); <.>
----
<.> Инициализация контекста объектов.
<.> Получение ссылки на объект.
<.> Установка дополнительных параметров загрузки.
<.> Получение документа.
<.> Вывод измененного примечания.
