= Реализация пользовательского интерфейса карточки

После завершения реализации стандартных интерфейсов, следующим шагом в разработке компонента карточки является расположение на контрольном элементе карточки различных элементов, предназначенных для управления поведением карточки; ввода, редактирования и удаления данных; и прочих необходимых функций. В качестве элементов управления могут быть использованы стандартные элементы управления Visual Studio, дополнительные контрольные элементы сторонних производителей или специализированные элементы управления Docsvision.

Элементы управления {dv} реализованы в библиотеке `DocsVision.Platform.WinForms.dll.` Для удобства, можно добавить элементы управления на панель инструментов Visual Studio (Toolbox), с выбором указанной библиотеки.

[NOTE]
====
Для карточек, разрабатываемых по технологии WPF, отдельных элементов управления {dv} не предусмотрено, поэтому при разработке карточки могут использоваться только стандартные элементы управления.
====

Элементы управления из библиотеки *DocsVision.Platform.WinForms.dll* можно условно разделить на три группы:

* *Источники данных* -- эти элементы управления сами не отображаются на форме и не взаимодействуют с пользователем, а служат только в качестве источников данных для других элементов управления. К этой группе относятся:
** *SessionSource* -- соединение с сервером Docsvision
** *CardDataSource* -- набор данных карточек
** *RowDataSource* -- набор строксекции карточки
** *InfoRowDataSource* -- данные представления
** *ReportDataSource* -- данные хранимой процедуры
* *Интерактивные элементы управления* -- элементы управления, которые размещаются на форме и с которыми напрямую взаимодействует пользователь. К этой группе относятся:
** *BoundChooseBox* -- универсальный элемент управления для выбора значений ссылочных полей
** *CardChooseBox* -- специализированный элемент управления для выбора карточек
** *FolderChooseBox*– специализированный элемент управления для выбора папок
** *RowChooseBox* -- элемент управления для выбора любых объектов
** *BoundTreeView* -- элемент управления для работы с иерархической секцией
** *WizardControl* -- вспомогательный элемент управления для создания Мастеров
** *NavigationToolStrip* -- навигационная панель инструментов
* *Диалоги* -- вспомогательные диалоги, которые могут быть вызваны из текущей формы, и открываются в новом окне:
** *SelectDirectoryEntryDialog* -- диалог выбора пользователя из Active Directory
** *SelectOrganisationalUnitDialog* -- диалог выбора подразделения из Active Directory
** *SelectDomainDialog* -- диалог выбора домена из Active Directory
** *SelectIconDialog* -- диалог выбора иконки из файла на диске

Описание данных элементов управление приведено в разделе xref:CardsDevCompControlsTools.adoc[Устаревшие элементы управления Docsvision].

Кроме стандартных элементов управления {dv}, описанных выше, могут быть использованы элементы управления из сборки `DocsVision.BackOffice.WinForms.dll`, которые возможно добавить в Toolbox Visual Studio.

Из сборки доступны следующие элементы управления:

* Элементы выбора данных Docsvision:
** *CardChooseBox* -- элемент управления для выбора карточки, аналогичен CardChooseBox из DocsVision.Platform.WinForms
** *RowChooseBox* -- элемент управления для выбора строки справочника, аналогичен RowChooseBox из DocsVision.Platform.WinForms
** *RowMultiChooseBox* -- элемент для выбора нескольких значений;
** *CommunicativeChooseBox* -- элемент для выбора сотрудника с возможностью интеграции с Microsoft Office Communicator/Lync
** *CommunicativeMultiChooseBox* -- элемент для выбора нескольких сотрудников
** *UniversalDirectoryChooseBox* -- элемент для выбора значения из Конструктора справочников
* Сложные элементы управления для работы с базовыми объектами:
** *CategoryListView* -- элемент выбора категорий карточки из дерева категорий
** *HistoryGrid* -- таблица журнала карточки
** *ReferenceListView* -- элемент для работы с файлами и ссылками
** *TaskTreeView* -- элемент для работы со связанными задачами
* Дополнительные элементы *выбора данных*:
** *FileSystemFileBox* -- элемент выбора файла с файловой системы
** *FolderChooseBox* -- элемент выбора папки с файловой системы
* *Вспомогательные*:
** *CommunicatorControl* -- элемент управления, отображающий статус пользователя в MS Office Communicator/Lync, позволяющий осуществить сеанс связи с пользователем (звонок, отправка мгновенного сообщения, отправка электронной почты). Используется в CommunicativeChooseBox и CommunicativeMultiChooseBox.
** *Preview* -- элемент просмотра содержимого файла. Используются средства предпросмотра, установленные в операционной системе (аналогично Microsoft Outlook ).

[IMPORTANT]
====
Пробную версию компонентов Developer Express можно получить с сайта https://www.devexpress.com/[devexpress.com], также необходимые сборки включены в инсталляционный пакет {dv} Client. При создании конечного продукта требуется приобрести соответствующую лицензию.
====

Описание данных элементов управление приведено в разделе xref:CardsDevCompControlsBO.adoc[Элементы управления Docsvision].
