= Раздел "Actions"

В разделе _Actions_ можно указать действия (команды), "понятные" данной карточке. В качестве команд могут выступать, например, такие действия как _Открыть в другом режиме_, _Переслать_, _Списать в архив_ и т. д.

Разработчик сам определяет перечень этих команд, их названия и семантику. Фактически, все описанные команды появляются в меню действий над карточкой в окне {wincl}а. При выборе пользователем одной из команд будет вызван клиентский компонент карточки с указанием идентификатора активированной команды и требуемые операции нужно будет запрограммировать самостоятельно в коде этого компонента.

Для добавления действий следует перейти в раздел _Actions_ и выбрать пункт меню _New action_.

.Описание действий над карточкой
image::card-actions-descriptionpng[Описание действий над карточкой]

.Свойства действия (метода) включают в себя:
* _Псевдоним_ -- псевдоним действия, с помощью которого к нему можно обращаться в коде. Псевдоним должен быть уникальным в рамках карточки.
* _Названия_ -- локализованные названия команды, отображаемые у пользователя в меню действий над карточкой.
* _Идентификатор_ -- уникальный идентификатор метода.
