= Раздел "Sections", Добавление полей и дочерних секций

Создание секции также включает в себя добавление полей и дочерних секций. Для этого следует выбрать нужную секцию и воспользоваться командой _New field_ или _New section_. Дочерние секции содержат те же свойства, что и секции первого уровня.

.Редактирование поля секции]
image::edit-section-fieldpng[Редактирование поля секции]

.Описание поля содержит следующие свойства:
* _Псевдоним_ -- псевдоним поля, с помощью которого к нему можно обращаться в коде. Псевдоним должен быть уникальным в рамках секции.
* _Тип_ -- тип (формат) данных в поле. Возможные типы полей:
** _int_ -- целое.
** _bool_ -- булево значение (Да/Нет).
** _datetime_ -- дата и время.
** _date_ -- дата.
** _time_ -- время.
** _enum_ -- перечисление (предопределённый набор уникальных значений).
** _bitmask_ -- битовая маска.
** _uniqueid_ -- уникальный идентификатор (`GUID`).
** _userid_ -- идентификатор пользователя.
** _string_ -- строка. Ограничение по размеру: не более `8000` символов.
** _unistring_ -- строка в формате `Unicode`. Ограничение по размеру: не более `4000` символов.
** _fileid_ -- идентификатор файла {dv}.
** _float_ -- число с плавающей точкой.
** _refid_ -- ссылка на строку другой секции.
** _refcardid_ -- ссылка на карточку.
** _text_ -- текст. Ограничение по размеру: 2^31-1^ байт (2 Гб).
** _unitext_ -- текст в формате Unicode. Ограничение по размеру: 2^31-1^ байт (2 Гб).
** _binary_ -- двоичные данные.
** _image_ -- изображение.
** _sdid_ -- идентификатор безопасности.
** _decimal_ -- десятичное число.
** _variant_ -- значение переменного типа.
* _Размер_ -- ограничение длины поля (используется в основном для полей строчного типа).
* _Тип ссылки_ -- указание типа ссылки для ссылочных полей (`refid`, `refcardid`).
+
Тип ссылки характеризует поведение объектов, связанных ссылкой.
+
.Возможны следующие типы ссылок:
** _Weak_ -- связанный объект разрешено удалять. При удалении объекта, содержащего ссылку, связанный объект останется.
** _Hard_ -- связанный объект запрещено удалять, пока на него существует ссылка. При удалении объекта, содержащего ссылку, связанный объект также будет автоматически удален.
** _None_ -- при удалении связанного объекта значение ссылочного поля будет очищено.
** _Auto_ -- при удалении связанного объекта будет удалена вся строка секции, содержащей ссылку.
* _Копирование_ -- режим копирования данных поля. Возможны следующие режимы:
** _Null_ -- значение поля при копировании обновляется.
** _Copy_ -- значение поля копируется.
** _CreateNew_ -- создание нового значения (используются для ссылок).
* _Названия_ -- локализованные названия поля, отображаемые у пользователя.
* _Description_ -- словесное описание поля, будет отображаться в виде подсказки к полю в диалогах поиска и представлений.
* _Идентификатор_ -- уникальный идентификатор поля.
* _Тип, куда ссылаемся (ID)_ -- уникальный идентификатор типа карточки, с полями или секциями которой связано данное поле. Тип карточки можно выбрать в диалоге типов.
* _Раздел, куда ссылаемся (ID)_ -- идентификатор секции связанной карточки, с полями которого осуществляется связь.
* _Значение по умолчанию_ -- значение поля, которое будет автоматически задаваться при создании новых экземпляров карточки.
* _Обязательное_ -- значение данного поля не может быть пустым. Система не позволит сохранить карточку без заданного значения этого поля.
* _Зависит от пользователя_ -- значение поля сопоставляется с конкретным пользователем системы. Таким образом, для каждого пользователя может храниться собственное уникальное значение этого поля.
* _Исключить из поиска_ -- поле не участвует в поиске и не отображается в диалоге поиска.
* _Удалять связанную строку при изменении значения_ -- признак удаления связанных строк в случае изменения значения этого поля (используется для ссылочных полей).
* _Отображается на форме карточки_ -- поле может быть сопоставлено с элементом пользовательского интерфейса. Этот признак используется в справочнике типов, если данная карточка обеспечивает возможность "тонкой" настройки.
* _Системное_ -- признак того, что поле является системным. Учитывается при некоторых операциях с данными.
* Также здесь содержится список полей связанной карточки, значения которых ассоциируются со строкой этой секции. Используются для ссылочных полей. Данная возможность позволяет при обращении к данным секции вернуть не только значения их собственных полей, но и ряда полей связанных карточек или секций. Это может быть удобным, например, чтобы снизить число обращений к серверу при чтении данных карточки или при её экспорте и печати.
