= Программное открытие справочников

.Во всех следующих примерах, описывающих методы открытия различных видов справочников:
* `selectionMode` -- определяет метод открытия записи и соответствует значению из перечисления xref:api/DocsVision/BackOffice/WinForms/Controls/ItemSelectionMode_EN.adoc[`DocsVision.BackOffice.WinForms.Controls.ItemSelectionMode`] приведенному к `System.Int32`.
+
.Допустимые значения:
** `0` -- позиционирование на записи.
** `1` -- открытие записи для редактирования.
** `2` -- открытие записи для чтения.
* `multiselect` -- возможность выбора нескольких записей, соответствует типу `System.Boolean`.
+
Значение `true`(множественный выбор разрешен) допустимо при `selectionMode` установленном в `0`, иначе должно быть `false` .

Методы в примере вызываются из некого скрипта, привязанного с кнопке в _Конструкторе разметок_. В компоненте карточки, унаследованном от xref:api/DocsVision/Platform/WinForms/CardControl_CL.adoc[`DocsVision.Platform.WinForms.CardControl`] или xref:api/DocsVision/BackOffice/WinForms/BaseCardControl_CL.adoc[`BaseCardControl`], код будет выглядеть аналогично. Единственное отличие в том, что параметр `CardHost` будет доступен уже из базового класса.

== Открытие записи из "Справочника категорий" в режиме редактирования

[source,csharp]
----
private void RefCategories_Click(object sender, EventArgs e) 
{
 string categoryID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant(); <.>
 int selectionMode = 1;
 bool multiselect = false;

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefCategories.ID; <.>

 object activateParams = new object[] { System.Reflection.Missing.Value, categoryID, multiselect, System.Reflection.Missing.Value, 
     selectionMode }; <.>

 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None,
     activateParams); <.>
}
----
<.> Идентификатор выбираемой категории в Справочнике категорий.
<.> Идентификатор Справочника категорий.
<.> Параметры активации.
<.> Вызов метода отображения карточки в режиме редактирования.

== Открытие записи из "Справочника ссылок" в режиме редактирования

[source,csharp]
----
private void RefLinks_Click(object sender, EventArgs e) 
{
 string linkID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant(); <.>
 int selectionMode = 1;
 bool multiselect = false;

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefLinks.ID; <.>

 object activateParams = new object[] { System.Reflection.Missing.Value, linkID, multiselect, System.Reflection.Missing.Value, 
     System.Reflection.Missing.Value, selectionMode }; <.>

 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None, 
     activateParams); <.>
}
----
<.> Идентификатор выбираемой ссылки в Справочнике ссылок.
<.> Идентификатор Справочника ссылок.
<.> Параметры активации.
<.> Вызов метода показа карточки в режиме редактирования.

== Открытие записи сотрудника из "Справочника сотрудников" в режиме редактирования

[source,csharp]
----
private void RefStaffEmployees_Click(object sender, EventArgs e) 
{
 string employeeID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant(); <.>
 int selectionMode = 1;
 bool multiselect = false;

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefStaff.ID; <.>

 string sectionID = DocsVision.BackOffice.CardLib.CardDefs.RefStaff.Employees.ID.ToString("B").ToUpperInvariant(); <.>

 object activateParams = new object[] { sectionID, employeeID, System.Reflection.Missing.Value, System.Reflection.Missing.Value,
     System.Reflection.Missing.Value, multiselect, false, false, 0, System.Reflection.Missing.Value, true, true, selectionMode }; <.>
 
 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None, 
     activateParams);
}
----
<.> Идентификатор выбираемого сотрудника.
<.> Идентификатор Справочника сотрудников.
<.> Идентификатор выбираемой секции справочника -- сотрудники.
<.> Параметры активации.

== Открытие записи группы из "Справочника сотрудников" в режиме редактирования

[source,csharp]
----
private void RefStaffGroups_Click(object sender, EventArgs e) 
{
 string groupID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant();
 int selectionMode = 1;
 bool multiselect = false; <.>

 string sectionID = DocsVision.BackOffice.CardLib.CardDefs.RefStaff.AlternateHierarchy.ID.ToString("B").ToUpperInvariant(); <.>

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefStaff.ID; <.>

 object activateParams = new object[] { sectionID, groupID, System.Reflection.Missing.Value, System.Reflection.Missing.Value, 
     System.Reflection.Missing.Value, multiselect, false, false, 0, System.Reflection.Missing.Value, true, true, selectionMode }; <.>

 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None, 
     activateParams); <.>
}
----
<.> Идентификатор выбираемой группы.
<.> Идентификатор выбираемой секции справочника -- группы.
<.> Идентификатор Справочника Сотрудников.
<.> Параметры активации.

== Открытие записи организации из "Справочника сотрудников" в режиме редактирования

[source,csharp]
----
private void RefStaffUnits_Click(object sender, EventArgs e) 
{
 string unitID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant();
 int selectionMode = 1;
 bool multiselect = false; <.>

 string sectionID = DocsVision.BackOffice.CardLib.CardDefs.RefStaff.Units.ID.ToString("B").ToUpperInvariant(); <.>

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefStaff.ID; <.>

 object activateParams = new object[] { sectionID, unitID, System.Reflection.Missing.Value, System.Reflection.Missing.Value, System.Reflection.Missing.Value,
     multiselect, false, false, 0, System.Reflection.Missing.Value, true, true, selectionMode }; <.>

 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None, 
     activateParams); <.>
}
----
<.> Идентификатор выбираемой организации.
<.> Идентификатор выбираемой секции справочника -- организации.
<.> Идентификатор Справочника Сотрудников.
<.> Параметры активации.
<.> Вызов метода показа карточки в режиме редактирования.

== Открытие записи сотрудника из "Справочника контрагентов" в режиме редактирования

[source,csharp]
----
private void RefPartnersEmployees_Click(object sender, EventArgs e) 
{
 string employeeID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant();
 int selectionMode = 1; <.>
 bool multiselect = false;

 string sectionID = DocsVision.BackOffice.CardLib.CardDefs.RefPartners.Employees.ID.ToString("B").ToUpperInvariant(); <.>

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefPartners.ID; <.>

 object activateParams = new object[] { sectionID, employeeID, System.Reflection.Missing.Value, System.Reflection.Missing.Value, System.Reflection.Missing.Value, 
     multiselect, System.Reflection.Missing.Value, false, true, true, selectionMode }; <.>

 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None, 
     activateParams); <.>
}
----
<.> Идентификатор выбираемого сотрудника.
<.> Идентификатор выбираемой секции справочника -- сотрудники.
<.> Идентификатор Справочника контрагентов.
<.> Параметры активации.
<.> Вызов метода показа карточки в режиме редактирования.

== Открытие записи группы из "Справочника контрагентов" в режиме редактирования

[source,csharp]
----
private void RefPartnersGroups_Click(object sender, EventArgs e) 
{
 string groupID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant();
 int selectionMode = 1; <.>
 bool multiselect = false;

 string sectionID = DocsVision.BackOffice.CardLib.CardDefs.RefPartners.Groups.ID.ToString("B").ToUpperInvariant(); <.>

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefPartners.ID; <.>

 object activateParams = new object[] { sectionID, groupID, System.Reflection.Missing.Value, System.Reflection.Missing.Value, System.Reflection.Missing.Value, 
     multiselect, System.Reflection.Missing.Value, false, true, true, selectionMode }; <.>

 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None, 
     activateParams); <.>
}
----
<.> Идентификатор выбираемой группы.
<.> Идентификатор выбираемой секции справочника -- группы.
<.> Идентификатор Справочника контрагентов.
<.> Параметры активации.
<.> Вызов метода показа карточки в режиме редактирования.

== Открытие записи организации из "Справочника контрагентов" в режиме редактирования

[source,csharp]
----
private void RefPartnersCompanies_Click(object sender, EventArgs e) 
{
 string unitID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant();
 int selectionMode = 1; <.>
 bool multiselect = false;

 string sectionID = DocsVision.BackOffice.CardLib.CardDefs.RefPartners.Companies.ID.ToString("B").ToUpperInvariant(); <.>

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefPartners.ID; <.>

 object activateParams = new object[] { sectionID, unitID, System.Reflection.Missing.Value, System.Reflection.Missing.Value, System.Reflection.Missing.Value, 
     multiselect, System.Reflection.Missing.Value, false, true, true, selectionMode }; <.>

 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None, 
     activateParams); <.>
}
----
<.> Идентификатор выбираемой организации.
<.> Идентификатор выбираемой секции справочника -- организации.
<.> Идентификатор Справочника контрагентов.
<.> Параметры активации.
<.> Вызов метода показа карточки в режиме редактирования.

== Открытие записи из "Справочника видов карточек" в режиме позиционирования

[source,csharp]
----
private void RefKindsCompanies_Click(object sender, EventArgs e) 
{
 string rootKindID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant(); <.>

 string kindID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant(); <.>

 string sectionID = DocsVision.BackOffice.CardLib.CardDefs.RefKinds.CardKinds.ID.ToString("B").ToUpperInvariant(); <.>

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefKinds.ID; <.>
 
 object activateParams = new object[] { sectionID, rootKindID, System.Reflection.Missing.Value, true, System.Reflection.Missing.Value, kindID, 
     System.Reflection.Missing.Value, System.Reflection.Missing.Value, System.Reflection.Missing.Value };
 
 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None, 
     activateParams);
}
----
<.> Идентификатор типа карточки (например, Документ).
<.> Идентификатор выбираемого вида карточки (например, Внутренний).
<.> Идентификатор выбираемой секции справочника.
<.> Идентификатор Справочника видов карточек.

[NOTE]
====
Справочник видов карточек поддерживает исключительно позиционирование на записи.
====

== Открытие записи узла из "Конструктора справочников" в режиме редактирования

[source,csharp]
----
private void RefBaseUniversalNode_Click(object sender, EventArgs e) 
{
 string nodeID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant(); <.>
 int selectionMode = 1;

 string sectionID = new Guid("A1DCE6C1-DB96-4666-B418-5A075CDB02C9").ToString("B").ToUpperInvariant(); <.>

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefBaseUniversal.ID; <.>

 object activateParams = new object[] { sectionID, nodeID, System.Reflection.Missing.Value, selectionMode }; <.>

 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None, 
     activateParams); <.>
}
----
<.> Идентификатор выбираемого узла.
<.> Идентификатор выбираемой секции справочника -- Узлы справочника.
<.> Идентификатор Конструктора справочников.
<.> Параметры активации.
<.> Вызов метода показа карточки в режиме редактирования.

== Открытие записи строки из "Конструктора справочников" в режиме редактирования

.Пример открытия на редактирование строки "Вид ОРД / Приказ":
[source,csharp]
----
private void RefBaseUniversalString_Click(object sender, EventArgs e) 
{
 Guid stringID = new Guid("285A31D9-2433-415A-AEC7-BAD45E705389"); 
 int selectionMode = 1; <.>

 Guid nodeID = new Guid("B8B58477-CCC3-4213-8190-EFC66FEF86C1"); <.>

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefBaseUniversal.ID; <.>

 object activateParams = new object[] { RefBaseUniversal.Items.ID, stringID, nodeID, selectionMode }; <.>

 base.CardControl.CardHost.ShowCard(RefBaseUniversal.ID, Guid.Empty, ActivateMode.Edit, ActivateFlags.None, activateParams); <.>
}
----
<.> Идентификатор выбираемой строки.
<.> Идентификатор узла содержащего выбираемую строку.
<.> Идентификатор Конструктора справочников.
<.> Параметры активации.
<.> Вызов метода показа карточки в режиме редактирования.

== Открытие записи из "Справочника серверов" в режиме редактирования

[source,csharp]
----
private void RefBaseUniversalString_Click(object sender, EventArgs e) 
{
 string serverID = new Guid("00000000-0000-0000-0000-000000000000").ToString("B").ToUpperInvariant(); <.>
 int selectionMode = 1;

 Guid cardID = DocsVision.BackOffice.CardLib.CardDefs.RefServers.ID; <.>

 object activateParams = new object[] { System.Reflection.Missing.Value, serverID, selectionMode }; <.>

 base.CardControl.CardHost.ShowCard(cardID, Guid.Empty, DocsVision.Platform.CardHost.ActivateMode.Edit, DocsVision.Platform.CardHost.ActivateFlags.None, 
     activateParams); <.>
}
----
<.> Идентификатор выбираемого сервера.
<.> Идентификатор Справочника серверов.
<.> Параметры активации.
<.> Вызов метода показа карточки в режиме редактирования.
