= Разработка скриптов карточки

Помимо разработки новых типов карточек, а также модификации компонентов существующих, новая бизнес-логика может быть добавлена в карточку с помощью скрипта карточки. В скриптах используется стандартный API {dv} (базовый и объектная модель), а средой разработки служит xref:baseobjects:desdirs:layouts/designer.adoc["Конструктор разметок"] и xref:baseobjects:desdirs:scripts/designer.adoc["Конструктор скриптов"], описание работы с которыми приведено в документации для модуля _Базовые объекты_.

В данном разделе приведена информация о специальных возможностях API {dv}, которые могут быть использованы в скриптах карточки.

.В этом разделе:
* xref:scripts/get-control.adoc[Доступ к элементам управления карточки]
* xref:scripts/card-host.adoc[Взаимодействие с контейнером карточек]
* xref:scripts/event-subscription.adoc[Подписка на события]
* xref:scripts/get-child-cards.adoc[Доступ к подчиненным карточкам из карточки BackOffice]
* xref:scripts/get-ribbon.adoc[Доступ к элементам ленты карточки]
