= Доступ к элементам ленты карточки

Лента карточки -- сущность типа https://documentation.devexpress.com/#WindowsForms/clsDevExpressXtraBarsRibbonRibbonControltopic[RibbonControl], доступ к которой обеспечивает одноименное свойство класса xref:api/DocsVision/BackOffice/WinForms/ICustomizableControl_IN.adoc[ICustomizableControl]:

[source,csharp]
----
RibbonControl ribbonControl = (CardControl as ICustomizableControl).RibbonControl;
----

Класс RibbonControl предоставляет доступ к существующим элементам ленты (страницы, группы и элементы), а также позволяет добавлять новые. В качестве примера использования данной сущности рассмотрим сценарий добавления на ленту карточки _Документ_ новой кнопки на страницу "Документ" в группу "Общие". Добавление может осуществляться при загрузке карточки при соблюдении условий, или при выполнении определенных действий с карточкой, или иной бизнес-логики, когда стандартных механизмов (например, ролевой модели) недостаточно для реализации сценария. В приведенном далее примере добавление нового элемента -- кнопки, выполняется при загрузке карточки.

[source,csharp]
----
// Обработчик загрузки карточки нужно добавить через Конструктор разметок
private void CardDocument_CardLoaded(System.Object sender, System.EventArgs e)
{
 // Получение доступа к элементам разметки
 ICustomizableControl customizable = this.CardControl as ICustomizableControl;
 if (customizable != null)
 {
  // Создание кнопки
  DevExpress.XtraBars.BarButtonItem button = new DevExpress.XtraBars.BarButtonItem(customizable.BarManager, "Новая кнопка");

  // Обрабочик нажатия
  button.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(MyRibbonButton_ItemClick);

  // Добавление кнопки на ленту
  // Обратите внимание, что доступ к определенной странице осуществляется по отображаемому (на ней) тексту, а к группе элементов -- по названию
  // Название и текст элементов задаются при добавлении через Конструктор разметок, а для стандартных (как в примере) сущностей данные параметры можно получить, к примеру, предварительно перебрав их foreach-ем 
  customizable.RibbonControl.Pages["Документ"].Groups["commonActionsRibbonPageGroup"].ItemLinks.Add(button);
 }
}

// Обработчик нажатия добавленной кнопки
private void MyRibbonButton_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
 MessageBox.Show("Выполняется сценарий нажатия кнопки 'Новая кнопка'");
}
----
