= Описание (схема) форматирования

Важной частью представления, помимо получения данных, является их форматирование (а также, возможно, дополнительная обработка) при отображении в конечном клиентском приложении.

{wincl}, который является базовым средством для работы с представлениями, предлагает следующие возможности обработки и форматирования данных:

* Фильтрация данных (при помощи дополнительных фильтров).
* Агрегация (вычисление статистических величин).
* Группировка данных в таблице.
* Сортировка данных в таблице.
* Указание шрифта для таблицы.
* Разметка линий сетки в таблице.
* Указание ширины строк в таблице.
* Задание имён колонок.

Для работы с настройками представлений {wincl}а в объектной модели предусмотрен объект `xref:api/DocsVision/Platform/ObjectManager/SystemCards/NavigatorCard.ViewSettings_PR.adoc[ViewSettings]`, доступный из карточки {wincl}а `xref:api/DocsVision/Platform/ObjectManager/SystemCards/NavigatorCard_CL.adoc[NavigatorCard]`.

Каждому конкретному представлению соответствуют индивидуальные настройки отображения, поэтому общее число объектов `ViewSettings` соответствует количеству настроенных в системе представлений.

.Пример кода работы с настройками представления:
[source,csharp]
----
SavedView view = viewcard.Views[0]; <.>

const string NAVIGATOR_CARD_TYPE = "{A7F9784B-96A4-4B3E-B820-2E714A2A1463}";
NavigatorCard nav = (NavigatorCard)session.CardManager.GetDictionary(new Guid(NAVIGATOR_CARD_TYPE)); <.>

ViewSettings settings = nav.ViewSettings[view.Id]; <.>

foreach(ViewColumnSettings col in settings.Columns)
{
 MessageBox.Show(col.Caption); <.>
}
----
<.> Получение первого попавшегося представления.
<.> Получение карточки {wincl}а.
<.> Получение настроек представления.
<.> Перебор всех колонок и вывод их названий.
