= ApprovalStageDecision.SaveImage - метод (ObjectContext, ApprovalStage, Image)

Загружает иконку для варианта завершения этапа согласования.

* [.keyword]*Пространство имен:* xref:ObjectModel_NS.adoc[DocsVision.ApprovalDesigner.ObjectModel]
* [.keyword]*Сборка:* [.ph .filepath]`DocsVision.ApprovalDesigner.ObjectModel.dll`

== Синтаксис

[source,pre,codeblock,language-csharp]
----
public void SaveImage(ObjectContext objectContext, ApprovalStage stage, Image image)
----

Параметры

objectContext::
  Тип: xref:../../Platform/ObjectModel/ObjectContext_CL.adoc[ObjectContext]
  +
  Текущий контекст объектов
stage::
  Тип: xref:ApprovalStage_CL.adoc[ApprovalStage]
  +
  Этап согласования, содержащий данный вариант завершения.
image::
  Тип: https://msdn.microsoft.com/ru-ru/library/system.drawing.image.aspx[System.Drawing.Image]
  +
  Загружаемое изображение

*На уровень выше:* xref:../../../../api/DocsVision/ApprovalDesigner/ObjectModel/ApprovalStageDecision_CL.adoc[ApprovalStageDecision - класс]
