= Создание расширения для Консоли настройки

[NOTE]
====
Исходный код _SnapIn_ расположен в подкаталоге `NetstatSolution.Snapin` приложенного архива.
====

На данном этапе необходимо создать расширение для Консоли настройки (_SnapIn_), которое отвечает за загрузку `CardPackage` и `SqlPackage` в {dv}, а также регистрирует пакет установки клиентской части.

[IMPORTANT]
====
_SnapIn_ является обязательным компонентом, при условии, что _решение_ использует собственную библиотеку карточек.
====

.Как часть "Модуля учета сетевых устройств", данный компонент выполняет следующие задачи:
* Устанавливает и удаляет библиотеку карточек _Модуля учета сетевых устройств_.
* Импортирует в {dv} бизнес-процесс _Проверка доступности сетевых узлов_, а также пример карточки _Карточка учета сетевого оборудования_, а также данные _справочника видов карточек_, _конструктора разметок_, _конструктора состояний_ и _конструктора ролей_.
* Регистрирует клиентский пакет установки.
* Добавляет в _{cns}_ форму для ввода конфигурационных параметров _Модуля учета сетевых устройств_.

[NOTE]
====
Пример реализации простого _SnapIn_ приведен в разделе xref:solutions:extensions/console-plugin.adoc[Модуль расширения Консоли настройки]
====

Компонент _SnapIn_ представляет собой библиотеку DLL, в которой присутствует класс, реализующий интерфейс `DocsVision.Tools.ServerConsole.ISnapIn` (сборка `DocsVision.Tools.ServerConsole.Interfaces.dll`).

.Также данный класс может реализовывать несколько дополнительных интерфейсов:
* `IDBInformation` -- является обязательным при создании _решения_, т.к. именно реализация данного интерфейса позволяет _SnapIn_ предоставлять пути к `CardPackage` и `SqlPackage`.
* `IConfigurator` -- добавляет в _SnapIn_ метод Execute, который запускается в режиме конфигурации модуля -- вызывается командой `ServerConsole.exe /c /n \{ИМЯ_РЕШЕНИЯ}`. Обычно данный метод отвечает за регистрацию пакетов установки клиентской части _решения_.
* `IUninstallSnapIn` -- добавляет метод `Uninstall`, который вызывается при удалении решения -- вызывается командой `ServerConsole.exe /rs /n ИМЯ_РЕШЕНИЯ`.

Помимо выполнения сервисных функций, _SnapIn_ может предоставлять пользовательский интерфейс для различных режимов работы _Консоли настройки_.

[NOTE]
====
Если вы работаете с исходными кодами проекта, то _SnapIn_ собирается третьим.
====
