= SignatureInfo -- конструктор (SignatureType signatureType, DateTime expireDate, CertificateInfo certificate, IEnumerable<TimestampInfo> timestamps)

Инициализирует новый экземпляр класса `xref:BackOffice-DigitalSignature:SignatureInfo_CL.adoc[SignatureInfo]`.

* *Пространство имён:* `xref:BackOffice-DigitalSignature:DigitalSignature_NS.adoc[DocsVision.BackOffice.DigitalSignature]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public SignatureInfo(SignatureType signatureType, DateTime expireDate, CertificateInfo certificate, IEnumerable<TimestampInfo> timestamps)
----

Параметры::
signatureType:::
Тип: `xref:BackOffice-ObjectModel:SignatureType_EN.adoc[SignatureType]`
+
Получает тип подписи

expireDate:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.datetime.aspx[System.DateTime]`
+
Получает дату и время истечения срока действия подписи

certificate:::
Тип: `xref:BackOffice-DigitalSignature:CertificateInfo_CL.adoc[CertificateInfo]`
+
Получает информацию о сертификате подписи

timestamps:::
Тип: `xref:BackOffice-DigitalSignature:TimestampInfo_CL.adoc[IEnumerable<TimestampInfo>]`
+
Получает набор штампов времени в подписи
