= ExportForm -- класс

Класс ExportForm представляет форму экспорта и печати содержимого карточки, позволяет отправлять содержимое по электронной почте.

* *Пространство имен:* xref:api/DocsVision/BackOffice/WinForms/Controls/Controls_NS.adoc[DocsVision.BackOffice.WinForms.Controls]
* *Сборка:* `DocsVision.BackOffice.WinForms.dll`

== Синтаксис

[source,csharp]
----
public class ExportForm : DevExpress.XtraEditors.XtraForm
----

== Конструкторы

[cols=",",options="header"]
|===
|Имя |Описание
|public ExportForm() |Инициализирует новый экземпляр класса ExportForm.
|===

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание
|Caption |Задает или возвращает тему письма, отправляемого из формы ExportForm.
|CardData |Задает или возвращает содержимое карточки, для которой вызывается диалог экспорта и печати.
|CardHost |Задает или возвращает контейнер карточки.
|CardTypeId |Задает или возвращает идентификатор типа карточки. Данный параметр используется при формировании списка доступных преобразований печати и экспорта.
|CardXml |Задает или возвращает содержимое произвольного XML-документа, предназначенного для вывода в диалог печати и экспорта. Используется вместо XML-документа, полученного из CardData.
|Session |Задает или возвращает пользовательскую сессию.
|TemplateAlias |Задает или возвращает псевдоним преобразования, которое будет выбрано по умолчанию.
|===

== Заметки

Класс ExportForm предоставляет два варианта использования:

. Используется `CardData` -- диалог вызывается для существующей карточки. Параметры `CardXml`, `CardTypeId`, `Caption` указывать не требуется.
. Используется `CardXml` -- диалог вызывается для печати переданной Xml-строки. Параметр `CardData` указывать не требуется. Данный параметр доступен начиная с версии платформы 5.4.

При печати собственного XML-документа список доступных пребразований печати и экспорта будет ограничен преобразованиями имеющими тип `Custom` (см. раздел xref:CardsDevDataSchemeSecTransformations.adoc[Раздел 'Transformations']).

Не рекомендуется задавать значения `CardData` и `CardXml` одновременно, так как при этом возможно формирование некорректного списка преобразований.

== Примеры

Ниже приведен пример скрипта, вызываемого из карточки, который открывает окно экспорта и печати

[source,csharp]
----
private void ExportButton_Click(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
 using (ExportForm exportForm = new ExportForm())
 {
  // Сессия, контейнер карточки и ее данные получаем из базового класса ScriptClassBase
  exportForm.Session = base.Session;
  exportForm.CardHost = base.CardFrame.CardHost;
  exportForm.CardData = base.CardData;

  // Вывод окна печати
  exportForm.ShowDialog();
 }
}
----

Далее приведен пример использования класса ExportForm при выводе на печать/экспорт собственного XML-документа

[source,csharp]
----
private void ExportButton_Click(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
 using (ExportForm exportForm = new ExportForm())
 {

  // Сессия и контейнер карточки получаем из базового класса ScriptClassBase
  exportForm.Session = base.Session;
  exportForm.CardHost = base.CardFrame.CardHost;

  // В данном случае XML-документ получен из файла CardXMLDocument.xml, также он может быть сформирован, например, при помощи XmlDocument
  exportForm.CardXml = System.IO.File.ReadAllText("CardXMLDocument.xml");

  // Идентификатор типа карточки, который используется при получении разрешенных преобразований (Transformation)
  exportForm.CardTypeId = new Guid("B9F7BFD7-7429-455E-A3F1-94FFB569C794");

  // Будет использован при создании электронного письма
  exportForm.Caption = "Произвольный XML-документ";

  // Если в списке доступных преобразований присутствует преобразование с псевдонимом "CustomTransformation", то оно будет выбрано по умолчанию
  exportForm.TemplateAlias = "CustomTransformation";

  // Вывод окна печати
  exportForm.ShowDialog();
 }
}       
----
