= IKindService.AddProcessOperation -- метод (KindsCardProcess, StatesOperation)

Добавляет бизнес-процесс к списку процессов, привязанных к операциям в карточке определённого вида.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
KindsCardProcessOperation AddProcessOperation(KindsCardProcess process, StatesOperation operation)
----

Параметры::
process:::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardProcess_CL.adoc[KindsCardProcess]`
+
Параметры связываемого бизнес-процесса

operation:::
Тип: `xref:BackOffice-ObjectModel-States:StatesOperation_CL.adoc[StatesOperation]`
+
Операция в карточке, приводящая к запуску бизнес-процесса

Возвращаемое значение::
Тип: `xref:BackOffice-ObjectModel-Kinds:KindsCardProcessOperation_CL.adoc[KindsCardProcessOperation]`
+
Операция процесса

== Исключения

[cols=",",options="header"]
|===
|Исключение |Условие
|`http://msdn.microsoft.com/ru-ru/library/system.argumentnullexception.aspx[System.ArgumentNullException]` |Ошибка возвращается в случае, если не задан параметр `process` или `operation`.
|===
