= Строки секции карточки объектной модели

В отличие от описания схемы метаданных карточки (или справочника), в данном случае, удобнее разработать сперва объектные модели строк секций, и лишь после этого приступать к самой карточке или справочнику.

Т.к. секции могут быть нескольких типов, далее приведён пример разработки классов для строк каждого из них.

В качестве базового класса строки секции выступает класс `xref:Platform-ObjectModel:ObjectBase_CL.adoc[ObjectBase]`.

== Плоская секция

Для примера опишем секцию, в которой содержится одно текстовое поле -- `Name`, а также одно ссылочное `Author`, которое ссылается на сотрудника в _справочнике сотрудников_.

.В таком случае объектная модель секции строки будет выглядеть так:
[source,csharp]
----
public class SampleCardStructSection : ObjectBase
{
 public static readonly ObjectProperty AuthorProperty; <.>
 public static readonly ObjectProperty NameProperty; <.>

 public StaffEmployee Author <.>
 {
  get { return (StaffEmployee)base.GetValue(SampleCardStructSection.AuthorProperty); }
  set { base.SetValue(SampleCardStructSection.AuthorProperty, value); }
 }
 public string Name
 {
  get { return (string)base.GetValue(SampleCardStructSection.NameProperty); }
  set { base.SetValue(SampleCardStructSection.NameProperty, value); }
 }

 static SampleCardStructSection() <.>
 {
  SampleCardStructSection.AuthorProperty = ObjectProperty.Register("Author", typeof(StaffEmployee), typeof(SampleCardStructSection)); <.>
  SampleCardStructSection.NameProperty = ObjectProperty.Register("Name", typeof(string), typeof(SampleCardStructSection));
 }

 internal SampleCardStructSection() <.>
 {
 }

 internal SampleCardStructSection(ObjectInitializationData data) : base(data) <.>
 {
 }
}
----
<.> Вначале идет объявление всех доступных полей. Всегда типа `ObjectProperty`.
<.> Рекомендуется использовать название поля из схемы метаданных с добавлением суффикса `Property`.
<.> Публичные свойства для обращения получения и записи значения соответствующего поля.
+
Тип свойства соответствует типу поля в схеме метаданных.
+
Для ссылочных полей тип соответствует типу сущности, на которую идет ссылка. В данном случае -- это объект сотрудник.
+
<.> Обязательный статический конструктор, в котором должна быть выполнена регистрация всех объявленных ранее свойств.
<.> В метод `Register` передаем название поля (как в схеме метаданных), его тип (как определён выше) и тип самой секции (текущий класс).
<.> Конструктор для новой карточки.

При желании, здесь можно добавить собственную бизнес-логику, а также проверку данных перед записью.

== Коллекционная секция

Реализация объектной модели для строки секции данного типа ничем не отличается от рассмотренной ранее. Есть отличие на этапе описания секции в классе карточки (будет рассмотрено далее).

== Иерархическая секция

Для такой секции свойственно наличие подчиненной секции, причем этой подчиненной секцией является сама секция. В этом основное отличие в реализации объектной модели.

[source,csharp]
----
public class SampleCardTreeSection : ObjectBase
{
 public static ObjectProperty DescendantsProperty; <.>

 public ObjectCollection<SampleCardTreeSection> Descendants <.>
 { 
  get { return (ObjectCollection<SampleCardTreeSection>)base.GetValue(SampleCardTreeSection.DescendantsProperty); }
 }

 static SampleCardTreeSection()
 {
  SampleCardTreeSection.DescendantsProperty = ObjectProperty.Register("Descendants",  typeof(ObjectCollection<SampleDescendantsSection>),  typeof(SampleCardTreeSection)); <.>
 }

 internal SampleCardTreeSection()
 {
 }
 internal SampleCardTreeSection(ObjectInitializationData data) : base(data)
 {
 }
}
----
<.> Объявление подчиненной секции.
<.> Свойство, через которое будут доступны строки подчиненной секции, т.е. строки самой этой секции.
<.> Связывание секции с соответствующим свойством.
+
`SampleDescendantsSection` -- некая секция, которая в схеме метаданных карточки подчинена секции `SampleCardTreeSection`.

В объектной модели библиотеки карточек _{bo}_ базовым классом для строк выступает класс `BaseCardSectionRow`, который предоставляет некоторые дополнительные методы. Примерами методов могут быть: получение дочерней секции по идентификатору, получение значения поля с приведением к типу `Guid`. Реализация объектной модели строек секций при использовании данного базового класса не изменится.
