= Разработка преобразователя данных

Неотъемлемой частью разработки объектной модели карточки является разработка _преобразователя данных_ -- объект, в котором объясняется каким образом элементы объектной модели карточки (или секций) связаны с данными этой карточки в базе данных.

_Контекст объектов_ задействует _преобразователь данных_ на этапе создания экземпляра карточки (к примеру, методом `GetObject`), а также при сохранении новых или измененных данных.

_Преобразователь данных_ разрабатывается для каждого созданного класса строки секции, а также для самой карточки.

С программной точки зрения, преобразователь данных должен вернуть объект типа `xref:Platform-ObjectModel:Mapping/ObjectMap_CL.adoc[ObjectMap]` (карта преобразователя), который содержит списки, связывающие элементы объектной модели с их эквивалентами в схеме метаданных карточки.

Далее рассматривается пример разработки преобразователей для строк секций и карточки, рассмотренных ранее.

== Преобразователь данных для строки секции

Базовым классом преобразователя для строки (не зависит от типа секции) является класс `CardRowMapper`. Для класса `CardRowMapper` указывается тип, соответствующий классу объектной модели строки для которой он создается.

.Для строки плоской секции, разработанной ранее, преобразователь будет выглядеть следующим образом:
[source,csharp]
----
internal sealed class SampleCardStructSectionMapper : CardRowMapper<SampleCardStructSection>
{
 private static ObjectMap map;

 static SampleCardStructSectionMapper() <.>
 {
  SampleCardStructSectionMapper.InitializeObjectMap(); <.>
 }

 public SampleCardStructSectionMapper(ObjectContext context) : base(context) <.>
 {
 }

 protected override ObjectMap GetObjectMap() <.>
 {
  return SampleCardStructSectionMapper.map;
 }

 protected override SampleCardStructSection CreateObject(ObjectInitializationData data) <.>
 {
  return new SampleCardStructSection(data);
 }

 private static void InitializeObjectMap() <.>
 {
  SampleCardStructSectionMapper.map = new ObjectMap();

  SampleCardStructSectionMapper.map.ObjectTypeId = new Guid("78006F34-55DF-497F-BD62-E0A33C8EEABF"); <.>
  
  SampleCardStructSectionMapper.map.Field(SampleCardStructSection.NameProperty, "Name"); <.>

  SampleCardStructSectionMapper.map.Reference(SampleCardStructSection.AuthorProperty, "Author"); <.>
 }
}
----
<.> Обязательный статический конструктор.
<.> Создаем карту преобразователя.
<.> Обязательный конструктор для передачи текущего контекста объектов.
<.> Обязательный метод, предоставляющей карту.
<.> Создание экземпляра объекта секции с заранее подготовленными данными.
<.> Создание карты преобразователя.
<.> Указываем идентификатор секции в схеме карточки.
<.> Связываем обычное поле.
+
Первый аргумент объявление поля в классе секции, а второй аргумент -- название поля в схеме карточки.
+
<.> Связываем ссылочное поле.

Преобразовать для строки коллекционной секции не отличается от преобразователя для строки плоской секции.

.Отличие в реализации преобразователя для строки иерархической секции в наличии в карте объявления подчиненных секций:
[source,csharp]
----
public class SampleCardTreeSectionMapper : CardRowMapper<SampleCardTreeSection>
{
 private static ObjectMap map;
 static SampleCardTreeSectionMapper()
 {
  SampleCardTreeSectionMapper.InitializeObjectMap();
 }
 public SampleCardTreeSectionMapper(ObjectContext context) : base(context)
 {
 }
 protected override ObjectMap GetObjectMap()
 {
  return SampleCardTreeSectionMapper.map;
 }
 protected override SampleCardTreeSection CreateObject(ObjectInitializationData data)
 {
  return new SampleCardTreeSection(data);
 }

 private static void InitializeObjectMap()
 {
  SampleCardTreeSectionMapper.map = new ObjectMap();
  SampleCardTreeSectionMapper.map.ObjectTypeId = new Guid("08ACDC17-EAB7-4E66-8C6D-428F09490F3A");

  SampleCardTreeSectionMapper.map.Collection(SampleCardTreeSection.DescendantsProperty, new Guid("80DB0D9B-D1E8-4A4D-8001-E71AC07B10CE")); <.>
 }
}
----
<.> В карту добавляется подчиненная секция. Первым аргументом передается объявление секции в родительской секции, а вторым -- её идентификатор из схемы метаданных.

== Преобразователь данных для карточки

Преобразователь данных для карточки оформляется аналогичным образом, за исключением базового класса (должен быть класс `xref:BackOffice-ObjectModel-Mapping:Mapping/BaseCardMapper_CL.adoc[BaseCardMapper<T>]`) и того, что в карте присутствуют исключительно секции.

[source,csharp]
----
public class SampleCardMapper : CardMapper<SampleCard>
{
 private static ObjectMap map;
 static SampleCardMapper()
 {
  SampleCardMapper.InitializeObjectMap();
 }
 public SampleCardMapper(ObjectContext context) : base(context)
 {
 }
 protected override ObjectMap GetObjectMap()
 {
  return SampleCardMapper.map;
 }
 protected override SampleCard CreateObject(ObjectInitializationData data)
 {
  return new SampleCard(data);
 }
 private static void InitializeObjectMap()
 {
  SampleCardMapper.map = new ObjectMap();

  SampleCardMapper.map.ObjectTypeId = new Guid("E1BF5846-FE0C-424B-9B71-B58D1A526BCF"); <.>

  SampleCardMapper.map.Collection(SampleCard.StructSectionProperty, new Guid("A3F0B456-587E-4769-B019-467AD4EB9BF8")); <.>
  SampleCardMapper.map.Collection(SampleCard.CollectionSectionProperty, new Guid("F6E9E009-7447-435D-8DB8-C3E4187E2D61"));
  SampleCardMapper.map.Collection(SampleCard.TreeSectionProperty, new Guid("EA968311-3702-4568-9663-2CE9CBE09CC6"));
 }
}
----
<.> Идентификатор типа карточки.
<.> Регистрация секций в карте преобразователя.

== Преобразователь данных для справочника

Класс преобразователя данных для справочника реализуется по аналогии с преобразователя данных карточки. Единственное отличие -- базовый класс здесь `xref:Platform-ObjectModel:Mapping/DictionaryMapper_CL.adoc[DictionaryMapper<T>]`.

[source,csharp]
----
public class SampleDictionaryMapper : DictionaryMapper<SampleDictionary>
{
 private static ObjectMap map;
 static SampleDictionaryMapper()
 {
  SampleDictionaryMapper.InitializeObjectMap();
 }
 public SampleDictionaryMapper(ObjectContext context) : base(context)
 {
 }
 protected override ObjectMap GetObjectMap()
 {
  return SampleDictionaryMapper.map;
 }
 protected override SampleDictionary CreateObject(ObjectInitializationData data)
 {
  return new SampleDictionary(data);
 }
 private static void InitializeObjectMap()
 {
  SampleDictionaryMapper.map = new ObjectMap();
  
  SampleDictionaryMapper.map.ObjectTypeId = new Guid("4E32BC51-5F50-4F68-9D0F-3BFBB6523B14"); <.>
  SampleDictionaryMapper.map.Collection(SampleDictionary.TreeSectionProperty, new Guid("0CD96A19-59EF-44EC-AF47-977A56BDDB32"));
 }
}
----
<.> Идентификатор типа справочника.

== Регистрация преобразователей данных

После того как классы преобразователей данных били разработаны, требуется создать еще один класс -- _фабрика преобразователей данных_. В созданном классе нужно связать тип преобразователя к классу карточки или секции, за который он отвечает. Базовым классом для _фабрики преобразователей данных_ выступает класс `ObjectMapperFactory`.

[source,csharp]
----
public sealed class SampleCardsMapperFactory : ObjectMapperFactory
{
 public SampleCardsMapperFactory(ObjectContext context) : base(context)
 {
  base.RegisterObjectMapper(typeof(SampleCardStructSection), typeof(SampleCardStructSectionMapper)); <.>
  base.RegisterObjectMapper(typeof(SampleCardCollectionSection), typeof(SampleCardCollectionSectionMapper));
  base.RegisterObjectMapper(typeof(SampleCardTreeSection), typeof(SampleCardTreeSectionMapper));
  base.RegisterObjectMapper(typeof(SampleCard), typeof(SampleCardMapper));
 }
}
----
<.> В метод передается тип объектной модели строки секции или карточки, а также тип соответствующего преобразователя.

Чтобы контекст объектов мог работать с типами карточек и секций, для которых разработаны _фабрики преобразователей данных_, эти фабрики должны быть добавлены в контекст (см. на примере добавления фабрики `BackOfficeMapperFactory` в xref:samples:object-model/init-context.adoc[примере]).
