= Бизнес-календарь

[cols=","]
|===
|Назначение
|Предназначена для хранения информации о расписании работы сотрудников (количество рабочих дней, рабочих часов и др.) на определённый период времени.

|Класс карточки
|`BackOffice-ObjectModel-Calendar:Calendar_CL.adoc[DocsVision.BackOffice.ObjectModel.Calendar]`
|===

Для работы с карточкой предназначен сервис `xref:BackOffice-ObjectModel-Services-ICategoriesService:ICalendarService_IN.adoc[ICalendarService]`. Сервис предоставляет следующие операции:

* Добавление рабочих дат в бизнес-календарь.
* Добавление рабочего время.
* Получение сроков рабочего времени для различных условий.

В примере создаётся бизнес-календарь в котором все пятницы 2014 года объявляются сокращенными (рабочее время с 10 до 15 часов). По созданному календарю будет работать текущий пользователь. Дополнительных проверок не проводим.

[source,csharp]
----
ICalendarService calendarService = objectContext.GetService<ICalendarService>();
IStaffService staffService = objectContext.GetService<IStaffService>(); <.>

CardData cardData = userSession.CardManager.CreateCardData(DocsVision.BackOffice.CardLib.CardDefs.CardCalendar.ID); <.>

DocsVision.BackOffice.ObjectModel.Calendar calendar = objectContext.GetObject<DocsVision.BackOffice.ObjectModel.Calendar>(cardData.Id); <.>
calendar.MainInfo.Name = "bestWorks";
calendar.Description = "Легкий день";
int year = 2014;

CalendarYear calendarYear = calendarService.AddCalendarYear(year); <.>

calendarYear.Days = new ObjectCollection<CalendarDay>();
DateTime startDate = new DateTime(year, 1, 1); <.>

for (DateTime i = startDate; i <= new DateTime(year, 12, 31); i = i.AddDays(1))
{
 if (i.DayOfWeek = DayOfWeek.Friday)
 { <.>
  CalendarWorkTime calendarWorkTime = calendarService.AddCalendarWorkTime(new System.DateTime(2000, 1, 1, 10, 0, 0), new System.DateTime(2000, 1, 1, 15, 0, 0)); <.>
  
  CalendarDay calendarDay = calendarService.AddCalendarDay(i.DayOfYear);
  calendarDay.WorkTime = new ObjectCollection<CalendarWorkTime>();
  calendarDay.WorkTime.Add(calendarWorkTime); <.>

  calendarYear.Days.Add(calendarDay); <.>
 }
}

calendar.Years.Add(calendarYear); <.>

staffService.GetCurrentEmployee().CalendarID = cardData.Id; <.>

objectContext.AcceptChanges(); <.>
----
<.> Инициализация контекста объектов и получение сервисов.
<.> Инициализация карточки типа Бизнес-календарь (использует `CardManager`, старый API).
<.> Доступ к карточке через объектную модель.
<.> Создание объекта типа "Год".
<.> Инициализация коллекции дней в году.
<.> Заполнение дней.
<.> Создание объекта содержащего укороченное рабочее время.
<.> Создание объекта типа "День" и добавление в него рабочего времени.
<.> Добавление дня в год.
<.> Сохранение года в календаре.
<.> Присвоение календаря текущему пользователю.
<.> Сохранение всех изменений.
