= Справочник контрагентов

[cols=","]
|===
|Назначение
|Предназначен для хранения информации о структуре и сотрудниках внешних организаций, с которыми взаимодействует компания.

|Класс карточки
|`xref:BackOffice-ObjectModel-Partners:Partners_CL.adoc[DocsVision.BackOffice.ObjectModel.Partners]`
|===

Для работы с карточкой предназначен сервис `xref:BackOffice-ObjectModel-Services-IPartnersService:IPartnersService_IN.adoc[IPartnersService]`, с помощью которого можно программно создавать и удалять контрагентов, сотрудников и группы компаний.

.Доступные операции:
* Управление подразделениями.
* Управление сотрудниками.
* Управление группами.
* Осуществление поиска по различным параметрам.

В приведенном примере создается новый вид для xref:bo-lib/document.adoc[карточки "Документ"]

[source,csharp]
----
IPartnersService partnersService = objectContext.GetService<IPartnersService>(); <.>

PartnersOrgType orgType = partnersService.AddNewOrgType();
orgType.Name = "ЗАО"; <.>

PartnersPosition positionDir = partnersService.AddNewPosition();
positionDir.Name = "Директор";        
PartnersPosition positionMan = partnersService.AddNewPosition();
positionMan.Name = "Начальник отдела продаж"; <.>
            
PartnersCompany partnersCompany = partnersService.AddNewUnit(null);
partnersCompany.Name = "ЗАО \"Луч\"";
partnersCompany.FullName = "Закрытое акционерное общество \"ЛУЧ\""; <.>
partnersCompany.Type = PartnersCompanyType.Organization;
partnersCompany.OrgType = orgType;
partnersCompany.IsVendor = true; <.> //

PartnersEmployee partnersEmployee = partnersService.AddNewEmployee(partnersCompany);
partnersEmployee.LastName = "Иванов";
partnersEmployee.FirstName = "Александр";
partnersEmployee.MiddleName = "Сергеевич"; <.>
partnersEmployee.Position = positionDir; <.> //

partnersCompany.Manager = partnersEmployee; <.>

PartnersCompany partnersDepartment = partnersService.AddNewUnit(partnersCompany);
partnersDepartment.Name = "Отдел продаж";
partnersDepartment.Type = PartnersCompanyType.Department; <.>
PartnersEmployee partnersEmployee2 = partnersService.AddNewEmployee(partnersDepartment);
partnersEmployee2.LastName = "Константинов";
partnersEmployee2.FirstName = "Сергей";
partnersEmployee2.MiddleName = "Иванович";
partnersEmployee2.Position = positionMan;
partnersDepartment.Manager = partnersEmployee2;

objectContext.AcceptChanges(); <.>
----
<.> Инициализация контекста объектов и получение сервиса
<.> Добавление типа юр. лица
<.> Добавление должностей
<.> Создание организации
<.> Ставим признак, что организации
<.> Добавление сотрудника
<.> Должность "Директор"
<.> Назначаем сотрудника руководителем
