= Конструктор ролей

[cols=","]
|===
|Назначение
|Определяет механизм распределения прав пользователей при работе с рядом приложений {dv} на основе данных самой карточки.

|Класс карточки
|`xref:BackOffice-ObjectModel-RoleModel:RoleModel_CL.adoc[DocsVision.BackOffice.ObjectModel.RoleModel]`
|===

Для работы с карточкой предназначен сервис `xref:BackOffice-ObjectModel-Services-IRoleModelService:IRoleModelService_IN.adoc[IRoleModelService]`, с помощью которого можно получить доступ к сохраненным правилам и свойствам ролевой модели, а также создавать и управлять объектами данного уровня безопасности.

.Доступные операции:
* Создание условий и групп условий для ролей.
* Создание пользовательских параметров и операций.
* Связывание настроек в сопоставление операция-состояние.
* Создание и получение настроек ролевой модели для вида карточки.
* Получение ролей для вида карточки.

В примере создается роль, которая может быть использована для ограничения времени доступа к документам в выходные дни.

[source,csharp]
----
IRoleModelService roleModelService = objectContext.GetService<IRoleModelService>(); <.>

KindsCardKind kindsCardKind = objectContext.GetObject<KindsCardKind>(new Guid("8ACE1220-A452-455D-8EEB-9EDF9DC6E327")); <.>

RoleModelCardKindRoleSetting roleModelCardKindRoleSetting = roleModelService.GetOrCreatePreferredCardKindSetting(kindsCardKind); <.>
RoleModelRole roleModelRole = roleModelService.CreateRole(roleModelCardKindRoleSetting);
roleModelRole.Name = "Работа по выходным";

roleModelRole.ConditionGroup.Operation = RoleModelRoleConditionGroupOperation.Or; <.>

RoleModelRoleCondition condition = roleModelService.AddCondition(roleModelRole.ConditionGroup); <.>
condition.Parameter = RoleModelRoleConditionParameter.Today;
condition.Operation = RoleModelRoleConditionOperation.Equals;
condition.Value = System.DayOfWeek.Saturday;

condition = roleModelService.AddCondition(roleModelRole.ConditionGroup); <.>
condition.Parameter = RoleModelRoleConditionParameter.Today;
condition.Operation = RoleModelRoleConditionOperation.Equals;
condition.Value = System.DayOfWeek.Sunday;

objectContext.AcceptChanges(); <.>

roleModelService.MakeRoleCommon(roleModelRole); <.>
----
<.> Инициализация контекста объектов и получение сервиса.
<.> Получение вида карточки "Документ".
<.> Создание настроек для вида карточки.
<.> Логическая операция между условиями -- `ИЛИ`.
<.> Создание первого условия: `сегодня = суббота`.
<.> Создание второго условия: `сегодня = воскресенье`.
<.> Сохранение изменений.

NOTE: Роль не создает реального ограничения, для настройки используется матрица доступа (недоступная для карточки "Документ", доступная для "ДокументУД").
