= Задание

[cols=","]
|===
|Назначение
|Предназначена для доставки на рабочие места пользователей информации о необходимости выполнения того или иного действия в рамках налаженного документооборота, а также доставки файлов, карточек и ссылок на внешние по отношению к системе {dv} объекты.

|Класс карточки
|`xref:BackOffice-ObjectModel:Task_CL.adoc[DocsVision.BackOffice.ObjectModel.Task]`
|===

Для работы с карточкой предназначен сервис `xref:BackOffice-ObjectModel-Services-ITaskService:ITaskService_IN.adoc[ITaskService]`, с помощью которого можно работать с заданиями. Позволяет создавать задания, настраивать и управлять ими.

.Доступные операции:
* Создание задания.
* Управление состоянием задания.
* Управление комментариями к заданию.
* Управление исполнителями и контроллерами задания.
* Управление делегированием задания.
* Управление подписями задания.
* Подготовка вложений задания.
* Управление настройками задания.
* Управление дочерними и родительскими заданиями.

Далее перечислены базовые сценарии работы с объектной моделью карточки "Задание", для которых действительно следующее:

* Контекст объектов может быть получен в соответствии с примером, приведенным в разделе xref:samples:object-model/init-context.adoc[Инициализация контекста объектов].
* Сервисы получаем стандартным способом:
+
[source,csharp]
----
IDocumentService documentService = objectContext.GetService<IDocumentService>(); <.>
ILinkService linkService = objectContext.GetService<ILinkService>(); <.>
IReferenceListService referenceListService = objectContext.GetService<IReferenceListService>(); <.>
IStaffService staffService = objectContext.GetService<IStaffService>(); <.>
IStateService stateService = objectContext.GetService<IStateService>(); <.>
ITaskService taskService = objectContext.GetService<ITaskService>(); <.>
----
<.> Сервис для работы с документами.
<.> Сервис для работы со "Справочником ссылок".
<.> Сервис для работы со списками ссылок.
<.> Сервис для работы со "Справочником сотрудников".
<.> Сервис для работы с "Конструктором состояний".
+
* Для получения информации по классам и переменным, используемым в примерах, воспользуйтесь поиском.

== Создание нового "Задания"

[source,csharp]
----
static void CreateTask()
{
 KindsCardKind kind = objectContext.GetObject<KindsCardKind>(new Guid("AB801854-70AF-4B6C-AB48-1B59B5D11AA9")); <.>

 StaffEmployee employee = objectContext.GetObject<StaffEmployee>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

 Task task = taskService.CreateTask(kind); <.>
 task.MainInfo.Name = "Название задания";
 task.Description = "Дайджест созданного задания"; 
 task.MainInfo.Author = staffService.GetCurrentEmployee(); <.>
 taskService.AddSelectedPerformer(task.MainInfo, employee); <.>
 task.MainInfo.Priority = TaskPriority.Low; <.>
 task.MainInfo.EndDate = DateTime.Now.AddDays(1); <.>
 task.MainInfo.Content = "Данное задание является примером и не требует исполнения";
 objectContext.SaveObject(task); <.>
}
----
<.> Получение вида для создаваемого задания. `AB801854-70AF-4B6C-AB48-1B59B5D11AA9` -- `На исполнение`.
<.> Получение сотрудника, назначаемого исполнителем задания.
<.> Создание задания и заполнение базовых данных.
<.> Автор задания.
<.> Добавление выбранного исполнителя.
<.> Установка низкого приоритета.
<.> Срок выполнения -- "завтра".
<.> Сохранение созданного задания.

== Добавление файла в "Задание"

[source,csharp]
----
static void AddFile()
{
 string file = @"z:\Sample.docx"; <.>
 
 Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

 ReferenceList referenceList = referenceListService.CreateReferenceList();
 task.MainInfo.ReferenceList = referenceList; <.>

 LinksLinkType linkType = linkService.FindLink("КЗ_ДополненияФайлы"); <.>

 KindsCardKind kind = objectContext.GetObject<KindsCardKind>(new Guid("F9A8D158-9884-4765-859D-31C4EFCA149D")); <.>
 Document fileCard = documentService.CreateDocument(file, kind); <.>
 fileCard.MainInfo.Name = "Файл для задания";
 objectContext.SaveObject(fileCard); <.>

 referenceListService.CreateReference(referenceList, linkType, fileCard, string.Empty, true); <.>
 objectContext.AcceptChanges();
}
----
<.> Загружаемый файл.
<.> Получение задания, в которое производится добавление файла.
<.> Создание нового списка ссылок.
<.> Получение типа ссылки по имени.
<.> Создание карточки Файл для последующей загрузки в задание.
<.> Получение вида карточки.
<.> Создание документа.
<.> Требуется сохранение.

== Отправка Задания на исполнение

[source,csharp]
----
static void StartTask()
{
 Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

 taskService.StartTask(task); <.>

 StatesStateMachineBranch branch = stateService.FindBranchByBuiltIn(Task.InitializationToStartedByStart, task.SystemInfo.State); <.>

 stateService.ChangeState(task, branch); <.>
}    
----
<.> Получение задания.
<.> Запуск задания на исполнение.
<.> Получение перехода `Подготовка` -- `Не начато`.
<.> Изменение состояния.

== Делегирование задания

[source,csharp]
----
static void DelegateTask()
{
 Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

 StaffEmployee newPerformer = staffService.Get(new Guid("00000000-0000-0000-0000-000000000001")); <.>
 
 taskService.Delegate(task, new StaffEmployee[] { newPerformer }, null, false, false, "Необходимо выполнить задание"); <.>

 stateService.ChangeState(task, stateService.FindStateByBuiltIn(Task.DelegatedState, task)); <.>
}
----
<.> Получение задания.
<.> Получение сотрудника, которому осуществляется делегирование задания.
<.> Делегирование задания сотруднику "newPerformer".
<.> Установка для задания состояния `Делегировано`.

== Завершение "Задания"

[source,csharp]
----
static void CompleteTask()
{
 Task task = objectContext.GetObject<Task>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

 BuiltInState state = taskService.CompleteTask(task, "Задание было завершено успешно"); <.>

 StatesState cancelState = stateService.FindStateByBuiltIn(state, task); <.>
 
 stateService.ChangeState(task, cancelState); <.>
}
----
<.> Получение задания.
<.> Завершение задания с комментарием.
<.> Поиск в "Конструкторе состояний" состояния, соответствующего "встроенного" состоянию `Завершено`.
<.> Изменение состояния.

Метод `CompleteTask` выполняет проверку и установку параметров, необходимых для корректного завершения задания, но фактическое изменение состояние производит метод `ChangeState`.

[NOTE]
====
При работе с методами сервиса `ITaskService` нужно учитывать, что при выполнении статусных методов (отозвать, принять, отклонить и т.д.) статус самого задание не изменяется. Для непосредственной смены статуса используется метод `IStateService.ChangeState(BaseCard, StatesState)`.
====
