= Элемент управления "HtmlBrowser"

Элемент управления `_HtmlBrowser_` предназначен для отображения произвольного HTML-документа, либо XML-содержимого связанной карточки с (опционально) примененным XSL-преобразованием. Соответствует элементу управления `_HTML браузер_` _Конструктора разметок_.

`_HtmlBrowser_` не содержит элементов управления.

== Свойства

* `*ContentType*` -- тип отображаемого контента:
** `*CardDataXml*` -- `_HtmlBrowser_` отобразит содержимое карточки, полученной из ссылочного поля, если определены `*ReferenceCardFieldAlias*` и `*ReferenceCardSectionId*`.
+
Если определено свойство `XslTransform`, будет применено соответствующее преобразование.
+
** `*CustomHtml*` -- предопределённый HTML-документ, который задан в значении `CustomData`.
** `*CustomUrl*` -- отображение HTML-страницы с URL. При установке значения `CustomData` необходимо соблюдать формат адреса, например: `\http://www.docsvision.com` .
** `*OwnCardDataXml*` -- `_HtmlBrowser_` отобразит содержимое текущей карточки в формате XML, либо преобразованный документ, если определено свойство `*XslTransform*`.
* `*CustomData*` -- URL-адрес для режима `*CustomUrl*`, либо HTML-документ для режима `*CustomHtml*`.
* `*IsContextMenuEnabled*` -- при значении `true` будет доступно контекстное меню.
* `*ObjectContext*` -- _контекст объектов_.
* `*ReferenceCardFieldAlias*` -- псевдоним ссылочного поля карточки, из которой должен быть получен идентификатор карточки для отображения содержимого в режиме `CardDataXml`.
* `*ReferenceCardSectionId*` -- идентификатор секции, в которой содержится поле `ReferenceCardFieldAlias`.
* `*XslTransform*` -- XSLT-шаблон для преобразования содержимого карточки в режимах `*CardDataXml*` и `*OwnCardDataXml*`.

.Пример инициализации `*HtmlBrowser*` с отображением содержимого карточки, идентификатор которой указан в ссылочном поле `CategoryList`:
[source,charp]
----
protected override void OnCardInitialized(EventArgs e)
{
 base.OnCardInitialized(e);
 InitializeComponent();
 
 this.htmlBrowser.ContentType = DocsVision.BackOffice.WinForms.Controls.HtmlBrowserContentType.CardDataXml;
 this.htmlBrowser.ReferenceCardSectionId = new Guid("783CD108-BA4A-432D-9C12-B32E0577D53C");
 this.htmlBrowser.ReferenceCardFieldAlias = "CategoryList";
}
----
