= IAccessCheckingService.IsOperationAllowed -- метод (BaseCard, BuiltInOperation)

Возвращает признак разрешения выполнения встроенной операции для заданной карточки.

* *Пространство имён:* `xref:BackOffice-ObjectModel-Services-Entities:Services_NS.adoc[DocsVision.BackOffice.ObjectModel.Services]`
* *Сборка:* `DocsVision.BackOffice.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
bool IsOperationAllowed(BaseCard card, BuiltInOperation operation)
----

Параметры::
card:::
Тип: `xref:BackOffice-ObjectModel-BaseCard:BaseCard_CL.adoc[BaseCard]`
+
Карточка из библиотеки _{bo}_

operation:::
Тип: `BackOffice-ObjectModel-BuiltIn:BuiltInOperation_CL.adoc[BuiltInOperation]`
+
Встроенная операция

Возвращаемое значение::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
`true` -- операция разрешена, иначе -- `false`

== Заметки

Если операция не запрещена, то она отмечается разрешённой.

== Примеры

Ниже приведён пример определения наличия прав у роли текущего сотрудника, достаточных для редактирования основного файла некого документа

[source,csharp]
----
<.>

IAccessCheckingService accessCheckingService = objectContext.GetService<IAccessCheckingService>(); <.>

Document document = objectContext.GetObject<Document>(new Guid("00000000-0000-0000-0000-000000000000")); <.>

bool allowed = accessCheckingService.IsOperationAllowed(document, Document.MainFileEditOperation); <.>
----
<.> Инициализация контекста объектов.
<.> Получение сервиса.
<.> Получение документа.
<.> `true` -- операция редактирования разрешена.
