= Согласование документа

[NOTE]
====
Для отправки документа на согласование с помощью API необходимо, чтобы в шаблоне, из которого создаётся согласование, был установлен флаг `*Запускать согласование без показа карточки*`. Также должен существовать режим создания согласования (в _Справочнике видов карточек_), который задействует данный шаблон.
====

. Подключите к проекту или скрипту карточки дополнительные сборки: `DocsVision.ApprovalDesigner.ObjectModel.dll` и `DocsVision.DocumentsManagement.ObjectModel.dll`, в которых определены преобразователь данных и сервис для отправки согласования.
. Подключите дополнительные пространства имён:
+
* `DocsVision.ApprovalDesigner.ObjectModel.Mapping`
* `DocsVision.ApprovalDesigner.ObjectModel.Services`
* `DocsVision.BackOffice.ObjectModel.Services`
* `DocsVision.DocumentsManagement.ObjectModel.Services`
* `DocsVision.Platform.ObjectModel.Mapping`
* `System.Linq`
+
. Подключите в коде сервисы и преобразователи данных для работы с согласованием:
+
[source,csharp]
----
IServiceFactoryRegistry serviceFactoryRegistry = context.GetService<IServiceFactoryRegistry>(); <.>
serviceFactoryRegistry.RegisterFactory(typeof(ApprovalDesignerServiceFactory));

var mapperFactoryRegistry = context.GetService<IObjectMapperFactoryRegistry>(); <.>
mapperFactoryRegistry.RegisterFactory(typeof(ApprovalDesignerMapperFactory));
----
<.> Добавляем в контекст фабрику `ApprovalDesignerServiceFactory`.
<.> Добавляем в контекст преобразовать данных `ApprovalDesignerMapperFactory`.
+
. Получите идентификатор согласуемого документа, например, так:
+
[source,csharp]
----
Guid initialCardId = context.GetObjectRef(this.BaseObject).Id; <.>
----
<.> Получаем идентификатор документа, при в скрипте карточки.
+
. Получите настройки режима создания согласования:
+
[source,csharp]
----
KindsCardKind cardKind = context.GetObject<KindsCardKind>(new Guid("9C0E5586-41B8-411E-B5CD-C94B605CB7A1")); <.>

KindsCardCreationSetting cardCreationSetting = cardKind.CreationSettings.FirstOrDefault(t => t.ModeName.Equals("СогласованиеПример")); <.>
----
<.> Получаем настройки вида карточки "Согласование КС".
<.> Получаем настройки режима создания "СогласованиеПример". Режим использует шаблон согласования с флагом `*Запускать согласование без показа карточки*`.
+
. Создайте новое согласование для документа:
+
[source,csharp]
----
Guid reconciliationId = context.GetService<IReconcileService>().CreateReconciliationCard(initialCardId, cardCreationSetting);
----
+
. Вызовите метод `HandleDocumentAfterReconcileCreated`, который завершит подготовку согласования и запустит его:
+
[source,csharp]
----
CardData reconciliationCardData = Session.CardManager.GetCardData(reconciliationId);
context.GetService<IReconcileService>().HandleDocumentAfterReconcileCreated((Document)this.BaseObject, reconciliationCardData);
----
+
Приведенным способом можно отправлять документы на согласование из скрипта карточки или из внешнего приложения.
